### ISSUE TITLE
Mangle properties prefix feature proposal

### ISSUE THREAD

**Issue by bo4arovpavel1989** [terser/terser#1001]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

using terser via terser-webpack-plugin v5.0.3

**Complete CLI command or `minify()` options used**

```
new TerserPlugin({ 
    parallel: false, 
    terserOptions: {
        nameCache: {},                            
        mangle: {
            properties: { regex: /^_private_/ }                            
        }                        
    }
})
```

**Problem description**
We use `TerserPlugin` with webpack, bundling several async chunks. `Terser` is configured to minify private properties of class methods by regexp, also parallel minifying disabled and nameCache provided to avoid unwanted method and property names overriding in inherited classes, when parent and child classes are located in different async chunks. But it still remains issue, that private property mangling can override parent's public/protected method or property. Issue could be solved by using `reserved` option, but having complex project we can not provide such a full reserved list.
**Proposed solution**
We'd like to have an option to mangle properties by some defined prefix, whitch is never used in props and methods, that are not meant to be mangled. 
Propose config example:
```
new TerserPlugin({ 
    parallel: false, 
    terserOptions: {
        nameCache: {},                            
        mangle: {
            properties: { regex: /^_private_/, outputPrefix: '$' }                            
        }                        
    }
})
```
Terser input:
```
class A {
   _private_foo = 'foo';
   _private_bar() {
        console.log('bar');
    }
}
```
Desired terser mangling properties output:
```
class A {
   $i = 'foo';
   $j() {
        console.log('bar');
    }
}
```

**Comment by fabiosantoscode** [comment]
Closed in #1038  -- thanks @jridgewell

**Comment by fvittorello** [comment]
Hi guys, I'm trying to set a prefix to all of the variables and properties of a project but couldn't understand how to solve it with the post mentioned, do you have an example of what the config should be like?

**Comment by fabiosantoscode** [comment]
Both `mangle.nth_identifier` and `mangle.properties.nth_identifier` options can be a variable name generator. In this generator, a prefix can be added.

The default generator is here. https://github.com/terser/terser/blob/d32e177c14694fba4ed4b025654b30a028cd84f1/lib/scope.js#L1015-L1061 It not only creates variable names, but it can also take in information about what characters are most common, to make more gzip-friendly names.

**Comment by fvittorello** [comment]
Thanks @fabiosantoscode, I will check them.

**Comment by arredgroup** [comment]
Hi everyone! @fvittorello can you share how you implement a override for add prefix?? I'm looking an approach to implement prefix with terser, thanks!
