### ISSUE TITLE
Incorrect transformation of nullish coalescing operator when passing "ecma" option.

### ISSUE THREAD

**Issue by ruipin** [terser/terser#1003]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
`terser 5.6.1`

**Complete CLI command or `minify()` options used**
`terser test.js -c ecma=2020`

Note that the issue can be reproduced with *any* value for `ecma`, e.g. `terser test.js -c ecma=1`, `terser test.js -c ecma=2000000`, `terser test.js -c ecma`, etc.

The issue does *not* occur if the `ecma` parameter is omitted, i.e. `terser test.js`.

**`terser` input**
A `test.js` file containing:
````js
if(!(a ?? b))
    throw new Error("Some error");
````

**`terser` output or error**
````js
if(a??!b)throw new Error("Some error");
````

**Expected result**
````js
if(!(a??b))throw new Error("Some error");
````

For reference, this is the output when not passing any `ecma` parameter.

To see why the output is incorrect code, see e.g.
````js
const a = 1;
const b = 2;
console.log(!(a ?? b)); // -> false
console.log(a ?? !b); // -> 1
````

**Comment by oxygene** [comment]
I'd like to note that this is quite a critical bug. It silently changes the logic of the application.

I have a Vue + webpack application with minification only active on production builds. So for use, this bug only becomes visible when the application hits QA, but the developers don't see it while coding.

**Comment by alexander-akait** [comment]
cc @fabiosantoscode I think critical
