### ISSUE TITLE
Shorthand properties with unicode character bug with `safari10`

### ISSUE THREAD

**Issue by Knutas** [terser/terser#1005]
**Bug report**
Properties with unicode characters are quoted with the `safari10` flag, but the value is omitted if shorthand is used to set it. I recreated the bug with a unittest in Terser.

**Version (complete output of `terser -V` or specific git commit)**
Terser 7.15.1

**Complete CLI command or `minify()` options used**
`{ safari10: true, ecma: 2015 }`

**`terser` input**
```
var ä = ""
console.log({ ä })
```

**`terser` output or error**
`var ä="";console.log({"ä"});`

**Expected result**
`var ä="";console.log({"ä":ä});`

**Comment by joeldenning** [comment]
I ran into a similar issue where lodash-es' deburrLetter function has an object with quoted unicode characters as its keys, but terser was compiling it to an unquoted unicode character. To fix it, I set `format.ascii_only` to true, as described in https://github.com/terser/terser/issues/410.

I use webpack - here's the changes I made:

```diff
module.exports = {
+  optimization: {
+   minimizer: [
+      new TerserPlugin({
+        terserOptions: {
+          format: {
+          // lodash'es deburrLetter function has unicode chars that don't work in all browsers yet
+            ascii_only: true
+          }
+        }
+      })
+    ]
+  },
}
```

**Comment by fabiosantoscode** [comment]
Thanks for opening this!

This is a problem in the output code, responsible for printing the JS at the end of compression and mangling.

The code that decides that `ä` needs a quote is used by the shorthand property printer :D

**Comment by fabiosantoscode** [comment]
The code that decides whether to print quoted or not, is affected by too many options. I need to look at this with more time.

**Comment by jridgewell** [comment]
@fabiosantoscode: Can you explain why `safari10` doesn't allow non-ascii identifiers? The sample code runs fine.

**Comment by fabiosantoscode** [comment]
@jridgewell I apologize for the late answer but in case you still want to know, I vaguely recall some version of Safari having trouble with unicode properties that can't be expressed without a surrogate pair, or something like that.

The problem here is kind of related. The ObjectKeyVal printer thinks it can use a shorthand property, but `print_name` thinks the prop needs quotes.
