### ISSUE TITLE
Incorrect interaction between nullish coalescing operator and evaluate option

### ISSUE THREAD

**Issue by phiberger-argo** [terser/terser#1007]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
5.2.1

**Complete CLI command or `minify()` options used**
```terser -c evaluate=true```

**`terser` input**
(trying to minify pdf.js...)
```
class BaseViewer {
  constructor(options) {
    if (!(option.container?.tagName === "DIV")) {
      throw new Error("Invalid `container` and/or `viewer` option.");
    }
  }
}
```

**`terser` output or error**
```
class BaseViewer{constructor(options){throw new Error("Invalid `container` and/or `viewer` option.")}}
```

**Expected result**
The value of "this.container?.tagName clearly cannot be known in advance and the comparison shouldn't be optimized out. The expected code is as produced with evaluate=false:
```
class BaseViewer{constructor(options){if("DIV"!==option.container?.tagName)throw new Error("Invalid `container` and/or `viewer` option.")}}
```

Note: if replacing the ?. with "!(option.container && option.container.tagName === "DIV"), all is good.

**Comment by WofWca** [comment]
Works as expected in `5.7.1`.

**Comment by rricard** [comment]
This can be closed as #1045 shows it is already behaving correctly

**Comment by rricard** [comment]
@fabiosantoscode I think you can close this one now that there is a regression test for it

**Comment by fabiosantoscode** [comment]
Indeed!
