### ISSUE TITLE
Variable assigned to itself

### ISSUE THREAD

**Issue by o-alexandre-felipe** [terser/terser#1010]
**Bug report or Feature request?**
Improvement

When a identity function is inlined, evenatually it keeps an assignment of a variable to itself.

**Version (complete output of `terser -V` or specific git commit)**
5.5.1

**Complete CLI command or `minify()` options used**

``` bash
 terser --compress --bypass.js
```

**`terser` input**
``` javascript
function bypass(x){
  var identity = function(x){return x}
  var a = 234;
  a=identity(a);
  return a;
}
```

**`terser` output or error**
``` javascript
function bypass(x){var a=234;return a=a}
```

**Expected result**
If I repeat the minification on the minified output 
``` bash
terser --compress -- bypass.js | terser --compress
```
I get the expected output
``` javascript
function bypass(x){var a=234;return a}
```

**Comment by avdg** [comment]
There is no guarantee that the assignment is useless. For both assigning and reading the variable, you can intercept the operation with getters and setters.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set

**Comment by o-alexandre-felipe** [comment]
And what you have to say about the what I have shown in the **Expected result**

**Comment by WofWca** [comment]
I would call this a non-issue, because what we have here is an example of why there is the `compress.passes` option (<https://terser.org/docs/api-reference#compress-options>).

**Comment by fabiosantoscode** [comment]
Hello! I agree, this is the kind of thing the passes option is for. Every optimization Terser does is kind of drive-by. It deletes some code and maybe something else can clean up further. Some times this leaves some code behind that could be minimised, and you can add more passes to help decimate this excess
