### ISSUE TITLE
Terser rewrites private fields instead of throwing a parser error

### ISSUE THREAD

**Issue by TimvdLippe** [terser/terser#1011]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**
The version of https://try.terser.org/ (I am assuming latest, but the website doesn't show me what version it is running)

**Complete CLI command or `minify()` options used**

```
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
export const myObject = {
  foo: 'bar',
  #something: 5,
}
```

**`terser` output or error**
```js
export const myObject={foo:"bar",something:5};
```

**Expected result**
Terser should error on this, as you can't use private fields in an object. However, `terser` rewrites it to a regular object field which is legal syntax. So even though the input is illegal JavaScript, if users don't catch this issue, `terser` rewrites it to legal syntax and leading to incorrect code. Therefore, if users don't check their code in any other way, running the `terser` output will result in runtime errors.

**Comment by fabiosantoscode** [comment]
Usually Terser doesn't check for valid syntax on purpose, but admittedly this isn't good behaviour. It can cause confusion.
