### ISSUE TITLE
Semantically-affecting minification of private fields in ternary operations

### ISSUE THREAD

**Issue by rricard** [terser/terser#1014]
**Bug report or Feature request?**

Bug Report

**Version (complete output of `terser -V` or specific git commit)**

- 5.6.0
- Version on https://try.terser.org/

**Complete CLI command or `minify()` options used**

```js
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
class A {
  #foo = false;
  #bar = true;
  test() {
    return this.#foo ? this.#foo : this.#bar;
  }
}

new A().test()
```

**`terser` output or error**

```js
(new class{#foo=!1;#bar=!0;test(){return this.#foo,this.#foo}}).test();
```

**Expected result**

```js
(new class{#foo=!1;#bar=!0;test(){return this.#foo ? this.#foo : this.#bar}}).test();
```

**Comment by rricard** [comment]
I will try to take a look at the issue later this week since I might have overlooked that in the private fields PR...

**Comment by rricard** [comment]
This could be related to https://github.com/terser/terser/issues/999 as well

**Comment by mkubilayk** [comment]
I have a fix for this. I'll push a PR today.
