### ISSUE TITLE
Function names are not properly minified and causes a invalid syntax when `ecma=5` is provided

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [terser/terser#1019]
**Bug**

Version **^5.7.0**

```json 
{ keep_fnames: true, keep_classnames: true } 
```
These values are initially passed inside the `terser-webpack-plugin`.  https://github.com/JayaKrishnaNamburu/terser-minifier-bug-reproduction/blob/main/webpack/webpack.config.prod.js#L18

I am using terser alongside `webpack` via `terser-webpack-plugin` and when built for production. The function is replaced with some `for loop` with a invalid syntax

**`terser` input**
Terser input was from a `npm` module. And the raw file can be found here https://unpkg.com/browse/@teleporthq/teleport-plugin-common@0.17.0/dist/esm/index.js

```js

// packages/teleport-plugin-common/src/utils/hast-utils.ts
var hast_utils_exports = {};
teleport_plugin_common_dist_esm_export(hast_utils_exports, {
  addAttributeToNode: () => addAttributeToNode,
  addBooleanAttributeToNode: () => addBooleanAttributeToNode,
  addChildNode: () => addChildNode,
  addClassToNode: () => addClassToNode,
  addTextNode: () => addTextNode
});
var addBooleanAttributeToNode = (node, key, value = true) => {
  node.properties[key] = value === true ? "" : false;
};
var addAttributeToNode = (node, key, value) => {
  node.properties[key] = value;
};
var addClassToNode = (node, className) => {
  node.properties.class = className;
};
var addChildNode = (node, child) => {
  node.children.push(child);
};
var addTextNode = (node, text) => {
  node.children.push(createTextNode(text));
};

```

**`terser` output or error**

```js
       teleport_plugin_common_dist_esm_export(_N, {
            addAttributeToNode: ()=>addAttributeToNode,
            addBooleanAttributeToNode: ()=>addBooleanAttributeToNode,
            addChildNode: ()=>addChildNode,
            addClassToNode: ()=>addClassToNode,
            addTextNode: ()=>addTextNode
        });
        for (var yN, vN, addBooleanAttributeToNode = (pT,xT,OT=!0)=>{
            pT.properties[xT] = !0 === OT && ""
        }
        , addAttributeToNode = (pT,xT,OT)=>{
            pT.properties[xT] = OT
        }
        , addClassToNode = (pT,xT)=>{
            pT.properties.class = xT
        }
        , addChildNode = (pT,xT)=>{
            pT.children.push(xT)
        }
        , addTextNode = (pT,xT)=>{
            pT.children.push(createTextNode(xT))
        }
```

I Recorded a small video on the behaviour and it can be found from the initial issue which i raised here https://github.com/webpack-contrib/terser-webpack-plugin/issues/410 in the webpack plugin itself.

https://user-images.githubusercontent.com/11075561/124172457-8040a780-dac7-11eb-933c-7c094412478f.mov

Git Repository to reproduce the bug
https://github.com/JayaKrishnaNamburu/terser-minifier-bug-reproduction

Steps to reproduce from the Git repository
https://github.com/JayaKrishnaNamburu/terser-minifier-bug-reproduction#readme

**Comment by JayaKrishnaNamburu** [comment]
I was able to reproduce this outside webpack, by using `terser-cli`. Here is the un-optimised chunk
https://drive.google.com/file/d/1ftvrauvf2nUITcWLchzv_DJoFQqPRTIz/view?usp=sharing

Here is the flags to be used in cli to get a chunk that generates the invalid syntax

```shell
terser 380.7ed8f3df.js<chunk-name> -o compress.js -c ecma=5 --keep_classnames --keep_fnames
```

Then load the chunk in browser

**Comment by fabiosantoscode** [comment]
Ok, I got to the bottom of this.

With `terser input.js -c` and input:

```
var var1 = somethingUnknown1;
var var2 = (key) => key in somethingUnknown2

for (var i = 0; i < chars.length; i++) {
    loopyLoop()
}
```

Terser will join `var1`, `var2` and `i` into just one decl to save space.

```
for (var var1 = somethingUnknown1, var2 = key => key in somethingUnknown2, i = 0; i < chars.length; i++) loopyLoop();
```

Because of `key in somethingUnknown2` is there, it mixes up the parser, which assumed the function was just `key => key` and then it sees `in`, assuming it's a for-in loop.

**Comment by JayaKrishnaNamburu** [comment]
Hi @fabiosantoscode  thanks for confirming. I don't have any knowledge of teasers codebase. But I am interested in helping to solve this in some way. Can you help me find any Dev docs or how to handle the scenario if the issue can be handled by a beginner to terser :)

**Comment by fabiosantoscode** [comment]
In the end it was just a matter of adding parens. This was already being done for other expressions, but not arrow functions.
