### ISSUE TITLE
A global def may break output if it's a function

### ISSUE THREAD

**Issue by gdh1995** [terser/terser#1022]
**Bug report or Feature request?** Bug

**Version (complete output of `terser -V` or specific git commit)** 5.7.1

**Complete CLI command or `minify()` options used**

`npx terser a.js --define 'As_=(i)=>i'`

**`terser` input**

``` javascript
// a.js
export const defaultKeyMappings_ = "f " + As_("foo") + ", b " + As_("bar")
```

**`terser` output or error**

``` javascript
export const defaultKeyMappings_="f bar, b bar";
```

**Expected result**

``` javascript
export const defaultKeyMappings_="f foo, b bar";
```

**Comment by fabiosantoscode** [comment]
😮 weird

**Comment by gdh1995** [comment]
BTW, `global_defs` works as expected when I use `"@__importStar": "function(_unknown4){return _unknown4}"` to strip `__importStar` which is generated by TypeScript. And `BgUtils_ = __importStar(BgUtils_)` will be converted to `o = o`.

Then here's another issue: I have enabled pure getters and unsafe_inline, and `BgUtils_` is a function argument, so I wonder whether terser can remove the output `o = o` directly.

**CLI**
`npx terser /wo/a.js --define '__importStar=function(_unknown4){return _unknown4}'`

**input**
``` javascript
define(["require", "exports", "./utils"], function (_require, exports, BgUtils_) {
  BgUtils_ = __importStar(BgUtils_);
  exports.test = () => BgUtils_
})
```

**output**
``` javascript
define(["require","exports","./utils"],(function(_require,exports,BgUtils_){BgUtils_=BgUtils_,exports.test=()=>BgUtils_}));
```

**Comment by fabiosantoscode** [comment]
I suppose more passes would resolve this?

**Comment by gdh1995** [comment]
Um, `npx terser a.js -f beautify --define '__importStar=function(_unknown4){return _unknown4}' -c passes=3,inline,unsafe,reduce_vars,pure_getters,comparisons,collapse_vars` generates:
``` javascript
define([ "require", "exports", "./utils" ], (function(_require, exports, BgUtils_) {
    BgUtils_ = BgUtils_, exports.test = () => BgUtils_;
}));
```
