### ISSUE TITLE
top level await only valid in modules

### ISSUE THREAD

**Issue by dnalborczyk** [terser/terser#1024]
I was just cruising for top level await support in `terser` and found: https://github.com/terser/terser/issues/903 and support was implemented in: https://github.com/terser/terser/commit/69e250b6754b84afc6b86b177052730cff847461

I wanted to mention that top level await is only supported in `module` contexts, not in script contexts (even with an explicit `use strict` directive)

related: https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#841-2021-06-24

feel free to close this issue if there is no issue, or if it's just a possible short coming of the tests.

**Comment by fabiosantoscode** [comment]
Hello!

Thanks for letting me know, but Terser doesn't distinguish between a module or script context yet. `--module` is just a shorthand for `toplevel` and `strict`.

Sometimes Terser doesn't tell you your code is invalid (for example you can use ES2020 syntax even if you pass `--ecma 5`), and I feel this is one of those cases.
