### ISSUE TITLE
Standalone executable

### ISSUE THREAD

**Issue by megakraken** [terser/terser#1027]
This program is great, but it's a shame you have to have nodejs and npm and all that notoriously unstable stuff set up in order to use it. It would be so much better, if it was available as a standalone executable that you could just integrate into your build process.

Is there any straightforward way to turn this into a standalone executable?

**Comment by fabiosantoscode** [comment]
Not Terser itself, but [swc](https://github.com/swc-project/swc) is working on porting it to rust (I'm helping out). So it'll be faster and also a standalone executable. My long term plan is to try to migrate people towards it.

Available today is [esbuild](https://esbuild.github.io/) which is only around 2% less efficient than Terser at compression.

**Comment by megakraken** [comment]
Oh very nice, that sounds very promising, thank you!

**Comment by jcrben** [comment]
@fabiosantoscode are you still thinking about nudging people to migrate to swc at this point? might be worth mentioning on the readme

**Comment by fabiosantoscode** [comment]
Not really? These days I think it's good to have alternatives, even if one is way slower and more memory-hungry :D
