### ISSUE TITLE
Overlaping props with dom props - how to mangle?

### ISSUE THREAD

**Issue by oliverfindl** [terser/terser#1028]
**Bug report or Feature request?**
Feature request / Question

**Version (complete output of `terser -V` or specific git commit)**
5.7.1

**Complete CLI command or `minify()` options used**
`$ npx terser --compress --mangle --mangle-props regex=/.+/ -- src/Class.js`

**`terser` input**
```javascript
// src/Class.js
class Class {
	static encode() {}
	static decode() {}
	static encrypt() {}
	static decrypt() {}
	static getSecret() {} // only this method gets mangled
}
```

**`terser` output or error**
class Class{static encode(){}static decode(){}static encrypt(){}static decrypt(){}static t(){}}

**Expected result**
class Class{static a(){}static b(){}static c(){}static d(){}static e(){}}

---

I can't figure out, how to mangle props, that overlaps with [dom props](https://github.com/terser/terser/blob/master/tools/domprops.js) (which are not used in my codebase). RegExp is not matching them and `--builtins` options mangles all [dom props](https://github.com/terser/terser/blob/master/tools/domprops.js), which is not desired in my case. Only possible solution that I'm aware of, is to rename (or just prefix with underscore) all props in question through my whole codebase. Therefore I want to ask beforehand, if there is some possibility to define custom RegExp / whitelist of [dom props](https://github.com/terser/terser/blob/master/tools/domprops.js), that can be safely mangled in scope of particular file or project.

Thanks.

**Comment by jridgewell** [comment]
This isn't a directly supported use case, and it'd be much better to avoid the naming collision entirely. However, you can work around it with a combination of `builtins`, `only_cache`, and `nameCache` options:

```js
// Options:
{
  nameCache: {
    props: {
      props: {
        "$encode": "t",
      }
    }
  },
  mangle: {
    properties: {
      builtins: true,
      only_cache: true
    }
  }
}
```

`only_cache: true` will instruct terser to only mangle matches in the `nameCache`, and `builtins: true` will allow you to mangle the domprops. Since `only_cache` is on, it will ignore the other domprops that you don't want to mangle.
