### ISSUE TITLE
Possible bug: Minifying javascript file removes parts of simple if typeof condition and console output

### ISSUE THREAD

**Issue by rencarl** [terser/terser#1031]
Hi,

i already wrote this bug report here: https://github.com/Josee9988/MinifyAllCli/issues/71#issue-946813563
Josee9988 wrote I should post a report here, because the javascript was minified by terser.

This is my code:
```javascript
...
FRONTEND.prototype = {
    con: function(obj){
        if(typeof console.log != "undefined")console.log(obj);
    },
    ....
}
...
frontend = new FRONTEND();
frontend.con('output to console');
```

In previous versions of MinifyAll the code was minified to:
```javascript
FRONTEND.prototype={con:function(n){void 0!==console.log&&console.log(n)},...
```

In MinifyAll version 2.7.0 the code is minified to:
```javascript
FRONTEND.prototype={con:function(e){console.log},...
```

Can you fix this?
If not, how do i have to change my code?

Best regards!

**Comment by rencarl** [comment]
Problem solved:
I don't know why, but in the MinifyAll settings called 'terserMinifyOptions' in Visual Studio Code  "drop_console" was set to "true" . I changed it to "false" and everything works fine again.

Thank you for your time! This case can be closed.

**Comment by fabiosantoscode** [comment]
Hey there!

`console.log` is being left there because `drop_console` only drops the console.log call, not the reference to `console.log` function in the typeof check.

It shouldn't be a big deal, so I'm not fixing that one. 

Cheers!
