### ISSUE TITLE
Shadowed variable is accessed before initialization

### ISSUE THREAD

**Issue by croes** [terser/terser#1033]
**Bug report**

Running the minified version of the code snippets below results in a
```
ReferenceError: Cannot access 'e' before initialization
```

**Version 5.7.1**

**Complete CLI command or `minify()` options used**

```
npx terser test.mjs -o test.min.mjs -c pure_getters=true
```

**`terser` input**

***test.mjs***
```javascript
function discretize(_opts) {
  return "ignore";
}

export function test(e) {
  const result = e.option1 || {};
  const normalizeArea = e.option2 && e.option3;

  if (!result.discretized) {
    const e = discretize({
      normalize: normalizeArea
    });
    result.discretized = e
  }

  return result;
}
```

***main.mjs*** (not transpiled, just for testing purposes)
```javascript
import {test} from "./test.mjs";
import {test as testMinified} from "./test.min.mjs";

console.log("unminified result: ", test({}));
console.log("minified result: ", testMinified({}));
```

**`terser` output or error**
***test.min.mjs*** (formatted)
```javascript
function discretize(_opts) {
  return "ignore"
}

export function test(e) {
  const result = e.option1 || {};
  if (!result.discretized) {
    const e = discretize({normalize: e.option2 && e.option3});
    result.discretized = e
  }
  return result
}
```
note that `e` inside the if block is re-declared and used in its own assignment, causing the error.

**Expected result**
Running the minified code does not result in a `ReferenceError`. It should run fine, just like the unminified source.

**Some context**
This issue was discovered by one of our customers when they tried to use our library in an Angular CLI application (production build only). We don't actually shadow variables in our sources, but we do ship minified modules, where shadowed variables do appear.

**Comment by fabiosantoscode** [comment]
Thanks for this report!
