### ISSUE TITLE
[BUG] @__PURE__ doesn't work with tagged templates

### ISSUE THREAD

**Issue by sirian** [terser/terser#1034]
**Bug**

Tagged templates doesn't respect pure functions.

**Complete CLI command or `minify()` options used**
`terser -c`

**`terser` input**

```javascript
(() => {
    const a = foo("a");
    const b = foo`b`;
    const c = /*@__PURE__*/foo`c`;

    /*@__PURE__*/
    function foo(){}
})();
```

**`terser` output or error**

```javascript
(() => {
    foo`b`, foo`c`;
    function foo() {}
})();
```

**Expected result**

``` foo`b` ``` and ``` foo`c` ``` should be dropped as well as `foo("a")`

**Comment by jdanyow** [comment]
duplicate of #975

**Comment by sirian** [comment]
@jdanyow thx
