### ISSUE TITLE
[Feature request] Regular expression minification

### ISSUE THREAD

**Issue by Finesse** [terser/terser#1039]
Not so important, just an idea. Examples:

- `/[^0-9]+/` → `/\D+/`
- `/[a-zA-Z,.0-9_]/` → `/[\w,.]/`
- `/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/` → `/(?:\d+\.){3}\d+/` (`?:` prevents the group from being captured in order not to change the original expression's capture groups)

The minification will change the `source` attribute value of the regular expression, so such minification may be inappropriate for Terser. This is similar to the `eval` case that has an option to enable mangling the code visible by `eval`s. So, the regular expression minification can be disabled by default and have an option to enable it.

**Comment by fabiosantoscode** [comment]
Hello! 

Currently, Terser treats regexps as just source and flags strings. It doesn't parse them.

It does seem like a neat idea, but given the complexity and how rare regexes are, I'll pass on adding this feature :) 

Cheers!
