### ISSUE TITLE
Unused static functions included in bundle

### ISSUE THREAD

**Issue by itayod** [terser/terser#1042]
Hi,
I have two applications that use a shared class, this class has a static function `init` that returns another class, one project uses that method and the other one doesn't, unfortunately, the class the `init` function output appears in both bundles.

I made a small sample that reproduces the behavior using your [playground](https://try.terser.org/):
```javascript
const someInstance = new class SomeClass {};

class ABC {

    static hello() {
    	return someInstance;
    }
}
  
const abc = new ABC();
```

the following will output will include `someInstance ` even though the script never call the `hello` function:

```javascript
const s=new class{};new class{static hello(){return s}};
```

I will be glad if you could take a look, thanks :)

**Comment by fabiosantoscode** [comment]
This is because Terser does not do flow analysis. It does check if variables are used, but it doesn't check its contents (IE the contents of classes). Some objects are simple enough to be checked, but it's severely limited to keep Terser fast. And it's still pretty slow :laughing: .

**Comment by itayod** [comment]
@fabiosantoscode thanks for the replay, in my case I don't even call this function, IMO it makes sense it won't be included in the bundle.

But do as you think :)
