### ISSUE TITLE
can't find variable $ for $.ajax

### ISSUE THREAD

**Issue by yogithesymbian** [terser/terser#1055]
1. run : `terser terser.js --mangle-props regex=/_$/` 
2. the result : `onTokeniseSuccess:e=>{$.ajax({url`
3. can't find variable $

**Comment by fabiosantoscode** [comment]
Hello!

What's the input code that generates this issue? Was it working before going through that command line?

JQuery's `$` is usually a global variable, is it set through another script tag in your case?

**Comment by fabiosantoscode** [comment]
Closing since can't repro
