### ISSUE TITLE
[Question] Nullish coalescing operator -> ES6

### ISSUE THREAD

**Issue by denyaalt** [terser/terser#1077]
**Question**

Can Tercer replace the nullish coalescing operator with ES6 format code for older browsers?
Thanks.

**Input**

`var t=0, baz=t??42;`

**Expected result**

`var t=0, baz=(t!==undefined&&t!==null?t:42);`

**Comment by fabiosantoscode** [comment]
Hello! No, this is not something terser does.

If you want a one-stop-shop for minifying and converting code for all browsers have a look at esbuild. SWC also has a minifier which I think is beta at the time.
