### ISSUE TITLE
Variable self assignment not removed (x = x)

### ISSUE THREAD

**Issue by Ahnfelt** [terser/terser#1081]
**Bug report or Feature request?**

Feature request.

**Version (complete output of `terser -V` or specific git commit)**

Online REPL 5th of October 2021

**Complete CLI command or `minify()` options used**

Default options:

```js
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
export function f(x) {
    x = x;
}
```

**`terser` output or error**

```js
export function f(f){f=f}
```

**Expected result**

```js
export function f(f){}
```

**Comment by jridgewell** [comment]
Do you see code like `f = f` as the output of some build step?

**Comment by Ahnfelt** [comment]
> Sometimes Terser itself outputs `x=x` IIRC

Yeah, i.e. this produces the exact same output:

```js
export function f(x) {
    const y = x;
    const z = y;
    x = z;
}
```
