### ISSUE TITLE
Supporting import assertions

### ISSUE THREAD

**Issue by lewisl9029** [terser/terser#1095]
**Feature request**

Hi there! I'd love to see support for the upcoming [import assertions proposal](https://github.com/tc39/proposal-import-assertions), currently at stage 3. It's aimed at enabling use cases for importing things other than ES modules, starting with JSON and CSS. 

The feature has been gaining a lot of traction, with support in babel [through a parser config](https://babeljs.io/docs/en/babel-parser#ecmascript-proposalshttpsgithubcombabelproposals), and has [recently landed](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#import-assertions) in TypeScript 4.5 beta as well. Having support in terser would bring us another step closer to being able to use this awesome feature in production and start deprecating legacy custom loader workflows!

**Version (complete output of `terser -V` or specific git commit)**
terser 5.9.0

**Complete CLI command or `minify()` options used**

`terser importAssertions.js`

**`terser` input**

```js
import styles from './styles.css' assert { type: 'css' }
```
> importAssertions.js

**`terser` output or error**

```
Parse error at importAssertions.js:1,34
import styles from './styles.css' assert { type: 'css' }
                                  ^
ERROR: Unexpected token: name (assert)
```
**Expected result**

`import styles from"./styles.css"assert{type:'css'};`
(Unsure if this is actually valid syntax, might need a space between `assert` and `{`?)

**Comment by fabiosantoscode** [comment]
This is pretty easy especially since Terser won't read any of it!
