### ISSUE TITLE
Wrong compression

### ISSUE THREAD

**Issue by borisdamevin** [terser/terser#1099]
**Bug report or Feature request?**

Bug.

**Version (complete output of `terser -V` or specific git commit)**

`5.9.0`

**Complete CLI command or `minify()` options used**

Via `webpack` 5 and `terser-webpack-plugin` 5.

**`terser` input**

`timestamp = countdown_default()(new Date(datetime + 'Z'), Date.now(), countdown_default.a.DAYS);`

**`terser` output or error**

`timestamp = countdown_default()(new Date(datetime + 'Z'), Date.now(), (countdown_default()).DAYS);`

**Expected result**

`timestamp = countdown_default()(new Date(datetime + 'Z'), Date.now(), countdown_default.a.DAYS);`

**Comment by fabiosantoscode** [comment]
I checked the original source by disabling minification:

```js
// webpack.config.js
module.exports = {
    optimization: {
        minimize: false
    },
}
```

Terser is correct as per the input code.

This is what we see in the output we disable minification. `countdown__(...)__default` gets called twice in the original source.

```js
(() => {
"use strict";
/* harmony import */ var countdown__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(268);
/* harmony import */ var countdown__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(countdown__WEBPACK_IMPORTED_MODULE_0__);


countdown__WEBPACK_IMPORTED_MODULE_0___default()(new Date(), Date.now(), (countdown__WEBPACK_IMPORTED_MODULE_0___default().DAYS))
})();
```

A console.log of the two webpack injected variables reveals that countdown appears to have exported `{}`

**Comment by jridgewell** [comment]
I don't think countdown is compatible with webpack 5, I could never get anything to work.

**Comment by fabiosantoscode** [comment]
Right. I'm going to close this issue. It sounds like an issue with countdown, where it fails to overcome the webpack environment

**Comment by borisdamevin** [comment]
@fabiosantoscode Right, so if the plugin is the problem, webpack 5 have any options for legacy support or is condemned to be only use with version 4?

**Comment by fabiosantoscode** [comment]
I don't really know much about webpack. It might be worth it to ask them through their channels
