### ISSUE TITLE
Variable in `finally` branch capture the wrong one

### ISSUE THREAD

**Issue by chbdetta** [terser/terser#1107]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
4.3.1

**Complete CLI command or `minify()` options used**
```js
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**
```js
function foo() {
  let bar = 23;
  
  try {
    const bar = 12;
    console.log(bar);
  } finally {
  	console.log(bar);
  }
}

foo();
```

**`terser` output or error**
```js
!function(){try{const o=12;console.log(o)}finally{console.log(o)}}();
```

**Expected result**
```js
!function(){try{const o=12;console.log(o)}finally{console.log(23)}}();
```

**Comment by fabiosantoscode** [comment]
This is related to how the AST is structured. The "finally" branch is a child of the "try" statement. Let me see what I can do about this
