### ISSUE TITLE
Long string inlining heuristics

### ISSUE THREAD

**Issue by samouri** [terser/terser#1111]
**summary**

I'm not sure how `terser` is deciding when to inline a variable vs. just minify the identifier.
I found a simple situation in which terser appears to be using a heuristic, yet makes what appears to be the incorrect decision.

**input**
```js
const LONG_PROPERTY_NAME2 = "SUPER_LONG_STRING_SO_SO_LONG_PLS_OPTI"

doFoo(LONG_PROPERTY_NAME2)
doFoo(LONG_PROPERTY_NAME2);
doFoo(LONG_PROPERTY_NAME2);
```

**output**
```js
doFoo("SUPER_LONG_STRING_SO_SO_LONG_PLS_OPTI"), 
doFoo("SUPER_LONG_STRING_SO_SO_LONG_PLS_OPTI"), 
doFoo("SUPER_LONG_STRING_SO_SO_LONG_PLS_OPTI");
```

---

If I modify the super long string by adding a character to the RHS, the total output is half the size:

```js
const o = "SUPER_LONG_STRING_SO_SO_LONG_PLS_OPTIM";

doFoo(o), doFoo(o), doFoo(o);
```

cc @jridgewell

**Comment by jridgewell** [comment]
The first output actually generates smaller compressed file sizes, though this trades compression for parse speed.

**Comment by samouri** [comment]
Dupe of https://github.com/terser/terser/issues/790
