### ISSUE TITLE
Support retaining default function parameters when a Function's .length is important

### ISSUE THREAD

**Issue by 12wrigja** [terser/terser#1115]
**Bug report or Feature request?**

Feature Request: Terser cannot be configured to keep default parameters around, and transpiles them to normal function parameters changing the function's .length value.

**Version (complete output of `terser -V` or specific git commit)**

5.7.1

**Complete CLI command or `minify()` options used**

```
{
  keep_classnames: true,
  keep_fnames: true,
  ecma: 2015,
  compress: {
    keep_fargs: true,
    keep_classnames: true,
    keep_fnames: true,
  },
  mangle: {
    keep_classnames: true,
    keep_fnames: true,
  }
}
```

**`terser` input**

```
let z = function(a, b=undefined) {
  console.log(a, b);
}
```

**`terser` output or error**

```
let z=function(o,l){console.log(o,l)};
```

**Expected result**
let z=function(o,l=undefined){console.log(o,l)};

** Notes ** 

Terser optimizes the default argument into a normal argument, but this changes the function's length (which should be 1, not 2).

The documentation for the keep_fargs option mentions that it is useful for code relying on Function.length output, I would like it to also work in this case as well.

**Comment by jridgewell** [comment]
If you're interested in contributing, the bug is in https://github.com/terser/terser/blob/3ccf5cffa6dcda1065600e2ec42f241197a4ef9c/lib/compress/index.js#L3682-L3684:

```diff
-     if (evaluateRight === undefined) {
+     if (evaluateRight === undefined && (!(compressor.parent() instanceof AST_Lambda) || !compressor.option("keep_fargs"))) {
```

**Comment by 12wrigja** [comment]
I'm interested - I'll try and take a look at this this week or next.

**Comment by fabiosantoscode** [comment]
Closed in https://github.com/terser/terser/commit/ca51c119cc67d6bd59ac12d55de69309e8b752d6
