### ISSUE TITLE
DCE known pure constructors

### ISSUE THREAD

**Issue by samouri** [terser/terser#1117]
**summary**
I'm seeing builtin/known pure constructors sticking around in the output as if they could have side effects.
Is there any way of informing `terser` that it is ok to DCE these?

Input
```js
new RegExp("Some regex")
```

**actual output**
```js
new RegExp("Some regex")
```

**expected output**
```js
```

cc @jridgewell

**Comment by jridgewell** [comment]
Solved by the [unsafe](https://github.com/terser/terser/#the-unsafe-compress-option) option (which is surprisingly safe)
