### ISSUE TITLE
support "#private in" syntax

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#1124]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

5.10.0

**Complete CLI command or `minify()` options used**

default

**`terser` input**

```js
class A {
    #p;
    isA () { return #p in this; }
}
```

**`terser` output or error**

```
Unexpected token: privatename (p)
```

**Expected result**

That's already stage 4, supported by nodejs, browser and latest acorn (v8.6.0)

**Comment by tchetwin** [comment]
`modern syntax` label?

**Comment by fabiosantoscode** [comment]
Hi! This was fixed last year but I forgot to close.
