### ISSUE TITLE
Feature: Functions/Classes on a new line

### ISSUE THREAD

**Issue by mangelozzi** [terser/terser#1126]
**Feature request**

I have seen some minified code where there are some new lines for the start of classes/functions, or variables between functions.
A few new lines across a whole file does not add much, but does add lots of source control advantages..

As far as I can tell (having gone through the many format options), there is no option for this?

The output could look something like:
```
function foo(.... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; );
function bar(.... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; );
let x=1,y=2,z=1;
function baz(.... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; .... ; ... ; );
```

**Comment by jridgewell** [comment]
The format options includes `max_line_len`, which gives you the ability to insert newlines at column indexes. But terser's output isn't designed to be source code, it's better to think of it like the binary output of a C compiler. We're outputting code for machines, not humans.

**Comment by mangelozzi** [comment]
I use the compress option not mangle. Although the output is designed for
machines, its still code checked in.
The problem with breaking after x chars, is a change in the file will
render lines from that point onwards different. If it was breaking on
functions, only that line would have a diff.
