### ISSUE TITLE
attr Jquery property mangle

### ISSUE THREAD

**Issue by makiBaraba** [terser/terser#1127]
I want to process some .js file of the chrome extension.

In that content script I use Jquery.

Terser options are:
`var options = {
    mangle: {
        toplevel: true,
        properties: true,
    },
    compress: {
        drop_console: true,
    },
    ecma: 2020,
    nameCache: {},
};`

When I set mangle.properties to "true", function $(e).attr('class') became $(e).t('class'), but all of the other Jquery function stays the same. Only attr function changes. When I set mangle.properties to false, attr stays attr.

**Comment by fabiosantoscode** [comment]
`mangle.properties` is an advanced feature that, as documented, **will** break your code. It requires you to control all the input code.

It does take care not to mangle DOM-related properties, which is why you don't see things like `.on` mangled.

Cheers!
