### ISSUE TITLE
Template minification generates incorrect code that omits toString() call

### ISSUE THREAD

**Issue by evanw** [terser/terser#1128]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

```
terser 5.10.0
```

**Complete CLI command or `minify()` options used**

```
terser -c
```

**`terser` input**

```js
`${x ? 1 : 2}${y}`
```

**`terser` output or error**

```js
x,y;
```

**Expected result**

```js
x,""+y;
```

The variable `y` could contain an object with a `toString()` method with side-effects such as this:

```js
y = {
  toString() {
    console.log('side effect')
  }
}
```

**Comment by evanw** [comment]
Never mind, I see that the readme has this:

> - `.toString()` and `.valueOf()` don't have side effects, and for built-in objects they have not been overridden.

**Comment by jridgewell** [comment]
Yah, a lot of common string operations can't be optimized if we respect `valueOf` and `toString`.

As a side note, using `'' + y` would also be incorrect, since that'll call `valueOf` over `toString`, if both are defined.

**Comment by evanw** [comment]
Thanks for pointing that out. I'll have to fix that in esbuild. I believe I have already fixed this for template lowering but not yet for template minification.
