### ISSUE TITLE
Feature: Add example of how to disable an option via CLI

### ISSUE THREAD

**Issue by mangelozzi** [terser/terser#1133]
**Feature request?**

The help says
```
drop_debugger (default: true) -- remove debugger; statements
```
But how does one set it to false? I can't find an example in the documentation of how to disable an option.
`--nodrop_debugger`, `--no-drop_debugger`, `--drop_debugger=false`, `--drop_debugger false` ???

**Comment by fabiosantoscode** [comment]
This was indeed missing, thanks for reporting.
