### ISSUE TITLE
The repo topic should be javascript

### ISSUE THREAD

**Issue by VdustR** [terser/terser#1135]
The repository topic is `javacript` now and it should be `java "s" cript`.

![image](https://user-images.githubusercontent.com/29639463/150447920-3510d4d1-8fa0-4188-9ef0-1c638073415a.png)

**Comment by fabiosantoscode** [comment]
Github agrees :D

![image](https://user-images.githubusercontent.com/1611595/150493862-efe188f0-97ca-4876-af2f-2bd938447735.png)

Thanks, fixed!
