### ISSUE TITLE
support static block syntax

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#1136]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

5.10.0

**Complete CLI command or `minify()` options used**

default

**`terser` input**

```js
class A {
    static { }
}
```

**`terser` output or error**

```
Unexpected token: punc ({)
```

**Expected result**

That's already stage 4, supported by nodejs, browser and acorn (v8.5.0)

**Comment by michael42** [comment]
It seems to me that's a duplicate of #1093.
