### ISSUE TITLE
import/export name can be string now (ES2022)

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#1137]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

5.10.0

**Complete CLI command or `minify()` options used**

default

**`terser` input**

```js
export { "a-a" as "b-b" } from "x";
```

**`terser` output or error**

```js
export{a-a as b-b}from"x";
```

**Expected result**

```js
export{"a-a"as"b-b"}from"x";
```

https://github.com/tc39/ecma262/pull/2154

**Comment by tchetwin** [comment]
`modern syntax` label?

**Comment by fabiosantoscode** [comment]
Yes, thanks for the reminder :)
