### ISSUE TITLE
Is it possible to release a 5.11.0 or 5.10.1

### ISSUE THREAD

**Issue by alexpott** [terser/terser#1143]
Thanks for Terser. We're making use of it in Drupal - another open source project. We currently have an interesting problem caused by the peer dependency on Acorn. After updating to 5.10 we get the following error when running ` yarn check -s`:
```
error "terser#acorn@^8.5.0" doesn't satisfy found match of "acorn@7.4.1"
```

This causes problems for our CI. I'm pretty sure that you've already committed a fix for this in https://github.com/terser/terser/commit/05b23eeb682d732484ad51b19bf528258fd5dc2a which is great - thanks again.

I was wondering if you could make a release to fix this? Or do you have a release schedule? I looked but couldn't find one.

**Version (complete output of `terser -V` or specific git commit)**
5.10

**Comment by fabiosantoscode** [comment]
5.11.0 released!

**Comment by alexpott** [comment]
Thanks @fabiosantoscode that's great - open source ❤️
