### ISSUE TITLE
Feature request: More flexible properties mangling options

### ISSUE THREAD

**Issue by armandn** [terser/terser#1146]
I would really appreciate more more options for including/excluding things from mangling.

Right now I maintain an exclude list, but it's becoming impractical. The project I'm working on is very large and I hate the idea of prefixing all functions/props that I want mangled.

I have two suggestions, but I don't know how practical an implementation would be:

1. Use annotations, such as` /*@__MANGLE__*/ function myF()`...
2. Include/exclude mangling by class or module.

Thank you.

**Comment by carcinocron** [comment]
👍 for this. The current mangle properties is way too _everywhere or nowhere_ in scope to be useful. I have a handful of scenarios where:

```js
// only mangle this object

/*@__MANGLE__*/
const propsBag = {
  foo, bar,
}

const { foo, bar } = propsBag
```
would be really useful without accidentally mangling DOM and 3rd party API props or serialization sensitive props 

The current alternative seems to be something like:
```
const propsBag = {
  $foo, $bar,
}

const { $foo: foo, $bar: bar } = propsBag
```

**Comment by armandn** [comment]
One year later, is there any consideration for this feature?
It would save me _a lot_ of trouble...

**Comment by fabiosantoscode** [comment]
@carcinocron's idea is pretty good. I think for a start it would be per-property (so you can use it in objects/classes with mixed mangledness.

Using `/*@__MANGLEPROP__*/` before your property once (say, in your constructor) would mangle that property name string everywhere.

Changing mangling options on a per-module basis seems a bit hard to do, especially since you could call something outside of it with different (or no) mangling.

**Comment by armandn** [comment]
Sounds great! I assume this will work for function names as well.
I agree that class/module-level mangling is too complicated.

**Comment by fabiosantoscode** [comment]
I don't see the utility in marking function names, unless you mean methods and object properties containing functions? 

Mangling variables is already a process that doesn't need the author to choose which names are safe.

**Comment by armandn** [comment]
Sorry for the misunderstanding, yes, I mean class methods & properties. I use mainly Typescript and I know which methods are private or protected and thus can be safely mangled. Prefixing 'safe' methods & properties with underscores and dollar signs to allow for regex-based mangling results in some very ugly code.

**Comment by fabiosantoscode** [comment]
Now that I think of it, I can imagine a typescript compilation step adding the annotation automatically to properties marked `private`

**Comment by fabiosantoscode** [comment]
Made some progress. All of these work!

```js
class Foo {
    /*@__MANGLEPROP__*/ foo() {}
    /*@__MANGLEPROP__*/ foo2 = 123
    /*@__MANGLEPROP__*/ static foo3 = 123
    /*@__MANGLEPROP__*/ async meth() {}
    /*@__MANGLEPROP__*/ async *meth() {}
    /*@__MANGLEPROP__*/ *meth() {}
}

const foo = {
    /*@__MANGLEPROP__*/ ["prop"]: 1,
    /*@__MANGLEPROP__*/ prop: 1,
    /*@__MANGLEPROP__*/ meth() {},
    /*@__MANGLEPROP__*/ async meth() {},
    /*@__MANGLEPROP__*/ async *meth() {},
    /*@__MANGLEPROP__*/ *meth() {},
}
```

**Comment by armandn** [comment]
Awesome! Is this present in v5.17.7?
I can start testing it next week.

**Comment by fabiosantoscode** [comment]
It's in development, stil on my machinel. I have a bunch of testing to do, to make sure it doesn't affect other features

**Comment by fabiosantoscode** [comment]
Added a branch with this WIP here https://github.com/terser/terser/pull/1397

**Comment by fabiosantoscode** [comment]
I think it's good to go. I'll release on Monday

**Comment by armandn** [comment]
Thank you!! I didn't have the chance to test it yet, but I do have a big project for it.
I'll also make a donation :)

**Comment by armandn** [comment]
I tested and found a bit of a snag:
The syntax
```
class Foo {
            /*@__MANGLE_PROP__*/ manglethis = "manglethis"
        }
```
is not allowed in ES6 (only in ES7 to my knowledge).
The ES6 equivalent would be
```
class Foo {
    constructor() {
        /*@__MANGLE_PROP__*/ this.manglethis = "manglethis"
    }
}
```
But in this case, `manglethis` does not get mangled.... 

Can anything be done?

**Comment by fabiosantoscode** [comment]
This is an interesting point.

The workaround is to use a getter, but adding that syntax to any property access is doable.

I just have to decide whether it should refer to the rightmost property or the leftmost. IE

`/*#__MANGLE_PROP__*/ obj.manglethis.orthis`

I'm leaning towards it mangling `.orthis`. You can always wrap obj.manglethis in parens to add the comment if you want to mangle `.manglethis`.

But I'd like to check if that's analogous to how the same issue is solved in the `/*#__PURE__*/` annotation with nested calls, because I like consistency :)

**Comment by armandn** [comment]
I thought about using a getter, but my project is quite performance-sensitive (chess).
`.orthis` looks like the obvious choice unless I'm missing any nuances.

**Comment by fabiosantoscode** [comment]
I've confirmed that `/*__PURE__*/` associates with the rightmost call so associating with the rightmost prop will make sense.

**Comment by armandn** [comment]
Sorry for the very long delay in feedback, the feature seems to be working perfectly now, thank you.
