### ISSUE TITLE
wrong regexp format output

### ISSUE THREAD

**Issue by novathore** [terser/terser#1147]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

terser 5.10.0

**Complete CLI command or `minify()` options used**

npx terser index.js --format ascii_only --ecma=2017

**`terser` input**

<pre><code>
console.log(/(^|[^а-яё])([☎☏✆📠📞📱]|т\.|тел\.|ф\.|моб\.|факс|сотовый|мобильный|телефон)(:?\s*?)([+\d(][\d \u00A0\-()]{3,}\d)/gi)
</code></pre>

**`terser` output or error**
<pre><code>
console.log(/(^|[^\u0430-\u044f\u0451])([\u260e\u260f\u2706\u{1f4e0}\u{1f4de}\u{1f4f1}]|\u0442\.|\u0442\u0435\u043b\.|\u0444\.|\u043c\u043e\u0431\.|\u0444\u0430\u043a\u0441|\u0441\u043e\u0442\u043e\u0432\u044b\u0439|\u043c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439|\u0442\u0435\u043b\u0435\u0444\u043e\u043d)(:?\s*?)([+\d(][\d \u00A0\-()]{3,}\d)/gi);
</code></pre>

**Expected result**
input regexp test on string '111111' ->> false
output regexp test on string '111111' ->> true

**Comment by artaommahe** [comment]
(based on this issue https://github.com/angular/angular-cli/issues/22707)

**Comment by fabiosantoscode** [comment]
This seems to be caused by using the `\u{hexhexhex}` form in RegExps:

```
/📞/.test("📞") // => true
/\ud83d\udcde/.test("📞") // => true
/\u{1f4de}/.test("📞") // => false
```

**Comment by fabiosantoscode** [comment]
There we go! I'll release this on Monday
