### ISSUE TITLE
Compress but keep obfuscated strings

### ISSUE THREAD

**Issue by alvarotrigo** [terser/terser#1150]
I have something like the following:

```js
parseInt('\x35\x31\x34')
```

And terser compression turns it into:

```js
parseInt("514")
``` 

Isn't there a way to keep the strings obfuscated without affecting the compression of other properties in the code?

**Comment by jridgewell** [comment]
I'm not sure what utility escaping ASCII chars gives us? If you're trying to avoid Unicode chars, you can set the `ascii_only` option.

**Comment by alvarotrigo** [comment]
It doesn't seem to be working for me.

I'm doing this:

```js
terser({
            compress: {
                passes: 2,
                drop_console: true,
            },
            output: {
                ascii_only: true
            }
        }
```

The output file still showing `parseInt("514")`

**Comment by jridgewell** [comment]
`514` is ASCII, so it's not escaped. Setting `asci_only` will prevent Unicode chars from appearing:

```js
// before
console.log("😀")

// default
console.log("😀")

// ascii_only: true
console.log("\ud83d\ude00");
```
