### ISSUE TITLE
Noop calls not dropped when body isn't empty

### ISSUE THREAD

**Issue by alecmev** [terser/terser#1152]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

5.11.0

**Complete CLI command or `minify()` options used**

```js
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
import Debug from 'debug'
const debug = Debug('test')
const NODE_ENV = "production"
function log(x) { if (NODE_ENV !== "production") debug(x) }
log("foo")
log("bar")
```

**`terser` output or error**

```js
import o from"debug";o("test");function f(o){0}f(),f();
```

**Expected result**

```js
import o from"debug";o("test");
```

---

If I remove `if (NODE_ENV !== "production") debug(x)`  **or** remove `log("bar")` **or** put `/*@__INLINE__*/` in front of both calls I get the expected result.

I think I understand why all of this is happening, more or less (the order of elimination passes, single-use inlining, etc.), just wanted to request this feature. My use-case is as in the example, debug code elimination in production builds.

**Comment by jridgewell** [comment]
This requires setting the `passes` option to a higher value:

```js
{
  module: true,
  compress: {
    passes: 2
  },
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

Each pass takes more time, only does 1 pass by default.

**Comment by alecmev** [comment]
@jridgewell Oh, that's great, thank you!

For future readers, two-pass compression also works for this:

```js
import Debug from 'debug'
const NODE_ENV = "production"
const debug = NODE_ENV !== "production" ? Debug('foo') : () => {}
debug("foo");
debug("bar");
```

Resulting in:

```js
import m from"debug";
```
