### ISSUE TITLE
How to stop class from being removed by dead code elimination?

### ISSUE THREAD

**Issue by AnderssonPeter** [terser/terser#1157]
Hi I have a Angular 13 project where half my code is Angular 13 and half is AngularJS.

The tree shacking feature of angular removes all components that aren't being used by Angular13..

Some of my Angular13 components are only being used by angularjs, and the angularjs code isn't being scanned by terser so it removes them as expected, is there some way to add a exception for a few classes so that I still can use dead code elimination, while preserving the components I know are being used by angular 13.

Is there some sort of Annotation comment I can add to my class to stop it from being removed?

**Comment by jridgewell** [comment]
There's no annotation for this. In order to prevent it from being marked as unused, you need to either `export { MyClass }` the class, or set it to a global `window.key = MyClass`

**Comment by AnderssonPeter** [comment]
The class/component is exported, but I managed to find a way to solve my issue, I added a array in a different file that contains the class.. Not a beautiful solution but it does the trick..
