### ISSUE TITLE
Incorrect transform of tagged template literal with new

### ISSUE THREAD

**Issue by Austaras** [terser/terser#1159]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**
**Complete CLI command or `minify()` options used**
I use terser playground

**`terser` input**
```js
new A()``
```

**`terser` output or error**
```js
new A``
```
which would be parsed as new (A``)
**Expected result**
output
```js
new A()``
// or
(new A)``
```

**Comment by fabiosantoscode** [comment]
What a weird corner case :) thanks for reporting!
