### ISSUE TITLE
WebComponents connectedCallback gets mangled/minified

### ISSUE THREAD

**Issue by xatian** [terser/terser#1170]
**Bug report or Feature request?**
Bug report?

**Version (complete output of `terser -V` or specific git commit)**
v5.12.1

**Complete CLI command or `minify()` options used**
```
{
  compress: {
    defaults:true,
    pure_getters:true,
  },
  ecma: 2020,
  mangle: {
    toplevel: true,
    properties: {
      keep_quoted: "strict"
    },
  },
  toplevel: true,
}
```

**`terser` input**
```
class Foo extends HTMLElement {
    public constructor () {
        super ();
    }
    public connectedCallback () {
    }
}
```

**`terser` output or error**
```
class D extends HTMLElement {
    constructor() {
        super()
    }
    ct() {}
}
```

**Expected result**
```
class D extends HTMLElement {
    constructor() {
        super()
    }
    connectedCallback() {}
}
```

connectedCallback is a reserved function name when using WebComponents yet terser seems not to care.
I tried using "reservedNames" but that seems to only work with variables and not with functions
I tried using "keep_fnames:/connectedCallback/" @ three locations (top-level, inside mangle, inside compress) --> no effect
I suppose I could fix my problem by abusing the "nameCache" but that is something I would like to avoid.

Thank you!

**Comment by xatian** [comment]
I "fixed" the issue by putting the function-name inside quotes --> like so:
```
class Foo extends HTMLElement {
    public constructor () {
        super ();
    }
    public "connectedCallback" () {
    }
}
```
This way the function-name is not touched and my problem goes away.

Still --> I think "connectedCallback" should be added to list of reserved (not to be mangled) function-names.

**Comment by fabiosantoscode** [comment]
Hello! Thanks for reporting. The properties in this list aren't mangled by default:

https://github.com/terser/terser/blob/master/tools/domprops.js

And apparently connectedCallback isn't there indeed. A quick google of the webcomponents API revealed `attributeChangedCallback` which is also not present.

**Comment by FreyaHolmer** [comment]
I just lost hours due to this issue ;-; would be nice to have this properly fixed to not have others run into the same problem!
