### ISSUE TITLE
Support removing constant if and switches if condition is local varaible

### ISSUE THREAD

**Issue by Austaras** [terser/terser#1174]
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**
Terser playground

**Complete CLI command or `minify()` options used**
playground default

**`terser` input**
```js
let x = window.a

if (x === x) console.log(1)

switch (x) {
  case x:
    console.log(2)
}
```

**`terser` output or error**
```js
let o=window.a;if(o==o&&console.log(1),o==o)console.log(2);
```

**Expected result**
```js
let o=window.a;console.log(1);console.log(2);
```

**Comment by fabiosantoscode** [comment]
This isn't safe to do because window.a here could be NaN, which isn't equal to itself.
