### ISSUE TITLE
Should produce simpler code.

### ISSUE THREAD

**Issue by xboy2022** [terser/terser#1183]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

```javascript
const a = () => true;
const b = () => 123;
const c = true ? a : b;
console.log(c());
```

**`terser` output or error**

```javascript
const o=()=>!0;console.log(o())
```

**Expected result**

```javascript
console.log(true)
```

**Comment by jridgewell** [comment]
Terser operates in passes, performing some minifications in order over each pass. In order to get the output you'd like, you need to run more passes:

```js
// options.json
{
  toplevel: true,
  compress: {
    passes: 2
  },
}

// input.js
const a = () => true;
const b = () => 123;
const c = true ? a : b;
console.log(c());

// output.js
console.log(!0);
```
