### ISSUE TITLE
`require` calls not inlined, even when marked `@__INLINE__` or `@__PURE__`

### ISSUE THREAD

**Issue by bbrk24** [terser/terser#1188]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

terser 5.13.0

**Complete CLI command or `minify()` options used**

Just the default options

**`terser` input**

```js
const x = require('foo');
console.log(x.y());
```

Maybe I just don't know how `@__INLINE__` and `@__PURE__` are supposed to be used, but I tried several configurations including the following:

```js
const x = /*@__PURE__*/require('foo');
/*@__INLINE__*/
console.log(x.y());
```

None of them seemed to make any difference.

**`terser` output or error**

```js
const o=require("foo");console.log(o.y());
```

**Expected result**

```js
console.log(require("foo").y());
```

**Comment by fabiosantoscode** [comment]
The `/*@__INLINE__*/` magic comment is used to tell Terser to ignore some rules (for instance, if the output would be a bit larger) when inlining functions. You don't need it to inline regular variables like `x` here.

Why is `x` not being inlined? I wrote a long explanation below, but TL;DR: "console" and "require" are unknown, and accessing them could crash or cause side effects.

In this case, `require` and `console` are not visible variables, so accessing it could have a side effect (or crash).

For instance, if someone ran the following code before yours:

```
const _console = window.console
Object.defineProperty(window, 'require', { get: () => { _console.log('getting require'); return () => {} } })
Object.defineProperty(window, 'console', { get: () => { _console.log('getting console'); return _console } })
```

Inlining the variable `x` will cause "getting require" to be logged before "getting console".
