### ISSUE TITLE
Replace string operations with literals when operands are static

### ISSUE THREAD

**Issue by romulof** [terser/terser#1196]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

5.12.1

**Complete CLI command or `minify()` options used**

```js
{
  ecma: 2022,
  module: true
}
```

**`terser` input**

```js
export const a = ["Hello", "World!"].join(" ");
export const b = "---Hello World!---".substring(3, 15);
```

**`terser` output or error**

```js
export const a=["Hello","World!"].join(" ");export const b="---Hello World!---".substring(3,15);
```

**Expected result**

```js
export const a="Hello World!";export const b="Hello World!";
```

I'm aware that `Array.prototype.join`, `String.prototype.substring` and other string manipulation functions can be tampered, but making this optimization as a non-default option might produce good results in both size and startup performance.

**Comment by jridgewell** [comment]
This is actually implemented under the [`unsafe` option](https://github.com/terser/terser#the-unsafe-compress-option). We assume that standard JS APIs are not monkey-patched, and perform the methods at compile time.
