### ISSUE TITLE
Question: Mangle private object field properties

### ISSUE THREAD

**Issue by Degubi** [terser/terser#1201]
**Question**

Is there a way to force terser to mangle the 'first' and 'second' properties of the '_internalState' field?

**Version (complete output of `terser -V` or specific git commit)**
5.13.1

**Complete CLI command or `minify()` options used**

```js
/** @type { import('terser').MinifyOptions } */
const jsMinifySettings = {
    module: true,
    compress: {
        passes: 3
    },
    mangle: {
        properties: {
            regex: /^_.*/
        }
    }
};
```

**`terser` input**

```js
export default class TestClass {

    _internalState = {
        first: 5,
        second: 'asd'
    };

    _privateMethod() {
        this._internalState.first = 20;
    }
}
```

**`terser` output or error**

```js
export default class t{t={first:5,second:"asd"};i(){this.t.first=20}}
```

**Expected result**

```js
export default class t{t={a:5,b:"asd"};i(){this.t.a=20}}
```

**Comment by jridgewell** [comment]
No, you would need to also use a leading `_` for those properties. We can't analyze where that object could escape to, so its properties could be part of some public API.
