### ISSUE TITLE
[Question] Later ecma versions produce larger outputs?

### ISSUE THREAD

**Issue by Slapbox** [terser/terser#1203]
How/why would a terser config specifying an `ecma` of 2019 produce larger output than specifying `ecma` of 8?

Is this expected?

**Comment by fabiosantoscode** [comment]
It's hard to tell without specifics. It's certainly not expected.

Can you try using 2017 instead of 8? Maybe Terser isn't converting between the classic ECMA versions and years, that would explain it.

**Comment by Slapbox** [comment]
Seems not to be the case. 2017 and 8 produce outputs almost identical (I guess there's some degree of non-determinism?)

2019 appears to produce some files larger, some files smaller, it averages out about the same upon further inspection.

But setting to 2020 or 2021 definitely produce larger builds. Although it's small, only about 10kb increase out of 14.5mb of bundled code, it is surprising to me.

**Comment by fabiosantoscode** [comment]
There shouldn't be any non determinism. The thing that varies the most is the names of variables in mangling output, as they are sensitive to the proportions of letters in names around them.

It's interesting that 2017 and 8 don't produce the exact same output, and I'll investigate. 

And even more interesting that 2020/1 produce larger output.

**Comment by Slapbox** [comment]
~~I mysteriously cannot reproduce my findings today. I figured it was maybe because I had made some small modifications so I rolled back to an earlier commit and re-ran the scripts with `2019` or `2021`, but I still cannot reproduce my findings.~~

**Edit:** I hadn't gone back far enough in my commits and was able to reproduce it. That probably means my experience is an edge case though.

Interestingly the none of the builds have any uses of `??`, even though our source code does use `??`. Maybe there's something else I'm overlooking? Could the actions of Babel plugins possibly be part of the equation?

**Comment by fabiosantoscode** [comment]
Terser is usually at the end of the chain, but if Babel is run on tersers output, it can generate larger code.

For instance a ?? b gets turned into something like a === null || a === undefined ? b : a which is much larger

**Comment by Slapbox** [comment]
Babel only runs before in our setup, so I'm really not sure what the cause could be.

Since it didn't occur on most of the commits I tested, and the changes we made between commits were not that dramatic, I guess this is a rare situation. I'll close this unless/until someone else experiences the same issue.

Thanks for your help and your great work @fabiosantoscode!
