### ISSUE TITLE
Disable ecma transpiling in Terser

### ISSUE THREAD

**Issue by budarin** [terser/terser#1205]
We use Terser as a plugin for Webpack
In our project Babel is responsible for the transpiling the code 

It turns out a double transpiling of the code, which we would like to avoid

Is there a possibility to disable ecma transpiling in Terser?
(at now we use `ecma: 2030` which is a hack)

**Comment by fabiosantoscode** [comment]
Hey there! Terser does not transpile code to older ES versions. The ecma option is meant to specify what kind of ecmascript your users' browser is OK with.

For instance with a high ecma option, you'll see `??` added in some situations to save bytes. Another example is emitting different kinds of string escape codes that are shorter than the alternatives available in earlier ecmascript versions.

If you use some modern JS like an async generator function, but your ecma option is, say, 5, Terser will not change it to ES5.
