### ISSUE TITLE
Why pure functions in a `void IIFE` may be removed

### ISSUE THREAD

**Issue by gdh1995** [terser/terser#1207]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V` or specific git commit)** 5.14.0

**Complete CLI command or `minify()` options used**

``` js
{
  compress: { pure_funcs: ["__awaiter"] },
  output: { beautify: true }
}
```

**`terser` input**
``` javascript
window.await_none = ((function (){
  return __awaiter(void 0, void 0, void 0);
})());
window.await_func = ((function (){
  return __awaiter(void 0, void 0, void 0, function  * () {
      console.log("foo bar")
  });
})());
window.void_await_none = void ((function (){
  return __awaiter(void 0, void 0, void 0);
})());
window.void_await_func = void ((function (){
  return __awaiter(void 0, void 0, void 0, function  * () {
      console.log(123)
  });
})());
void console.log("run 'void await' directly:")

void ((function (){
  return __awaiter(void 0, void 0, void 0, function  * () {
      console.log("here should run")
  });
})());
```

**`terser` output or error**

``` javascript
window.await_none = __awaiter(void 0, void 0, void 0),
window.await_func = __awaiter(void 0, void 0, void 0, (function*() {
    console.log("foo bar");
})),
window.void_await_none = void 0,
window.void_await_func = void 0,
console.log("run 'void await' directly:");
```

(I added extra new lines to make it easier to read)

**Expected result**

Right-hand function calling of those `void_await_*` should be kept.

**Other info**

My project has recently used `void (async() { ...  })()`, in which `void` is just to make lint tools happy, but this change causes a serious bug of function never running as reported in https://github.com/gdh1995/vimium-c/issues/646 .

**Comment by gdh1995** [comment]
Now I notice that this code is also compressed into an empty string:
``` javascript
((function (){
  return __awaiter(void 0, void 0, void 0, function  * () {
      console.log("here should run 2")
  });
})());

__awaiter(void 0, void 0, void 0, function  * () {
  console.log("here should run 3")
});

__awaiter(function() {
  console.log("here should run 4")
});
```

So, should`pure_funcs` ensure its arguments are also plain objects or pure functions?

**Comment by fabiosantoscode** [comment]
Hey there!

I think this behavior is correct. If __awaiter is really a pure function, it's not going to call the callback. We will only call it for its return value. However in this case, the return value is given to `void` and therefore eliminated.

> should pure_funcs ensure its arguments are also plain objects or pure functions?

Creating a function or plain object is a pure operation. Only calling the function can be impure.
