### ISSUE TITLE
Why can i still see the source code after build?

### ISSUE THREAD

**Issue by JessieChen5** [terser/terser#1218]
rollup-plugin-terser, after build, The first part of the min.js is confused, and the second part is the source code. There is a key for encryption in the source code. I don't want users to see this part by browser. What is the correct configuration, please?

**Comment by fabiosantoscode** [comment]
Hello!

This is the wrong repo for this issue, there's a rollup-plugin-terser repo which I don't own.

But terser is not an obfuscation tool. If the encryption key is in the input source, it will come out on the other side unless it's deemed unused (I don't recommend trusting this mechanism to guarantee dropping your keys).

If you have an encryption key, keep it on the server side and make sure it's not a part of your source code.
