### ISSUE TITLE
Inlining function with rest arguments leads to invalid code being generated

### ISSUE THREAD

**Issue by jpdutoit** [terser/terser#1226]
**Bug report**

When inlining functions using rest arguments Terser sometimes tries to spread a rest argument into a variable, which is invalid Javascript. In the example below, it seems that Terser has missed that `identity` is only using its first argument.

**Version (complete output of `terser -V` or specific git commit)**

https://try.terser.org

**Complete CLI command or `minify()` options used**
```
{
  module: true,
  compress: {
    passes: 3
  }
}
```

**`terser` input**
```
function identity(x) {
  return x
}

function outer(keyFn) {
  return function inner(...args) {
    const key = keyFn(...args)
    console.log(key)
  }
}

outer(identity)(1)
```

**`terser` output or error**
```
!function(...o){const n=...o;console.log(n)}(1);
```

**Expected result**
```
!function(...o){const n=o[0];console.log(n)}(1);
```
or
```
!function(o){const n=o;console.log(n)}(1);
```

**Comment by fabiosantoscode** [comment]
Thanks for reporting! I think I know why this happened
