### ISSUE TITLE
Using Terser with multiple files in a config

### ISSUE THREAD

**Issue by devPaulRS** [terser/terser#1228]
This is more of a informative request of configuration and usage on CLI than a feature request or bug.

I would like to know if i could use the `--config` to specify a list of files i would like to minify.

I have a media.ini listing all the file names that i would like to minify rather than placing them in a very long cli command, is it possible to for instance do the following:

**media.ini**
```
[js 1]
foo.js
bar.js

[js 2]
foo2.js
bar2.js
```

Or something similar in JSON  format and have those minified in two separate outputs in some shape or form without adding more custom things to it, these JS files already contain all the JS (large JS files), if not then i'll need to make a custom handler.

If it's possible, can someone perhaps give me an example? @fabiosantoscode

**Comment by jridgewell** [comment]
I don't believe we've documented it, but it looks like we support `files` config option:

- https://github.com/terser/terser/blob/ea5dcc3e712cb3805160d69ba37d20f48891cca5/lib/cli.js#L65-L66
- https://github.com/terser/terser/blob/ea5dcc3e712cb3805160d69ba37d20f48891cca5/lib/cli.js#L161-L162
