### ISSUE TITLE
Support ES2020 `export * as ns from 'module'` syntax

### ISSUE THREAD

**Issue by lubieowoce** [terser/terser#1231]
**Feature request**

Hi there! I've had no issues with other import/export stuff (under `--module`), but i was unable to get `export * as ns from "module"` to parse. I'm assuming this syntax simply isn't supported yet, though i'd be happy to be proven wrong 😅

(the snippet comes directly from the [introduction to the ES2020 standard](https://tc39.es/ecma262/2020/#sec-intro), so I'm assuming it's the correct syntax)

**Version (complete output of `terser -V` or specific git commit)**
terser 5.14.2

**Complete CLI command or `minify()` options used**
```
--module
```

**`terser` input**
```
export * as ns from "module"
```
**`terser` output or error**
```
Parse error at 0:1,12
export * as ns from "module"
            ^
ERROR: Unexpected token: name (ns)
```
**Expected result**

Anything better than a parse error :D
I'm not sure what the optimal (valid) output is, but acorn allows this (with `{ sourceType: 'module', ecmaVersion: 2020 }`):
```
export*as ns from"module"
```

**Comment by fabiosantoscode** [comment]
Appreciate the reminder! I thought only some obscure stuff was missing
