### ISSUE TITLE
Invalid for of/in target generated if it's a member expression with object literal

### ISSUE THREAD

**Issue by Austaras** [terser/terser#1234]
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**
latest

**Complete CLI command or `minify()` options used**
playground

**`terser` input**
```js
for ({
    x: 0,
}.x of iter()) {
    console.log(123);
}
```

**`terser` output or error**
```js
for(0 of iter())console.log(123);
```

**Expected result**
I don't know, but maybe some valid js

**Comment by fabiosantoscode** [comment]
I need a WTF JS label because I have no idea what the former is supposed to do :P

**Comment by Codezilluh** [comment]
> I need a WTF JS label because I have no idea what the former is supposed to do :P

It is just the same as this:

```js
for (const x of iter()) {
    console.log(123);
}
```

So Terser should output this when fixed:

```js
for(x of iter())console.log(123);
```

Although this probably should be fixed, I do think that we should not depend on Terser to correct every coding flaw we make. I think that a sane person would avoid doing what was shown; however, once again, I do think it should be fixed. I will go bleach my eyes now.

**Comment by fabiosantoscode** [comment]
For sure, Terser is ostensibly a compiler not an opinionated lint and it has to accept anything.

But this is cursed syntax even in comparison to things like `+!![]`

**Comment by ehoogeveen-medweb** [comment]
The `{ x: 0 }.x` doesn't create a binding called x:
```javascript
let x = 'foo';
for ({ x: 0 }.x of [1, 2, 3]) console.log(x)
```
logs `foo` three times. I think this falls into the 4th syntax of [14.7.5 The for-in, for-of, and for-await-of Statements](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-for-in-and-for-of-statements) where `{ x: 0 }.x` is a [LeftHandSideExpression](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-LeftHandSideExpression) (even though I don't think there's a way to reference it in the loop).

**Comment by fabiosantoscode** [comment]
Just for fun, you can use setters to observe `.x` being set on that object

```
for ({
    get x() {
        console.log('got x')
    },
    set x(newX) {
        console.log('set x to', newX)
    }
}.x of [1,2,3]) {
    console.log(123);
}
>set x to 1
>123
>set x to 2
>123
>set x to 3
>123
```

**Comment by fabiosantoscode** [comment]
This logs 1, 2, 3 in sloppy mode

```js
function xx(a) {
    for (arguments[0] of [1, 2, 3]) {
        console.log(a)
    }
}

xx(9)
```
