### ISSUE TITLE
terser_minifier is not a function

### ISSUE THREAD

**Issue by HadiAbbasi** [terser/terser#1235]
Hello

I've installed terser inside my project directory using:

`npm i terser  --save
`
now in my script:

```
var terser_js_minifer = require("terser");
async function jsMinify(code)
{
      try{
                console.log(await terser_js_minifer(code,{warnings: true , toplevel: false , sourceMap: true}).code);
            } catch(err) {
                 console.log(err);
            }
}

jsMinify(`
var str = "hello"; //this is our str
var myInt = 10; //this is our int
/*
	this is myFunction
*/
function myFunct(ourInt)
{
	console.log(ourInt);//console log input arg
};

myFunct(myInt); // run this function
`);

```

After testing my code:

`TypeError: terser_js_minifer is not a function
`
but it must show my minified js content!

this code is tested in 2 servers by same results! (npm version:  8.11.0)
what can I do?

**Comment by fabiosantoscode** [comment]
Hello there!

Terser does not export a function. You'll need to use terser_js_minifer.minify()

Cheers!

**Comment by HadiAbbasi** [comment]
thanks a lot...
