### ISSUE TITLE
Question: How to only enable tree-shaking?

### ISSUE THREAD

**Issue by hyrious** [terser/terser#1237]
**Question**
I recently have a [test](https://hyrious.me/tool/tree-shake.html#bGV0JTIwYSUyMCUzRCUyME9iamVjdC5kZWZpbmVQcm9wZXJ0eQ==) about tree-shaking on different tools (rollup/terser/esbuild). But I'm not familiar with terser minify options so I don't know how to correctly configure it to _only perform tree-shaking_. Currently I just enabled `module: true`.

Even with just `module: true`, I found some interesting behavior that it seems terser does not mark <q>known-static-global-variables</q> as pure. Like `Math.sin`, `console.log`, etc. While it does mark many instance methods as pure, like [`[].slice`](https://hyrious.me/tool/tree-shake.html#bGV0JTIwYSUyMCUzRCUyMCU1QiU1RC5zbGljZQ==).

So I come here to ask for help about whether I was missing some terser options, or terser just works as is.

If terser does work as is, the <q>pureness intersection</q> of terser and esbuild will be almost nothing. Which means [some kind of code](https://cdn.jsdelivr.net/npm/lib0@0.2.52/math.js) can only be minified in one tool while not in another. Then the minification comparison will differ a lot according to the coding style of the author, for example:

```js
let hasProp1 = Object.prototype.hasOwnProperty // only tree-shakeable in esbuild
let hasProp2 = {}.hasOwnProperty // only tree-shakeable in terser
```

Fortunately there aren't many examples like above since esbuild is too ~~pedantic~~careful to include more <q>known-globals</q>.

**Version (complete output of `terser -V` or specific git commit)**
5.14.2

**Complete CLI command or `minify()` options used**
```js
terser.minify(code, { module: true })
```

**`terser` input**
```js
let a = Object.defineProperty
```

**`terser` output or error**
```js
Object.defineProperty
```

**Expected result**
```js
// nothing
```

**Comment by fabiosantoscode** [comment]
You can't really enable only tree-shaking, as the Terser compress step will do a lot of things even with all options disabled (turning `undefined` to `void 0` for instance).

But you could use something like the following to first disable most compression, and then re-enable unused code removal.

```
{
  module: true,
  compress: { defaults: false, unused: true },
  mangle: false,
}
```

It will also remove all whitespace :)

**Comment by gaoanyuan** [comment]
> referenced
How to preserve whitespace ? Removed whitespace make the source code difficult to understand !
