### ISSUE TITLE
Class with effectful accessor is wrongfully removed

### ISSUE THREAD

**Issue by Austaras** [terser/terser#1244]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser playground

**Complete CLI command or `minify()` options used**

default

**`terser` input**
```js
class A {
  static get proto() {
    console.log(111)
  }
}

A.proto
```

**`terser` output or error**
Entire file is removed.

**Expected result**
Preserve side effect.

**Comment by fabiosantoscode** [comment]
Hello! 

This is purposeful behaviour, some laxness to help tree-shaking. Getters are assumed to be pure in this and some other situations.

Is this causing an issue with real world code?

**Comment by Austaras** [comment]
Well, no, I'm just testing terser with babel tests.
