### ISSUE TITLE
[Feature request] allow keep `=== null` `=== void 0` not `== null`

### ISSUE THREAD

**Issue by bluelovers** [terser/terser#1260]
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

```js
(name === null || name === void 0 ? void 0 : name.toUpperCase())
(name?.toUpperCase())
```

**`terser` output or error**

```js
(null == r ? void 0 : r.toUpperCase())
```

**Expected result**

```js
(null === r || void 0 === name ? void 0 : r.toUpperCase())
```

**Comment by fabiosantoscode** [comment]
Hello there!

What's the issue? Terser is yielding a shorter output.
