### ISSUE TITLE
String literal expression is not preserved with `--compress expression`

### ISSUE THREAD

**Issue by polytypic** [terser/terser#1273]
**Bug report**

For some reason, a string literal expression is completely removed from the compress output while e.g. a number literal expression is not.  Here is a shell interaction with various related behaviours:

```sh
➜  terser terser --version
terser 5.15.1
➜  terser terser --compress expression <<EOF
"Hello, world!"  
EOF

➜  terser terser --compress expression <<EOF
42               
EOF
42;
➜  terser terser --compress expression <<EOF
\`Hello, world!\`
EOF
;"Hello, world!";
```

**Version (complete output of `terser -V` or specific git commit)**

```sh
➜  terser terser --version
terser 5.15.1
```

**Complete CLI command or `minify()` options used**

```sh
➜  terser terser --compress expression <<EOF
"Hello, world!"  
EOF

```

**`terser` input**

```js
"Hello, world!"
```

**`terser` output or error**

Empty &mdash; the string literal is eliminated from output.

**Expected result**

```js
"Hello, world!";
```

**Comment by jridgewell** [comment]
When a string appears at the start of a program (or a function body), it's a [directive](https://tc39.es/ecma262/multipage/ecmascript-language-source-code.html#sec-directive-prologues-and-the-use-strict-directive) and not a string. Think `"use strict";`. So we've eliminated a useless directive, not a string literal.

**Comment by polytypic** [comment]
Interesting.  What if the input also includes a directive:

```sh
➜  terser --compress expression <<EOF
"use strict";
"Hello, bug!"
EOF
"use strict";
```

In the above example, the directive is preserved, but the following string literal is not.

However, if the string literal is replaced with a number literal, it is preserved:

```sh
➜ terser --compress expression <<EOF
"use strict";
101
EOF
"use strict";101;
```

Is the case with the directive followed by a string literal still the desired behaviour?

**Comment by jridgewell** [comment]
```
"use strict";
"Hello, bug!"
```

That's 2 directives statements:

> longest sequence of ... where each ExpressionStatement in the sequence consists entirely of a StringLiteral token

To stop directive parsing, you need to insert a non-string statement. Eg:

```
;
"Hello, world!";
```

Is not a directive, which is why the 3rd output from OP is `;"Hello, world!";`, it printed the string ``` `Hello, world!` ``` as a regular double quote, and had to insert a leading `;` to prevent it from being parsed as a directive.
