### ISSUE TITLE
[Feature request] Rollup plugin

### ISSUE THREAD

**Issue by syranide** [terser/terser#1276]
**Bug report or Feature request?**

Feature request

**Information**

It seems the only Rollup plugin for terser that really exists is https://github.com/TrySound/rollup-plugin-terser, which seems abandoned, not updated for 2 years. So it's both depending on an old terser version, as well as not supporting the recently released Rollup 3. Even your README suggest to use terser with Rollup, so it doesn't seem like an esoteric use-case.

Would you consider maintaining your own official plugin for Rollup that would be more properly maintained?

**Comment by mishankov** [comment]
Found some recent alternatives:
- https://github.com/sjinks/rollup-plugin-terser
- https://github.com/wutility/rollup-terser

But official plugin will be definetly better

**Comment by dasa** [comment]
> But official plugin will definetly be better

PR https://github.com/rollup/plugins/pull/1323

**Comment by lpellegr** [comment]
I am looking forward to seeing an official terser plugin for Rollup!

**Comment by mahozad** [comment]
The [official rollup terser plugin](https://github.com/rollup/plugins/tree/master/packages/terser) is out.

But I'm getting the following warning from rollup:

```text
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "terser") should generate accompanying sourcemaps.
```

I tried to config the terser like this in my *rollup.config.mjs* file:

```javascript
import terser from '@rollup/plugin-terser';

export default {
    input: "src/main.js",
    output: [
        {
            file: "dist/theme-switch.min.js",
            format: "iife",
            validate: true,
            sourcemap: true,
            name: "themeSwitch",
            plugins: [terser({
                sourceMap: {
                    filename: "theme-switch.min.js",
                    url: "theme-switch.min.js.map"
               }
            })]
        }
    ]
};
```

and this is the result *theme-switch.min.js.map* file:

```text
{"version":3,"file":"theme-switch.min.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}
```

Could you please help me?

**Comment by syranide** [comment]
As above, official rollup plugin for terser exists now.
