### ISSUE TITLE
Feature Request: Minify multiple bundles with the same mangled props context

### ISSUE THREAD

**Issue by mckravchyk** [terser/terser#1277]
Use case:

Props can be mangled by regex, i.e. by adding a trailing underscore to props to be minified and adding a regex to target.

The use case is for Electron apps or any apps which share APIs in multi-process context, which require multiple output bundles for each process. Terser allows to mangle props, the most practical approach is to apply a convention where your own props are accompanied by a trailing underscore and target it by regex. However, this is not going to work across processes / bundles and requires to be mindful about not mangling props of objects which are passed between processes - which results in an inconsistent pattern, where some props use underscores and some not.

Possibly related to https://github.com/terser/terser/issues/544 but the goal is to just ensure that different files can be minified in the same mangling context and output separately - they don't have to be taken at once. *In fact, it would even be preferable (for use with module bundlers), if this could be used separately.* I.e.

- Given a special argument, Terser would cache the mangling context and return its id
- When minifying another file, the id of the mangling context would be passed as an argument

but implementing it as a part of the previously mentioned issue would work too :)

**Comment by fabiosantoscode** [comment]
There exists a minify() option called `nameCache`, which gets mutated ( 🤮 ) and then you can use the same object again in further minification.

Look for "nameCache" under here.

https://github.com/terser/terser#api-reference
