### ISSUE TITLE
[Bug]: Terser removes a name of super class

### ISSUE THREAD

**Issue by p51lee** [terser/terser#1285]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
```console
$ terser -V
terser 5.15.1
```
**Complete CLI command or `minify()` options used**
I turned off the `unsafe` option.
```console
$ terser input.js -c unsafe=false
```

**`terser` input**
```js
class x extends function f ( ) { } { };
console.log(Object.getPrototypeOf(x).name);
```

**`terser` output or error**
```js
class x extends function(){}{}console.log(Object.getPrototypeOf(x).name);
```

**Expected result**
Executing the output code,  `f` is expected to be printed but nothing was printed out.

```console
$ node -e 'class x extends function f ( ) { } { }; console.log(Object.getPrototypeOf(x).name);' // input code
f
$ node -e 'class x extends function(){}{}console.log(Object.getPrototypeOf(x).name);' // output code

```

**Comment by fabiosantoscode** [comment]
Thanks for the report but this is intended. The option `keep_fnames` can be used to disable this behavior.
