### ISSUE TITLE
[Bug]: hoisted var declaration will causing unexpected simplification

### ISSUE THREAD

**Issue by hyf0** [terser/terser#1306]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

playground

**Complete CLI command or `minify()` options used**

playground

**`terser` input**

```js
(function () {
	var first = state();
	var on = true;
	var obj = {
		state: state
	};
	log(first)
	log(obj.state());
	function state() {
		return on ? "ON" : "OFF";
	}
})();


```

**`terser` output or error**

![image](https://user-images.githubusercontent.com/49502170/201505471-f07cd283-4a7b-4552-bfe5-d739da6437ed.png)

__If enable these options, there will be a correct output__
![image](https://user-images.githubusercontent.com/49502170/201505529-fe876ce4-6131-4879-9505-6a00999996c6.png)

**Expected result**
`return on ? "ON" : "OFF";` should not be simplify to `return "ON"`

**Comment by fabiosantoscode** [comment]
Created a smaller repro

```js
var first = log_on();
var on = true;
function log_on() {
    console.log(on === undefined ? "PASS" : "FAIL")
}
```

And here are the options needed to reproduce, with default options excluded

```json
{
  compress: {
    defaults: false,
    toplevel: true,
    reduce_vars: true,
    unused: true,
    evaluate: true
  }
}
```
