### ISSUE TITLE
No more class chaining since 5.15.1 (class C extends class B extends class A)

### ISSUE THREAD

**Issue by VandeurenGlenn** [terser/terser#1308]
**Bug report or Feature request?**
One of the two ^^

**Version (complete output of `terser -V` or specific git commit)**
v5.15.1
**Complete CLI command or `minify()` options used**
```js
{
    mangle: false,
    keep_classnames: true,
    ecma: 6
}
```

**`terser` input**

```js
class A  {
  constructor() {
    console.log('super')
  }
}

class B extends A {
  constructor() {
    super()
  }
}

class C extends B {
  constructor() {
    super()
  }
}

export { C as default } 
```

**`terser` output or error**
```js
class A {constructor(){console.log('super')}}class B extends A{constructor(){super()}}class C extendsB{constructor(){super}}
```
**Expected result**
```js
class C extends class B extends class A {constructor(){console.log('super')}}{constructor(){super()}}{constructor(){super()}}
```

**Comment by fabiosantoscode** [comment]
Classes aren't inlined anymore in some cases to prevent them being created multiple times and then being !== from themselves after a compilation (eg https://github.com/terser/terser/issues/1267).

It's really tricky to analyze whether something will be executed multiple times (and specializing that for Extends), so I think this is a good trade-off for less scoping bugs, assuming it doesn't increase source code size a lot.

**Comment by VandeurenGlenn** [comment]
@fabiosantoscode Thanks for the answer, only problem here is that if I try to put the result as text in a 'new Function(code)'
It fails now, I tried multiple ways like adding semicolon after each class etc but no success, only seems to work when the classes are inlined, any ideas?

**Comment by fabiosantoscode** [comment]
Try adding returning the class you want the function to return. You'll need to add the bare_returns parse option so Terser doesn't think the `return` outside a function is a syntax error.

**Comment by VandeurenGlenn** [comment]
Thanks, I missed the bare_returns option
