### ISSUE TITLE
Project built by vue-cli3,terserPlugin drop_console does not take effect,node version 18.12.1,terser-webpack-plugin version 5.3.6

### ISSUE THREAD

**Issue by haoyuxin** [terser/terser#1309]
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

**`terser` output or error**

**Expected result**

**Comment by haoyuxin** [comment]
module.exports.configureWebpack.optimization: {
            minimize: true,
            minimizer: [
                new TerserPlugin({
                    extractComments: false,
                    terserOptions: {
                        format: {
                            comments: false,
                        },
                        compress: {
                            warnings: true,
                            drop_console: true,
                            drop_debugger: true
                        }
                    }
                })
            ]
        },

**Comment by fabiosantoscode** [comment]
`drop_console` seems to be working properly. A common reason for options like this not to work is if your source code (or the source code from your compiler) defined a `console` variable somewhere in-scope.

```
console.log("removed")

{
  const console = window.console
  console.log("not removed")
}
```
