### ISSUE TITLE
[Bug] Compressing switch statement results in loose equality instead of strict equality

### ISSUE THREAD

**Issue by f52985** [terser/terser#1315]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 5.16.1

**Complete CLI command or `minify()` options used**
`terser sample.js -c`

**`terser` input**
```js
switch ( -1 ) {
  case -1n: console.log("BigInt"); break;
  case -1: console.log("Number"); break;
}

// > 'Number'
```

**`terser` output or error**
```js
if(-1==-1n)console.log("BigInt");else console.log("Number");

// > 'BigInt'
```

**Expected result**
```js
if(-1===-1n)console.log("BigInt");else console.log("Number");

// > 'Number'
```

**Additional context**
Terser transforms certain switch statements into a if statement with **Loose equality**, although **Strict equality** should be used according to the [specification](https://262.ecma-international.org/13.0/#sec-runtime-semantics-caseclauseisselected:~:text=4.%204.%20Return%20IsStrictlyEqual(input%2C%20clauseSelector).).
Strangely enough, this behavior seems to be only observed when the selector of switch is not a literal. For example, terser correctly transforms `switch (-1) { case 1n: .... }` into `if(-1===1n) ...`.

**Comment by fabiosantoscode** [comment]
Hello there! Appreciate the report

**Comment by fabiosantoscode** [comment]
Here's a more minimal repro

`if (-1 !== -1n) console.log('PASS')`

The specific option responsible is comparisons, IE `{defaults: false, comparisons: true}` is the minimal set of options to make this fail.
