### ISSUE TITLE
Terser 5.16.3 has larger output

### ISSUE THREAD

**Issue by AndrJ** [terser/terser#1338]
Terser 5.16.3 has larger output.
The execution results are the same, but the output is larger.
5.16.2 is clearly better.
Thank you.

```
(function () {
  const DEBUG = false;

  function log() {
    if (DEBUG) {
      console.log("DEBUG");
    } else {
      console.log("No DEBUG");
    }
  }
  Promise.resolve().then(log);
})();
```
-------------
Terser options: all Default

Terser 5.16.3
`!function(){const o=!1;Promise.resolve().then((function(){o?console.log("DEBUG"):console.log("No DEBUG")}))}();`

Terser 5.16.2
`Promise.resolve().then((function(){console.log("No DEBUG")}));`

**Comment by fabiosantoscode** [comment]
Function definitions are hoisted, and Terser wasn't dealing with it. I [detached them](https://github.com/terser/terser/commit/7f6187a461340451c2f6bfd2cfd6544de24844a8) from some optimization flows for this reason, but I'm sure I can fix some cases without throwing the baby out with the bathwater.

**Comment by cbratschi** [comment]
Using 5.16.3 does not remove our debug constant anymore:

```JavaScript
```

**Comment by fabiosantoscode** [comment]
A possible workaround for this issue is to increase the compress.passes option.

**Comment by cbratschi** [comment]
@fabiosantoscode We are using 5 passes right now.

**Comment by taozhou-glean** [comment]
should we expect this to be resolved soon ? like in next release ? ;) trying to see if we should pin the version down to 5.16.2 or just wait for the next release

**Comment by fabiosantoscode** [comment]
This is a pretty slow project. I'd pin the version.

It's probably possible to reduce size here but in general, not all Terser versions will decrease or maintain output size. In some situations, being bug-free means that assumptions can't be made.

For instance, there's an open bug pointing out that math operators like `+` can sometimes throw. So Terser has to stop assuming every `+` operation is safe, which limits what code can be removed and moved around.

**Comment by jakutis** [comment]
Having the same issue with 5.16.3, 5.16.4, 5.16.5. Setting compress.passes to 5 does not help. So pinning to version 5.16.2 for now.

**Comment by cbratschi** [comment]
@fabiosantoscode just upgraded to 5.16.6 and in one file still seeing:

```
'use strict';const DEBUG_FETCH=!1;...
```

It is now better but this case was fully optimized away with 5.16.2. So still keeping the older version.

**Comment by cbratschi** [comment]
Just upgraded another project and four files contained debug constants which are always set to false and which were previously optimized away (terser 5.17.1 against 5.16.2):

```
'use strict';var DEBUG=!1,DEBUG_MESSAGES=!1,DEBUG_AD=!1,...;DEBUG&&console.log('notifyPlay: '+d);...

'use strict';var DEBUG=!0,DEBUG_PROGRESS=!1;..
```

Another case where both lazy load values are kept:

```
'use strict';var USE_LAZY_LOAD=!0;...
```

Therefore downgraded again to 5.16.2.

**Comment by cbratschi** [comment]
@fabiosantoscode Yes, #1382 is the same issue. Tried now version 5.17.5 and it works fine. Thanks a lot.

**Comment by fabiosantoscode** [comment]
Glad that's out of the way :) this had me worried for a while. I didn't want to reintroduce the #1306 bug

**Comment by cbratschi** [comment]
@fabiosantoscode actually just updated another project which has some debug values again. It took me some time to remove some code to still reproduce it:

```JavaScript
'use strict';

const DEBUG = false;

function initPlayer() { // eslint-disable-line
    const player = new createPlayer();

    return player;
}

function createPlayer() {
    if (DEBUG) {
        console.log('-> new player');
    }

    this.destroy = () => {
        if (DEBUG) {
            console.log('-> destroyed player');
        }
    };
}
```

This minifies to:

```JavaScript
'use strict';var DEBUG=!1;function initPlayer(){return new createPlayer}function createPlayer(){DEBUG&&console.log('-> new player');this.destroy=function(){DEBUG&&console.log('-> destroyed player')}}
```

Used Terser options:

```JavaScript
const TERSER_OPTS = {
    compress: {
        top_retain: terserTopRetain,
        passes: 5,
        sequences: false
    },
    output: {
        quote_style: 1
    }
};

function terserTopRetain(def) {
    if (def.name.startsWith('DEBUG')) {
        return false;
    }

    if (def.name === 'USE_LAZY_LOAD') {
        return false;
    }

    return true;
}
```
