### ISSUE TITLE
dead code not removed behind local `false` constant vs global_defs

### ISSUE THREAD

**Issue by taozhou-glean** [terser/terser#1340]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

latest or whatever is used in https://try.terser.org/ as of now.

**`terser` input**

 tersor option

```
{
  module: true,
  compress: {global_defs: {
            DEBUG: false
        }},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

input:

```
const isDebug = false

const b = true

function init() {
  if (isDebug) {
    if (!b) {
      throw new Error("dddd")
    }
  }
  
  if (DEBUG) {
    if (!b) {
      throw new Error("dddd")
    }
  }
}

init()
```

output:

```
const d=!1,n=!0;!function(){if(d&&!n)throw new Error("dddd")}();
```

**Expected result**

expect the branch under `if(isDebug)` should also be removed just like `DEBUG`

**Comment by taozhou-glean** [comment]
looks like the code is not removed even if I do `isDebug = DEBUG` at the beginning

**Comment by fabiosantoscode** [comment]
Hi! This is the same issue as #1338 so I'm closing.
