### ISSUE TITLE
Compression opportunity: shorten names of private class methods?

### ISSUE THREAD

**Issue by hooperbloob** [terser/terser#1350]
New to Terser so apologies if I'm revisiting a dead topic but was wondering if private methods in a module could be shortened/renamed the same way class names currently are. I know that use of the '#' prefix on method names isn't universal so if the user could specify a chosen prefix, i.e. an underscore, to identify pvt methods then renaming/shortening the name and all references to it should be safe to do, no?

**Comment by fabiosantoscode** [comment]
https://github.com/terser/terser#cli-mangling-property-names---mangle-props

Have a look at the "properties" mangle option, but this is a pretty dangerous transform and I don't recommend it unless your codebase is small and has few (ideally zero) dependencies.
