### ISSUE TITLE
Boolean not compressed when inlined multiple times

### ISSUE THREAD

**Issue by nicolo-ribaudo** [terser/terser#1352]
**Bug report or Feature request?**

Missing optimizations

**Version (complete output of `terser -V` or specific git commit)**

https://try.terser.org/ as of 2023-03-06

**Complete CLI command or `minify()` options used**

```json5
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
let x = true;

fn(x, x);
```

**`terser` output or error**

```js
fn(true,true);
```

**Expected result**

```js
fn(!0,!0);
```

Note that when the variable is not inlined or it's inlined just once, `true` is properly replaced with `!0`:
- `let x = true; f(x,x,x)` becomes `let x=!0;f(x,x,x)`
- `let x = true; f(x)` becomes `f(!0)`

**Comment by jridgewell** [comment]
You need to enable more passes:

```
{
  module: true,
  compress: {
    passes: 2
  },
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

The first pass inlines `true` everywhere `x` is used, and the second transforms to `!0`. I'm not sure why the single use case is special.

**Comment by nicolo-ribaudo** [comment]
Thank you 👍
