### ISSUE TITLE
Cannot parse object with number as key

### ISSUE THREAD

**Issue by tranvansang** [terser/terser#1354]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**

I use web playground to test: https://try.terser.org/

**Complete CLI command or `minify()` options used**

**`terser` input**

`{1: 2}`

**`terser` output or error**

Error: `Unexpected token: punc (:)`

**Expected result**

Empty output or the same as the input

**Additional information**

Same as issue https://github.com/terser/terser/issues/967
My webpack output is below. Currently, I cannot minify webpack output.

```javascript
"use strict";
{

/***/ 8599:
/***/ (function(module) {

/*globals self, window */


/*eslint-disable @mysticatea/prettier */
const { AbortController, AbortSignal } =
    typeof self !== "undefined" ? self :
    typeof window !== "undefined" ? window :
    /* otherwise */ undefined
/*eslint-enable @mysticatea/prettier */

module.exports = AbortController
module.exports.AbortSignal = AbortSignal
module.exports["default"] = AbortController


/***/ })

};
//# sourceMappingURL=599.f9887edef7767dfbf67b.js.map

```

**Comment by fabiosantoscode** [comment]
Hello there! This is invalid JS code. To distinguish an object from a block statement, you need to wrap it in parentheses.

`({ hello })` -> Object with the key "hello"
`{ hello }` -> A block statement containing a reference to the variable "hello"

I'm curious as to what combination of webpack options and plugins causes it to output this.

**Comment by tranvansang** [comment]
In Chrome

```javascript
{1:2}
a=10
{a}
```

is parsed normally.

![image](https://user-images.githubusercontent.com/13043196/226754943-83708d4b-88ad-41bb-bd89-26bdc3a2f361.png)

> { hello } -> A block statement containing a reference to the variable "hello"

Do you mean that `foo = {bar}` is the assignment of a block statement to variable foo?

**Comment by tranvansang** [comment]
well, `node -e "{1:2}"` gives an error, though.
Probably, you are true.

```
node -e "{1:2}"                                                                     
[eval]:1
{1:2}
  ^

SyntaxError: Unexpected token ':'
    at new Script (node:vm:100:7)
    at createScript (node:vm:259:10)
    at Object.runInThisContext (node:vm:307:10)
    at node:internal/process/execution:79:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:78:60)
    at node:internal/main/eval_string:28:3

Node.js v18.14.2
```

**Comment by fabiosantoscode** [comment]
I'm guessing the chrome console has some magic in it. If you're trying out creating some objects, you don't want chrome to come up to you like "🤓 well aaactually"
