### ISSUE TITLE
`undefined` as default parameter is preserved since 5.16.6

### ISSUE THREAD

**Issue by ericfortis** [terser/terser#1366]
**`terser` input**
```js
function foo(a = undefined) { return a; }
alert(foo())
```

**`terser` output or error** (5.16.6+)
```js
alert(function(n=undefined){return n}());
```

**Expected result** (5.15.5)
```js
alert(function(n){return n}());
```

---
**Why do I write signatures like that?**
In WebStorm, there's a "Signature Mismatch" inspection but it doesn't handle optional parameters. Therefore, in those cases I add `undefined` as default value.

**Comment by fabiosantoscode** [comment]
I'm noticing more than a few optimization opportunities here (all that should be just `alert(void 0)` but the default parameter is being preserved because removing it changes the function's .length property.

I guess it can be done if we know about all the function's calls.

**Comment by fabiosantoscode** [comment]
I'm pushing a partial fix (it's really fast and easy to detect a function is an IIFE). For your case (which I'm sure is not just IIFE) you can try disabling the keep_fargs option, which makes functions' lengths not important, and therefore `= undefined` considered safe to remove.
