### ISSUE TITLE
Terser breaks ability to debug

### ISSUE THREAD

**Issue by olfek** [terser/terser#1367]
I have this in my webpack config

```
...
optimization: {
    minimize: true,
    minimizer: [new TerserPlugin(
        {
            terserOptions: {
                sourceMap: {
                    content: 'inline',
                    includeSources: true,
                    url: 'inline'
                }
            }
        })],
},
...
```

Everything is `undefined` when stepping over code in the browser.

Switching mangle off makes the problem go away.

Why is this happening? 😕😕😕

When Terser mangles, does it _**not**_ update the sourcemap with information to de-mangle?

**Comment by ehoogeveen-medweb** [comment]
Yes, if identifiers are inlined or otherwise optimized out (like by a browser's JIT compiler), no mapping can take place. But this is a separate problem from mangling, since unmangled symbols can be inlined too (it might even be *more* worthwhile to inline them since they are longer).

**Comment by fabiosantoscode** [comment]
Hi all

This is the heart of the sourcemap output. Something that can be easily changed here is opting in more nodes:

https://github.com/terser/terser/blob/master/lib/output.js#L2365-L2418

But from what I understand from the comments, the problem here was not Terser's fault?

**Comment by ehoogeveen-medweb** [comment]
Sounds like in this case it was a problem with the Firefox devtools configuration, and in general I don't think it's terser's fault when scope mapping fails.

But thank you for the reference! I completely missed that list. I'll have to find some time to experiment with extending the list of AST nodes to see if it fixes my TypeScript debugging woes.
