### ISSUE TITLE
Terser replacing `;` to `,`

### ISSUE THREAD

**Issue by renhiyama** [terser/terser#1376]
```js
//config for terser
{
  module: true,
  compress: {},
  output: {},
  parse: {},
  rename: {},
}
```

```js
// sample code
import Surreal from "surrealdb.js";

const db = new Surreal(Deno.env.get("DB_URL"));

await db.signin({
  user: Deno.env.get("DB_USER"),
  pass: Deno.env.get("DB_PASSWORD"),
});

await db.use("test", "test");

export default db;
```

---

### Result

```js
import e from"surrealdb.js";const t=new e(Deno.env.get("DB_URL"));await t.signin({user:Deno.env.get("DB_USER"),pass:Deno.env.get("DB_PASSWORD")}),await t.use("test","test");export default t;
```

Do note that in original code, after `db.signin()` function, there's `;` but in compiled code, it shows `,`.

**Comment by Conduitry** [comment]
Does the resulting code not work? Are you aware of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator ?

**Comment by renhiyama** [comment]
The resulting code doesnt work on deno deploy 🤔

**Comment by fabiosantoscode** [comment]
Hi there!

You can disable these commas by disabling the `sequences` compress option.

It doesn't seem like the error comes from that (since the output code is valid), but if the error disappears after removing that option, please reopen with more details.

Cheers!
