### ISSUE TITLE
`terser @ 5.16.9 -> 5.17.0` breaks `core-js`

### ISSUE THREAD

**Issue by zloirock** [terser/terser#1379]
Steps to reproduce:

- Clone [`core-js`](https://github.com/zloirock/core-js)
- Run all tests (`npm run r`)
  - All tests passed
- Bump `terser` `5.16.9 -> 5.17.0` [here](https://github.com/zloirock/core-js/blob/v3.30.1/scripts/bundle-package/package.json#L4)
- Re-run tests with updated `terser` (`npm run r`)
  - A significant part of unit tests fails

Now I do not have no enough time to dig what transform causes this problem. One of the problem cases is `JSON.stringify` wrapper from [this module](https://github.com/zloirock/core-js/blob/v3.30.1/packages/core-js/modules/esnext.json.raw-json.js).

**Comment by fabiosantoscode** [comment]
Hello there! I think this is a duplicate of #1380. Please try the just-released 5.17.1 that fixes it

**Comment by zloirock** [comment]
Yes, thanks, it seems it's fixed.
