### ISSUE TITLE
Dead code elimination is broken in some caes

### ISSUE THREAD

**Issue by manucorporat** [terser/terser#1382]
**Bug report or Feature request?**
Bug report, can be easily reproduced in the REPL.

**`terser` output or error**

```

const qDev = false;

function assertEqual() {
    if (qDev) {
        throw new Error('SHOULD BE REMOVED')
    }
}

export {assertEqual}


export class ReadWriteProxyHandler {
    set() {
        if (qDev) {
            if (invokeCtx) {
            }
        }
    }
}
```

Generates:
```
const r=!1;function e(){if(r)throw new Error("SHOULD BE REMOVED")}export{e as assertEqual};export class ReadWriteProxyHandler{set(){r&&invokeCtx}}
```

**Expected result**
Notice that dead code elimitation is not working, if removing the class, or the exported function... it works.

**Comment by manucorporat** [comment]
For Qwik this means a ~20KB regression for the optimized bundle:

    "terser": "5.16.2",
```
🐭 core.min.mjs: { original: '63.5kb'}
```

    "terser": "5.17.1",
```
🐭 core.min.mjs: { original: '80kb'}
```

**Comment by fabiosantoscode** [comment]
Thanks for the repro! Will look into it
