### ISSUE TITLE
[Question] Does terser have rules about styling (or css in js) code?

### ISSUE THREAD

**Issue by yishayweb** [terser/terser#1383]
**Bug report or Feature request?**
It's more of a question, because I'm not sure if it is a bug

**Version (complete output of `terser -V` or specific git commit)**
terser 5.17.1

I'm using terser through the terser-webpack-plugin in this case, but I think this is a terser behavior
The portion of the code I'm asking about is this:

```
const TextIconStyle = styled$1('div', {
    shouldForwardProp: (prop) => !['hoverFlag', 'iconLocation'].includes(prop),
})(({ hoverFlag, iconLocation }) => ({
    padding: '5px 15px 5px',
    lineHeight: '1.5rem',
    '& .this-is-some-class': {
        alignSelf: 'center',
        color: 'green',
    },
}));

const TextWithIcon = ({ iconLocation = 'left', text, onClick, }) => {
    return (jsxs(StyledText, Object.assign({ hoverFlag: !!onClick, iconLocation: iconLocation }, { children: ["Hi the icon with text:", jsx("div", Object.assign({ className: "this-is-some-class" }, { children: text }), void 0)] }), void 0));
};
```
This is part of a transpiled code with React component - **TextWithIcon**, and a css in js object (styled utility of material-ui) - **TextIconStyle**
When I bundle this with webpack, the **TextWithIcon** code is removed but the **TextIconStyle** is not removed, although they are both unused in the app. It looks like the TextIconStyle is not removed because it contains code that relates to styling.
So the question is: does terser have some logic or rules about css in js code that instruct it not to remove styling related code?
(btw, if I annotate the TextIconStyle with `/*@__PURE__*/` the code is removed)

Thanks !!

**Comment by fabiosantoscode** [comment]
No rules about css-in-js at all!

To Terser, `style$1` is just some regular old variable, which it knows nothing about.

I think some css-in-js tools produce the pure comment you mention, to indicate to Terser that it's OK to remove (IE doesn't throw, doesn't cause side effects).
