### ISSUE TITLE
IIFE in static field has incorrect this after minification

### ISSUE THREAD

**Issue by mischnic** [terser/terser#1385]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

5.17.1

**Complete CLI command or `minify()` options used**

`terser x.js -mc`

**`terser` input**

```js
let Foo = (()=>{
    let _classThis;
    var Foo = class {
        static #_ = (()=>{
            Foo = _classThis = this;
        })();
        foo(){
            return 2;
        }
    };
    return Foo = _classThis;
})();
console.log(new Foo().foo());
```

This is a very real input unfortunately, coming from [tsc](https://www.typescriptlang.org/play?target=9&ssl=11&ssc=1&pln=1&pc=1#code/MYewdgzgLgBAwgV2iAtgUQDYFMVbLAXhgAooBDAcwC4ZoAnASzAoEoYCA+GAbwCgYYdLFAR0wMADwAVGFgAeUPABMIMMFgDuJNpxgAJKQFkAMphx4oHYvwExgUEHRpSANDYGh88qDTgYyEBAAIligdGQOdHDgigrSHDY6XHy2duAQINgAdBggFMQAROQUBS52kWWesVAsANzugsKi4vaO9QIAvvVdvLwAAojI6Ni4+IWgKAAO4BYAtGQFLLzA-oEwAIKyCsqqBiZmo7ApaZBQdAitdMRsxwIQCJNYV3UNUAAWDBBZTOp0e8bsGAFaJTGb4DYwT4wDSOADWTBK7RgHV4KOW6UyWByeWI6i062uWWKADkyLgXkA) via [Babel/swc](https://babeljs.io/repl#?browsers=Chrome%2090&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=DYUwLgBAghC8EAoEEo4D4IG8BQE8VEgH0BjYAQwGdKAREEgewCdyxnK4IBtAYQFdKbALYBRUEJAA7MAgBEjIQAcGkqWAC05WcgC6Ablz5CEUhWp1KJJgEtFbJgfwFwJslUoiAHmBYBJSdZg1uTA1gBeIEwc8Fz6hnjGpu4AKgAW1pSO-ABu5EzQnG7UECDeUgAmHAASyQCyADJiIBLSWPFOEIKs1iRtHf0mRCC09MysIAiSfMDAADSuZiOWNnbMnJgQucB8IABcEGDpHAC-80nmoyz2lPMbANbWkuX78ouy85LkEvuHGQB0nwkEFOECmMzORQ83j8ASCIXCkUoyCyA3wMHg50oaQynExFistnsfy2OxRqMGTD4kn8gWCoQiUQQmOxNwW7i8PnINLh9MRyPaTmOAvwjEkgkpJHsKD65LwlD4ikiKDJqN-lD-j1UTBqDU4sh4DCUKjUBRxAHdmA9JABzWQq_BCwVkpjgPhMSQFDGQlkGY7IZVAA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.21.8&externalPlugins=&assumptions=%7B%7D)

**`terser` output or error**

`this` now points to the undefined/global object instead of `Foo`
```js
let Foo=(()=>{let o;(()=>{o=this})();return o})();console.log((new A).foo());
```

Note that it works fine with using a proper `static { }` block instead of the `static #_ = (()=>{})()` fallback

**Expected result**
Class is retained?

**Comment by fabiosantoscode** [comment]
Thanks for reporting!

**Comment by fabiosantoscode** [comment]
This can be reproduced with `{ defaults: false, unused: true }` compress options.

**Comment by fabiosantoscode** [comment]
See, this is why I don't sleep at night :D 

It's fixed, I should release tomorrow.
