### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sameerthiteipro** [terser/terser#1402]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
4.8.1
also tried below
4.1.2
4.3.9
tried version which given in stackoverflow answers also like below
run npm iterser@3.14

"react-scripts": "4.0.1",
"react": "17.0.1",
"react-dom": "17.0.1",
Node 14.20.0
NPM 6.14.17
Webpack 4.44.2
Ubuntu 22.04.2 LTS (build creation is working on Ubuntu 20)

**Complete CLI command or `minify()` options used**
react-csp stage && REACT_APP_BUILD_ENV='stage' react-scripts --max_old_space_size=4096 build && gulp licenses

**`terser` input**

**`terser` output or error**
```
Failed to compile.

Failed to minify the bundle. Error: static/js/main.efa683f7.chunk.js from Terser
RangeError: Maximum call stack size exceeded
    at /home/sameer/Dev/Projects/admin-panel/node_modules/react-scripts/scripts/build.js:188:23
    at finalCallback (/home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/Hook.js:154:20)
    at /home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/Hook.js:154:20)
    at /home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sameer/Dev/Projects/admin-panel/node_modules/tapable/lib/Hook.js:154:20)
    at /home/sameer/Dev/Projects/admin-panel/node_modules/webpack/lib/Compilation.js:1414:32
Read more here: https://cra.link/failed-to-minify

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon-dashboard-pro-react@1.2.0 build_staging: `react-csp stage && REACT_APP_BUILD_ENV='stage' react-scripts --max_old_space_size=4096 build && gulp licenses`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon-dashboard-pro-react@1.2.0 build_staging script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

npm debug log:
```
13 verbose stack Error: argon-dashboard-pro-react@1.2.0 build_staging: `react-csp stage && REACT_APP_BUILD_ENV='stage' react-scripts --max_old_space_size=4096 build && gulp licenses`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/sameer/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/home/sameer/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid argon-dashboard-pro-react@1.2.0
```

**Expected result**
Build should complete successfully. Started facing this issue in last 3-4 days. Tried all answers of stackoverflow and github issue section but still build creation is failing

**Comment by fabiosantoscode** [comment]
Hey there! Terser 4.x is really old, and it's no longer supported.

Can you check for recent changes in your lockfile? Perhaps your build tools are using a more recent version and it's out of your control.

Also, do the issues persist if you disable the `reduce_vars` compress option?

**Comment by fabiosantoscode** [comment]
I suggest the latest 2 versions: `5.18.1` and `5.18.0`.

You can try them by using [npm overrides](https://stackoverflow.com/a/67397982) or yarn resolutions. Something like `"overrides": { "terser": "5.18.0" }`.

If the problem only reproduces with 5.18.1 and not 5.18.0 then it's probably [this commit](https://github.com/terser/terser/commit/f315d17e1d28b515e1887780f584540043f7c251) but I can't tell how it might be infinitely recursive, or how it might only fail on ubuntu 22.

**Comment by sameerthiteipro** [comment]
Hi @fabiosantoscode 
I have somehow resolved the issue using **react-app-rewired** package. Tried all other things before that.
I have created one `config-overrides.js` file and added same configurations of webpack for `terser-webpack-plugin` and `optimize-css-assets-webpack-plugin`, and it worked.
Below is config-overrides.js

`
const TerserPlugin = require('terser-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const safePostCssParser = require('postcss-safe-parser');
/* config-overrides.js */

module.exports = function override(config, env) {
    config.optimization.minimizer = [ new TerserPlugin({
        terserOptions: {
          parse: {
            ecma: 8,
          },
          compress: {
            ecma: 5,
            warnings: false,
            comparisons: false,
            inline: 2,
          },
          mangle: {
            safari10: true,
          },
          keep_classnames: true,
          keep_fnames: true,
          output: {
            ecma: 5,
            comments: false,
            ascii_only: true,
          },
        },
        sourceMap: false,
      }),
      new OptimizeCSSAssetsPlugin({
        cssProcessorOptions: {
          parser: safePostCssParser,
          map: false,
        },
        cssProcessorPluginOptions: {
          preset: ['default', { minifyFontValues: { removeQuotes: false } }],
        },
      })
    ];
    return config;
}
`

But still not able to find, what was the root cause of build failure.
Thank you
