### ISSUE TITLE
Option output.inline_script misses a few cases

### ISSUE THREAD

**Issue by Skalman** [terser/terser#1408]
**Bug report or Feature request?** Bug

**Version (complete output of `terser -V` or specific git commit)** 5.18.2

**Complete CLI command or `minify()` options used**
`{ output: { inline_script:true } }`

**`terser` input**

Three test cases:

1. `a = 0 < (/script>/).test()`
2. `a = 1 < (!--x + 1)`
3. `a = !x-- > 1`

**`terser` output or error**

1. `a=0</script>/.test();`
2. `a=1<!--x+1;`
3. `a=!x-->1;` _(I'm not sure whether this is an error)_

**Expected result**

1. `a=0< /script>/.test();`
   The output should never contain `</script>`

2. `a=1< !--x+1;`
   The output should never contain `<!--` (at least not in this case)

3. `a=!x-- >1;`
   The output should never contain `-->` (I think, but I'm unable to produce an actual HTML bug by including `-->` here)

**Comment by fabiosantoscode** [comment]
Thanks for the report!
