### ISSUE TITLE
Bug: Terser generates wrong source-map "names" for concise async methods

### ISSUE THREAD

**Issue by szuend** [terser/terser#1411]
**Bug report or Feature request?** Bug

**Version (complete output of `terser -V` or specific git commit)** 6a444c3d3b69fcbd52739e8001d5266bfb08b2b7

**Complete CLI command or `minify()` options used**

```
npx terser --source-map includeSources --module --output bundle.js calculator.js
```

**`terser` input**

calculator.js:

```
export class Calculator {
    async add(arg1, arg2) {
        return arg1 + arg2;
    }
    async sub(arg1, arg2) {
        return arg1 - arg2;
    }
}
```

**`terser` output or error**

"names" section in `bundle.js.map`:

```
"names":["Calculator","async","arg1","arg2"]
```

**Expected result**

Use https://evanw.github.io/source-map-visualization/ to visualize the source map.

We expect the `async add(` and `async sub(` tokens to be mapped to `add` and `sub` names respectively. Currently they are mapped to just `async`. This leads to confusing stack trace in e.g. DevTools:

![screenshot](https://github.com/terser/terser/assets/325588/461fc479-69b0-431b-b0b4-bd1a8ca60df6)).

The root cause seems to be missing/wrong handling of `AST_ConciseMethod` w.r.t. to source maps. Note that static concise methods exhibit the same problem.

**Comment by fabiosantoscode** [comment]
Interesting, thanks for the report! I suspect `.start` (the start token property) of the method is being used to generate the mapping instead of the method's name property.

**Comment by szuend** [comment]
Thanks for the fast fix, greatly appreciated :)
