### ISSUE TITLE
Variable assigned inside class static{} block incorrectly dropped

### ISSUE THREAD

**Issue by vicb** [terser/terser#1412]
I would like to report an issue.

I am sorry that I don't have an isolated test case yet. Feel free to close if you can not do anything with this, I know I am not supposed to create a bug without that.

I am building my project at https://github.com/vicb/flyxc/tree/zoleo (zoleo branch)

The way to build it is:

- `npm i`
- `npx nx build fxc-front --prod`

In `dist/apps/fxc-front/static/js/live-track-9e97706b.js` you can see:

```js
    class xa extends ja {
        constructor() {
            super(...arguments), this[_a$1] = Boolean
        }
        static {
            _a$1 = Oa
        }
        static {
            this.createEmptyValue = Boolean
        }
    }
```

The issue is that `_a$1` is never defined.

The source code is [libs/vaadin-nodom/src/lib/Models.ts](https://github.com/vicb/flyxc/blob/zoleo/libs/vaadin-nodom/src/lib/Models.ts#L95)

```js
export class BooleanModel extends PrimitiveModel<boolean> implements HasFromString<boolean> {
  public static override createEmptyValue = Boolean;

  public [_fromString] = Boolean;
}
```

The project is built using [vite](https://github.com/vicb/flyxc/blob/zoleo/apps/fxc-front/vite.config.ts#L45):

```
    minify: 'terser',
```

As you can see in the comment esbuild generates the same buggy output.
So the issue is probably not with terser itself but with a common dependency.

Again I'm sorry because

1. I don't have an isolated example,
2. The issue is probably not in terser itself but in a dep (because esbuild has the same issue)

But any help would be greatly appreciated - at least on how/where to investigate further.

Thanks

**Comment by vicb** [comment]
I was able to reproduce on a smaller/standalone example.

I first compiled the code without minification and got:

```js
var _a$1, _b, _c;
  const _ItemModel = Symbol("ItemModel");
  const _parent = Symbol("parent");
  const _key = Symbol("key");
  const _fromString = Symbol("fromString");
  const _validators = Symbol("validators");
  const _binderNode = Symbol("binderNode");
  const _getPropertyModel = Symbol("getPropertyModel");
  const _properties = Symbol("properties");
  const _optional = Symbol("optional");
  function getBinderNode(model) {
    if (!model[_binderNode]) {
      model[_binderNode] = null; //new BinderNode(model);
    }
    return model[_binderNode];
  }
  class AbstractModel {
    static {
    }
    static createEmptyValue() {
      return void 0;
    }
    constructor(parent, key, optional, ...validators) {
      this[_parent] = parent;
      this[_key] = key;
      this[_optional] = optional;
      this[_validators] = validators;
    }
    toString() {
      return String(this.valueOf());
    }
    valueOf() {
      const { value } = getBinderNode(this);
      if (value === void 0) {
        throw new TypeError("Value is undefined");
      }
      return value;
    }
  }
  class PrimitiveModel extends AbstractModel {
  }
  class BooleanModel extends PrimitiveModel {
    constructor() {
      super(...arguments);
      this[_a$1] = Boolean;
    }
    static {
      _a$1 = _fromString;
    }
    static {
      this.createEmptyValue = Boolean;
    }
  }
```

see `var _a$1` on the first line.

I then used https://try.terser.org/ to minify the code and it shows the bug (beautified output):

```
Symbol("ItemModel");
const t = Symbol("parent"),
    e = Symbol("key"),
    o = Symbol("fromString"),
    s = Symbol("validators"),
    r = Symbol("binderNode"),
    l = (Symbol("getPropertyModel"), Symbol("properties"), Symbol("optional"));
class a {
    static {}
    static createEmptyValue() {}
    constructor(o, r, a, ...i) {
        this[t] = o, this[e] = r, this[l] = a, this[s] = i
    }
    toString() {
        return String(this.valueOf())
    }
    valueOf() {
        const {
            value: t
        } = ((e = this)[r] || (e[r] = null), e[r]);
        var e;
        if (void 0 === t) throw new TypeError("Value is undefined");
        return t
    }
}
class i extends a {}
class n extends i {
    constructor() {
        super(...arguments), this[_a$1] = Boolean
    }
    static {
        _a$1 = o
    }
    static {
        this.createEmptyValue = Boolean
    }
}
```

**Comment by vicb** [comment]
```
$ npm ls terser
flyxc@2.0.0 /usr/local/google/home/berchet/code/flyxc
├─┬ @nx/webpack@16.5.1
│ └─┬ terser-webpack-plugin@5.3.9
│   └── terser@5.19.0 deduped
├── terser@5.19.0
└─┬ vite@4.4.2
  └── terser@5.19.0 deduped
```

**Comment by vicb** [comment]
It seems like this issue is actually specific to terser and esbuild is not affected. (My project was setup to do a second pass of terser on top of the esbuild output which is where the error originates)

**Comment by fabiosantoscode** [comment]
Appreciate the report and the reproducibility of it. Thanks!

**Comment by fabiosantoscode** [comment]
Changed the title if you don't mind.

**Comment by fabiosantoscode** [comment]
Smaller repro

```js
var donotdrop;
class C {
    static {
        donotdrop = 1234;
    }
}
```

**Comment by vicb** [comment]
Thanks!

**Comment by vicb** [comment]
Hey @fabiosantoscode do you have an ETA for the next release?
Thanks.

(I switched to esbuild to avoid this bug but it breaks Mac users with older Safari versions).

**Comment by fabiosantoscode** [comment]
In a couple hours. I usually release during the week to minimize weekend breakage.

**Comment by vicb** [comment]
That's smart!
I broke my app for mac users right before the weekend :(
Thanks
