### ISSUE TITLE
Performance regression between 5.19.0 and 5.19.1

### ISSUE THREAD

**Issue by aovchinn** [terser/terser#1414]
I am using terser indirectly trough webpack
with terser 5.19.0 prod build took 2m 11.8s
with 5.19.1 took 6m 40.0s

**Comment by aovchinn** [comment]
sorry that I don't have a "proof" or reproducible scenario, 
project on which I found this is private

**Comment by fabiosantoscode** [comment]
Thanks for the report. I'm suspecting this new function https://github.com/terser/terser/commit/fb48cb11adc366f9cd8c2cda6be3fe27b44158a5#diff-6c7efafd39517a688543ab1f5ac11c4ea0419cab43bc806896db5c0c6b334a54R193-R203 which is called a lot

**Comment by fabiosantoscode** [comment]
@aovchinn 5.19.2 is out, so I'd really appreciate if you could re-time your process and let me know.

The change has improved performance on a few test chunks I have laying around but not something as substantial as your reported performance regression.

**Comment by aovchinn** [comment]
thanks, that did it, with 5.19.2 took 2m 15.8s

**Comment by fabiosantoscode** [comment]
Awesome!
