### ISSUE TITLE
Question: why const a = f() is not inlined?

### ISSUE THREAD

**Issue by rentalhost** [terser/terser#1425]
**Bug report or Feature request?** 

Feature Request/Question

**Version**

Terser REPL (Playground, possibly 5.19.2)

**Input**

```js
// Example 1
const a = b();
c(a);

// Example 2
function x() {
  const y=z();
  return n(y);
}

x();
```

**Current output (prettified)**

```js
const o=b();
c(o),
function(){
  const c=z();
  n(c)
}();
```

**Expected output**

```js
c(b()),
function(){
  n(z())
}();
```

**Expected output (+)**

```js
c(b()),
n(z())
```

**TLDR**

I had posted this to the [SWC team](https://github.com/swc-project/swc/issues/7765), and they recommended asking here first, as I believe they take inspiration from Terser's decisions to bring to SWC. I'm curious about why this optimization isn't performed, just that. I tried researching in various ways and didn't find a reason, but as it's something that "seems simple," there's likely a good reason for it not happening.

However, other code works perfectly, like `const a = 123; b(a)` becomes `b(123)`.

**Comment by fabiosantoscode** [comment]
This is a bit more complicated than it looks. I'm going to take this bit of your example:

```
const a = b();
c(a);
```

To evaluate `c(a)` we must first evaluate `c`, then `a`. Because `c` is an unknown variable, evaluating it might crash and/or its access might cause a side effect.

Same for accessing `b`.

So it's not a safe change, since code that may crash with "`b` is not defined" would now crash with "`c` is not defined". Or global object accessors would execute out of order.

If the code was instead:

```
const a = b();
a(c);
```
 You can see that Terser does what you expect: `b()(c)`

**Comment by rentalhost** [comment]
Ah, that makes sense! Actually, I thought that in `c(b())`, `b()` would be executed BEFORE `c(...)`, but I tested it here and realized that, in this case, `c` is checked first and ends up failing before `b()` can be checked and executed. Thank you!

**Comment by danieltroger** [comment]
I just stumbled upon this issue and got really confused. Here's an example that might help illustrate what I think you guys are talking about for the next reader:

```
Object.defineProperty(globalThis, "a", {get(){console.log("a was accessed"); return () => console.log("a was executed")}}); 
Object.defineProperty(globalThis, "d", {get(){console.log("d was accessed"); return () => console.log("d was executed")}}); 

a(d())
```

Prints in this order

<img width="856" alt="Screenshot 2023-08-30 at 14 18 43" src="https://github.com/terser/terser/assets/4047180/3a8d6b33-6c56-438e-a2eb-3efea6f2bda6">

Which means that d is indeed executed before a, just as one expects, but it's about that the value of `a` is first read (which can have side-effects) before d is both "accessed" and "executed".
