### ISSUE TITLE
Inlining classes changing semantics of the program

### ISSUE THREAD

**Issue by skovhus** [terser/terser#1431]
**Bug**

The current behaviour of inling classes can change the semantics of a program. 

**Version (complete output of `terser -V` or specific git commit)**
`5.19.3`

**Complete CLI command or `minify()` options used**

`npx terser -c --module example.js` or `terser.minify(fileContent, {module: true})`

**`terser` input**

```javascript
let NodeType$1 = class NodeType2 {
  constructor(attrs2) {
    this.attrs = attrs2;
  }
  eq(other) {
    return this == other || other instanceof NodeType2;
  }
};
export class Decoration {
  constructor(type) {
    this.type = type;
  }
  eq(other) {
    return this.type.eq(other.type);
  }
  static node(attrs2) {
    return new Decoration(new NodeType$1(attrs2));
  }
}
```

**`terser` output or error**

```javascript
export class Decoration {
  constructor(type) {
    this.type = type;
  }
  eq(other) {
    return this.type.eq(other.type);
  }
  static node(attrs2) {
    return new Decoration(
      new (class NodeType2 {
        constructor(attrs2) {
          this.attrs = attrs2;
        }
        eq(other) {
          return this == other || other instanceof NodeType2;
        }
      })(attrs2)
    );
  }
}

```

**Expected result**

The `NodeType2` class should not be inlined, essentially create a a new class for each call to `node`, so the instance type would differ.

```javascript
const d1 = Decoration.node({ a: 1 });
const d2 = Decoration.node({ a: 1 });
console.log("d1.eq(d2)", d1.eq(d2)); // returns false when inlined (it should be true!)
```

This is the output from esbuild, without configuring mangling:

```javascript
let NodeType$1 = class NodeType2 {
  constructor(attrs2) {
    this.attrs = attrs2;
  }
  eq(other) {
    return this == other || other instanceof NodeType2;
  }
};
export class Decoration {
  constructor(type) {
    this.type = type;
  }
  eq(other) {
    return this.type.eq(other.type);
  }
  static node(attrs2) {
    return new Decoration(new NodeType$1(attrs2));
  }
}
```

With full minification (note that `s` is not inlined):
```
let s=class e{constructor(t){this.attrs=t}eq(t){return this==t||t instanceof e}};export class Decoration{constructor(t){this.type=t}eq(t){return this.type.eq(t.type)}static node(t){return new Decoration(new s(t))}}
```

**Comment by skovhus** [comment]
@fabiosantoscode I can help out fixing this one.

**Comment by skovhus** [comment]
It seems like the logic inside `def_is_constant_expression` is broken. 

Here is a failing test case:
```javascript
keep_meaningful_classes: {
    mangle = false;
    options = {
        module: true,
        // either:
        // defaults: true,

        // or:
        reduce_funcs: true,
        reduce_vars: true,
        unused: true,
    };
    input: {
        let NodeType$1 = class NodeType2 {
            constructor(attrs2) {
                this.attrs = attrs2;
            }
            eq(other) {
                return this == other || other instanceof NodeType2;
            }
        };
        export class Decoration {
            constructor(type) {
                this.type = type;
            }
            eq(other) {
                return this.type.eq(other.type);
            }
            static node(attrs2) {
                return new Decoration(new NodeType$1(attrs2));
            }
        }
    }
    expect: {
        let NodeType$1 = class NodeType2 {
            constructor(attrs2) {
                this.attrs = attrs2;
            }
            eq(other) {
                return this == other || other instanceof NodeType2;
            }
        };
        export class Decoration {
            constructor(type) {
                this.type = type;
            }
            eq(other) {
                return this.type.eq(other.type);
            }
            static node(attrs2) {
                return new Decoration(new NodeType$1(attrs2));
            }
        }
    }
}

```

**Comment by fabiosantoscode** [comment]
Smaller repro here:

```js
let ClassInLet = class ClassInLet {
  func(other) {
    return other instanceof ClassInLet;
  }
};

export function getInstance(attrs2) {
  return new ClassInLet()
}
```

If you remove `let ClassInLet =` then Terser behaves appropriately. It already detects if the class's name is used within it.

But here's a simpler case where inlining should still be illegal:

```js
class Class {};

export function getInstance(attrs2) {
  return new Class() // <- becomes `new class {}()`
}
```

Even though this class doesn't contain a reference to its own constructor, the code calling `getInstance` could store the object's constructor or prototype, and it will be a new one every time! This is no good.

So my conclusion is that classes can't be inlined into other scopes at all. IE, if it's a function or loop, different versions of the same class will be created.

**Comment by skovhus** [comment]
Seems like a pretty nasty bug. Any idea why this wasn’t discovered before? Seems it will break a lot of libraries and bundles.

**Comment by fabiosantoscode** [comment]
There's lots of bugs that seem super obvious but have been around for ages. For example, when React hooks came around, a bug was discovered where functions were being inlined into places that some other code could do `===` comparison of the function. So it would always be false because the function was inlined.

In this case I suppose it's because there's a ton of things that can save you from it. If you use the class in multiple places (like exporting it), you're already free of the issues. People don't usually just define a class and refer to it once.
