### ISSUE TITLE
Pure notation in static class property declaration is not respected if function references class itself

### ISSUE THREAD

**Issue by danieltroger** [terser/terser#1444]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**

5.19.4

**Complete CLI command or `minify()` options used**

try.terser.org

**`terser` input**

```
class myClass extends EventTarget {
  static #happenedEvents = /*@__PURE__*/(() => {
    const set = new Set();
    window.addEventListener("event", e => myClass.#happenedEvents.add(e));
    return set;
  })();
  
  #classProperty = "Whole class doesn't get stuff removed now at all";
}
```

**`terser` output or error**

```
class e extends EventTarget{static#e=(()=>{const t=new Set;return window.addEventListener("event",(t=>e.#e.add(t))),t})();#t="Whole class doesn't get stuff removed now at all"}
```

**Expected result**

```
EventTarget
```

(Or ideally if something like https://github.com/terser/terser/issues/1443 is implemented, nothing)

**Comment by bgoscinski** [comment]
It would also be really cool if a class declaration could be annotated with `/*@__PURE__*/` somehow:

**input:**
```js
/*@__PURE__*/class o {
  static {
    o.prototype.foo = 'bar'
  }
}
```

**actual output:**
```js
class o{static{o.prototype.foo="bar"}}
```

**expected output:**
```
// nothing
```

**Comment by fabiosantoscode** [comment]
This is actually caused by the global variable access `EventTarget`. It makes the class side-effectful. By letting the `unused` option pick apart the `extends` bit of the class, I was able to fix it.
