### ISSUE TITLE
Exception when API is called without any file

### ISSUE THREAD

**Issue by HolgerJeromin** [terser/terser#1449]
**Bug report**
I use grunt-terser to run terser in my build system.

**Version (complete output of `terser -V` or specific git commit)**

"terser": "5.19.3" via npm

**Complete CLI command or `minify()` options used**

When the input file is not existing it calls:

`minify({}, { output: { comments: 'some' }, mangle: false })`

**`terser` output or error**

```
Fatal error: Cannot read properties of null (reading 'resolve_defines')
TypeError: Cannot read properties of null (reading 'resolve_defines')
    at Compressor.compress (\node_modules\terser\dist\bundle.min.js:18446:29)
    at minify (\node_modules\terser\dist\bundle.min.js:30387:12)
```
Reading the [source code](https://github.com/terser/terser/blob/1a036e288e2c53b604660803e056e6ab5422e46e/lib/minify.js#L212) I see `options.parse.toplevel = null;`  and without files this `null` is written to the variable `toplevel = options.parse.toplevel;` twelve lines below. 

At least in call `new Compressor(/* ... */).compress(toplevel)` call we get an exception in the line https://github.com/terser/terser/blob/1a036e288e2c53b604660803e056e6ab5422e46e/lib/compress/index.js#L374

**Expected result**
A clean noop/abort: `No files were given`

**Comment by HolgerJeromin** [comment]
I can provide an PR with a throw before `toplevel = options.parse.toplevel;`:
```js
if(options.parse.toplevel === null)
   throw new Error("no source file given");
```
But I do not know if you want to have smarter error handling here.

**Comment by fabiosantoscode** [comment]
Thanks for the report. Would appreciate that PR!

**Comment by HolgerJeromin** [comment]
@fabiosantoscode 
I created the PR.
