### ISSUE TITLE
Bug when parsing ternery with  arrow function as a party

### ISSUE THREAD

**Issue by nick950222** [terser/terser#1452]
**Bug report or Feature request?**

A Bug

**Version (complete output of `terser -V` or specific git commit)**

version that https://try.terser.org/ is currently using 

**Complete CLI command or `minify()` options used**

{
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}

**`terser` input**

const Comp = () => {
    const shouldRender = () => [1,2,3,4].find(x => x > 3);
    return shouldRender ? 1 : 2
}

// think about the result of Comp(), should be number 1 or 2

**`terser` output or error**

const Comp=()=>()=>[1,2,3,4].find((n=>n>3))?1:2;

// after terser， the result of Comp() becomes a function, that's just not right

![image](https://github.com/terser/terser/assets/24955297/3056a07b-a132-4b8a-9daf-34e3f7ecf1c0)

**Expected result**

![image](https://github.com/terser/terser/assets/24955297/0eb765f9-aaff-48b9-86d5-7922f4be204d)

this is what i get with esbuild, parens arround the arrow function as the first parameter of the ternery, which is correct

**Comment by nick950222** [comment]
if this is a bug, then...
if this ain't a bug, is there a way to config terser properly to get the correct result?

**Comment by fabiosantoscode** [comment]
Thanks for the report! Yes, this is a parse bug. It can't be configured away.
