### ISSUE TITLE
Adding `--define` option will cause terser not work properly

### ISSUE THREAD

**Issue by Rezakarimi66** [terser/terser#1453]
I have written a small js file, called 'test.js', like below:

```
function setup() {
  let testVar = { property1: "property1", property2: "property2" };
}

setup();

console.log(x);
```
when I run the terser without `define` option everything works fine.
 
**Version (complete output of `terser -V` or specific git commit)**
5.21.0

**Complete CLI command or `minify()` options used**

terser test.js --toplevel --mangle-props --mangle reserved=["setup"] --define x=10

**`terser` output or error**
console.log(10);

**Expected result**
function setup(){let p={p:"property1",o:"property2"}}setup();console.log(10);

**Comment by fabiosantoscode** [comment]
This is actually caused by the toplevel option. Since setup() doesn't cause any side effects it's safely removed. If you need to place this script on a script tag and create a "setup" global variable, disable toplevel or use the top_retain=["setup"] compress option
