### ISSUE TITLE
Floating point numbers constant become longer

### ISSUE THREAD

**Issue by cuixiping** [terser/terser#1454]
**Bug report or Feature request?**

enhancement

**Version**

latest

**Complete CLI command or `minify()` options used**

`{}`

**`terser` input**
```
const a=0.1, b=0.2, c=a+b;
console.log(c);
```

**`terser` output**
```
console.log(.30000000000000004);
```

**Expected result**
```
console.log(.3);
```
Or
```
console.log(.1+.2);
```

**Comment by fabiosantoscode** [comment]
Interesting! 0.1 + 0.2 is actually not the same as 0.3 due to floating point binary representation, but Terser shouldn't think the + is worth evaluating here. Probably an issue in lib/size.js

**Comment by cuixiping** [comment]
input:
```js
console.log(0.1 + 0.2);
console.log(0.1 + 2);
console.log(1 + 0.2);
console.log(1 + 2);
```

terser output:
```js
console.log(.1 + .2), // not evaluated
console.log(2.1), // evaluated
console.log(1.2), // evaluated
console.log(3); // evaluated
```
