### ISSUE TITLE
JS heap out of memory when minify js file

### ISSUE THREAD

**Issue by hangaoke1** [terser/terser#1459]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
terser@5.21.0

**Complete CLI command or `minify()` options used**
```
const terserOptions = {
  format: { beautify: false, comments: [] },
  module: false,
  ecma: 5,
  compress: { ecma: 5, arrows: false },
  mangle: true,
  parse: {},
  sourceMap: { asObject: true },
};
```

Reproduce https://github.com/hangaoke1/terser-test

- clone the repository
- npm install
- node test.js

Memory keeps growing Until memory runs out
<img width="685" alt="image" src="https://github.com/terser/terser/assets/19623160/1d5b2ffc-2756-4feb-8a49-25082140df79">

**Comment by fabiosantoscode** [comment]
This works for me in node 20. It does take a really long time though.

Excessive memory usage in huge JS files (this one is 25mb) is a long standing, known issue. I've been working on it in the background.

**Comment by hangaoke1** [comment]
> This works for me in node 20. It does take a really long time though.
> 
> Excessive memory usage in huge JS files (this one is 25mb) is a long standing, known issue. I've been working on it in the background.

Thanks for your reply，Currently, the problem can be solved by using ```maxSize: 10 * 1024 * 1024``` in "webpack.splitChunks" to limit the size of the split chunks.

**Comment by fabiosantoscode** [comment]
This still made me have a deeper look, and I accidentally found a way to reduce output time when comments are enabled. I'm still not entirely sure why this works, so I'm leaving it in a branch for a bit.
