### ISSUE TITLE
SyntaxError: Unexpected token: punc (.) on build atempt

### ISSUE THREAD

**Issue by kubasanitrak** [terser/terser#1464]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
terser 5.22.0

**Complete CLI command or `minify()` options used**

**`terser` input**

**`terser` output or error**
Wnen trying to build react project by running 'yarn build' I get the following error:
message: 'Unexpected token: punc (.)',
  stack: 'SyntaxError: Unexpected token: punc (.)\n' +
    '    at Z.get (/Users/me/Git-folder/project-folder/node_modules/parcel-bundler/node_modules/terser/dist/bundle.min.js:1:525)\n'

**Expected result**
I would like to know, what to do to remove this error and be able to build the project

**Comment by fabiosantoscode** [comment]
Hello there! This doesn't seem to be Terser 5.22, because the stack trace reveals a minified file. Today, bundle.min.js is no longer minified.

I think this may be caused by the modern `?.` optional property access syntax.

Have you tried updating parcel? A new version may have come out that uses a newer version of Terser with support for this syntax.

**Comment by kubasanitrak** [comment]
Ok, thank you. I will look into it, thanks for pointing the (hopefuly) right direction.

**Comment by jonathanvanschenck** [comment]
Ran into the same problem -- seems to be related to an older version of terser. A library I was using had terser@4.8.1 as a dependency, and it was throwing this same error. Here's a minimal example:

On terser@4.8.1:
```js
const result = terser.minify(`console.log({a:1}?.b);`);
console.log(result); // { error: "e [SyntaxError]: Unexpected token: punc (.)" }
```

On terser@5.22.0:
```js
const result = terser.minify(`console.log({a:1}?.b);`);
console.log(result); // Promise { { code: 'console.log({a:1}?.b);' } }
```

Haven't looked into the details for the differences between the version -- but consider upgrading to the newest version
