### ISSUE TITLE
Option to Exclude Built-in Objects from Mangle Process

### ISSUE THREAD

**Issue by kyaido** [terser/terser#1473]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

https://try.terser.org/

I would like to inquire if there's a possibility to exclude built-in objects from the mangling process.
Currently, when declaring a variable with the same name as a built-in object, such as `Symbol`, and then using that built-in object, both the user-defined variable and the usage of the built-in object get mangled.

Here's a snippet that reproduces the issue, which you can also replicate using the [Terser REPL](https://try.terser.org/):

**`terser` input**

```js
console.log(Symbol);
const Symbol = 'Symbol';
console.log(Symbol);
```

**`terser` output or error**

```js
console.log(o);const o="Symbol";console.log(o); // => o is not defined
```

However, the desired outcome is to keep the built-in object Symbol intact while only mangling the user-defined variable name:

**Expected result**

```js
console.log(Symbol);const o="Symbol";console.log(o);
```

Is there an existing option or workaround to achieve this behavior? If not, could this be considered for a future enhancement?

**Comment by fabiosantoscode** [comment]
With `const` I don't think this reproduces a problem, because Terser's output is going to crash the same way as the input:

> ReferenceError: can't access lexical declaration 'Symbol' before initialization

Maybe your example was a bit more contrived.

But changing your example to `var` does reveal an issue:

```js
console.log(Symbol); // -> function Symbol()
var Symbol = 'Symbol';
console.log(Symbol); // -> "Symbol"
```

Because it compresses to:

```js
console.log(o); // -> undefined
var o="Symbol";
console.log(o); // -> "Symbol"
```

Which has different behavior

**Comment by fabiosantoscode** [comment]
What's the source issue you're trying to solve? Is this related to concatenating files?
