### ISSUE TITLE
Resolve Ternary Operations with Static Conditions

### ISSUE THREAD

**Issue by Lakuna** [terser/terser#1481]
**Bug report or Feature request?**

Feature request.

**Version (complete output of `terser -V` or specific git commit)**

```powershell
terser 5.26.0
```

**Complete CLI command or `minify()` options used**

```powershell
terser ./test.js --compress --module
```

**`terser` input**

```javascript
function isOne(a) {
	if (a === 1) {
		return "one";
	}

	return "not one";
}

console.log(isOne(1));
```

**`terser` output or error**

```javascript
console.log(1===1?"one":"not one");
```

**Expected result**

```javascript
console.log("one");
```

**Comment by Lakuna** [comment]
Note that the following input with the same command produces the expected output, so it seems that this can probably be implemented by just reordering some optimizations.

```javascript
console.log(1 === 1 ? "one" : "not one");
```

**Comment by fabiosantoscode** [comment]
As you point out, you can keep running the compressor to achieve that optimization. There's a `passes` compress option that does this for you. Terser will always require multiple passes to do things like these. Pulling a function in is one step, evaluating an IIFE with known static arguments is another.

If you set the `passes` compress option to 2 or 3, you'll achieve your desired effect without much of a slowdown.
