### ISSUE TITLE
Enclose setting ignored (sometimes) where topLevel is true

### ISSUE THREAD

**Issue by asos-tomp** [terser/terser#1485]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
5.26.0

**Complete CLI command or `minify()` options used**

```js
{ 
  toplevel: true, 
  enclose: "foo:boz" 
}
```

**`terser` input**
```js
window[foo] = "bar";
```

**`terser` output or error**
```js
var a;a=boz,window[a]="bar";
```
**Expected result**
```js
!function(n){window[n]="bar"}(boz);
```
N.B. The expected above is the result where `toplevel: false`.   

I would expect the input to _always_ be enclosed in a function, irrespective of top-level mangling.   Since not enclosed, the output cannot be reliably be used in an inline script, without polluting global scope.

N.B. Where an assignment is made, then the enclosing occurs (its understood that the assignment makes little sense, but it illustrates the point).

e.g.
```js
let baz = window[foo]; 
baz = "bar";
```
becomes
```js
!function(n){let o=window[n];o="bar"}(boz);
```
...with `topLevel: true`

**Comment by fabiosantoscode** [comment]
The output here is also correct. Since `toplevel: true` is set, Terser thinks it's okay to pollute your top-level scope.

If you need to place the output code in a script tag, you should set `toplevel: false` to prevent any pollution. This way, the `enclose` IIFE will be retained.

**Comment by asos-tomp** [comment]
Thank you, once again!

I have again misinterpreted when enclosing code is inserted - I somewhat assumed it was an afterthought from minification, and that enclosure wraps the top level scope (rather than becoming it)

This makes sense.
