### ISSUE TITLE
Enclose setting removes code.. irrespective of toplevel value

### ISSUE THREAD

**Issue by asos-tomp** [terser/terser#1486]
**Bug report or Feature request?**
Bug Report

**Version (complete output of `terser -V` or specific git commit)**
5.26.0

**Complete CLI command or `minify()` options used**
```js
{
   enclose: true
}
```

**`terser` input**
```js
let foo = "bar";
```

**`terser` output or error**
```
```

**Expected result**
```js
let foo="bar";
```

...this result is returned with no `enclose` setting.   Setting `toplevel` to `true` or `false` has no effect.

**Comment by fabiosantoscode** [comment]
Hello!

I believe this output is correct. Enclose produces a function, and then Terser finds this function to be removable because it has no side effects.

If you wish to retain unused code, you can disable the `compress.unused` option.

**Comment by asos-tomp** [comment]
Ah... that make sense; I somewhat hadn't imagined terser optimising the code _after_ enclosing - but obviously an enclosed function that has no side effects is superfluous, as you suggest.

Thanks so much for your insight.

**Comment by asos-tomp** [comment]
I can confirm that with settings:
```js
{
  enclose: true, 
  compress: { 
    unused: false 
  } 
}
```
...the output is:
```js
!function(){let n="bar"}();
```
