### ISSUE TITLE
Build failed it show error ( Cannot read properties of undefined (reading 'TYPE')

### ISSUE THREAD

**Issue by Purushottam-12** [terser/terser#1493]
17:54:59 #13 563.7 Failed to minify the bundle. Error: static/js/main.2ead3aca.js from Terser plugin
17:54:59 #13 563.7 Cannot read properties of undefined (reading 'TYPE')
17:54:59 #13 563.7 TypeError: Cannot read properties of undefined (reading 'TYPE')

**Comment by turingNotaWoman** [comment]
I have this problem too....

**Comment by Purushottam-12** [comment]
Bro I am geting same error in this version 5.27.2

**Comment by fabiosantoscode** [comment]
Fixed in `5.28.1`. Any tips on what input code might be triggering this could be helpful. I still don't know what was wrong with the `5.28.0` release.
