### ISSUE TITLE
Failed to minify the bundle. Error: static/js/main.eec18f52.js from Terser plugin

### ISSUE THREAD

**Issue by nikhil94319** [terser/terser#1495]
18:37:57 #13 536.0 Failed to minify the bundle. Error: static/js/main.eec18f52.js from Terser plugin
18:37:57 #13 536.0 Cannot read properties of undefined (reading 'TYPE')
18:37:57 #13 536.0 TypeError: Cannot read properties of undefined (reading 'TYPE')
18:37:57 #13 536.0     at /app/node_modules/react-scripts/scripts/build.js:179:23
18:37:57 #13 536.0     at finalCallback (/app/node_modules/webpack/lib/Compiler.js:454:32)
18:37:57 #13 536.0     at /app/node_modules/webpack/lib/Compiler.js:471:13
18:37:57 #13 536.0     at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
18:37:57 #13 536.0     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
18:37:57 #13 536.0     at onCompiled (/app/node_modules/webpack/lib/Compiler.js:469:21)
18:37:57 #13 536.0     at /app/node_modules/webpack/lib/Compiler.js:1213:17
18:37:57 #13 536.0     at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
18:37:57 #13 536.0     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
18:37:57 #13 536.0     at /app/node_modules/webpack/lib/Compiler.js:1209:33
18:37:57 #13 536.0     at finalCallback (/app/node_modules/webpack/lib/Compilation.js:2802:11)
18:37:57 #13 536.0     at /app/node_modules/webpack/lib/Compilation.js:3107:11
18:37:57 #13 536.0     at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
18:37:57 #13 536.0     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
18:37:57 #13 536.0     at /app/node_modules/webpack/lib/Compilation.js:3100:38
18:37:57 #13 536.0     at eval (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
18:37:57 #13 536.0     at eval (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
18:37:57 #13 536.0     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@fabiosantoscode  
How much time will you take to resolve this issue

**Comment by rusicsemenov** [comment]
Downgrade to 5.27.2

**Comment by fabiosantoscode** [comment]
Fixed in `5.28.1`. Any tips on what input code might be triggering this could be helpful. I still don't know what was wrong with the `5.28.0` release.

**Comment by jajedidiah** [comment]
ty @fabiosantoscode its causing some issues on our legacy deps as well. we tried deploying again 15min ago and now its gone
![Screen Shot 2024-02-23 at 11 17 40 PM](https://github.com/terser/terser/assets/65166737/8aad4ac9-ee1d-4032-9488-b168d60e9a96)
![Screen Shot 2024-02-23 at 8 55 36 PM](https://github.com/terser/terser/assets/65166737/cacce15b-7341-4405-90d9-d7ecb202022c)

**Comment by fabiosantoscode** [comment]
This has been fixed in `5.28.1`. Perhaps your package-lock.json or yarn.lock is still referring to the old version?

**Comment by jajedidiah** [comment]
@fabiosantoscode yes, since we haven't touched anything on our end. pretty weird. we have 2 green deployments now.
