### ISSUE TITLE
✨ Property mangling - allow preserve object key order

### ISSUE THREAD

**Issue by reececomo** [terser/terser#1501]
### Bug report or Feature request?

✨ Feature request: ✨ Allow object property order to be retained during property mangling.

### Background

It seems to only happen when property mangling is enabled (which makes sense). Interestingly order seems to be preserved when `debug: true`.

The de facto argument against this is usually "the ECMAScript specification does not guarantee order", but that hasn't quite been true for nearly 10 years. Since `ES2015` (and later reinforced in `ES2020`) property order is guaranteed insertion for string keys* ([see relevant ECMA spec](https://tc39.es/ecma262/#sec-ordinaryownpropertykeys)).

<sup>* With the exception of positive array-index-like values, e.g. `"0"` and `"1"`</sup>

All major JS engines implement this spec:
- ✅ V8 (used in Google Chrome and Node.js)
- ✅ SpiderMonkey (used in Firefox)
- ✅  JavaScriptCore (used in Safari)

It would be very useful to optionally only shrink names, but retain order.

### Related topics
- Not implemented by default (a good thing!): https://github.com/terser/terser/issues/959

**Comment by reececomo** [comment]
I can see from [lib/propmangle.js](https://github.com/terser/terser/blob/6f269e42efcb2f039d28b9b8699c952161454e0c/lib/propmangle.js) that maps and sets are used (which I can understand), but it's not _immediately_ obvious to me why order **is** preserved when `mangle.properties.debug = true` 🤔

I haven't looked closely enough tonight, but I'll have another peek tomorrow.

**Comment by reececomo** [comment]
TIL both `Map` and `Set` also preserve insertion order since ES6. Now I'm doubly confused 😆

**Comment by fabiosantoscode** [comment]
Could you post a reproduction of this issue? A quick test didn't reveal the issue.


This code:

    export default { cc: 3, aa: 4, bb: 5, }

Mangles, using `mangle: { properties: { keep_quoted: 'strict' } }`, to

    export default{t:3,l:4,o:5};

**Comment by reececomo** [comment]
> I had no knowledge of object property mangling switching the order of properties around! I rely on it being stable every day.

You're 100% right, sorry @fabiosantoscode I was looking at two totally different, similarly shaped objects 🤦

There is an issue, but it is not this. Note to self: no more debugging at 1AM

Thanks for the quick response! Closing now.
