### ISSUE TITLE
Terser creates non "strict" code

### ISSUE THREAD

**Issue by Caligatio** [terser/terser#1502]
**Bug report**
All ES6/ECMA 2015 modules are supposed to be `strict` but terser is emitting code that uses variables before they are declared.

**Version (complete output of `terser -V` or specific git commit)**
terser 5.29.1

**Complete CLI command or `minify()` options used**

```bash
terser test.mjs --module --mangle --compress
```

**`terser` input**
Please note this is taken from my project, jsSHA, so the naming conventions might seem a little wonky.

```javascript
class Int_64 {
    constructor(msint_32, lsint_32) {
        this.highOrder = msint_32;
        this.lowOrder = lsint_32;
    }
}

function xor_64_5(a, b, c, d, e) {
    return new Int_64(a.highOrder ^ b.highOrder ^ c.highOrder ^ d.highOrder ^ e.highOrder, a.lowOrder ^ b.lowOrder ^ c.lowOrder ^ d.lowOrder ^ e.lowOrder);
}

export function roundSHA3(block, state) {
    let round, x, y, B;
    const C = [], D = [];
    for (round = 0; round < 24; round += 1) {
        for (x = 0; x < 5; x += 1) {
            C[x] = xor_64_5(state[x][0], state[x][1], state[x][2], state[x][3], state[x][4]);
        }
    }
    return state;
}
```

**`terser` output or error**
```javascript
class r{constructor(r,e){this.highOrder=r,this.lowOrder=e}}export function roundSHA3(e,h){let o,d;const O=[];for(o=0;o<24;o+=1)for(d=0;d<5;d+=1)O[d]=(i=h[d][0],t=h[d][1],l=h[d][2],n=h[d][3],w=h[d][4],new r(i.highOrder^t.highOrder^l.highOrder^n.highOrder^w.highOrder,i.lowOrder^t.lowOrder^l.lowOrder^n.lowOrder^w.lowOrder));var i,t,l,n,w;return h}
```
**Expected result**
This is bit of an eye test but the `var` line that declares the variables used in the sequence should come before sequence.

```javascript
class r{constructor(r,e){this.highOrder=r,this.lowOrder=e}}export function roundSHA3(e,h){let o,d;const O=[];var i,t,l,n,w;for(o=0;o<24;o+=1)for(d=0;d<5;d+=1)O[d]=(i=h[d][0],t=h[d][1],l=h[d][2],n=h[d][3],w=h[d][4],new r(i.highOrder^t.highOrder^l.highOrder^n.highOrder^w.highOrder,i.lowOrder^t.lowOrder^l.lowOrder^n.lowOrder^w.lowOrder));return h}
```

**Comment by Caligatio** [comment]
I had no idea that the `var` declarations are hoisted to the top of the relevant scope, thank you for the info!

This appears to be a problem with my user's bundler, esbuild.

**Comment by fabiosantoscode** [comment]
It's very helpful that `var` behaves like that, since Terser can add `var` statements to a surrounding function while it's transformed, which is really cool. Since items are added at the end, looping isn't affected, and will in fact eventually get there.
