### ISSUE TITLE
`ascii_only` changes semantics of redundantly escaped regexes

### ISSUE THREAD

**Issue by DavidBuchanan314** [terser/terser#1506]
```sh
$ npx terser -V
terser 5.29.2
```

Steps to repro:

```sh
$ cat testcase.js
console.log("hello\\world❗".split(/[\❗]/));
$ node testcase.js 
[ 'hello\\world', '' ]
$ npx terser testcase.js -f ascii_only=true | tee min.js
console.log("hello\\world\u2757".split(/[\\u2757]/));
$ node min.js
[ 'hello', 'world❗' ]
```

When it occurs inside a regex literal, `\❗` is equivalent to just `❗` - the redundant escape is ignored by JS runtimes (as far as I can tell?).

But, once the emoji has been replaced with a unicode escape sequence (by terser), the `\\` substring parses as an escaped backslash, changing the meaning of the regex.

Maybe there needs to be an initial pass to strip redundant backslashes?

(By the way, when `\❗` occurs inside a string literal, it appears to be handled correctly)

**Comment by fabiosantoscode** [comment]
Cool bug!

The behavior with emojis that need two `\uXXXX` is also fun. The backslash of the first gets escaped, not the second.

`"".split(/[\😁\ç]/);`

becomes

`"".split(/\\ud83d\ude01\\xe7/);`
