### ISSUE TITLE
using a variable in a default parameter expression that is shadowed in that function's body causes a reference error

### ISSUE THREAD

**Issue by aweary** [terser/terser#1509]
**Bug report or Feature request?**

Bug report

If you have a default function parameter that refers to a variable, and then you _shadow_ that same variable inside the same function, then Terser confuses the outer variable with the inner one and ends up pointing the default parameter to the inner variable which is not actually in scope yet.

To make that clearer: in the example below `database` is defined outside of `query`; the `query` function has a `db` parameter which defaults to that outer `database` variable. Then `query` defines its _own_ `database` variable that it accesses the value through.

**`terser` input**

```js
var database = { open() { /* ... */ } }

function query(db = database) {
  var database = db;
  database.open();
}
```

**`terser` output or error**
You can see that `query(a=e)` means its defaulting to the `e` variable _within_ the `query` function 
```js
var database={open(){}};function query(a=e){var e=a;e.open()}
```

**Expected result**
but thats incorrect, it should be defaulting to the outer `database` value.
```js
var database={open(){}};function query(a=database){var e=a;e.open()}
```

**Comment by dasa** [comment]
This looks similar to #1478

**Comment by fabiosantoscode** [comment]
Yes, it's duplicated. The next quarter I'll be working on this
