### ISSUE TITLE
The application appears blank when using Terser 5.29.0

### ISSUE THREAD

**Issue by ab-ram-krishna** [terser/terser#1510]
**Bug report**

**Version 5.29.0 **

**Used as a dependency in TerserWebpackPlugin for webpack: 5.89.0**

**`terser` - No error during build time **

The generated code is buggy with react 16+ & Webpack 5.89.0

Buggy transpilation code due to terser: 

**Working code**
`o.onCommitFiberRoot(xo, n, void 0, !!(64 & ~n.current.flags));`
**Buggy code**
`o.onCommitFiberRoot(xo, n, void 0, !(64 & ~n.current.flags));`

**Working code**
`if (3 & ~e.tag) `
**Buggy code**
`if ( !(3 & ~e.tag)  ) `

**Working code**
` !!(3 & ~r.tag) `
**Buggy code**
` !!3 & ~r.tag)`

**Observations:**

1. No errors occurred during build time
2. No issues appeared on the console
3. The application displayed a blank screen without rendering anything
4. Additionally, several functions from React Fiber, which is React's internal code, failed to mount.

**Resolution**
**Updating the terser version to 5.29.1 worked! **

**Comment by fabiosantoscode** [comment]
That's right, this was fixed in 5.29.1. I don't think there was an issue created for this bug, just a comment.
