### ISSUE TITLE
Private fields, `in` and precedence (?)

### ISSUE THREAD

**Issue by jakubledl** [terser/terser#1519]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**

`terser 5.30.3`

**Complete CLI command or `minify()` options used**

`terser input.js --compress --mangle`

**`terser` input**

```js
class Test {
    #test;

    test(num, obj) {
        return num === 2 && #test in obj;
    }
}

const t = new Test();
console.log(t.test(2, {}));
```

**`terser` output or error**

```
Parse error at input.js:5,28
        return num === 2 && #test in obj;
                            ^
ERROR: Unexpected token: privatename (test)
    at ...
```

**Expected result**

`class Test{#t;test(t,s){return 2===t&&#t in s}}const t=new Test;console.log(t.test(2,{}));`

Version 5.30.2 works and gives the expected output, 5.30.3 gives the error. The input is valid code, works in browsers and node. 

Changing the offending line to

```js
return (num === 2) && (#test in obj);
```

makes the error goes away, so maybe the problem is with operator precedence and 0e04a22cb36a34d0e2a76ca790c5a6138e2262e8 might be to blame? [Both `in` and `===` have higher precedence than `&&`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table), so the two `return` statements should be entirely equivalent.

**Comment by fabiosantoscode** [comment]
I've fixed it. Since a lone `#privateprop` is not a valid expression, the detection for `#private in` needs to happen in more places.
