### ISSUE TITLE
Not sure what to call this. Javascript destructuring?

### ISSUE THREAD

**Issue by seannherdy** [terser/terser#1547]
**Bug report or Feature request?**
feature request

**Version (complete output of `terser -V` or specific git commit)**
5.15.1

**Complete CLI command or `minify()` options used**
terser -c

**`terser` input**
obj={a:1}
wrapper={obj}

**`terser` output or error**
obj={a:1},wrapper={obj:obj};

**Expected result**
obj={a:1},wrapper={obj};

**Comment by Conduitry** [comment]
This works if you tell Terser the version of JS it's allowed to use, by passing `ecma` of `2015` or higher.

**Comment by seannherdy** [comment]
Thank you! I verified that this works with:
      terser -c --ecma 2015
caniuse.com says ecma2015 is available worldwide on 98% of browsers which is good enough for me.
