### ISSUE TITLE
Issue in Minification in v5.31.4

### ISSUE THREAD

**Issue by aswinsekar** [terser/terser#1548]
In minifier process, a object reference alone not renamed to the new reference. All other reference are renamed, leading to issues. This is working properly in v5.31.3 

**Version (complete output of `terser -V` or specific git commit)**
v5.31.4

**Complete CLI command or `minify()` options used**
Used from webpack, but this issue is replicable in official terser repl

**`terser` input**
https://gist.github.com/aswinsekar/b4215d9a808c6da60ead7903d6439d79#file-input-js
**`terser` output or error**
https://gist.github.com/aswinsekar/b4215d9a808c6da60ead7903d6439d79#file-issueoutput-js
**Expected result**
https://gist.github.com/aswinsekar/b4215d9a808c6da60ead7903d6439d79#file-expectedoutput-js

**Comment by fabiosantoscode** [comment]
Hey there! Which object reference is not being renamed? Also, does this issue exist when `mangle` option is disabled? I would appreciate the reproduction without mangle, if you can still reproduce.

**Comment by fabiosantoscode** [comment]
I'm reverting 5.31.4 for now, but I appreciate a concise repro if possible.
