### ISSUE TITLE
5.31.4 is dropping base classes when there are sub classes that extend the base class.

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [terser/terser#1549]
**Bug report**

Base classes are being removed.

**Version (complete output of `terser -V` or specific git commit)**
5.31.4

**Complete CLI command or `minify()` options used**
I know this doesn't fit your requirements for terser alone, you can close this if you want.  But, this is our setup and it's a very large enterprise app, so I don't have a way to break it out to a reproducible example.  I also don't know how to use terser alone, only through webpack.  Learning terser and then creating an example unfortunately doesn't fit into my workday schedule.  But, I still wanted to make you aware of this issue because I suspect it's easy to reproduce for someone who knows how to use terser directly.

We are using terser-webpack-plugin.  When we add a direct dependency on 5.31.3 it works, when we change it to 5.31.4 it breaks.  This is our setup for webpack.config.js.

```
            new TerserPlugin({
                parallel: true,
                terserOptions: {
                    ecma: 2018,
                },
            }),
```

We are using Typescript that is transpiled to JS in the webpack pipeline.  The specific scenario that is failing is that we have a model type defined in a model.ts file.  This type extends another type in a different model.ts file.  Terser is removing the base definition.

base-model.ts
```
export class BaseType {
    // implementation here
}
```

model.ts
```
import {BaseType} from "./base-model.ts"

export class SubType extends BaseType {
    // implementation here
}
```

**Comment by fabiosantoscode** [comment]
Do you have any more details on this? What kind of error do you get in the compiled code? A ReferenceError?

Is the subclass also being dropped, or does it just exist while referring to a non-existing base?

**Comment by marvelsrp** [comment]
I don't know what you did but my projects crashed and I only found you on the 6th hour of debugging

**Comment by fabiosantoscode** [comment]
I'm reverting 5.31.4 for now, but I appreciate a concise repro if possible.
