### ISSUE TITLE
ESTree `ImportExpression`s are not recognized

### ISSUE THREAD

**Issue by BenjaminAster** [terser/terser#1557]
For dynamic `import()`s, terser internally simply uses call expressions with the identifier `import` as the callee. ESTree, however, [uses a special `ImportExpression`](https://github.com/estree/estree/blob/master/es2020.md#importexpression) type, which terser does not recognize. Ideally, adding support for it should be as easy as adding something like
```js
ImportExpression: function(M) {
    return new AST_Call({
        start: my_start_token(M),
        end: my_end_token(M),
        expression: from_moz({
            type: "Identifier",
            name: "import"
        }),
        optional: M.optional,
        args: [from_moz(M.source)]
    });
},
```
to the `MOZ_TO_ME` object variable in [lib/mozilla-ast.js](https://github.com/terser/terser/blob/master/lib/mozilla-ast.js). Note that the other direction (terser internal AST to ESTree) would require checking each and every function call to see if the callee is an identifier called `import`.

I'm not sure if I'm missing something though, which is why I'm posting this as an issue instead of a pull request.

**Comment by fabiosantoscode** [comment]
This was more than half of a PR, thanks! I was able to also output mozilla AST correctly, by virtue of `import()` being unambiguously *not* a function call. You can't create a variable called `import` and call it.

It looks like Terser can survive a little more without being able to understand that `import("x")` is its own thing!

**Comment by BenjaminAster** [comment]
Thanks!
