### ISSUE TITLE
source-map-support on 0.5.21 is impacted by CWE-22 - Path Traversal

### ISSUE THREAD

**Issue by danielnobusada** [terser/terser#1571]
terser version used: 5.29.1

As per the following snyk report, published on November 12th 20204, terser on the latest version has the dependency `source-map-support:^0.5.21` that is affected by `CWE-22 - Path Traversal vulnerability`.

Snyk report: https://security.snyk.io/vuln/SNYK-JS-SOURCEMAPSUPPORT-6112477

![image](https://github.com/user-attachments/assets/83866658-a501-4ff7-8602-6d5eee1145cf)

**Comment by fabiosantoscode** [comment]
Seems like it was amended, which I think is correct.

> This was deemed not a vulnerability.

Terser wouldn't be affected anyway, since it doesn't pass any options to `.install()`.

I'm closing this but I'm happy to re-open if `npm audit` or similar tools bother Terser users about it.
