### ISSUE TITLE
Chrome.runtime.port -mangle-props error

### ISSUE THREAD

**Issue by ChiMuYuan** [terser/terser#1573]
**Bug report or Feature request?**

Hello everyone, I am a beginner, and English is not my native language. I use ChatGPT for translation. Please let me know if I make any mistakes.

The `chrome.runtime.port` methods were obfuscated incorrectly using mangle.
`postMessage` is OK
`onDisconnect` -mangle-props to `o`
`onMessage` -mangle-props to `m`

https://developer.chrome.com/docs/extensions/reference/api/runtime#type-Port

**Version (complete output of `terser -V` or specific git commit)**

5.36.0

**Complete CLI command or `minify()` options used**

 terser .\test.js -c passes=2 -m --mangle-props -o ./test.t.js

**`terser` input**

``` javascript
let port = chrome.tabs.connect(tabId, { name: name });
port.postMessage({ message: "return message" });
port.onDisconnect.addListener(
    (() => { chrome.runtime.lastError && console.log("error", chrome.runtime.lastError) })
);
port.onMessage.addListener((contentText => { resolve(contentText) }));
```

**`terser` output or error**

``` javascript
let port=chrome.tabs.connect(tabId,{name:name});
port.postMessage({message:"return message"}),
port.o.addListener((()=>{chrome.runtime.lastError&&console.log("error",chrome.runtime.lastError)})),
port.m.addListener((e=>{resolve(e)}));
```

**Expected result**

**Comment by fabiosantoscode** [comment]
Looks like it should be added to [domprops](https://github.com/terser/terser/blob/master/tools/domprops.js)!

Other names can be mined from [this JSON file](https://chromium.googlesource.com/chromium/src/+/master/extensions/common/api/runtime.json).

**Comment by fabiosantoscode** [comment]
I ended up creating an extension to read the props from the `chrome` object.

**Comment by fabiosantoscode** [comment]
Will release the fix tomorrow!

**Comment by ChiMuYuan** [comment]
> Will release the fix tomorrow!

Thank you.
You guys are doing an nice job!
