### ISSUE TITLE
Keep name of variable with anonymous function

### ISSUE THREAD

**Issue by GevatterGaul** [terser/terser#191]
**Bug report or Feature request?**

Feature Request?

**Version (complete output of `terser -V`)**

terser 3.11.0

**Complete CLI command or `minify()` options used**

npm test

**`terser` input**

```
keep_var_fnames: {
    mangle = {
        keep_fnames: true,
    }
    input: {
        function foo() {
            const bar = function() {
                return "foobar";
            }
        }
    }
    expect: {
        function foo() {
            const bar = function() {
                return "foobar";
            }
        }
    }
}
```

**`terser` output or error**

```
Running test [keep_var_fnames]
!!! failed
---INPUT---
{
    function foo() {
        const bar = function() {
            return "foobar";
        };
    }
}
---OUTPUT---
function foo(){const o=function(){return"foobar"}}
---EXPECTED---
function foo(){const bar=function(){return"foobar"}}


```

**Expected result**

It would be mighty convenient if terser would recognize `bar` as function and not mangle the name when `keep_fnames` is set to true.

**Comment by fabiosantoscode** [comment]
Nice issue.

The workaround is not to mangle. Not a good workaround.

I'll start working on it.

**Comment by fabiosantoscode** [comment]
...But I have no idea how to do it. I'll work on it later.

**Comment by fabiosantoscode** [comment]
PRs welcome!

**Comment by jahed** [comment]
This also applies to arrow functions. Using the same example with `keep_fnames`,

```js
const bar = () => 'foobar'
```

becomes

```js
const o = () => 'foobar'
```

**Comment by fabiosantoscode** [comment]
It should be shipped soon. I don't know what took me so long, I love using anonymous arrow functions and giving them meaningful names.

**Comment by thaoms** [comment]
Thank you for fixing this! This made all our React Components that are written as functional hooks `Anonymous`.

**Comment by fabiosantoscode** [comment]
My use case was mostly for React too!

**Comment by gdh1995** [comment]
@fabiosantoscode  The commit ff16f02d4c07dcd0fe1cd568a2fc09f43f597329 is not correct enough - `keep_fnames` may be a regexp, but this commit treats a regexp as `true` when handing such functions.
