### ISSUE TITLE
hoist_props not working on relatively simple code

### ISSUE THREAD

**Issue by calebeby** [terser/terser#213]
**Bug report**

**Version**
```
terser 3.13.1
```

**`minify()` options used**

```js
{
  ecma: 8,
  module: true,
  compress: {
    passes: 15,
    unsafe: true,
    pure_getters: true,
    join_vars: false,
    hoist_props: true,
  },
  mangle: false,
  output: { beautify: true },
}
```

**`terser` input**

```js
const style = {
  scout: '_ab083',
}

function render() {
  return style.scout
}

console.log(() => (d => d)(render))
```

**`terser` output or error**

```js
const style = {
    scout: "_ab083"
};

function render() {
    return style.scout;
}

console.log(() => (d => d)(render));
```

**Expected result**

```js
console.log(() => (d => d)(function () {
  return "_ab083";
}));
```

`render()` should be inlined
`style.scout` should be hoisted/inlined

I noticed that any of these changes cause the object properties to be hoisted/inlined:

- Changing `render` to an arrow function :thinking:
- Deleting the `d => d` wrapper function around the call to render :confused:
- Taking out the arrow function in the `console.log()` :grey_question: 

I am confused why these changes cause different prop hoisting behavior. It seems like the hoisting should be possible even in the original scenario.

**Comment by hulkish** [comment]
@calebeby Per https://github.com/terser-js/terser/tree/master#compress-options, looks like you need to set `mangle: true` & `compress.toplevel: true`

> hoist_props (default: true) -- hoist properties from constant object and array literals into regular variables subject to a set of constraints. For example: var o={p:1, q:2}; f(o.p, o.q); is converted to f(1, 2);. Note: hoist_props works best with mangle enabled, the compress option passes set to 2 or higher, and the compress option toplevel enabled.

**Comment by calebeby** [comment]
@hulkish 

I tried those options, they did not affect whether it was inlined.

Since I have `module` set to `true`, [`toplevel` is enabled automatically](https://github.com/terser-js/terser/tree/master#minify-options):

> If compress or mangle is enabled then the toplevel option will be enabled

Mangle does not affect the prop-hoisting either.

**Comment by calebeby** [comment]
Created a repo so it is easier for you to test this: https://github.com/calebeby/terser-bug

**Comment by fabiosantoscode** [comment]
Thanks for this neat report!

This kind of compression is already done by prepack, so I'm not happy to start working on code that I will just remove in the next major. I suggest you wait a little bit for the new version.

**Comment by garkin** [comment]
Object here is mutable and referenced asynchronously. How will you distinguish it from a valid mutable cases without providing additional typing information?

**Comment by fabiosantoscode** [comment]
Hey there!

In the meantime I've changed my mind regarding prepack.

Also, in the meantime, optimisations have been created which minify your example to:

```
"use strict";                    
                                 
function render() {              
    return "_ab083";             
}                                
                                 
console.log(() => render);       
```

With just `toplevel=true,passes=2` as options. The reason that `render` isn't inlined into the arrow function in console.log is that Terser doesn't know what console.log might be doing. If it calls its first argument twice and compares the results, they will return two functions which are semantically equal but are `!==` because they aren't the same function.
