### ISSUE TITLE
Disabling beautify for good

### ISSUE THREAD

**Issue by fabiosantoscode** [terser/terser#214]
I propose to remove the beautify option. Plenty other projects are capable of doing this, and it's just more bug surface for terser, as its main purpose is to make code, well, terser.

**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V`)** latest

**Complete CLI command or `minify()` options used** `-b`

**`terser` input** any

**`terser` output or error** a beautified codebase

**Expected result** `-b` option not found

**Comment by fabiosantoscode** [comment]
De-documented beautify and added a note.

**Comment by tryzniak** [comment]
I think I'd like to take this one, if you don't mind.

**Comment by fabiosantoscode** [comment]
Hey there! Thanks in advance, do send a PR :?

**Comment by aminya** [comment]
Could you instead of removing add a dependency on Prettier? 

I use the beautify option to observe the output of the generated code. Using this option I was able to detect this bug for example #907

**Comment by fabiosantoscode** [comment]
I don't really want to add a dependency to it. 

I can relate to your problem, as I also use beautify locally while debugging and testing. Otherwise, large test cases are really hard to read.

I don't really know what to do to be honest

**Comment by aminya** [comment]
Optional dependencies do not count as a dependency, and only people that want/need that feature should install it. So, I think optional dependency is the best approach to take here. As it is the best of both worlds.

**Comment by alfaproject** [comment]
Oh man, I only really need terser for dead code elimination to keep my lambdas small but I want the code to look as close to original as possible so I can debug things on the fly without having to worry about source maps.

Basically this in webpack config:
```js
      new TerserPlugin({
        extractComments: false,
        terserOptions: {
          compress: {
            dead_code: true,
            defaults: false,
            unused: true,
          },
          ecma: 2020,
          mangle: false,
          format: {
            beautify: true,
            comments: false,
            indent_level: 2,
          },
        },
      }),
```

I was trying to find a webpack plugin to run prettier on the generated bundle chunks but I couldn't find anything ):

**Comment by fabiosantoscode** [comment]
You may want to try out this babel plugin:

https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-dead-code-elimination

Together with Babel's "retainLines" option.

I never tried to, though.

**Comment by alfaproject** [comment]
Yeah, I saw that but it's discontinued. For now, Terser beautify still works and I guess I'll have to try something else when the day comes. Maybe there will be a Prettier plugin by then
