### ISSUE TITLE
Turn for loops that don't modify `i` mid-loop and don't use `i` anywhere else into .forEach

### ISSUE THREAD

**Issue by fabiosantoscode** [terser/terser#216]
**Bug report or Feature request?** Feature request

For loops and forEach are equivalent in speed, but the forEach has less than half the overhead in terms of code size.

Because we're going to remove `i` or other loop variable, we can use `i` as the item's name without any scope checking necessary.

**Version (complete output of `terser -V`)** latest

**Complete CLI command or `minify()` options used** any

**`terser` input**

```js
for (var i = 0; i < foo.length; i++) bar(foo[i])
```

**`terser` output or error**

(the same but a bit smaller)

**Expected result**

```js
foo.forEach(i => { bar(i) }
```

**Comment by getify** [comment]
This should be an option at minimum, because I definitely wouldn't want this sort of transform on my code. It changes the error stack if an exception occurs inside the loop, by adding a function call. Especially since I can't name the function that would be used (I'm guessing it would be an anonymous function, maybe an arrow?), that error stack will be more confusing.

**Comment by fabiosantoscode** [comment]
@getify given a source map, it will point you to the correct line number. Is that still a problem?

**Comment by huozhi** [comment]
variable `foo` may be a array-like object, which doesn't extends full prototype from `Array`. transform for-loop to forEach may break code.

**Comment by getify** [comment]
@fabiosantoscode 

1. I think I recall that the error stack still reports the actual function calls, not a fabricated call-stack as it would have been in the original code.

2. I often run code in environments where I won't benefit at all from sourcemaps, such as simple node command-line call (not with node debugger or even chrome devtools remoting). I can handle mangled function calls and even messed up line numbers, but I really don't want the confusion of sifting through reported function calls that I didn't author.

**Comment by getify** [comment]
> variable `foo` may be a array-like object

Actually, it doesn't even need to be as exotic as a NodeList, it might just be a regular object with (some) numeric indexing:

```js
var myObj = {
   a: 100,
   b: 200,
   0: 50,
   1: 300,
   length: 2
};

for (let i = 0; i < myObj.length; i++) {
   console.log(myObj[i]);
}
```

**Comment by getify** [comment]
Of course, you could make the transform be:

```js
// unsafe
myObj.forEach(...)

// safer, but 8 characters longer
[].forEach.call(myObj, ...)
```

But I still would object to this (at least without it being behind an option) based on my other remarks.

**Comment by fabiosantoscode** [comment]
It would do the unsafe method safely if it can verify it's an array (by checking the variable's definition), and use the safe method otherwise.

And of course there will be an option for it! Good idea :)

**Comment by fabiosantoscode** [comment]
I've decided not to do this.
