### ISSUE TITLE
Properties in the argument were mangled

### ISSUE THREAD

**Issue by Mann90** [terser/terser#225]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V`)**
3.14.1

**Complete CLI command or `minify()` options used**

terser --compress --mangle --mangle-props -- test.js

**`terser` input**
foo({name: 'jane', age: 10});

**`terser` output or error**
foo({name:"jane",o:10});

**Expected result**
foo({name:"jane",age:10});

**Comment by jridgewell** [comment]
This is an expected output when using `--mangle-props`. If we take a full example, we see that `age` will be mangled to `o` consistently:

```js
// input
function foo({ name, age }) {
  console.log(name, age);
}
foo({ name: 'jane', age: 10 });

// output
function foo({name: o, o: e}) {
    console.log(o, e);
}

foo({ name: "jane", o: 10 });
```
