### ISSUE TITLE
Static properties not mangled

### ISSUE THREAD

**Issue by Mann90** [terser/terser#227]
**Bug report or Feature request?**
Bug.

**Version (complete output of `terser -V`)**
3.14.1

**Complete CLI command or `minify()` options used**

terser --compress --mangle --mangle-props -- test.js

**`terser` input**
class Foo{};Foo.Event={red: 1,blue: 2};

**`terser` output or error**
class Foo{}Foo.Event={red:1,blue:2};

**Expected result**
class Foo{}Foo.a={red:1,blue:2};

**Comment by fabiosantoscode** [comment]
This also fails:

`function foo(){var Foo={};Foo.Event={red:1,blue:2}}`

**Comment by M4rk9696** [comment]
It seems to be the name. `Event` is treated as a reserved keyword

https://github.com/terser/terser/blob/a1d132eebbe83c9cd2f1835a0182a0f5205a0d6e/tools/domprops.js#L747

@fabiosantoscode Maybe an `option.dom` to specify whether the code will use the DOM, and if not mangle those?

**Comment by fabiosantoscode** [comment]
@M4rk9696 you're right on the money.

There's an option for `--mangle-properties`, `domprops`, which tells it to ignore DOM properties.
