### ISSUE TITLE
Terser Won't Drop Unused Functions Created by Other Functions

### ISSUE THREAD

**Issue by Lonniebiz** [terser/terser#249]
Terser Version: 3.8.1"
Operating System: Ubuntu 16.04.5
Node Version: 10.14.2
NPM Version: 6.70
webpack Version: 4.29
terser-webpack-plugin Version: 1.10
Additional tools: eslint 5.12.1

Issue:
```
Summary()
{
	// Terser cannot treeshake an unused export function if that function 
	// was created by another function inside of the same module.
}
```
For example, lets say I have the following file named test.mjs :

```
export const mirror = function mirror(str)
{
    return str;
};

let createCounterFunction = function createCounterFunction()
{
    let i = 0;
    let counter = function counter()
    {
        i += 1;
        return i;
    };
    return counter;
};
export const funcCount = createCounterFunction();
```

Now, let's say I try to only import the function "mirror" into my index.js file:

```
import { mirror } from './test.mjs';
console.log(mirror("Hello World"));
```

Result:
```
Result()
{
	// Terser is unable to treeshake any of the code above, despite the 
	// fact that we have no intention of importing any of the "counter-related" code.
}
```
Here is the actual contents of the bundled file, produced from the two files mentioned above:

```
!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=0)}([function(e,t,n){n.r(t);!function(){let e=0}();console.log("Hello World")}]);
```

As you can see, none of the unused functions are dropped; no tree-shaking was achieved.

I've concluded that anytime you call a function inside a module itself, that function is considered "used" because you used it before even exporting it. However, it seems possible that a smart enough bundler could treeshake this still.

My workaround, is to put functions like this into their own code file, so that they only get imported when explicitly specified.

One thing you might find interesting, is that Chrome's [Coverage Tool](https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage) also considers these unintended imports "used", because after slipping by the tree-shaker, `createCounterFunction()` gets called in the client.

**Comment by Lonniebiz** [comment]
The author of webpack noticed that terser will drop the function if a certain let is change to var. Read this:
https://github.com/webpack/webpack/issues/8692#issuecomment-459683396

**Comment by fabiosantoscode** [comment]
Thanks for the issue! I'll have a look and attempt a fix when I have time.

Yes indeed let and const should just work like var whenever possible. In some places that's not done yet.

**Comment by fabiosantoscode** [comment]
But to help make this clear can you paste in the compiled code resulting from compiling those 2 files?

**Comment by Lonniebiz** [comment]
Sure, I've updated issue 249 to include the actual bundle output (see above).

**Comment by fabiosantoscode** [comment]
It looks like webpack and terser are both working properly. I've beautified the code and it's just the machinery and the code you're using, properly tree shaked:

```
! function(e) {
    // (webpack machinery)
}([function(e, t, n) {
    n.r(t);
    ! function() {
        let e = 0
    }();
    console.log("Hello World")
}]);
```

Additionally, Terser doesn't do tree-shaking. While it's possible to minify multiple files, that's just a shortcut for concatenating them together and then minifying.

If you want to remove this machinery, I suggest using Rollup, which has been made with imports in mind. Check out this page, it demonstrates how small the output can be: https://rollupjs.org/repl. Rollup is recommended by Terser as it produces output that's smaller and easier to minify.

**Comment by fabiosantoscode** [comment]
This is one of the 2 bugs I'm having a look at this weekend.

**Comment by fabiosantoscode** [comment]
@Lonniebiz it looks like if you increase the passes option `-c passes=3` it works. Maybe passes=2 works too. Can you check?

**Comment by fabiosantoscode** [comment]
This looks like a really hard bug, on one of the hardest parts of the code. I can't fix it just like that :disappointed:

**Comment by Lonniebiz** [comment]
That's ok. I know how that goes. I can imagine that code must be pretty complicated.

**Comment by TheLarkInn** [comment]
@fabiosantoscode is there a way to break up the work into contributable pieces from the community. I'm sure theres more then a few people who'd love to help if its possible.

**Comment by fabiosantoscode** [comment]
I can't reproduce this anymore as of 4.2.1, as long as I set the `module` option to true. Please confirm.

I suppose it's been fixed while fixing something else.

**Comment by fabiosantoscode** [comment]
@TheLarkInn everyone is welcome to contribute. These days I've been adding the "good first PR" label to some easy issues to help out new contributors. However, I'm afraid that's not enough, as not many people are stepping up to do it.

This is why I assume I'll be fixing things when I comment on issues, even though sometimes I give hints to someone who might want to fix the problem.
