### ISSUE TITLE
typeof/instanceof comparisons are retained

### ISSUE THREAD

**Issue by filipesilva** [terser/terser#250]
**Bug report or Feature request?**

I think this is a bug, but it might be working as intended.

**Version (complete output of `terser -V`)**
3.16.0

**Complete CLI command or `minify()` options used**

`terser test.js --toplevel --compress --mangle`

**`terser` input**
```js
// test.js
var __window = typeof window !== 'undefined' && window;
var __self = typeof self !== 'undefined' && typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope && self;
var __global = typeof global !== 'undefined' && global;
if (typeof ngDevMode === 'undefined' || ngDevMode) { }
if (typeof ngDevMode !== 'undefined' && ngDevMode) { }
```

**`terser` output or error**
Output is
```
"undefined"!=typeof window&&window,
"undefined"!=typeof self&&"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope&&self,
"undefined"!=typeof global&&global;
"undefined"==typeof ngDevMode||ngDevMode,
"undefined"!=typeof ngDevMode&&ngDevMode;
```
(Note: I added line breaks for readability, but the output proper did not have line breaks.

**Expected result**
I expected the output to be nothing. 

Maybe there's a reason for leaving these comparisons there that I don't see.

**Comment by fabiosantoscode** [comment]
Thanks for this issue. It's a bit low priority though. I think most unused code is wrapped inside an if that can be clearly removed.
