### ISSUE TITLE
Invalid regular expression (lookbehinds)

### ISSUE THREAD

**Issue by fabiospampinato** [terser/terser#269]
Terser isn't able to minify my code because I'm using [lookbehinds](http://2ality.com/2017/05/regexp-lookbehind-assertions.html), which have been added in ES2018, is this something that will be supported?

**Comment by L2jLiga** [comment]
@fabiospampinato could you kindly describe what went wrong in details? I tried to compress examples from given link with Terser and for me it works:

Input
```javascript
const RE_DOLLAR_PREFIX = /(?<=\$)foo/g;
"$foo %foo foo".replace(RE_DOLLAR_PREFIX, "bar");

(() => {
    const RE_DOLLAR_PREFIX = /(\$)foo/g;
    "$foo %foo foo".replace(RE_DOLLAR_PREFIX, "$1bar");
})();

(() => {
    const RE_NO_DOLLAR_PREFIX = /(?<!\$)foo/g;
    "$foo %foo foo".replace(RE_NO_DOLLAR_PREFIX, "bar");
})();
```

Output:
```javascript
const RE_DOLLAR_PREFIX=/(?<=\$)foo/g;"$foo %foo foo".replace(RE_DOLLAR_PREFIX,"bar"),"$foo %foo foo".replace(/(\$)foo/g,"$1bar"),"$foo %foo foo".replace(/(?<!\$)foo/g,"bar");
```

**Comment by fabiospampinato** [comment]
@L2jLiga sure, having the following regex:

```js
 /(?:<pre><code\s[^>]*language-(?:tex|latex|katex)[^>]*>([^]+?)<\/code><\/pre>)|(?:(?<!\\)\$\$(?!<)(\S(?:.*?\S)?)(?<!\\)\$\$(?!\d))|(?:(?<!\\)\$(?!<)(\S(?:.*?\S)?)(?<!\\)\$(?!\d))/g
```

Makes Terser throw the following exception for me: 

```
    ERROR in renderer.js from Terser
    Invalid regular expression: /(?:<pre><code\s[^>]*language-(?:tex|latex|katex)[^>]*>([^]+?)<\/code><\/pre>)|(?:(?<!\\)\$\$(?!<)(\S(?:.*?\S)?)(?<!\\)\$\$(?!\d))|(?:(?<!\\)\$(?!<)(\S(?:.*?\S)?)(?<!\\)\$(?!\d))/: Invalid group [./src/renderer/utils/markdown.ts:29,7][renderer.js:52315,9]
```

I have Terser configured [here](https://github.com/notable/notable/blob/master/webpack.js).

**Comment by fabiosantoscode** [comment]
@fabiospampinato A little dirty secret of Terser is that it sometimes uses the underlying RegExp engine that node is using. This was a decision that was probably taken because ES6 and all the new features didn't come out at the time. Check your node version. On node 11 this works for me.

**Comment by fabiospampinato** [comment]
@fabiosantoscode thanks for the tip! I've since modified that regex to not use lookbehinds so I don't need this anymore.

Perhaps this important detail should be mentioned somewhere?

**Comment by fabiosantoscode** [comment]
I think instead we should make Terser ignore these RegExp errors and output a warning when they happen. Running the regexps isn't essential to minification, it's optional.

**Comment by fabiospampinato** [comment]
That probably a good idea too.

**Comment by namxam** [comment]
I am not sure if this is the same issue, but I just had issues with using terser on some code which uses named matching groups. It works perfectly fine in node 11.13.* but terser fails.

**Comment by L2jLiga** [comment]
@namxam could you run terser with `TERSER_NO_BUNDLE=1` environment parameter and provide stacktrace?

**Comment by oteku** [comment]
I have the same issue with this regexp using lookbehind : `/((?<!\d)[\.,;:\?\!](?!\d))/g`
It's perfectly fine with node 9+

**Comment by tchetwin** [comment]
Just noticing failures with regex groups on node 8, working on 10 and 11.

Source:
```javascript
/(?<year1>\d{4})/.exec("2019")
```

Result:
```
$ TERSER_NO_BUNDLE=1 bin/uglifyjs a.js
Parse error at a.js:1,0
/(?<year1>\d{4})/.exec("2019");
^
ERROR: Invalid regular expression: /(?<year1>\d{4})/: Invalid group
    at JS_Parse_Error.get (/c/dev/jit/terser/lib/utils.js:83:23)
    at fatal (/c/dev/jit/terser/bin/uglifyjs:311:53)
    at run (/c/dev/jit/terser/bin/uglifyjs:250:9)
    at Object.<anonymous> (/c/dev/jit/terser/bin/uglifyjs:178:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

Version of terser: fbebaaff9ff021bd46cc4dcb344348f3fbb3b57b

Inspector shows it goes wrong when passing the source to `RegExp` as [mentioned](https://github.com/terser-js/terser/issues/269#issuecomment-464521971).

https://github.com/terser-js/terser/blob/fbebaaff9ff021bd46cc4dcb344348f3fbb3b57b/lib/parse.js#L748-L754

**Comment by fabiosantoscode** [comment]
It was a bit of a stretch, and technically a breaking change, but I've done this now.
