### ISSUE TITLE
Computed properties results incorrect code evaluating in Safari

### ISSUE THREAD

**Issue by otakustay** [terser/terser#272]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V`)**

terser 3.16.1

**Complete CLI command or `minify()` options used**

```
terser --compress -- in.js
```

**`terser` input**

```js
(function() {
    function f(o) {
        return {[o.key]: o};
    }
    function g(o) {
        return o;
    }
    var obj = {key: 'xyz'.slice(1, -1)};
    var result = g(f(obj));
    console.log(result);
})();
```

**`terser` output or error**

```js
!function(){var o,obj={key:"xyz".slice(1,-1)},result=function(o){return o}({[(o=obj).key]:o});console.log(result)}();
```

**Expected result**

This output code can be correctly evaluated in chrome 71.0.3578.98 which results:

```
{"y": {"key": "y"}}
```

![image](https://user-images.githubusercontent.com/639549/52934316-11000800-3391-11e9-8ca2-fba409cf56ad.png)

In safari 12.0.2 (14606.3.4) it behaves incorrectly:

```
{"y": undefined}
```

![image](https://user-images.githubusercontent.com/639549/52934345-2117e780-3391-11e9-807e-1cb9166802c4.png)

It seems not safe to compress computed property key like this

**Comment by LeuisKen** [comment]
I run the following code in these browsers:

```js
({[(console.log(1), 'x')]: (console.log(2), 1)})
```

In Chrome 72.0.3626.109 gets:

![image](https://user-images.githubusercontent.com/7701575/52935861-8372e700-3395-11e9-8560-c4a1cc5366e6.png)

and Safari 12.0 (14606.1.36.1.9) gets:

![image](https://user-images.githubusercontent.com/7701575/52935937-be751a80-3395-11e9-9deb-96d10cdc08f3.png)

**Comment by otakustay** [comment]
I know this is actually a BUG of safari, however code introduced by tools like terser are unpredictable and hard to find root cause, it's better to avoid known compatibility issues in major browsers

**Comment by fabiosantoscode** [comment]
I think we can piggy-back on the options we already have for Safari 10/11 on this.

We also need to enable these options by default as Safari has a lot of usage. I don't think it's reasonable for Terser to produce code that fails on a very used browser that people don't test their code on enough.

**Comment by fabiosantoscode** [comment]
I'm preventing this inline step on all browsers. I suspect it'll have a small impact on output size.
