### ISSUE TITLE
Output Options Cannot Be Passed via CLI

### ISSUE THREAD

**Issue by bdkjones** [terser/terser#273]
**Bug report or Feature request?**

Enhancement Request

**Version (complete output of `terser -V`)**

3.16.1

**Issue**

There does not currently seem to be a way to pass any of the Output Format options to Terser via the CLI. For example, if I want to pass `ecma=6`, I cannot do that. (I CAN pass the main CLI `ecma` flag, but that overrides all my other options according to the docs.) Likewise, I can't pass a `max_line_len` value or `braces`, etc.

I attempted to pass these options via the `-b` CLI flag, but that caused Terser to generate very un-minified code. (Uglify-es used to accept output options via the `-b` flag and simply ignore any that applied only to beautification if the `-c` flag was also passed, so Terser's behavior surprised me.)

I do understand that beautification is being removed. But many of these output options are valid and useful in minified code.

How do we pass these options via the CLI?

**Comment by bdkjones** [comment]
Annnnnnd right after I post the issue I find a workaround. This line is the culprit:

 https://github.com/terser-js/terser/blob/0cf9167c5278986744d6584255e153dd5555fd1a/bin/uglifyjs#L95

So if I pass my options via the CLI and tack on `beautify=false` to the end, I can get the desired effect. Example:

      [...] -b ecma=6,inline_script=true,braces=true,beautify=false

When beautify is officially removed, the `-b` option flag will be replaced with something more appropriate, I guess? If I might make a suggestion, whatever the new CLI flag to pass Output Format options is named, it should support using `-b` for backwards compatibility.

**Comment by fabiosantoscode** [comment]
I'm happy to support "-b" but won't document it, otherwise people will keep using it forever.

Thanks for the issue, I didn't predict this would happen at all!

**Comment by bdkjones** [comment]
Actually, it's easy for me to change to something else. It's just that `-o` is already taken in the CLI, so I'm not sure what makes the most sense. Maybe if these were renamed "Formatting Options" you could use `-f`? Or just "Output Format" and use `-f`? 

As long as it gets put into the changelog when it's implemented, I can update my app. And thanks for actually WRITING a changelog! I tried to get UglifyJS to do one for literally years.

**Comment by fabiosantoscode** [comment]
I'm going to sleep on that. `-o` would be perfect but `-b` really has to go.

**Comment by fabiosantoscode** [comment]
I've decided to keep `-b` but undocument it and use `-f` until 5.0

**Comment by fabiosantoscode** [comment]
Also, thanks for the issue. Besides this being a bad interface (having to pass beautify=false), the documentation for `ecma` was completely misunderstandable. If you pass `--ecma` it doesn't override the other options. It's just a shorthand to pass `ecma` to all of them.

**Comment by bdkjones** [comment]
Sounds great! I think `-f` makes sense.

**Comment by fabiosantoscode** [comment]
@bdkjones any chance you could send a PR where `-f` and `--format` becomes the norm and `-b` just an alias for it? I've started work on this but other issues came up.

**Comment by fabiosantoscode** [comment]
Fixed in v5 beta.
