### ISSUE TITLE
Option to return source-map object

### ISSUE THREAD

**Issue by tolmasky** [terser/terser#278]
Feature Request (sub-optimal code)

Currently the resulting source map (returned as `map`) is a string. We take this source map and do further post-processing on it, which means we are parsing it immediately, so we are eating the performance hit of an unused stringification, as well as parsing it immediately after. It would be nice to be able to just get the object itself and avoid the extra step and performance degradation.

Note: I *believe* parcel has a similar need, as in their code they seem to use `source_map` as either a hidden option (or hack?) to inject their own custom source map object [(link to relevant code)](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/terser.js#L23).  However, this may be for an unrelated reason.

**Comment by fabiosantoscode** [comment]
Great suggestion.

This is easy to do so I'm giving it the Good First PR label.

Yes we should add a minify option (I propose we use `sourceMap.asObject`, inside the existing `sourceMap` option) where `map` becomes an object, but it should not be a CLI option.
