### ISSUE TITLE
Incorrect Type Definitions

### ISSUE THREAD

**Issue by RebeccaStevens** [terser/terser#290]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V`)**
terser 3.16.1

**Complete CLI command or `minify()` options used**
N/A

**`terser` input**
N/A

**`terser` output or error**
N/A

**Expected result**
N/A

**Description**
Typing info is incorrect for some options. I have spotted two, those being `indent_start` and `max_line_len`, there may be more.

**Current Typings**

```ts
indent_start?: boolean;
max_line_len?: boolean;
```

**Expected Typings**

```ts
indent_start?: number;
max_line_len?: number | false;
```

**Comment by fabiosantoscode** [comment]
Both of these options are on the way out with 4.0, but I'll add the label so I don't forget to change the typescript typings.

**Comment by fabiosantoscode** [comment]
Correction: only `indent_start` will die.

**Comment by fabiosantoscode** [comment]
I ended up not killing these options right now so I decided to fix this one.
