### ISSUE TITLE
Parser support for Public Class Fields

### ISSUE THREAD

**Issue by robpalme** [terser/terser#303]
**Feature request**

This is a proposal to add support for [Public Class Fields](https://github.com/tc39/proposal-class-fields) to the Terser parser.
The goal is simply to allow pass-through behavior - no compression or mangling.
The proposed scope is public fields only, as that is what has been shipping in Chrome 72 since January 2019.

The language proposal is currently Stage-3 so I'd like to check if the Terser project is comfortable adding support at this point in time?
The status of other tooling's support for this feature is found [here](https://github.com/tc39/proposal-class-fields/issues/57).
Of note, [Babel](https://babeljs.io/blog/2018/08/27/7.0.0#tc39-proposals-https-githubcom-tc39-proposals-support) and [Acorn](https://github.com/acornjs/acorn-class-fields) have already landed support.
TypeScript support is a [work-in-progress](https://github.com/bloomberg/TypeScript/tree/es-private-fields).

If this proposal is acceptable, we can follow up with PRs to add the feature, unless someone else out there is super keen to contribute this.

**Comment by fabiosantoscode** [comment]
Great idea.

Please go ahead, but don't expect me to merge it soon. Terser 4 has to go out the door first.

**Comment by robpalme** [comment]
Excellent. It's understandable that this must follow Terser 4.

To help with timing, can you provide any rough estimate for Terser 4 landing? If it was April, we might start now. If it was Q3, we'd defer starting this work.

**Comment by fabiosantoscode** [comment]
I ended up creating a `terser-4` branch where I'm adding breaking changes. You're clear to go!

**Comment by fabiosantoscode** [comment]
I'm working on this. I have to review a lot of code since there's a new closure after the `=` of a non-static property, and furthermore these are executed out of order. I need to find every place in the code where such assumptions are made.
