### ISSUE TITLE
Wrong processing produces `Missing initializer in const declaration`

### ISSUE THREAD

**Issue by Ajaxy** [terser/terser#318]
**Bug report**

**Version (complete output of `terser -V`)**
terser 3.17.0

**Complete CLI command or `minify()` options used**
```sh
terser -c -m -- file.js
```

**`terser` input**
```js
;(function () {
  window.func0 = func0;

  function func0() {
    return func1();
  }

  function func1() {
    function func2() {
      return func3();
    }

    return func2;
  }

  function func3() {
    const aaa = func4();
    const bbb = Math.random();
    bbb.someMethod();
  }

  function func4() {
    return Math.random();
  }
})();
```
Changing any line from above will likely make the bug go away.

**`terser` output and error**
```js
!function(){function n(){const n=t(),o;Math.random().someMethod()}function t(){return Math.random()}window.func0=function(){return function(){return function(){return n()}}()}}();
```
Producing `Uncaught SyntaxError: Missing initializer in const declaration`. Note: `const n=t(),o;`.

**Expected result**
Same, but without `,o`.

**Comment by fabiosantoscode** [comment]
I can't reproduce this anymore today.

**Comment by fabiosantoscode** [comment]
I have to assume this is gone now.
