### ISSUE TITLE
Dublicate banner comment

### ISSUE THREAD

**Issue by vivcogit** [terser/terser#328]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V`)**
terser 3.17.0

**Complete CLI command or `minify()` options used**
Default webpack options:
```
output: {
  comments: /^\**!|@preserve|@license|@cc_on/i
}
```

**`terser` input**
library [classnames](https://github.com/JedWatson/classnames) after webpack:
Reproduce code see here: https://gist.github.com/vivcogit/66671fd4f921f9e3f43a3ceb579eb70c#file-test-js

**`terser` output or error**
dublicate "banner" comment with author and license data:
`\n/*!\n  Copyright (c) 2017 Jed Watson.\n  Licensed under the MIT License (MIT), see\n  http://jedwatson.github.io/classnames\n*/\n/*!\n  Copyright (c) 2017 Jed Watson.\n  Licensed under the MIT License (MIT), see\n  http://jedwatson.github.io/classnames\n*/`
Full output here: https://gist.github.com/vivcogit/66671fd4f921f9e3f43a3ceb579eb70c#file-result-json

**Expected result**
one banner comment like in source file.
Full expected output here: https://gist.github.com/vivcogit/66671fd4f921f9e3f43a3ceb579eb70c#file-expected_result-json

**Description**
I found that comments are added by two functions - `append_comments` (first time) and `prepend_comments` (second time) in this code: 
```
function doit() {
  stream.prepend_comments(self);
  self.add_source_map(stream);
  generator(self, stream);
  stream.append_comments(self);
}
```

**Relative issues**
At [classnames](https://github.com/JedWatson/classnames/issues/163)
At [webpack](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/294)

**Comment by fabiosantoscode** [comment]
This has been fixed by someone else in the meantime :)
