### ISSUE TITLE
Minified code gets confused when declaring same variable name in try-block

### ISSUE THREAD

**Issue by bpasero** [terser/terser#335]
**Bug**

**Version (complete output of `terser -V`)**

`terser 4.1.4`

**Complete CLI command or `minify()` options used**

`terser --compress --mangle`

**`terser` input**

```js
function test(foo, bar) {
    let model = false;
    if (model) {

    } else {
        model = true;
    }
    try {
        const bar = {};
    } catch (error) {
        bar.dispose();
    }
}
```

**`terser` output or error**

`function test(t,c){let s=!1;s||(s=!0);try{const t={}}catch(c){t.dispose()}}`

**Expected result**

Within the catch block, it should be `c.dispose()` and not `t.dispose()`! After all, the wrong parameter is being called `dispose` on.

**Comment by freund17** [comment]
I was able to reproduce this in `4.0.0`.

One note, because it tripped me off initially:
It is expected to be `c.dispose()` because of `function test(t,c)`, not because of `catch(c)`.
The use of the variable name `c` in the `catch` is actually wrong.

**Comment by fabiosantoscode** [comment]
Thank you very much for the report.

**Comment by bpasero** [comment]
This still reproduces with Terser `4.1.4`.

**Comment by fabiosantoscode** [comment]
Probably with the latest version too. I'll see what I can do this week.

**Comment by bpasero** [comment]
Thanks, I just recently [replaced](https://github.com/microsoft/vscode/commit/c7d4c3ce1be78fecd013cfa22a711e014a78dc8c) `uglify-es` with latest `terser` for VSCode and it would be great to get that fix in eventually 👍

**Comment by fabiosantoscode** [comment]
Very subtle bug, as it revealed a slight problem in the AST design.

**Comment by bpasero** [comment]
Oh great, thanks for fixing it.
