### ISSUE TITLE
Broken source maps?

### ISSUE THREAD

**Issue by stevenvachon** [terser/terser#345]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V`)**
3.17.0

**Complete CLI command or `minify()` options used**
```shell
browserify index-es5.js --debug --transform=sourceify | terser --compress --mangle --output=temp.js --source-map='url=temp.js.map'
```

**`terser` input**
too long

**`terser` output or error**
too long

**Expected result**
Working code.

---

This is very annoying.

Firstly, if I exclude the `'url=temp.js.map'` part, it doesn't automatically include `//# sourceMappingURL` in temp.js.

Secondly, the generated source maps appears broken in Chrome and Safari:
![temp js](https://user-images.githubusercontent.com/170197/56994538-6284fa00-6b6d-11e9-9dbe-eef393b5d773.png)
![0](https://user-images.githubusercontent.com/170197/56994542-64e75400-6b6d-11e9-9b7c-9a7b1bcb1784.png)

**Comment by L2jLiga** [comment]
Have you tried to open this via http protocol? Few month ago I faced with same issue when trying to open files via `file://` protocol

**Comment by L2jLiga** [comment]
I see that you use browserify with `--debug`. Terser uses `node-source-map-support` under the hood and this issue may be relevant to you: https://github.com/evanw/node-source-map-support/pull/66

**Comment by stevenvachon** [comment]
If I remove the `--debug` option, the source map does not get updated (since `babel` (cli) which produced index-es5.js from index.js).

I still have to try with` http://` instead of `file://`.

**Comment by fabiosantoscode** [comment]
Did things work over HTTP @stevenvachon? I'm not too happy to support the `file://` use case :/
