### ISSUE TITLE
terserOptions warnings vs compress.warnings

### ISSUE THREAD

**Issue by dlong500** [terser/terser#346]
**Request for clarification**

How does the terserOptions warnings property differ from the compress.warnings property?  Are they different at all, and if not is one deprecated?  Both properties are currently listed in the documentation.  Apparently UglifyJS recently removed the compress.warnings property and it now emits an error if that property is present.  See https://github.com/mishoo/UglifyJS2/issues/3394.

I can look through the code myself to see what's going on but I thought I'd see if anyone has a quick answer.

**Comment by jridgewell** [comment]
`warnings` is simply a shorthand for setting `compress.warnings`.
