### ISSUE TITLE
Nested function with shadowed variable bug

### ISSUE THREAD

**Issue by ma2ciek** [terser/terser#348]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

3.17.0

**Complete CLI command or `minify()` options used**

```json
{
	"output": {
		"beautify": true
	},
	"compress": {
		"passes": 2
	}
}

```

**`terser` input**

```js
function x(e) {
  function f(t) {
    if (t) {
      const e = t;
      if (e)
        return e;
    }
  }

  return f(e);
}
```

**`terser` output or error**

```js
function x(n) {
    return function(n) {
        if (n) {
            const n = n;
            if (n) return n;
        }
    }();
}
```

**Expected result**

```js
function x(n) {
    return function(n) {
        if (n) {
            const n = n;
            if (n) return n;
        }
    }(n);
}
```

**Comment by ma2ciek** [comment]
@fabiosantoscode, could you provide some insights were the bug might be located? Maybe I'll be able to dig a little bit into it and try to fix it.

**Comment by fabiosantoscode** [comment]
The standard procedure is to disable the "defaults" option so that you can enable and disable compress options, which act as feature flags for Terser. When you find the feature that's actually guilty of this change, you grep for it in the `lib/compress/index.js` file. It has a lot of conditions like `if (compressor.option("unsafe"))` and inside those conditions is the code that runs when that option is enabled.

**Comment by ma2ciek** [comment]
> The standard procedure is to disable the "defaults" option so that you can enable and disable compress options, which act as feature flags for Terser. When you find the feature that's actually guilty of this change, you grep for it in the lib/compress/index.js file. It has a lot of conditions like if (compressor.option("unsafe")) and inside those conditions is the code that runs when that option is enabled.

But the only thing that is used is `passes: 2` - I guess it's not an *unsafe* option. I haven't set the `unsafe: true` flag which is mentioned in the docs (https://github.com/terser-js/terser#the-unsafe-compress-option).

**Comment by ma2ciek** [comment]
The weird thing is that with the `"passes": 1` the produced code is correct and further minifications don't break it.

**Comment by ma2ciek** [comment]
I guess that the error is somewhere in the `collapse()` function in the `compress/index.js` file, but it's hard for me to debug this function as its body is full of implicit globals and with almost no comments 😞

**Comment by ma2ciek** [comment]
```
 ./bin/uglifyjs input.js --config-file options.json -o out.js --verbose
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Dropping unused function f [input.js:2,13]
WARN: pass 0: last_count: Infinity, count: 21
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing e [input.js:5,17]
WARN: Collapsing t [input.js:3,13]
WARN: Collapsing t [input.js:4,22]
WARN: pass 1: last_count: 21, count: 19
```

I guess that the last ones cause the error (`WARN: Collapsing t [input.js:3,13]`, `WARN: Collapsing t [input.js:4,22]`).

**Comment by fabiosantoscode** [comment]
Yes, it's certainly collapse_vars. When I start terser with `collapse_vars=false` it doesn't do this. Thanks for digging into it!

**Comment by fabiosantoscode** [comment]
Managed to close this by being a tad more conservative around variable redefinitions. Could've increased the complexity of the code somewhat but I don't feel it's necessary at all.
