### ISSUE TITLE
Feature Request: ES2018 private class field support

### ISSUE THREAD

**Issue by CodeElegant** [terser/terser#349]
Thank you for considering.

**Comment by GrosSacASac** [comment]
it is not yet a standard (not ES2018)
see https://github.com/tc39/proposals/blob/master/finished-proposals.md for a list of finished proposals

**Comment by jhpratt** [comment]
@GrosSacASac It's stage 3, which is when proposals typically start shipping — it's already shipped in Chrome. I'm currently using Babel to transform private fields, but as soon as Firefox and Safari land, I'm ditching that in favor of _actual_ private fields; that would then necessitate a minifier capable of handling them.

**Comment by tchetwin** [comment]
See https://github.com/terser-js/terser/pull/326 for work on public class fields

**Comment by lazarljubenovic** [comment]
@jhpratt That said, it's still wrong to call it ES2018, as it's misleading. Stage 3 features are _probably_ safe to start using, but they are not standard yet.

**Comment by jhpratt** [comment]
@lazarljubenovic I never called it ES2018. All I said was that it had reached stage 3.

**Comment by CodeElegant** [comment]
I called it ES2018. Sorry I wasn't more pedantic, I was in a hurry and I
have work to get done.

**Comment by TimvdLippe** [comment]
Private fields are now a stage 4 proposal since April 2021: https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by TimvdLippe** [comment]
Oh this was already implemented in #702 so I think we can close this?

**Comment by jridgewell** [comment]
Yup, closing.
