### ISSUE TITLE
Feature request: Evaluate RegExp properties

### ISSUE THREAD

**Issue by RunDevelopment** [terser/terser#400]
**Feature request**

While `toString` on RegExp literals is evaluated, all [other properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Properties_2) are not.
It would be nice if `flags`, `dotAll`, `global`, `ignoreCase`, `multiline`, `source`, `sticky`, and `unicode` were also evaluated.

**`terser` input**
```js
console.log(/foo/.source);
console.log(/a/i.flags);
console.log(/./s.dotAll);
```

**`terser` output**
Same as input.

**Expected result**
```js
console.log("foo");
console.log("i");
console.log(true);
```

**Comment by fabiosantoscode** [comment]
This is quite interesting, but even more so in replacing `someArray.length` with the actual number when Terser knows for sure it's an array.
