### ISSUE TITLE
New option to wrap function arguments

### ISSUE THREAD

**Issue by joseprio** [terser/terser#427]
Feature request

`OptimizeJS` is deprecated, and the `wrap_iife` option in Terser is a very valid replacement. However, `OptimizeJS` will also wrap functions that are passed as arguments under the assumption that they're likely to be called immediately. It would be nice to have an additional option in order to wrap those functions (i.e. `wrap_func_args`).

Happy to provide a PR.

**Comment by fabiosantoscode** [comment]
Could you please provide an example of what you want to happen exactly? I'm not sure I follow.

**Comment by joseprio** [comment]
@fabiosantoscode the Terser `wrap_iife` parameter and the OptimizeJS plugin appeared to optimize the parsing of JS files:
https://github.com/mishoo/UglifyJS2/issues/640

OptimizeJS adds an optimization that Terser currently doesn't have: it will wrap function arguments, so this:
```
a(function() { console.log("Hello world");});
```
Becomes this:
```
a((function() { console.log("Hello world");}));
```
The assumption here is that most function arguments will be executed immediately in that function call, which seems to be a common pattern using in Node-style errbacks, Promise chains, and UMD/Browserify/Webpack module declarations.

The change takes just a few lines of code:
https://github.com/joseprio/terser/commit/c3dc703848fe15a57f44b2ead54256292b428b70

OptimizeJS is now unmaintained and it has some bugs, like in sourcemap generation; I think adding that option would allow Terser to replace that plugin functionality entirely.

**Comment by fabiosantoscode** [comment]
This is very interesting. Thanks for bringing this up.

I'm a bit skeptical that functions passed to other functions are invoked immediately though, node-style callbacks and promises are not called immediately. Although most other functions are.

I'm actually happy to remove the options that turn `(function(){})()` into `!function(){}()`, since besides negating the output it seems to make parsing slower. I never heard about it but I don't think 2 characters is an unfair price to pay for better speeds, and besides arrow functions need the parens anyway and they are the way of the future.

It might be nice to have @nolanlawson's input here, IIUC he used to be behind optimize.

**Comment by joseprio** [comment]
I was certain that wrapping-function heuristic had a benefit, but I certainly didn't know how much would it be, so I decided to adapt a benchmark from OptimizeJS.
I ran Terser with the following options:
- No options (default compress and mangle)
- `negate_iife` + `wrap_iife`
- `negate_iife` + OptimizeJS (in theory this should be exactly as `wrap_iife` and wrapping the function arguments)

Firefox 48 results:
| Library | Terser | Terser+IIFE  | Terser+Opt |
| ------- |:------:| ------------:|:-----------:|
| Create React App | 18.16 | 15.9 | 12.34 |
| Immutable | 3.5 | 3.54 | 2.84 |
| jQuery | 9.27 | 9.1 | 7.84 |
| Lodash | 7.8 | 7.53 | 7 |
| PouchDB | 8.5 | 8.5 | 7.58 |
| Three | 20.34 | 20.72 | 18.4 |

Firefox 68 results (for some reason the resolution is very poor):
| Library | Terser | Terser+IIFE  | Terser+Opt |
| ------- |:------:| ------------:|:-----------:|
| Create React App | 14 | 14 | 12 |
| Immutable | 3 | 3 | 3 |
| jQuery | 8 | 8 | 8 |
| Lodash | 8 | 7 | 7 |
| PouchDB | 8 | 8 | 7 |
| Three | 20 | 19 | 18 |

Chrome 76 results:
| Library | Terser | Terser+IIFE  | Terser+Opt |
| ------- |:------:| ------------:|:-----------:|
| Create React App | 14.62 | 14.94 | 11.89 |
| Immutable | 3.52 | 3.48 | 3.16 |
| jQuery | 9.76 | 9.48 | 9.44 |
| Lodash | 7.53 | 7.98 | 7.02 |
| PouchDB | 7.02 | 7.33 | 7.16 |
| Three | 20.06 | 19.89 | 18.56 |

**Comment by fabiosantoscode** [comment]
Interesting results. Have you disabled `negate_iife` as well in the terser and terser+opt results?

**Comment by joseprio** [comment]
`negate_iife` is only enabled in the vanilla `Terser` results; I will re-run the benchmarks with it disabled.

**Comment by joseprio** [comment]
The results in Chrome 76:

| Library | Negate IIFE | w/o Negate IIFE  |
| ------- | ------ | ------------ | 
| Create React App | 14.57 | 14.83 |
| Immutable | 3.61 | 3.45 |
| jQuery | 8.19 | 7.52 |
| Lodash | 7.7 | 7.42 |
| PouchDB | 6.84 | 6.9 |
| Three | 18.94 | 19.08 |

**Comment by fabiosantoscode** [comment]
Looks like `negate_iife` is irrelevant here then.

**Comment by fabiosantoscode** [comment]
Please send a PR with your commits :) it would be cool to enable this option by default actually, so if it doesn't break too many tests please do do that. That would mean a lot of websites could immediately benefit from this change.

Thanks a lot for bringing this up!

**Comment by joseprio** [comment]
@fabiosantoscode surprisingly, no tests break when I made `wrap_func_args` enabled by default.

About enabling it by default, I see two potential problems:
- @nolanlawson [benchmarks for Safari](https://github.com/nolanlawson/optimize-js) show a performance hit (-1.04%); Safari makes up 15% of the web browser market share thanks to iPhone
- The output uses a few more bytes; it certainly would prove beneficial for most users and scenarios, but the change may upset people who only measure byte size

So I see this change as somewhat controversial. I think the safe option would be to add a section on the README that goes more into detail about `wrap_iife` and `wrap_func_args`, how they work, and present it as a way to improve performance in many scenarios, but with a YMMV disclaimer. I'll put the PR like I have it now, but will definitely amend it with your preferred option.

**Comment by joseprio** [comment]
Created PR: https://github.com/terser-js/terser/pull/433
