### ISSUE TITLE
Sequence ignored when it used in extends of unused class

### ISSUE THREAD

**Issue by L2jLiga** [terser/terser#430]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

latest master

**Complete CLI command or `minify()` options used**

`npx terser issue.js -c --toplevel`

**`terser` input**

```javascript
let x = "FAIL";
class A extends(x = "PASS", Object){}
console.log(x); // PASS
```

**`terser` output or error**

```javascript
let x = "FAIL";
console.log(x); // FAIL
```

**Expected result**

```javascript
let x = "FAIL";
x = "PASS";
console.log(x); // PASS
```

or

```javascript
let x = "PASS";
console.log(x); // PASS
```

or

```javascript
console.log("PASS"); // PASS
```

**Comment by fabiosantoscode** [comment]
Interesting corner case. Maybe this is a more general problem. Can you find more instances of sequences being ignored? Maybe sequences within AST_Export or AST_DefaultAssign?

**Comment by fabiosantoscode** [comment]
Maybe inside AST_Expansion too

**Comment by L2jLiga** [comment]
I'll try my best

**Comment by fabiosantoscode** [comment]
Just closed it @L2jLiga :)

**Comment by L2jLiga** [comment]
@fabiosantoscode very nice fix! But I see couple of todos :wink:

**Comment by fabiosantoscode** [comment]
I probably forgot them there lol
