### ISSUE TITLE
Modify Default --Comments Value

### ISSUE THREAD

**Issue by bdkjones** [terser/terser#438]
**Bug report or Feature request?**
Feature Request

**Version**
4.2.0

**Request**

If I pass `--comments` to the CLI, the current behavior is to keep any comment that has `@license`, `@preserve` and so forth.

I propose this this default be expanded to also keep any comment that begins with `/*!` 

This comment delimiter has become a bit of an unofficial standard across many languages—if there’s an exclamation point, it’s a “strong” comment that’s meant to persist. 

Many scripts use this delimiter rather than `@license`, so it would be handy if Terser recognized the standard by default. Currently, to support it, I must pass a regex value to `comments`, but then I lose automatic support for the other default values and must specify them myself.

I think adding `/*!` to the default set of comments kept when `comments` is passed makes Terser better and eases a very common configuration hassle for users.

Thanks!

**Comment by fabiosantoscode** [comment]
Very interesting! Yes, this makes total sense. Want to send a PR? :)

**Comment by fabiosantoscode** [comment]
@bdkjones I see that terser-webpack-plugin does this by default, but only for comments starting with `/**!`. I feel this would be a better default.

**Comment by fabiosantoscode** [comment]
I agree with this default behaviour! So ignore every `/` or `*` character and the first character that's not one of those, if it's a bang (`!`) marks a comment that's not to be dropped.

**Comment by fabiosantoscode** [comment]
Out in 4.3.4

**Comment by bdkjones** [comment]
Thank you! (Sorry; I meant to send a PR but due to terrible time-management skills I never got around to implementing this.)
