### ISSUE TITLE
Error in command: afk.js TypeError: Cannot read property 'name' of undefined [discord.js]

### ISSUE THREAD

**Issue by developerSupreme** [terser/terser#448]
```
const Discord = require('discord.js');
const db = require('quick.db')

exports.run = async (client, message, args) => {
 
  let user = message.author
  let sebep = args.join(" ")
 
  if (!sebep) return message.channel.send(`:x: Bir sebep yazmalısın.`)
 
  db.set(`afk_${user.id}`, sebep)
  message.channel.send(`:x: Artık \`${sebep}\` sebebiyle AFK'sın.`)
};

exports.help = {
  name: 'afk',
  description: "AFK olmanızı sağlar.",
  usage: 'afk <sebep>'
}
```
---

**Error in command: afk.js TypeError: Cannot read property 'name' of undefined
at cmdFiles.forEach.file (/app/index.js:48:28)
    at Array.forEach (<anonymous>)
at load (/app/index.js:43:10)
    at <anonymous>**

How can I fix it?

**Comment by fabiosantoscode** [comment]
Please follow the issue template by providing the required information, and post a minimal issue which can be reproduced directly with Terser. I tried minifying the file you provide with the default options and the output does export the help object with a name inside.

```
> require('/tmp/discordscript.min.js').help
{
  name: 'afk',
  description: 'AFK olmanızı sağlar.',
  usage: 'afk <sebep>'
}
```
