### ISSUE TITLE
Version 4.3.0 cause the missing variable

### ISSUE THREAD

**Issue by renamoo** [terser/terser#451]
**Bug report**

**Version : 4.3.0** 

I use terser through `ng-packagr`. 
I'm not sure to which repository I should post it, so I will post it to both. 
[Here](https://github.com/ng-packagr/ng-packagr/issues/1399) is the issue in `ng-packgr` .

## Description

_A bug: 
I use ng-packgr to build my library made with Angular.
Suddenly my product uses the library start to throw an error: `mXSSAttempts is not defined` this morning. However, `mXSSAttempts ` is defined [here](https://github.com/angular/angular/blob/master/packages/core/src/sanitization/html_sanitizer.ts#L255) and it had been worked well until the last weekend.
When I looked into the detail, it seems the error is thrown when there is component using `innerHTML`. 

※When I force to use `terser: 4.2.1` , it is fixed. So I assume this might be caused by terser `4.3.0` .

#### How To Reproduce

1. create library with Angular
2. create component with innerHTML
3. build it with ng-packgr
4. use it in other Angular project
5. serve with `--prod` then you'll get an error

#### Expected Behaviour

No Error thrown.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.5.0
@angular/*: 8.3.3
typescript: 3.4.5
``

**Comment by fabiosantoscode** [comment]
@renamoo please try again with 4.3.1

**Comment by Petronious** [comment]
We have the same issue in an Angular 8.2.4 project without ng-packagr.

**Comment by fabiosantoscode** [comment]
@Petronious Can you reproduce this with Terser 4.3.1?

**Comment by xumepadismal** [comment]
@fabiosantoscode Have faced into the same issue in 4.3.0. Just upgraded to 4.3.1 and the error is gone. Thanks!

**Comment by fabiosantoscode** [comment]
Cool, thanks!

**Comment by renamoo** [comment]
@fabiosantoscode Ver 4.3.1 works well in my project, too! Thank you for quick fixing!

**Comment by Petronious** [comment]
@fabiosantoscode 4.3.1 works indeed. Didn't had to change anything in the end, as it was a transitive dependency of angular cli using ```~```
