### ISSUE TITLE
Non-EcmaScript Multiline string using backslash corrupts source map

### ISSUE THREAD

**Issue by SimmeNilsson** [terser/terser#454]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

4.3.1

**Complete CLI command or `minify()` options used**

compress: false
mangle: true

**`terser` input**

Multiline string constructed with the help of backslash.
**NOTE: I'm aware that this is not valid EcmaScript (although it seems to work in all relevant browsers), so I'm fine if this is closed with that as answer.
I still thought I should write this bug report for confirmation and for the next person that has the same issue.**
I used webpack toolchain to reproduce (sorry for that):
https://github.com/SimmeNilsson/Terser-Multiline-Backslash-Concatenation

**`terser` output or error**

Source map of main_embedded.js is broken.
Can be verified by uploading them to
http://sokra.github.io/source-map-visualization/#custom

Breakpoints can't be put in the lines of interest.
Stepping through code in a debugger using the source mapped code behaves erratically.

**Expected result**

I can put break point inside examples print function.
Stepping through code in debugger behaves as expected.

**Comment by ChlorideCull** [comment]
Multi-line strings are part of EcmaScript as far as I'm aware, [defined as the LineContinuation token](http://www.ecma-international.org/ecma-262/10.0/index.html#sec-literals-string-literals).

**Comment by fabiosantoscode** [comment]
Very interesting! Thanks for the report :)

**Comment by kzc** [comment]
I tried the code in question using rollup and terser and it works correctly in http://sokra.github.io/source-map-visualization/#custom.

There's a reason why the issue template form asks for a test case without third party tools like webpack - to remove unknown variables from the equation. Report this issue to either webpack or the maker of the browser you're using.

**Comment by SimmeNilsson** [comment]
@kzc In case you didn't use a bundler, did you compensate for it by putting it all in one file?
My theory is that these type of multilines each introduce an unwanted offset for the lines that follow.
So if you just ran with the example files and no bundler, there would be two separate files and source maps, and no lines following after the multiline string in the htmlEmbedded.js file that can demonstrate the issue.

main_embedded.js:
`const htmlEmbedded = '\
		<div>\
            <span>Embedded</span>\
        </div>';

function print() {
    console.log(htmlEmbedded.html);
}

print();
`

node_modules/.bin/terser main_embedded.js --output dist/main_embedded.js --source-map 'includeSources=true,url=main_embedded.js.map' --verbose
(hope this is the correct way to run it outside the webpack plugin)

The source map that is produced by this does not look good for me in source-map-visualization (mapping-wise) or chrome developer tools (breakpoint-wise).

**Comment by kzc** [comment]
Source maps are only as good as the bundler that prepares the input to the minifier.

Don't use terser at all and observe the output of rollup in http://sokra.github.io/source-map-visualization/#custom and your browser:

```
node_modules/.bin/rollup ./main_embedded.js -f iife -o dist/bundle.js --sourcemap
```

Examine `dist/bundle.js` and `dist/bundle.js.map` in your tools of choice. If it doesn't work then it's the viewer and/or browser's problem.

Also try modifying the rollup `-f iife` output format to `-f es` or `-f umd` for different results.

If you want to view the beautified minified version of the output of rollup, run:

```
node_modules/.bin/terser dist/bundle.js --output dist/bundle.min.js --source-map 'includeSources,content=dist/bundle.js.map,url=bundle.min.js.map' -bmc
```

and then load `dist/bundle.min.js` and `dist/bundle.min.js.map` in your viewer.

Also experiment with using the terser options `--toplevel -bmc passes=3` to see more optimized results. Keep in mind that as code gets heavily inlined and optimized by definition stepping will not work in a debugger. This is expected as some lines of code and functions are completely optimized away. To see the results without optimization change `-bmc passes=3` to just `-bm` for mangling only, or just `-b` for no optimization and no mangle.

**Comment by SimmeNilsson** [comment]
@kzc Thank you for the in-depth information.
My team was trying to keep even the minimized code as debuggable as possible.
Just mangling the code and skipping more aggressive optimizations.
However, debugging was not working well in our test environments with access to source maps.
That was why I looked into this and saw that as soon as terser was running, even without optimizations, we had this issue.
Narrowed it down to the existence of some multiline strings in our code.

In my second attempt, mentioned in my last post, I removed webpack and bundling from the equation but perhaps I should have stated it more clearly.
I've simplified and updated my repo for this issue:
https://github.com/SimmeNilsson/Terser-Multiline-Backslash-Concatenation

No webpack, only terser.
No bundling.
No mangle, no compress, no beautify.
One working example using the newer template literal string format.
One not working example using the backslash multiline string format.

In the source-map-visualization you can see that in the backslash multiline case, the print line maps to a line number that is bigger than the number of lines in the original source.
Every backslash in the multiline string seems to increase the line number in the source map for the following lines with 1 (unintended?) extra.

I attach the generated files if you want to drop them directly into the source-map-visualizer.
[GeneratedFiles.zip](https://github.com/terser/terser/files/3616847/GeneratedFiles.zip)

**Comment by ChlorideCull** [comment]
@kzc As Simme said, this is reproducible with just terser. [I've uploaded a repo with his minimal example and another one](https://github.com/ChlorideCull/terser-repro-454).

His example produces a working sourcemap, the "index.js" example produces an invalid one.

I'd hope the tool isn't incorrect, because it uses `source-map`, just like terser :)

**Comment by kzc** [comment]
I get essentially get the same source map line/column mapping results to those repos in the source map viewer using rollup alone **without terser** using the command I posted above.  If there's a problem then it's strictly a source map issue with the source map viewer and/or browser. Good luck guys.

**Comment by SimmeNilsson** [comment]
@kzc I get correct results if I disable terser in my initial sample. That is bundling with Webpack without minification.
[WebpackOnly.zip](https://github.com/terser/terser/files/3619649/WebpackOnly.zip)

I don't understand why you are so quick in blaming both the viewer and browser given what we know from this conversation and can see in the source maps. Especially when template literals work fine. That source map should look very similar to the backslash multiline one, but in the latter one we see an unwanted offset introduced for each backslash that sabotages the line mappings for the lines that follow after.

So terser has the problem even when running alone without mangling and compression.
And from what you are saying maybe Rollup has one too.

**Comment by ChlorideCull** [comment]
@kzc
> I get essentially get the same source map line/column mapping results to those repos in the source map viewer using rollup alone **without terser** using the command I posted above. If there's a problem then it's strictly a source map issue with the source map viewer and/or browser. Good luck guys.

Claiming the issue is "strictly a source map issue with the source map viewer and/or browser" when it works perfectly fine with Webpack, requires more evidence than Rollup also producing the same issue.

There's plenty of ways to break a source map, it's an annoying standard with a complex implementation. It's completely possible Rollup is doing the same thing.

I'll cool it from now on, we're drifting off-topic. If no one else gets to it, I can debug it later.

**Comment by fabiosantoscode** [comment]
@ChlorideCull would greatly appreciate you looking into this :)

**Comment by kzc** [comment]
Again, I don't see a bug in terser here. 

> requires more evidence than Rollup also producing the same issue.

I used Rollup as another example because it has a completely independent source map generation implementation.

All the terser-only demo repos above debug correctly in FF69. If latest Chrome cannot, then report the bug to that project.

Here's the source map dump of the two examples in https://github.com/SimmeNilsson/Terser-Multiline-Backslash-Concatenation. All mappings look correct to me:

```
$ npm ls | grep source-map@
  ├── source-map@0.6.1
```
```
$ cat dump.js
[
    {"version":3,"sources":["not_working.js"],"names":["myHtml","print","console","log"],"mappings":"AAAA,MAAMA,OAAS,mDAKf,SAASC,QACLC,QAAQC,IAAIH,QAGhBC","sourcesContent":["const myHtml = '\\\n    <div>\\\n        <span>Embedded</span>\\\n    </div>';\n\nfunction print() {\n    console.log(myHtml);\n}\n\nprint();"]},
    {"version":3,"sources":["working.js"],"names":["myHtml","print","console","log"],"mappings":"AAAA,MAAMA,gEAKN,SAASC,QACLC,QAAQC,IAAIH,QAGhBC","sourcesContent":["const myHtml = `\n    <div>\n        <span>Embedded</span>\n    </div>`;\n\nfunction print() {\n    console.log(myHtml);\n}\n\nprint();\n"]},
].forEach(function(json) {
    console.log(JSON.stringify(json));
    var sourcemap = json;
    var consumer = new require("source-map").SourceMapConsumer(sourcemap);
    consumer.eachMapping(m => console.log(JSON.stringify(m)));
    console.log("-----------------------");
});
```
```
$ cat dump.js | node
{"version":3,"sources":["not_working.js"],"names":["myHtml","print","console","log"],"mappings":"AAAA,MAAMA,OAAS,mDAKf,SAASC,QACLC,QAAQC,IAAIH,QAGhBC","sourcesContent":["const myHtml = '\\\n    <div>\\\n        <span>Embedded</span>\\\n    </div>';\n\nfunction print() {\n    console.log(myHtml);\n}\n\nprint();"]}
{"source":"not_working.js","generatedLine":1,"generatedColumn":0,"originalLine":1,"originalColumn":0,"name":null}
{"source":"not_working.js","generatedLine":1,"generatedColumn":6,"originalLine":1,"originalColumn":6,"name":"myHtml"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":13,"originalLine":1,"originalColumn":15,"name":null}
{"source":"not_working.js","generatedLine":1,"generatedColumn":64,"originalLine":6,"originalColumn":0,"name":null}
{"source":"not_working.js","generatedLine":1,"generatedColumn":73,"originalLine":6,"originalColumn":9,"name":"print"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":81,"originalLine":7,"originalColumn":4,"name":"console"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":89,"originalLine":7,"originalColumn":12,"name":"log"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":93,"originalLine":7,"originalColumn":16,"name":"myHtml"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":101,"originalLine":10,"originalColumn":0,"name":"print"}
-----------------------
{"version":3,"sources":["working.js"],"names":["myHtml","print","console","log"],"mappings":"AAAA,MAAMA,gEAKN,SAASC,QACLC,QAAQC,IAAIH,QAGhBC","sourcesContent":["const myHtml = `\n    <div>\n        <span>Embedded</span>\n    </div>`;\n\nfunction print() {\n    console.log(myHtml);\n}\n\nprint();\n"]}
{"source":"working.js","generatedLine":1,"generatedColumn":0,"originalLine":1,"originalColumn":0,"name":null}
{"source":"working.js","generatedLine":1,"generatedColumn":6,"originalLine":1,"originalColumn":6,"name":"myHtml"}
{"source":"working.js","generatedLine":1,"generatedColumn":70,"originalLine":6,"originalColumn":0,"name":null}
{"source":"working.js","generatedLine":1,"generatedColumn":79,"originalLine":6,"originalColumn":9,"name":"print"}
{"source":"working.js","generatedLine":1,"generatedColumn":87,"originalLine":7,"originalColumn":4,"name":"console"}
{"source":"working.js","generatedLine":1,"generatedColumn":95,"originalLine":7,"originalColumn":12,"name":"log"}
{"source":"working.js","generatedLine":1,"generatedColumn":99,"originalLine":7,"originalColumn":16,"name":"myHtml"}
{"source":"working.js","generatedLine":1,"generatedColumn":107,"originalLine":10,"originalColumn":0,"name":"print"}
-----------------------
```

If it doesn't work in a particular viewer or browser then they're probably not incrementing the original source line number when it encounters a backslash followed by a newline.

**Comment by kzc** [comment]
Here's the visualization of the same source map produced by **`terser not_working.js --output dist/not_working.js --source-map includeSources=true,url='not_working.js.map'`** from the terser-only example repo above:

https://sokra.github.io/source-map-visualization/#base64,Y29uc3QgbXlIdG1sPSIgICAgPGRpdj4gICAgICAgIDxzcGFuPkVtYmVkZGVkPC9zcGFuPiAgICA8L2Rpdj4iO2Z1bmN0aW9uIHByaW50KCl7Y29uc29sZS5sb2cobXlIdG1sKX1wcmludCgpOwovLyMgc291cmNlTWFwcGluZ1VSTD1ub3Rfd29ya2luZy5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vdF93b3JraW5nLmpzIl0sIm5hbWVzIjpbIm15SHRtbCIsInByaW50IiwiY29uc29sZSIsImxvZyJdLCJtYXBwaW5ncyI6IkFBQUEsTUFBTUEsT0FBUyxtREFLZixTQUFTQyxRQUNMQyxRQUFRQyxJQUFJSCxRQUdoQkMiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zdCBteUh0bWwgPSAnXFxcbiAgICA8ZGl2PlxcXG4gICAgICAgIDxzcGFuPkVtYmVkZGVkPC9zcGFuPlxcXG4gICAgPC9kaXY+JztcblxuZnVuY3Rpb24gcHJpbnQoKSB7XG4gICAgY29uc29sZS5sb2cobXlIdG1sKTtcbn1cblxucHJpbnQoKTsiXSwiZmlsZSI6ImV4YW1wbGUuanMifQ==,Y29uc3QgbXlIdG1sID0gJ1wKICAgIDxkaXY+XAogICAgICAgIDxzcGFuPkVtYmVkZGVkPC9zcGFuPlwKICAgIDwvZGl2Pic7CgpmdW5jdGlvbiBwcmludCgpIHsKICAgIGNvbnNvbGUubG9nKG15SHRtbCk7Cn0KCnByaW50KCk7

And here's an optimized version of the same source file generated with **`terser not_working.js --toplevel -mc --output dist/not_working.min.js --source-map includeSources=true,url='not_working.min.js.map'`**:

https://sokra.github.io/source-map-visualization/#base64,Y29uc3QgZD0iICAgIDxkaXY+ICAgICAgICA8c3Bhbj5FbWJlZGRlZDwvc3Bhbj4gICAgPC9kaXY+Ijtjb25zb2xlLmxvZyhkKTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9bm90X3dvcmtpbmcubWluLmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vdF93b3JraW5nLmpzIl0sIm5hbWVzIjpbIm15SHRtbCIsImNvbnNvbGUiLCJsb2ciXSwibWFwcGluZ3MiOiJBQUFBLE1BQU1BLEVBQVMsbURBTVhDLFFBQVFDLElBQUlGIiwic291cmNlc0NvbnRlbnQiOlsiY29uc3QgbXlIdG1sID0gJ1xcXG4gICAgPGRpdj5cXFxuICAgICAgICA8c3Bhbj5FbWJlZGRlZDwvc3Bhbj5cXFxuICAgIDwvZGl2Pic7XG5cbmZ1bmN0aW9uIHByaW50KCkge1xuICAgIGNvbnNvbGUubG9nKG15SHRtbCk7XG59XG5cbnByaW50KCk7Il0sImZpbGUiOiJleGFtcGxlLmpzIn0=,Y29uc3QgbXlIdG1sID0gJ1wKICAgIDxkaXY+XAogICAgICAgIDxzcGFuPkVtYmVkZGVkPC9zcGFuPlwKICAgIDwvZGl2Pic7CgpmdW5jdGlvbiBwcmludCgpIHsKICAgIGNvbnNvbGUubG9nKG15SHRtbCk7Cn0KCnByaW50KCk7

It's working as designed.

**Comment by SimmeNilsson** [comment]
Seems the difference between our source maps are the line endings.
\r\n vs \n

Mine does not debug well in FF69.
This is the source map using same line as you:
http://sokra.github.io/source-map-visualization/#base64,Y29uc3QgbXlIdG1sPSIgICAgPGRpdj4gICAgICAgIDxzcGFuPkVtYmVkZGVkPC9zcGFuPiAgICA8L2Rpdj4iO2Z1bmN0aW9uIHByaW50KCl7Y29uc29sZS5sb2cobXlIdG1sKX1wcmludCgpOwovLyMgc291cmNlTWFwcGluZ1VSTD1ub3Rfd29ya2luZy5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vdF93b3JraW5nLmpzIl0sIm5hbWVzIjpbIm15SHRtbCIsInByaW50IiwiY29uc29sZSIsImxvZyJdLCJtYXBwaW5ncyI6IkFBQUEsTUFBTUEsT0FBUyxtREFRZixTQUFTQyxRQUNMQyxRQUFRQyxJQUFJSCxRQUdoQkMiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zdCBteUh0bWwgPSAnXFxcclxuICAgIDxkaXY+XFxcclxuICAgICAgICA8c3Bhbj5FbWJlZGRlZDwvc3Bhbj5cXFxyXG4gICAgPC9kaXY+JztcclxuXHJcbmZ1bmN0aW9uIHByaW50KCkge1xyXG4gICAgY29uc29sZS5sb2cobXlIdG1sKTtcclxufVxyXG5cclxucHJpbnQoKTsiXSwiZmlsZSI6ImV4YW1wbGUuanMifQ==,Y29uc3QgbXlIdG1sID0gJ1wNCiAgICA8ZGl2PlwNCiAgICAgICAgPHNwYW4+RW1iZWRkZWQ8L3NwYW4+XA0KICAgIDwvZGl2Pic7DQoNCmZ1bmN0aW9uIHByaW50KCkgew0KICAgIGNvbnNvbGUubG9nKG15SHRtbCk7DQp9DQoNCnByaW50KCk7

`{"version":3,"sources":["not_working.js"],"names":["myHtml","print","console","log"],"mappings":"AAAA,MAAMA,OAAS,mDAQf,SAASC,QACLC,QAAQC,IAAIH,QAGhBC","sourcesContent":["const myHtml = '\\\r\n    <div>\\\r\n        <span>Embedded</span>\\\r\n    </div>';\r\n\r\nfunction print() {\r\n    console.log(myHtml);\r\n}\r\n\r\nprint();"]}
{"source":"not_working.js","generatedLine":1,"generatedColumn":0,"originalLine":1,"originalColumn":0,"name":null}
{"source":"not_working.js","generatedLine":1,"generatedColumn":6,"originalLine":1,"originalColumn":6,"name":"myHtml"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":13,"originalLine":1,"originalColumn":15,"name":null}
{"source":"not_working.js","generatedLine":1,"generatedColumn":64,"originalLine":9,"originalColumn":0,"name":null}
{"source":"not_working.js","generatedLine":1,"generatedColumn":73,"originalLine":9,"originalColumn":9,"name":"print"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":81,"originalLine":10,"originalColumn":4,"name":"console"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":89,"originalLine":10,"originalColumn":12,"name":"log"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":93,"originalLine":10,"originalColumn":16,"name":"myHtml"}
{"source":"not_working.js","generatedLine":1,"generatedColumn":101,"originalLine":13,"originalColumn":0,"name":"print"}`

**Comment by ChlorideCull** [comment]
@fabiosantoscode I'll take a peek to see if I can fix it when I have time, possibly this weekend.

Seems somewhere in the code something doesn't account for differing lengths of EOL :)

**Comment by kzc** [comment]
git converted the line endings of the JS in the repro repos to unix format which is why the problem did not appear when building from source. It would have been useful information to know that the source files were created on Windows.

Here's a fix:
```patch
--- a/lib/minify.js
+++ b/lib/minify.js
@@ -153 +153,2 @@ function minify(files, options) {
-                options.parse.toplevel = parse(files[name], options.parse);
+                var contents = options.sourceMap ? files[name].replace(/\r\n?/g, "\n") : files[name];
+                options.parse.toplevel = parse(contents, options.parse);
```

The technically more correct fix would be to adjust `current_line` in `lib/output.js` to account for `AST_String` line continuations with DOS line endings. But it's possible that the patch above may have less overhead anyway - and the search/replace is only done if source maps are requested.

When creating the PR please create new mocha sourcemap tests for line continuations with both DOS and unix line endings. Throw in regular and template string literals for good measure.

**Comment by fabiosantoscode** [comment]
Probably the more correct fix is to fix the string parsing code here. Agree that we need tests for DOS line endings.

**Comment by kzc** [comment]
> the more correct fix is to fix the string parsing code

Indeed. The originalLine/originalColumn numbers are wrong with DOS line endings.  I was thinking lib/parse.js and then looked at lib/output.js instead. The generatedLine/generatedColumn output numbers are fine.

Do timings in any case. The line ending search/replace is just a millisecond for a 5MB source file, and may be safer in the event of other DOS line ending issues.

**Comment by kzc** [comment]
Alternative fix in parse:

```patch
--- a/lib/parse.js
+++ b/lib/parse.js
@@ -294,3 +294,3 @@ function tokenizer($TEXT, filename, html5_comments, shebang) {
             S.col = 0;
-            if (!in_string && ch == "\r" && peek() == "\n") {
+            if (ch == "\r" && peek() == "\n") {
                 // treat a \r\n sequence as a single \n
```

It's more efficient and probably as comprehensive as the previous patch. 

When making a PR add mocha source map tests for this code for both unix and dos line endings using toplevel mangle with compress disabled:

```js
const regular = 'A\
    B';
const template = `C\
    D`;
const template2 = `E
    F`;
console.log(regular);
console.log(template);
console.log(template2);
```

**Comment by kzc** [comment]
The suggested mocha test above brought to light that `` `template strings` `` are not presently mapped in source maps. This additional patch adds support for that:

```patch
--- a/lib/output.js
+++ b/lib/output.js
@@ -1922,6 +1922,7 @@ function OutputStream(options) {
         AST_Symbol,
         AST_Switch,
         AST_SwitchBranch,
+        AST_TemplateString,
         AST_Try,
     ], function(output) {
         output.add_mapping(this.start);
```

I'm surprised it went unnoticed.

**Comment by fabiosantoscode** [comment]
Thanks @kzc I applied everything in  c2b53c1

**Comment by kzc** [comment]
@fabiosantoscode The test in c2b53c1 does not exercise the bug fix. 

There was never an issue with multiline template strings and DOS line endings. The problem was with multiline ES5 strings with continuation characters followed by DOS line endings. The template source mapping thing was just an unrelated item I noticed at the time when testing.

The test in https://github.com/terser/terser/issues/454#issuecomment-533676472 actually exercises the ES5 string literal DOS line ending bug. ES6 templates were thrown in just to be comprehensive. I'd suggest such a test be added.

**Comment by fabiosantoscode** [comment]
Oh, alright. I'll add the tests.

**Comment by SimmeNilsson** [comment]
Thank you!
Is it okay if I remove the "Non-EcmaScript" part of the title, so as not to propagate the misinformation that the strings were not part Ecmascript?

**Comment by fabiosantoscode** [comment]
I got this, no problem :)

**Comment by kzc** [comment]
The bug was specifically:

DOS formatted file with multiline ES5 string (backslash CR LF) produces wrong source map line numbers
