### ISSUE TITLE
Shorthand property names/methods not being generated

### ISSUE THREAD

**Issue by dd-pardal** [terser/terser#457]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)**
```
terser 4.3.1
```

**Complete CLI command or `minify()` options used**

```
terser test.js
```

**`terser` input**

```js
const foo = "bar",
obj = {
	getFoo: function () {
		return this.foo;
	},
	foo
};
```

**`terser` output or error**

```js
const foo="bar",obj={getFoo:function(){return this.foo},foo:foo};
```

**Expected result**

```js
const foo="bar",obj={getFoo(){return this.foo},foo};
```

Shorthand property *names* are never generated, while shorthand property *methods* are only generated if present in the original code.

**Comment by fabiosantoscode** [comment]
This is not a safe transform. If you want to do it you have to enable the `unsafe_methods` compress option.

**Comment by dd-pardal** [comment]
You're right. Shorthand property **methods** can't be constructors.

But why does `terser` convert `obj={foo}` into `obj={foo:foo}`?

**Comment by fabiosantoscode** [comment]
@dd-pardal unless you specify an `ecma` output option of 6 or higher Terser will not do that. Anyway mostly Terser is used with mangling, which makes it pointless.
