### ISSUE TITLE
Doesnt fully optimize 'this'

### ISSUE THREAD

**Issue by pimlie** [terser/terser#458]
**Bug report ~~or Feature request~~?**

**Version (complete output of `terser -V` or specific git commit)**
terser 4.3.1

**Complete CLI command or `minify()` options used**
`terser ./terser.js -mc`

**`terser` input**
```js
module.exports = function test () {
  return {
    fn () {
      var aVariable = this.aVariable
      var bParam = this.bParam

      this.cFunc(() => {
        return {
          a: aVariable,
          b: bParam,
          c: this.cFunc.test
        }
      })
    }
  }
}
```

**`terser` output or error**
```
module.exports=function(){return{fn(){var t=this.aVariable,a=this.bParam;this.cFunc(()=>({a:t,b:a,c:this.cFunc.test}))}}};
```

**Expected result**
```
module.exports=function(){return{fn(){var a=this,c=a.aVariable,n=a.bParam;a.cFunc(()=>({a:c,b:n,c:a.cFunc.test}))}}};
```
The expected result was created by changing the input to:
```js
module.exports = function test () {
  return {
    fn () {
      var $this = this
      var aVariable = $this.aVariable
      var bParam = $this.bParam

      $this.cFunc(() => {
        return {
          a: aVariable,
          b: bParam,
          c: $this.cFunc.test
        }
      })
    }
  }
}
```

**More info**
I noticed in a project that terser generated the following:
```
var i=this,u=this.$root,f=this.$options,c=this.$isServer;
```
I cant replicate this exact behaviour in a simple test (I tried, hence the maybe strange replication code), but the `i` was used in a sub scope and it seems strange it didnt use `i` for the `$root` etc variables as well.

**Comment by pimlie** [comment]
Hmm, after playing with my rollup config a bit more, this seems to be caused by babel actually:

Source:
```js
    destroyed () {
      if (!this.$parent || !hasMetaInfo(this)) {
        return
      }
      const interval = setInterval(() => {
        if (this.$el && this.$el.offsetParent !== null) {
          return
        }
        clearInterval(interval)
        triggerUpdate(this.$root, 'destroyed')
      }, 50)
    }
```
Babel returns:
```js
      destroyed: function destroyed() {
        var _this2 = this;
        if (!this.$parent || !hasMetaInfo(this)) {
          return;
        }
        var interval = setInterval(function () {
          if (_this2.$el && _this2.$el.offsetParent !== null) {
            return;
          }
          clearInterval(interval);
          triggerUpdate(_this2.$root, 'destroyed');
        }, 50);
      }
```

which terser minifies to:
```js
destroyed:function(){var n=this;if(this.$parent&&O(this))var e=setInterval((function(){n.$el&&null!==n.$el.offsetParent||(clearInterval(e),N(n.$root,"destroyed"))}),50)}
```

Would it still be reasonable to expect that terser will optimise this?

**Comment by fabiosantoscode** [comment]
It seems like a good optimization space-wise, but I'm skeptical of the benefit this might bring post-gzip. It's not bad to have a bunch of "this." strings as gzip eats that up easily. Also adding another operation to reassign `this` to some name certainly has some cost, both memorywise and performance-wise. So this is not an optimization we would like to have.

**Comment by pimlie** [comment]
Thanks for taking the time to get back on this. Fyi, I checked and for this case it saves post-gzip 6-bytes  (when I manually assign `this` to a local var first). With brotli its 3-bytes.
