### ISSUE TITLE
Object.assign({}, ...) should be considered pure

### ISSUE THREAD

**Issue by leeoniya** [terser/terser#461]
currently, i think terser treats all `Object.assign` calls as impure since the first argument is mutated, but the common case of `const x = Object.assign({}, ...)` is pure and can probably be marked as such so it can be dead-code-eliminated if `x` is unused.

**Comment by fabiosantoscode** [comment]
Terser doesn't feature any kind of knowledge of which functions are pure. You can see from the documentation that not even `Math.floor` is considered pure. The reason for this is that they can be modified by code on runtime, polyfill-style.

If we ever have this kind of information embedded into Terser (which is a pretty good idea and I would welcome the PR) this would certainly go in. However, Terser does not have this at the moment.

**Comment by leeoniya** [comment]
since it's not possible to whitelist a specific signature using the `pure_funcs` option, i guess the way to do it in this case is at the call-site via `/*#__PURE__*/`.
