### ISSUE TITLE
Feature request: Improve elimination of empty switch statements

### ISSUE THREAD

**Issue by jroessel** [terser/terser#465]
**Bug report or Feature request?** Minor improvement

**Version (complete output of `terser -V` or specific git commit)** 4.3.1

**Complete CLI command or `minify()` options used** `-c`

**`terser` input**

```
function f(a){
  switch(a){
    default: break;
    case 0: break;
  }
  return 0;
}
```

**`terser` output or error** (run through prettier afterwards)

```
function f(a) {
  switch (a) {
    default:
    case 0:
  }
  return 0;
}
```

**Expected result**

```
function f(a) {
  return 0;
}
```

This works as expected if the `default` case is the last one, or there's no `default` at all, e.g.:

```
function f(a){
  switch(a){
    case 0: break;
    default: break;
  }
  return 0;
}
```

or

```
function f(a){
  switch(a){
    case 0: break;
  }
  return 0;
}
```

both get the complete `switch` removed.

**Comment by jroessel** [comment]
Well, it's not an uncommon pattern in code I see here (default as non-last case). It's basically a `switch` that handles a set of enum values and one of them happens to also be the default for something unexpected where the default is just a fall-through to a regular case.

That those are empty, well, that's not a common pattern, admittedly (the one I stumbled over here is already empty before conversion to JS). But since terser actually optimizes this already and for some reason requires `default` to be the last option, I thought it was more a case of removing an explicit `if` somewhere to make it work for more cases where the cases are just ordered differently.

**Comment by fabiosantoscode** [comment]
I think if it was that simple it would've been fixed already :) have a look at lib/compress/index.js. Every little case is meticulously planned for (and sometimes goes wrong). There's no way anyone put in an extra if there that increases complexity and output size.

**Comment by jroessel** [comment]
Yeah, I took a look, or three. While I do maintain a compiler and we do some transformations on the output, I had a hard time figuring out what happens where in terser's code (plus, I couldn't figure out how to debug the code). That's more my unfamiliarity with the AST and how to do things in JS, though, I guess.
