### ISSUE TITLE
Feature request: Rewrite a += -b and a -= -b

### ISSUE THREAD

**Issue by jroessel** [terser/terser#466]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.3.1

**Complete CLI command or `minify()` options used** `-c`

**`terser` input**

`a += -b`
`a -= -b`

**`terser` output or error**: The same

**Expected result**

`a += -b` could be rewritten to `a -= b` and `a -= -b` could be rewritten to `a += b`.

This *may* work only if `a` and `b` are known to be numbers, although it could perhaps work even if they're not, as the unary `-` forces at least `b` to be a number. Right now it doesn't make a difference even if everything should be known:

`var a = 5; a -= -7` remains the same, but could become `var a = 5; a += 7` (technically it could become `var a = 12`, but that's a wholly different transformation, of course).

**Comment by kzc** [comment]
> This may work only if a and b are known to be numbers

That's the problem. That's difficult to determine in most scenarios in a dynamic language. For constants, it's already handled:
```
$ echo 'var a = 5, b = 2; a -= -b; console.log(a, b)' | terser --toplevel -c
console.log(7,2);
```
In general an optimization to save a byte or two in rare scenarios (less than 1/100th of one percent of the code size) is not worth the complexity of implementation, minification slowdown incurred, and the risk of inadvertently introducing bugs. Such an optimization would not even be noticed in the bundle size of most real world code post gzip.

**Comment by kzc** [comment]
Related: https://github.com/developit/microbundle/issues/394#issuecomment-495954063

**Comment by jroessel** [comment]
Good point, and yes, it doesn't matter much.
