### ISSUE TITLE
Selective mangling of function names

### ISSUE THREAD

**Issue by Elberet** [terser/terser#468]
**Feature request:**

`terser` should allow the author to tag functions whose name is important; functions tagged in this way should not have their `.name` mangled.

**Background**

I'm working with ES2018 code and a suite of custom Babel plugins to transpile the code into IE11-compatible JavaScript. Due to the frontend framework in use, classes get transpiled in such a way that Terser has no way to detect which functions are actually the class constructor, and as such no currently available options can be used to preserve class constructors' function names.

However, since I can fully control the transpiler output, it would be trivial to emit an annotation comment with the constructor function, but Terser lacks a feature to control function name mangling via such an annotation.

On the other hand, controlling function name mangling based solely on the function name via a regex such as `/^[A-Z]/` seems too broad, and adapting the terser options is in my case harder than injecting a comment into the transpiled source code... 😉

**Version (complete output of `terser -V` or specific git commit)**

Tested with [try.terser.org](https://try.terser.org/)

**Options**

Defaults.

**`terser` input**

```js
define([Superclass], function(Superclass) {
  var ClassName = _decorate(function(Superclass) {
    var ClassName =
    /*#__PURE__*/
    function (Superclass) {
      Superclass.extend("ClassName", {
        constructor: ClassName
      })
      Object.setPrototypeOf(ClassName, Superclass)
      /*#__KEEP__*/
      function ClassName() {
        this.value = "This is the actual class constructor"
      }
      return ClassName
    }(Superclass)

    return { F: ClassName, d: [] }
  })
  return ClassName
})
```

This code is slightly simplified for readability, but is largely based on the output of Babel 7 with @babel/preset-env and @babel/proposal-decorators.

The `/*#__KEEP__*/` annotation is an example for the tag I would like to insert into the code and have terser respect, analogous to the already supported `/*#__PURE__*/` annotation inserted by Babel's @babel/preset-env.

**`terser` output or error**

```js
define([Superclass],function(t){return _decorate(function(t){return{F:function(t){function e(){this.value="This is the actual class constructor"}return t.extend("ClassName",{constructor:e}),Object.setPrototypeOf(e,t),e}(t),d:[]}})});
```

**Expected result**

```js
define([Superclass],function(e){return _decorate(function(e){return{F:function(e){function ClassName(){this.value="This is the actual class constructor"}return e.extend("ClassName",{constructor:ClassName}),Object.setPrototypeOf(ClassName,e),ClassName}(e),d:[]}})});
```

This output was generated with options `{ mangle: { keep_fnames: /^[A-Z]/ } }` - but see above.

**Comment by fabiosantoscode** [comment]
Hey, that's pretty good!

That sounds great to me. Sometimes function names being lost to oblivion is a bother.

Side note: you need to add an option for compress to keep function names as well. I'm not sure it supports regex though.

**Comment by Elberet** [comment]
Yeah, I forgot to add that to the options in the examples above.
In my case, the framework I (grudgingly have to) use already completely disables compression, and the `terser` repl doesn't automatically enable it, so it never came up. 😅

**Comment by fabiosantoscode** [comment]
When you say terser repl do you mean https://try.terser.org ? I think it enables compression by default.

**Comment by Elberet** [comment]
Yeah, that's where I got the actual/expected output samples from. I didn't have to set any `compress` options to get the results, `mangle.keep_fnames` seems sufficient.

**Comment by jridgewell** [comment]
Closing this as `keep_fnames` solves the issue.

**Comment by Elberet** [comment]
@jridgewell can you explain how `keep_fnames` solves this issue specifically?

As far as I can tell, it will either disable function name mangling globally (which is a bad tradeoff), or require the author to maintain an enourmous regex matching only constructor function names (which may, in theory, be impossible).
