### ISSUE TITLE
Output size regression when updating from 4.3.2 to 4.3.3

### ISSUE THREAD

**Issue by filipesilva** [terser/terser#470]
**Bug report or Feature request?**

This is a bug report

**Version (complete output of `terser -V` or specific git commit)**
4.3.3

**Complete CLI command or `minify()` options used**

```
const terserOptions = {
  warnings: false,
  safari10: true,
  output: { ecma: 6, comments: false, webkit: true },
  compress: {
    ecma: 6,
    pure_getters: true,
    passes: 3,
    global_defs: { ngDevMode: false, ngI18nClosureMode: false }
  },
  mangle: true
};
```

**`terser` input**

The output is quite large, but I added a full reproduction that only depends on Terser in https://github.com/filipesilva/terser-4.3.3-size-regression:
```
git clone https://github.com/filipesilva/terser-4.3.3-size-regression
cd terser-4.3.3-size-regression
npm i
npm test
```

You should see the following output:
```
input is 1454.80 kB at ./input.js
terser@4.3.2 output is 13.58 kB at ./output-4.3.2.js
terser@4.3.3 output is 124.01 kB at ./output-4.3.3.js
```

**`terser` output or error**
Output of size 124.01 kB

**Expected result**
Output of size 13.58 kB (this is the size for 4.3.2)

**Other information**

Heya 👋 

At Angular CLI we saw this size regression during a routing renovate-bot pr (https://github.com/angular/angular-cli/pull/15696). I stripped down the repro tooling until it only depended on Terser, but unfortunately the input is still very large.

This is a case were Terser performed extremely well, minifying a 1454 kB input down to only 14 kB in 4.3.2, leaving it at only 1% original size. In 4.3.3 however, the output is now almost 10x larger at 124 kB.

I'm not sure which of the options is actually responsible for the regression but I imagine it's something in `compress`. I left the original input and the full set of options in the repro for easier debugging.

**Comment by fabiosantoscode** [comment]
I wanted to get to this yesterday but was busy. I'll see what I can do.

**Comment by fabiosantoscode** [comment]
That's a nice big real world use case of terser you got here ;) do you have a unit test suite which can run on the compressed code? I'm looking for open source codebases to create a bunch of functional tests for testing code after it's been through the terser default options.

**Comment by filipesilva** [comment]
This particular example is a hello world Angular app, [this one](https://github.com/angular/angular/tree/master/integration/cli-hello-world-ivy-minimal) specifically. 

I can make a Protractor unit test, that checks the app is still running properly. Would that work for you?

**Comment by fabiosantoscode** [comment]
If Angular has unit tests that work on the compressed library, that's even better. AFAIK protractor tests may be flaky and are more useful for application development.

**Comment by filipesilva** [comment]
Oh yeah we do have a bunch of those. We have very aggressive size tracking to ensure we don't introduce regressions in the build pipeline, which is how we found this one to start with.

I updated the repro above to use `terser@4.3.4` and got these results:
```
input is 1454.80 kB at ./input.js
terser@4.3.2 output is 13.58 kB at ./output-4.3.2.js
terser@4.3.4 output is 44.63 kB at ./output-4.3.4.js
```

The bulk of it seems to be gone (124.01 -> 44.63 kB), but I think there's still 30kb extra that weren't there in 4.3.2.

**Comment by fabiosantoscode** [comment]
Oh, indeed. I thought I'd fixed it but then changed something else. I'll have another look.

**Comment by fabiosantoscode** [comment]
Interesting. It's got something to do with pure annotations.

**Comment by fabiosantoscode** [comment]
Ok, I've got it fixed. I shall be releasing a new version soon.

**Comment by fabiosantoscode** [comment]
@filipesilva where can I yoink your unit tests from? :)

**Comment by filipesilva** [comment]
Thank you so much for taking a look at this regression! 

The tests for this particular app installs https://github.com/angular/angular/tree/master/integration/cli-hello-world-ivy-minimal, then builds it, then compares the artifact sizes with https://github.com/angular/angular/blob/877f9ad7b9151324c4a94d3c80e7d37691bb9fd5/integration/_payload-limits.json#L13-L17. 

But to run that you'd need a whole lot of other things to build, and there's nowhere to just update terser in. I don't think that's quite what would work for you. WDYT of me yanking it all out myself and giving you something you can just replace the terser dependency to get a result?

**Comment by fabiosantoscode** [comment]
I appreciate the offer @filipesilva, but that smells like protractor tests, I'd rather have something more lightweight.

I think replacing the terser dependency shouldn't be too hard, just deleting node_modules/terser and placing a symlink there just before the test should do the trick.

**Comment by filipesilva** [comment]
Yes, you're right, it would have to be Protractor... I don't think there's a good way of testing that app otherwise, since it's a browser app that needs to be loaded into a browser environment. I'm sorry that I don't have an example that could be tested for output correctness run outside a full browser environment.

Outside testing it for correctness, testing just the file size would be as easier in the repro in the original issue report here.

Replacing Terser on the toplevel in a complex node_modules might work but I'm not 100% sure it would always work, because that'd depend on hoisting behaviour that is specific to the package installer and is considered an implementation detail that isn't necessarily deterministic. If there's multiple Terser installs that can't be deduper, it'll be hard to determine what packages are getting which Terser.

**Comment by fabiosantoscode** [comment]
True :/ but yarn has a way to replace transitive dependencies with other dependencies or other versions of the dependencies.

Anyway, doesn't angular itself have a test suite that only talks to the exported module(s)? (never used Angular so don't know if it exports a class or a function or a bunch of these)

**Comment by filipesilva** [comment]
This sort of app doesn't actually export modules. The core Angular libs are free from toplevel side effects. So what apps like this do is import a bunch of stuff then call a toplevel bootstrap/render ([here](https://github.com/angular/angular/blob/877f9ad7b9151324c4a94d3c80e7d37691bb9fd5/integration/cli-hello-world-ivy-minimal/src/main.ts#L7)) that does have a side-effect.

When everything goes right, everything but the direct imports are tree shaken. Hence why the resulting app was only 1% of the original pre-compress size.

But there's no export or anything per se. The bootstrap/render is using DOM apis to do its thing.

I remember there were tests somewhere that used https://github.com/fgnass/domino so there might be a way to test correctness on a node environment... let me ask around.

**Comment by fabiosantoscode** [comment]
Interesting, I didn't know about domino. It looks a lot like jsdom

**Comment by filipesilva** [comment]
Ended up making a test with jsdom instead, the documentation was better. It's uploaded to https://github.com/filipesilva/terser-4.3.3-size-regression and contains instructions in the README:

# Testing the output correctness

To test if the output results in a correct app, follow the commands below, replacing the output file with the one you want to test:
```
cp output-4.3.2.js jsdom-test/main-es2015.js
node run-jsdom-test.js
```

If the app works, nothing is printed and the exit code is 0.


If the app does not work, you should get a thrown error like this:
```
$ node run-jsdom-test.js
D:\sandbox\terser-size-regression\run-jsdom-test.js:13
      throw new Error('Angular app was not rendered correctly.')
      ^

Error: Angular app was not rendered correctly.
    at Timeout.setTimeout [as _onTimeout] (D:\sandbox\terser-size-regression\run-jsdom-test.js:13:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by fabiosantoscode** [comment]
@filipesilva looks like you haven't pushed the changes though!

**Comment by filipesilva** [comment]
Oh geez, sorry about that, pushed now!

**Comment by fabiosantoscode** [comment]
Super cool! I can certainly use that test.

I've been copying code into this repo for functional tests: https://github.com/terser/terser-functional-tests. I'll look into copying this over when I can.

**Comment by filipesilva** [comment]
Heya @fabiosantoscode, do you have a timeline for the `4.3.5` release? Our user generated projects are getting `4.3.4` transitively through `terser-webpack-plugin` and thus can't pin it down on, so the best we can do is wait for the release.

**Comment by fabiosantoscode** [comment]
Hey @filipesilva I thought I was going to have more time to work on Terser this week but didn't, so I didn't ship it either. I'm shipping now.

**Comment by filipesilva** [comment]
Thanks for taking the time to release it @fabiosantoscode!

Checked with my repro again and now it's even slightly smaller :D
```
input is 1454.80 kB at ./input.js
terser@4.3.2 output is 13.58 kB at ./output-4.3.2.js
terser@4.3.6 output is 13.56 kB at ./output-4.3.6.js
```
