### ISSUE TITLE
terser minify function modifies options

### ISSUE THREAD

**Issue by evilebottnawi** [terser/terser#471]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

4.3.3

**Complete CLI command or `minify()` options used**

`minify()`

**`terser` input**

Any

**`terser` output or error**

No

**Expected result**

Terser should not modify options

For example:
```js
var code = {
    "file1.js": "function add(first, second) { return first + second; }",
    "file2.js": "console.log(add(1 + 2, 3 + 4));"
};
var options = { toplevel: true };
var result = Terser.minify(code, options);
console.log(result.code);

// !Look here!
console.log(options);
```

It is very bad practice modify argument, will be great fix it

**Comment by L2jLiga** [comment]
Clone of https://github.com/terser/terser/issues/366

**Comment by evilebottnawi** [comment]
Thanks!
