### ISSUE TITLE
Why simple arithmetic functions are not inlined?

### ISSUE THREAD

**Issue by ashi009** [terser/terser#474]
**Bug report or Feature request?**

Question

**Version (complete output of `terser -V` or specific git commit)**

terser 4.3.4

**Complete CLI command or `minify()` options used**

```shell
terser --toplevel --compress inline=true,passes=10 test.js
```

**`terser` input**

```js
function add(a, b) {
  return a + b;
}
function rshift(a, b) {
  return a >> b;
}
function lshift(a, b) {
  return a << b;
}

console.log(add(x, y));
console.log(rshift(add(x, y), r));
console.log(rshift(lshift(add(x, y), l), r));
```

**`terser` output or error**

```js
// formatted for readability
function add(a,b){return a+b}
function rshift(a,b){return a>>b}
console.log(add(x,y)),
console.log(rshift(add(x,y),r)),
console.log(rshift(add(x,y)<<l,r));
```

**Expected result**

```js
// formatted for readability
console.log(x + y);
console.log(x + y >> r);
console.log(x + y << l >> r);
```

**Comment by fabiosantoscode** [comment]
It depends on how many times you use the function. In this case Terser is erroneously assuming that just because the `add` function is used 3 times and the `rshift` function is used 2 times they're not worth it to inline. It's not the case.

However, it's hard for it to understand how small the functions will get after they are inlined, since other terser steps are at play here. I will see what I can do, and invite the community to have a look as well.

Thanks for the report!

**Comment by kzc** [comment]
> In this case Terser is erroneously assuming that just because the add function is used 3 times and the rshift function is used 2 times they're not worth it to inline. It's not the case.

There's no such erroneous assumption. It was a design decision at the time. Single-use function inlining is easier to implement and reason about - and even then it's not that simple in light of function symbol lifetime tracking, scopes, shadowing, captured variables and unique function identities that are relied upon. Never mind the fact that code size always decreases when inlining single-use functions - not necessarily the case for inlining multi-use functions.

**Comment by fabiosantoscode** [comment]
One way we can work around this is with the future `/*#__INLINE__*/` annotation which I'll be adding in a few weeks if I get the time.

**Comment by ashi009** [comment]
> One way we can work around this is with the future `/*#__INLINE__*/` annotation which I'll be adding in a few weeks if I get the time.

I might have been spoiled by the closure compiler, as there are way too many annotations needed to get the pipeline work as intended. Yet, this will make some advanced code optimation possible. Thanks!

**Comment by fabiosantoscode** [comment]
@ashi009 you can now use `/*#__INLINE__*/` on each call to force the function to be inlined. I might implement callee-side inline/noinline annotations too, let's see where this takes us.

**Comment by ashi009** [comment]
> @ashi009 you can now use `/*#__INLINE__*/` on each call to force the function to be inlined. I might implement callee-side inline/noinline annotations too, let's see where this takes us.
I’ll give it a shot.
