### ISSUE TITLE
CLI: `--mangle-props regex=/regex/` is broken

### ISSUE THREAD

**Issue by RReverser** [terser/terser#483]
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**
4.3.4

**Complete CLI command or `minify()` options used**
```bash
$ npx terser --mangle-props regex=/^_/ temp.js
```

(just like provided in the README, using Bash shell)

**`terser` input**

```js
function f(obj) {
	obj._somePrivateProperty = false;
	obj.nonPrivateProperty = true;
}
```

**`terser` output or error**

```js
function f(f){f.t=false;f.u=true}
```

**Expected result**
```js
function f(f){f.t=false;f.nonPrivateProperty=true}
```

**Comment by RReverser** [comment]
Some logging shows the possible cause of the issue - regex from command-line is parsed into a plain object `{ source: '^_', flags: '' }`, which actual minifier then tries to pass to `new RegExp(...)` in

https://github.com/terser/terser/blob/2a0918f01b1b65f01ae0d030f11805ccae2c79f1/lib/propmangle.js#L167

which ends up creating a regex `/[object Object]/`.

This means that any properties with these chars will be minified, whereas any others won't. For example, if I extend my example above to:

```js
function f(obj) {
	obj._somePrivateProperty = false;
	obj.nonPrivateProperty = true;
    obj.huh = '?';
}
```

then it gets minified to

```js
function f(f){f.t=false;f.u=true;f.huh="?"}
```

**Comment by RReverser** [comment]
PR incoming soon.

**Comment by OmarelBouari1** [comment]
--mangle-props regex=/^_/` not working correctly
**complete cli command:**
` $ terser chart.js -o temp.js -c  -m --mangle-props regex=/^_/ --name-cache cache.json`
**content of chart.js**
`let Log = {
	_timeTable: [],
    number_Users:null,
	timeRecovered: [],
	war_ning_: function(msg) {
	},
	time: function(lbl) {
		this.timeTable[lbl] = new Date().getTime();
	},
	sendToServer: function() {
		//TO DO
	},
};`
**cache output or error:**
`{"vars":{"props":{}},"props":{"props":{"$_timeTable":"t","$number_Users":"i","$war_ning_":"o"}}}`
**result expected:**
`{"vars":{"props":{}},"props":{"props":{"$_timeTable":"t"}}}`

Best Regards

**Comment by fabiosantoscode** [comment]
Hey there! I think the underscores are messing with your message :) could you please fix?

**Comment by RReverser** [comment]
My attempt to fix the message based on their Markdown (it also used `` ` `` for multiline code where ```` ``` ```` was needed instead):

---

`--mangle-props regex=/^_/`not working correctly

**complete cli command:**

```bash
$ terser chart.js -o temp.js -c -m --mangle-props regex=/^_/ --name-cache cache.json
```

**content of chart.js**

```js
let Log = {
  _timeTable: [],
  number_Users:null,
  timeRecovered: [],
  war_ning_: function(msg) {
  },
  time: function(lbl) {
    this.timeTable[lbl] = new Date().getTime();
  },
  sendToServer: function() {
    //TO DO
  },
};
```

**cache output or error:**

```js
{"vars":{"props":{}},"props":{"props":{"$_timeTable":"t","$number_Users":"i","$war_ning_":"o"}}}
```

**result expected:**

```js
{"vars":{"props":{}},"props":{"props":{"$_timeTable":"t"}}}
```

---

Just checked, and it does seem to be an issue, although probably a separate one from this one I reported - `/^_/` is matching and mangling properties like `number_Users` and `was_ning_` with underscore in the middle, whereas it should match only `_timeTable`.

**Comment by fabiosantoscode** [comment]
Fascinating! Thanks for checking this out!

**Comment by OmarelBouari1** [comment]
thanks for your answer, changing "/ ^_ /"  to  `/ ^_ / ` solve the problem

**Comment by fabiosantoscode** [comment]
Hey, this seems to have been fixed! I just checked and it works fine.
