### ISSUE TITLE
Duplicate toplevel added in v4.3.7

### ISSUE THREAD

**Issue by guycreate** [terser/terser#485]
**Bug report**

**Version df7cf850ddc96d95fdd1a2c32d026e9521b13dae**

```
../../../node_modules/terser/tools/terser.d.ts(55,5): error TS2300: Duplicate identifier 'toplevel'.
../../../node_modules/terser/tools/terser.d.ts(57,5): error TS2300: Duplicate identifier 'toplevel'.
```

Duplicate `toplevel` was introduced at line 57 of [tools/terser.d.ts](https://github.com/terser/terser/commit/df7cf850ddc96d95fdd1a2c32d026e9521b13dae#diff-13283385a624f611b25f1d95b3f0da53) that causes tsc error against line 55.   Please can you revert this change?

**Comment by fabiosantoscode** [comment]
Sure, it's going out in a few seconds.
