### ISSUE TITLE
Unused variable's assignments aren't removed

### ISSUE THREAD

**Issue by mischnic** [terser/terser#487]
**Bug report or Feature request?**

sub-optimal

**Version (complete output of `terser -V` or specific git commit)**

terser 4.3.8

**Complete CLI command or `minify()` options used**

`terser -cm test.js`

**`terser` input**

```js
(function() {
  var mySetTimeout;

  function defaultSetTimout() {
    throw new Error("setTimeout has not been defined");
  }

  (function() {
    try {
      if (typeof setTimeout === "function") {
        mySetTimeout = setTimeout;
      } else {
        mySetTimeout = defaultSetTimout;
      }
    } catch (e) {
      mySetTimeout = defaultSetTimout;
    }
  })();
})();
```

**`terser` output or error**

```js
!function(){function defaultSetTimout(){throw new Error("setTimeout has not been defined")}!function(){try{"function"==typeof setTimeout?setTimeout:defaultSetTimout}catch(e){defaultSetTimout}}()}();
```
prettified:
```js
!(function() {
  function defaultSetTimout() {
    throw new Error("setTimeout has not been defined");
  }
  !(function() {
    try {
      "function" == typeof setTimeout ? setTimeout : defaultSetTimout;
    } catch (e) {
      defaultSetTimout;
    }
  })();
})();
```

Really strange that all the assignments e.g. `mySetTimeout = setTimeout;` are turned into `setTimeout;` (because `mySetTimeout` is never used and therefore removed), but the right hand side is just an identifier, these statements should be removed completely.

**Expected result**

empty file

**Comment by kzc** [comment]
@mischnic I'm surprised you didn't try the minify options discussed in a few parcel issues.

Given the input in the top post in t487.js:
```
$ terser -V
terser 4.3.8
```
```
$ terser t487.js --toplevel -bmc passes=2
!function() {
    try {
        "function" == typeof setTimeout && setTimeout;
    } catch (t) {}
}();
```
```
$ terser t487.js --toplevel -bmc passes=2,unsafe
// no output
```

> but the right hand side is just an identifier, these statements should be removed completely

Unknown identifiers will throw, so they cannot be generally be safely removed if the aim is to be bug compatible with the original code. The `unsafe` option adds some well known global identifiers. The minifier is conservative by default and doesn't make many assumptions about the environment in which it is run.

**Comment by mischnic** [comment]
> I'm surprised you didn't try the minify options discussed in a few parcel issues.

😬 
For my use case, this would ideally work with the default terser configuration (I don't want to make `unsafe` the default)

> Unknown identifiers will throw, so they cannot be generally be safely removed if the aim is to be bug compatible with the original code.

- In this case, `defaultSetTimout` is a local variable that can be safely removed.
- I don't know how if terser can work on this level, but in `"function"==typeof setTimeout&&setTimeout` the second `setTimeout` is only reached if it is defined.

**Comment by kzc** [comment]
The defaults are optimized for speed and good average minification size for most projects. 95% of minify reduction is generally due to whitespace elimination and mangling identifiers. The final 5% code size reduction in `compress` takes 70% of the time.

> in "function"==typeof setTimeout&&setTimeout the second setTimeout is only reached if it is defined

You're welcome to implement such a feature, but it's not needed in this case. Despite the name, "unsafe" is generally safe unless someone changes the default behavior of builtin functions and classes. These are the same sorts of assumptions that Rollup uses by default. Unless "unsafe" is used, then "setTimeout" is considered to be an unknown global that could throw at runtime. It's exactly like this scenario:

```
$ echo 'var a = unknown_global;' | node
[stdin]:1
var a = unknown_global;
        ^
ReferenceError: unknown_global is not defined
```

`unknown_global` can't be dropped and be compatible with the original code.

Anyway, I don't see an issue here. You have the options to produce no code.

**Comment by mischnic** [comment]
> Anyway, I don't see an issue here. You have the options to produce no code.

My issue is that making `unsafe: true, passes: 2` the default for Parcel is not really an option.
Anyway, thanks again for your help.

**Comment by fabiosantoscode** [comment]
As @kzc says that code can be made to crash. If terser sees code that might crash, it transforms it into minimal code that crashes in the same ways.

You can run this in your favorite JS console (not in a browser tab you might be using though, since this breaks most of the internet :) ):

```
> delete window.setTimeout
> var foo = setTimeout
ReferenceError: setTimeout is not defined
```
