### ISSUE TITLE
Numeric value gets modified

### ISSUE THREAD

**Issue by apierzch** [terser/terser#488]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

terser 4.2.1

**Complete CLI command or `minify()` options used**

```bash
./node_modules/terser/bin/uglifyjs source.js
```

**`terser` input**
```js
let buildTimestamp = 20191009124502559;
```

**`terser` output or error**

```js
let buildTimestamp=0x47bb9da685cc20;
```

**Expected result**

```js
let buildTimestamp=0x47bb9da685cc1f;
```

**Comment by Conduitry** [comment]
That number is too big to be represented precisely in javascript. If you evaluate `20191009124502559` in a browser console or in Node, you'll see it's getting rounded to `20191009124502560`. Terser presumably knows this, and is using it when minifying numbers.

**Comment by fabiosantoscode** [comment]
Terser isn't that smart :) it probably just loses the precision when parseFloat is called!

The thing is that the input and terser output floats you provided are equal to each other:

```
20191009124502559 == 0x47bb9da685cc20
true
```

So while it's not *technically* correct I can't call this a bug, or I'd have to use a bignum library to emulate the necessary precision.
