### ISSUE TITLE
[Bug][Breaking Change][4.3.4>=4.3.5] Error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kopax** [terser/terser#490]
I am using Webpack `4.41.0` and I have issue with production build of documentations.

My documentation is react-styleguidist, they use terser-webpack-plugin which use terser.

Without terser on, it work fine,

I got all my documentation production build broken because it is on.

Example: https://rollup-umd.github.io/test/

`Error:  RangeError: Maximum call stack size exceeded`

I haven't change anything in my source code. It just happen to be broken. 

I can't remove UglifyJS plugin because `react-styleguidist` forbid it. 

**Current behavior**

After running `npm run styleguide:build`, I have:

```bash
bundle.ebc589be.js:65 Uncaught RangeError: Maximum call stack size exceeded
    at e (bundle.ebc589be.js:65)
    at e (bundle.ebc589be.js:65)
   ...
Show 170 more frames
```

**To reproduce**

- Example: https://rollup-umd.github.io/test
- Local Reproduction:

```
git clone https://github.com/rollup-umd/test.git
cd test
npm i
npm run styleguide:build
npm i -g serve
serve public
# open chrome and http://localhost:5000
```

**Expected behavior**

- Work as in `npm run styleguide`.

**Related information**

It was working the 3rd of october or after, since then, I have not change anything in all my sources codes.

- https://github.com/webpack/webpack/issues/9794
- https://github.com/styleguidist/react-styleguidist/issues/1441

**All my production build** in all my projects are down.

I believe (unless I am wrong but to me it is the only valid reason): the dep tree as changed.

For those who ask why I don't have a lock file: It is because we do not use `package-lock.json` in distributed modules, because lock file are for application.

**Comment by kopax** [comment]
After long hours of debugging, I finally found that it break between terser `4.3.4` abd `4.3.8`.

**Comment by fabiosantoscode** [comment]
I think I've fixed this. Please try again with v4.3.9 and @ me :)

**Comment by kopax** [comment]
@fabiosantoscode yes error is fixed, thanks a lot!

**Comment by fabiosantoscode** [comment]
Yaas!

This was caused by the fact that keep_fnames now preserves names of variables which contain anonymous functions. It wasn't implemented right.

**Comment by IgnacioHR** [comment]
Hello,

After migrating our project to Angular 9 I'm having this problem too. Here is additional information that hope helps find the reason
![Window](https://user-images.githubusercontent.com/16385090/76511973-36582c00-6454-11ea-97ad-07e365873aa4.jpg)
:

Cheers

**Comment by cmxl** [comment]
![image](https://user-images.githubusercontent.com/10906748/77225561-757f2f00-6b70-11ea-8878-f660cc726bb2.png)

Please reopen this issue. 
Same error as @IgnacioHR

**Comment by fabiosantoscode** [comment]
Hello there! The current version is 4.6.6. Could you try that one?

Also, could you try to provide a minimal reproduction of the issue? I can't help if I don't know what is crashing Terser.

**Comment by arthurspa** [comment]
> Hello,
> 
> After migrating our project to Angular 9 I'm having this problem too. Here is additional information that hope helps find the reason
> ![Window](https://user-images.githubusercontent.com/16385090/76511973-36582c00-6454-11ea-97ad-07e365873aa4.jpg)
> :
> 
> Cheers

I have the same problem after upgrading to angular 9

**Comment by fabiosantoscode** [comment]
Hello! Please upgrade to the latest version of Terser. If you find an issue, please open a new issue and follow the reporting guide.

**Comment by arthurspa** [comment]
Hi, when I ran `ng update @angular/core` and `ng update @angular/cli` it worked. Probably because one of those two commands upgraded Terser lib.

Thanks.
