### ISSUE TITLE
BUG: IE8 problem

### ISSUE THREAD

**Issue by jasmineMu** [terser/terser#491]
**Bug report**

**Version  "terser": "^4.3.8" **

**`terser` output or error**
Source code：
```
function messageBoard(config) {
  var incomtpl = config.incomtpl,
    outgotpl = config.outgotpl;
  function doSomething(msg, i) {
    if (i >= 10) {
      return;
    }
    i++;
    console.log(msg,i);
    doSomething(msg, i);
  }
  return {
    append: function (type, msg) {
      var template;
      switch (type) {
        case 'i':
          template = incomtpl;
          break;
        case 'o':
          template = outgotpl;
          break;
      }
      try {
        if(!template){
          throw new Error("Template exception!")
        }
        doSomething([template, type, msg].join("-"), 0);
      } catch (e) {
        console.error(e,template,type,msg);
      }
    }
  }
}

var mboard = messageBoard({incomtpl:"incomtpl",outgotpl:"outgotpl"})
mboard.append("i","test");
mboard.append("o","test");
mboard.append("s","test");
```

output：

terser.minify(code, {
  ie8: true
})

```
function messageBoard(o){var t=o.incomtpl,e=o.outgotpl;return{append:function(o,a){var r;switch(o){case"i":r=t;break;case"o":r=e}try{if(!r)throw new Error("Template exception!");!function t(o,e){e>=10||(e++,console.log(o,e),t(o,e))}([r,o,a].join("-"),0)}catch(n){console.error(n,r,o,a)}}}}var mboard=messageBoard({incomtpl:"incomtpl",outgotpl:"outgotpl"});mboard.append("i","test"),mboard.append("o","test"),mboard.append("s","test");
```
![image](https://user-images.githubusercontent.com/11729993/66621275-21157200-ec16-11e9-8dec-ee08a4882920.png)

**Expected result**
![image](https://user-images.githubusercontent.com/11729993/66621305-38ecf600-ec16-11e9-9c52-2a8591bda981.png)

**Comment by fabiosantoscode** [comment]
I have to get my hands on an IE8 to test this :)

How long are you going to support it for? Microsoft has abandoned it a while ago.

**Comment by Martii** [comment]
@fabiosantoscode 

> I have to get my hands on an IE8 to test this

In case you don't know already... https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by fabiosantoscode** [comment]
@Martii I do know that site very well :) it just takes a while to download and while I want to support IE8, it's not such a priority to me.

That said, why close? I will get to this eventually.

**Comment by fabiosantoscode** [comment]
I've changed my mind. IE8 is really, really old :/ I'll be deprecating it eventually. But for now I'll just keep this closed.
