### ISSUE TITLE
Constructor names prefixed with "js_"

### ISSUE THREAD

**Issue by CreativeBulma** [terser/terser#492]
Hi,

when using Terser with following webpack settings:
```js
optimization: {
		minimizer: [new TerserPlugin({
			sourceMap: false,
			terserOptions: {
				compress: true,
				keep_fnames: true,
				ie8: false,
				output: {
					comments: false,
				},
			}
		})],
	}
```

my classe's constructor names are prefixed by "js_". I d'ont understand why ? How can I prevent them to get prefixed and keep the original class name?

EDIT: only classnames  from node_modules are prefixed. Not the one from my own code.

Regards,

**Comment by fabiosantoscode** [comment]
Does this still happen when you turn Terser off? Because there's nothing in it that changes names besides mangling them.

**Comment by CreativeBulma** [comment]
When I turn Terser off my function names and class names are minified and I lose the original name

**Comment by fabiosantoscode** [comment]
But if you remove the minifier step completely, can you still reproduce?

**Comment by fabiosantoscode** [comment]
Closing since it is very unlikely that Terser is adding prefixes to names.
