### ISSUE TITLE
Terser - incorrect reassignment of global variable within local scope

### ISSUE THREAD

**Issue by karanaditya993** [terser/terser#494]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser: 4.0.0

**Complete CLI command or `minify()` options used**
using Terser REPL https://try.terser.org/
with default options:
```
// edit terser options
{
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**
```js
(function (scopedGlobal1, scopedGlobal2, scopedGlobal3) {
    var firstModule = require("6789");
    var secondModule = require("1234");
    var thirdModule = require("1023");
    var mod = require("moduleInQuestion");

    function doACheck() {
        // MOD CONTEXT HERE IS GLOBAL MOD VAR ABOVE
        mod.useModInQuestion();
    }

    function constructArray(a, otherModuleProp, scopedGlobal3) {
        var newData = [];
        for (var i = 0; i < 10; i++) {
            doACheck() ? newData.push({
                a, 
                otherModuleProp, 
                scopedGlobal3,
            }) : newData.push({});
        }
        return newData;
    }

    function functionInQuestion(scopedGlobal1, scopedGlobal2, scopedGlobal3, r) {
        var localVar = scopedGlobal1.someProperty;
        var otherLocalVar = localVar.deeperProperty;
        var mod = localVar.getOtherModule(scopedGlobal2);
        
        var data = constructArray(otherLocalVar.a, mod.otherModuleProp, scopedGlobal3);
        return { data, r };
    }

    function cleanup(firstModule) {
        firstModule.cleanup();
    }

    function remove(firstModule) {
        cleanup(firstModule);
    }

    function someFunction(thirdModule, firstModule) {
        if (thirdModule.property) { remove(firstModule); }
        const randomHash = Math.random(0, 100);
        const finalResult = functionInQuestion(scopedGlobal1, scopedGlobal2, scopedGlobal3, randomHash);
        console.log(finalResult);
    }

    function init(firstModule) {
        secondModule.fn();
        someFunction(thirdModule, firstModule);
    }
    init(firstModule);
})(scopedGlobal1, scopedGlobal2, scopedGlobal3);
```

**`terser` output or error**
```js
! function (o, e, r) {
    var n = require("6789"),
        u = require("1234"),
        t = require("1023"),
        l = require("moduleInQuestion");
    ! function (n) {
        u.fn(),
            function (n, u) {
                n.property && function (o) {
                    ! function (o) {
                        o.cleanup()
                    }(o)
                }(u);
                const t = Math.random(0, 100),
                    l = function (o, e, r, n) {
                        var u = o.someProperty,
                            t = u.deeperProperty,
                            l = u.getOtherModule(e);
                        return {
                            data: function (o, e, r) {
                                for (var n = [], u = 0; u < 10; u++) void l.useModInQuestion() ? n.push({
                                    a: o,
                                    otherModuleProp: e,
                                    scopedGlobal3: r
                                }) : n.push({});
                                return n
                            }(t.a, l.otherModuleProp, r),
                            r: n
                        }
                    }(o, e, r, t);
                console.log(l)
            }(t, n)
    }(n)
}(scopedGlobal1, scopedGlobal2, scopedGlobal3);
```

**Expected result**
The issue at hand is the reassignment of a global variable within the context of an anonymous function. 
*In the terser input:*
`functionInQuestion` is assigning a local variable `mod` to be a module whose accessed property is passed into the `constructArray` function in the next line.
The `mod` variable's scope is restricted to `functionInQuestion`...any other references to `mod` outside of the `functionInQuestion` scope are referring to the global `mod` declared at the T.O.F

*In the terser output:*
As you can see, the `constructArray` function is minified to be an anonymous function whose return value is the value of the `data` key in the object that is returned out of the `functionInQuestion` , `(function (o, e, r, n))` in terser output:
```js
 data: function (o, e, r) { // constructArray in terser input
    for (var n = [], u = 0; u < 10; u++) void l.useModInQuestion() ? n.push({
        a: o,
        otherModuleProp: e,
        scopedGlobal3: r
    }) : n.push({});
    return n
}(t.a, l.otherModuleProp, r),
```
 
If we look inside the anonymous function, we are using the overwritten local context of the `l` variable, as opposed to the global context of `l`, (at the top, `require("moduleInQuestion")`). However, in the terser input, we are using the global context of `mod` (minified to be `l`).
```js
 l = u.getOtherModule(e);
...
for (var n = [], u = 0; u < 10; u++) void l.useModInQuestion() ? n.push({
// l.useModinQuestion() is using above l context instead of global l context
```
*Issue and questions:*
Forgive my ignorance here, but I am wondering how the terser minifier decides when to anonymize a function declaration vs. calling out to an external function. It seems to me as though the issue here would be resolved if the minifier ended up calling out to a named function for the value of `data:` instead of anonymously declaring and invoking it inline. 

Please let me know if there are any questions you may have as I know that this code is a little tricky to understand. Thank you very much in advance.

**Comment by fabiosantoscode** [comment]
I have only skimmed the issue here, I'll have a deeper look later. But it seems like you're not used to reading multiple var declarations. They're not often used because they're hard to read, but `var a = 1, b = 2` declares two variables `a` and `b`. `b` is declared in this scope and not assigned to an outer scope, since this comma makes it part of the `var` statement itself.

**Comment by karanaditya993** [comment]
@fabiosantoscode that definitely did trip me up a bit, however the issue (using your example) is that `b` is being used within an anonymously declared inline function incorrectly after being minimized through terser

**Comment by fabiosantoscode** [comment]
Oh, I see what you mean. This looks serious.

**Comment by JessicaSachs** [comment]
Hey @fabiosantoscode, thank you so much for the response. I work with Karan. We had this same issue back in March with a different area of the codebase, but never got around to distilling it in a cleaned-up way. If you need an additional sample to help narrow down the issue I can do some sleuthing and dig up another sample of the bug.

For anyone finding this issue and looking for a quick fix... a temporary workaround we've used is to redeclare the global requires in the functions that use them.

**Comment by Erutan409** [comment]
Yikes, this is unfortunate.  Seeing the same issue with what's outlined in the ticket.

**Comment by fabiosantoscode** [comment]
I've been a bit busy but I'll look into this today!

**Comment by fabiosantoscode** [comment]
I've made it a tad more minimal.

```
(function (){
    var mod = require("moduleInQuestion");

    function doACheck() {
        // MOD CONTEXT HERE IS GLOBAL MOD VAR ABOVE
        mod.useModInQuestion();
    }

    function constructArray() {
        //var newData = [];
        for (;;) {
            doACheck()
        }
        //return newData;
    }

    function functionInQuestion(a) {
        var mod = leak()//ocalVar.getOtherModule(scopedGlobal2);


        var data = constructArray(leak(mod));
        return { data, };
    }
        const finalResult = functionInQuestion()//scopedGlobal1, scopedGlobal2, scopedGlobal3, randomHash);
        console.log(finalResult)
})()
```

**Comment by fabiosantoscode** [comment]
There we go :)
