### ISSUE TITLE
Get a list of files that ended up in the bundle after optimization

### ISSUE THREAD

**Issue by n1kk** [terser/terser#495]
I'm using terser with webpack to remove dev/debug code from the bundle using conditional compilation constants. It works fine but I am looking for a way to programatically check for it and fail build if my dev/debug files get included in production build.

Is there a way to get the list of source files that end up in the output?

**Comment by fabiosantoscode** [comment]
Webpack calls terser with JS source code strings, not file names. I suggest you open an issue on webpack if you can't find the solution you want in their docs. I think their "stats" object might have what you want but it's been years since I've looked at one of those so I'm not sure :)
