### ISSUE TITLE
Terser doesn't remove unused function 

### ISSUE THREAD

**Issue by cmc3cn** [terser/terser#497]
> 

     var t = function(module, __webpack_exports__, __webpack_require__) {

         __webpack_require__.d(__webpack_exports__, "a", function() {
                return cube;
        });    

        function cube(x) {
                  return x * x * x;
        }

       function addX1(x) {
                    return x + Math.random() * 1111111111;
        }

       function addX2(x) {
                    return x + Math.random() * 2222222222 * eval("addX5")(x);
        }    

    }

the function addX1 and  addX2 should be remove by terser.

**Comment by fabiosantoscode** [comment]
When `eval` is used, all bets are off! Terser won't read the eval string and just assumes it might be using any function in the scope.

Avoid using eval to get around this :)
