### ISSUE TITLE
How to reserve 1000 (not convert to 1e3)

### ISSUE THREAD

**Issue by kaxium** [terser/terser#499]
Hi,

when using Terser, I find it converts 1000 to 1e3 by default, but i don't want this behavior. How to set option  to disable the feature?

**Comment by L2jLiga** [comment]
Terser chooses shortest possible variant of number and there is no flag, yet :wink:
When printing number Terser calls make_num method here: https://github.com/terser/terser/blob/master/lib/output.js#L1970
