### ISSUE TITLE
Invalid JS produced when unused variables are removed

### ISSUE THREAD

**Issue by guillaumesmo** [terser/terser#503]
Hello,

I identified an issue with terser when unused variables are removed in specific situations

The code is completely fake, but is based on a real-world file (https://github.com/kartik-v/strength-meter/blob/master/js/strength-meter.js) where variables are incremented in complex conditions and then not used

test.js

    function test() {
        var hello = "world", a = 0, b = 0;

        if (hello.match(/[^\w]/g)) {
            if (hello !== "") {
                a++;
                b++;
            }
            hello = "";
        }
    }

terser -c -- test.js

    function test(){var hello="world";hello.match(/[^\w]/g)&&(""!==hello&&(),hello="")}

the {a++, b++} is compiled to () which doesn't seem to be valid JS:
`Uncaught SyntaxError: Unexpected token ')'`

**Comment by guillaumesmo** [comment]
A small bisect analysis revealed the last good version is 4.3.4
so the issue has been introduced in 4.3.5

**Comment by fabiosantoscode** [comment]
Hey! Fake code is perfectly OK, if it's small enough I can pretend to run it in my head. I managed to fix this, and will release later today. Thanks for reporting!
