### ISSUE TITLE
Incorrect error "unexpected token punc (;)" for class element

### ISSUE THREAD

**Issue by fkleuver** [terser/terser#505]
**Bug report**

Non-leading/trailing semicolon class elements are considered invalid syntax by terser but they are valid as per the spec. See: http://www.ecma-international.org/ecma-262/#prod-ClassElement

[This appears to be the offending code](
https://github.com/terser/terser/blob/c2b53c13dcc95b24d3dfa37e81334825d518aedd/lib/parse.js#L2433)
```ts
            method = concise_method_or_getset(as_property_name(), start, true);
            if (!method) { unexpected(); }
```

In the parser, you only appear to be allowing leading and trailing semicolons.

We discovered this via an issue reported at [Aurelia](https://github.com/aurelia/aurelia/issues/735). Obviously that was a sloppy bit of code that we had to sort, but still it shouldn't have failed in terser in the first place.

**Version (complete output of `terser -V` or specific git commit)**

The offending code exists on the master branch

**Complete CLI command or `minify()` options used**

Not sure. Issue was reported by one of our users. I don't think it matters though

**`terser` input**

```ts
class Foo {
    constructor() {}
    ;
    ;
    method() {}
}
```

Note that this is the sort of code that TypeScript will generate if you accidentally have two semicolons after an inline property assignment, e.g.:

```ts
class Foo {
    public prop = null;;
    constructor() {}
    method() {}
}
```

**`terser` output or error**

```
ERROR in main.js from Terser
Unexpected token: punc (;)
```

**Expected result**

No errors.

**Comment by fabiosantoscode** [comment]
Thanks for reporting this!
