### ISSUE TITLE
Cannot access 'n' before initialization

### ISSUE THREAD

**Issue by bp0002** [terser/terser#508]
**Bug report or Feature request?**
`Bug report`

**Version (4.3.1)**

**Complete CLI command or `minify()` options used**
<pre>
// options
{
  toplevel: true,
  compress: {
    passes: 5,
    pure_getters: true
  },
}
</pre>

**`terser` input**
<pre>
const foo = () => {
    let a;

    {
        let b = [];

        {
            console.log();
        }

        a = b;

        {
            let c = a;
            let b = 123456;
            console.log(b);
            c.push(b);
        }

    }
};

foo();
</pre>

**`terser` output or error**
<pre>
(()=>{let o;console.log();{let l=o=n,n=123456;console.log(n),l.push(n)}})()
</pre>
<pre>
// err
Uncaught ReferenceError: Cannot access 'n' before initialization
</pre>

**Expected result**

**Comment by fabiosantoscode** [comment]
Excellent report, thanks!

**Comment by fabiosantoscode** [comment]
This has been fixed and is out now as 4.4.1. Thank you!
