### ISSUE TITLE
ERROR: Unexpected token: operator (=)

### ISSUE THREAD

**Issue by yarekc** [terser/terser#509]
```
class ChatMessenger {
    asyncLoadScripts = (origin) => {
   console.log(origin);
 }
}
```

gives me : 
**Unexpected token: operator (=)**

**Comment by Conduitry** [comment]
That syntax is still a stage 3 proposal and isn't official yet.

**Comment by L2jLiga** [comment]
Hi there,
It duplicates https://github.com/terser/terser/issues/303 and PR already in place https://github.com/terser/terser/pull/326

**Comment by fabiosantoscode** [comment]
Indeed! Thanks for the report anyway!
