### ISSUE TITLE
Identity function should be inlined

### ISSUE THREAD

**Issue by orokanasaru** [terser/terser#510]
**Feature request**

In TypeScript, it's frequently convenient to write an identity function to simplify type conversions. 
Unfortunately, the definitions and calls continue to remain after invoking Terser.
Is it possible to get Terser to optimize this case?

**Version (complete output of `terser -V` or specific git commit)**
4.4.0

**Complete CLI command or `minify()` options used**

```js
{}
```

Also tried explicitly setting `inline`:

```js
{
  compress: {
    inline: true
  }
}
```

**`terser` input**

```js
const id = x => x;
const repro = [id(1), id(2)];
console.log(repro);
```

**`terser` output or error**

```js
const id=o=>o,repro=[id(1),id(2)];console.log(repro);
```

**Expected result**

```js
const repro=[1,2];console.log(repro);
```

or even:

```js
console.log([1,2])
```

**Comment by fabiosantoscode** [comment]
Sounds like a great idea! I love the identity function but in this case I'm not sad to see it go
