### ISSUE TITLE
Improve redecoration error naming

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [terser/terser#515]
Recently we got an error in a webpack production build.
```js
ERROR in dashboard.2bbdd6.js from Terser
module redeclared [dashboard.2bbdd6.js:6659,6]
```
It was confusing for us what module it is that's being referred. It turned out it's not an actual module, it is a variable named module. Would be easy for us if it was saying `"module" is redeclared` or `something named "module" is redeclared` at:
https://github.com/terser/terser/blob/a0a50eaca7cb57e75c74e2b07f25f25762bd3844/lib/scope.js#L321

I know it throws with filename and the line number, but in our case it was a single huge bundled file

**Comment by fabiosantoscode** [comment]
Thanks for pointing this out? Want to send a PR? `"module" is redeclared` sounds great to me.

**Comment by OrkhanAlikhanov** [comment]
Is it okay to use ES6 template strings?
```js
`"${node.name}" is redeclared`
```

**Comment by fabiosantoscode** [comment]
Yes, it is :)

**Comment by OrkhanAlikhanov** [comment]
Sent the PR #516
