### ISSUE TITLE
Inline annotation behavior appears inconsistent

### ISSUE THREAD

**Issue by orokanasaru** [terser/terser#531]
**Bug report or Feature request?**

Feature request. 

It seems like the behavior of inline annotations seems inconsistent depending on declaration.

**Version (complete output of `terser -V` or specific git commit)**

4.4.2. 
It looks like the terser.org REPL does not support this at all.

**Complete CLI command or `minify()` options used**

```js
{
  compress: {
    passes: 999999
  },
  mangle: false,
  output: {
    beautify: true
  },
  module: true
}
```

**`terser` input**

1.
```js
function shouldInline(n) {
  return +n;
}

function shouldNotInline() {
  return 1;
}

const a = /*@__INLINE__*/ shouldInline(0);
const b = /*@__INLINE__*/ shouldInline(0);
const c = /*@__NOINLINE__*/ shouldNotInline();
const d = /*@__NOINLINE__*/ shouldNotInline();

console.log(a, b, c, d);
```

2.
```js
const shouldInline = n => +n;
const shouldNotInline = () => 1;

const a = /*@__INLINE__*/ shouldInline(0);
const b = /*@__INLINE__*/ shouldInline(0);
const c = /*@__NOINLINE__*/ shouldNotInline();
const d = /*@__NOINLINE__*/ shouldNotInline();

console.log(a, b, c, d);
```

**`terser` output or error**

1.
```js
function shouldNotInline() {
    return 1;
}

const c = shouldNotInline(), d = shouldNotInline();

console.log(0, 0, c, d);
```

2.
```js
const shouldInline = n => +n, 
shouldNotInline = () => 1, 
a = shouldInline(0), 
b = shouldInline(0), 
c = shouldNotInline(), 
d = shouldNotInline();

console.log(a, b, c, d);
```

**Expected result**

1. It did what I expected (other than not collapsing single reference constants).
```js
function shouldNotInline() {
    return 1;
}

console.log(0, 0, shouldNotInline(), shouldNotInline());
```

2. The `/*@__NOINLINE__*/` annotation worked, but the `/*@__INLINE__*/` annotation did not. Again, single reference constants were not collapsed, which seems like another issue (#215?).
```js
const shouldNotInline = () => 1; 

console.log(0, 0, shouldNotInline(), shouldNotInline());
```

**Comment by fabiosantoscode** [comment]
Thank you for posting this nice and reproducible issue! I've reproduced this myself, tinkered around a bit, and am going to have a deeper look at this. I probably overlooked something when implementing these annotations.

**Comment by fabiosantoscode** [comment]
So I fixed the issue, and it seems like I fixed the "bonus issue" (single use constants not being collapsed) as well as improved compression in some cases. Thanks a lot for posting this issue!
