### ISSUE TITLE
ECMAScript versions should be settable by year

### ISSUE THREAD

**Issue by justinfagnani** [terser/terser#535]
**Feature request**

JavaScript after ES6/ES2015 is referred to by year name. "ES7" or "ES8" basically doesn't exist, they are rather ES2016 and ES2017. This applies to how TC39 talks about and ratifies ECMAScript versions, and how other tools (like TypeScript, for instance) use the labels in their settings.

Since I know that my project uses ES2017, and I use that to reference the version everywhere else, I'd rather use that in setting than try to figure out which "numbered version" that corresponds to.

**Comment by fabiosantoscode** [comment]
I've thought about this one, and it does make a lot of sense. I also never know what version we're at at any point, and using the current year is a lot easier. Would you like to send a PR for this? The previous way of specifying versions should still work, so as to avoid breaking changes.

**Comment by L2jLiga** [comment]
Hi there, I've created PR for that: https://github.com/terser/terser/pull/541

Hopefully I changed all places when it was required :sweat_smile:
