### ISSUE TITLE
BigInt turned into scientific notation numbers

### ISSUE THREAD

**Issue by AlexGustafsson** [terser/terser#546]
**Bug**

**Version: 4.4.0**

**Complete CLI command: `terser --compress --mangle`**

**`terser` input**

```
const a = 10n ** 6n;
```

**`terser` output or error**

```
const a = 1e6;
```

**Expected result**

```
const a = 1000000n;
```

As you can tell, the plugin does not respect `BigInt` and turns them into regular numbers which are not compatible with `BigInt` arithmetic.

**Comment by AlexGustafsson** [comment]
@fabiosantoscode Any idea when this might get published to NPM?

**Comment by fabiosantoscode** [comment]
@AlexGustafsson in 30 minutes or 1 hour. I'm fixing another issue.

**Comment by fabiosantoscode** [comment]
Actually, it's fixed. I'ts going out right now.

**Comment by AlexGustafsson** [comment]
Great!
