### ISSUE TITLE
How to keep unreferenced functions? Why are unreferenced functions being removed although "unused" flag in options is set to false?

### ISSUE THREAD

**Issue by yilmazhasan** [terser/terser#554]
**Bug report**
Although I have set unused flag to false in terserOptions, I don't see unreferenced functions in minified file. As far as I understand setting that to false should be enough to keep unreferenced functions. 

I have also tried by setting toplevel and top_retain

Is there any point that I am misssing?

In docs it is mentioned as:
> unused (default: true) -- drop unreferenced functions and variables (simple direct variable assignments do not count as references unless set to "keep_assign")

> toplevel (default: `false`) -- drop unreferenced functions (`"funcs"`) and/or variables (`"vars"`) in the top level scope (`false` by default, `true` to drop both unreferenced functions and variables)

>  top_retain (default: `null`) -- prevent specific toplevel functions and variables from `unused` removal (can be array, comma-separated, RegExp or function. Implies `toplevel`)

**Version**
`-- terser@4.6.3
`-- webpack@4.41.5

**Comment by fabiosantoscode** [comment]
Hey there!

A bunch of other options can remove functions. `reduce_vars` also does that. `inline` I'm not sure. Check that disabling one or two of these options fixes your problem, and keep this open so I remember to update the documentation :)

**Comment by fabiosantoscode** [comment]
If not, please provide a concise example and the exact options you've used so I can check it out, it might be a bug.

**Comment by yilmazhasan** [comment]
Santos, I have tried by setting combinations of reduce_vars and inline to false but still didn't see the unreferenced functions. 

**I have solved my issue with a trivial way, by moving them to another file.**

In my file, there is

```
$(function () {
})

// Function that needs to be in min.js
function unreferenced() {}

```
_Here is my options:_

```
        terserOptions: {
          keep_classnames: undefined,
          keep_fnames: true,
          reduce_vars: false,
          // inline: false,
          unused: false,
          // dead_code: false,
        }
```

**Comment by fabiosantoscode** [comment]
Terser options are split into multiple parts. I think what you're trying to do would be accomplished with something like

```
{
  toplevel: false,
  compress: {
    unused: false,
    reduce_vars: false
  }
}
```

**Comment by fabiosantoscode** [comment]
By default `toplevel` is false so you don't need to set that one.

**Comment by yilmazhasan** [comment]
It worked like that! Thank you, I haven't seen such to write in compress obj.

**Comment by fabiosantoscode** [comment]
Maybe the docs need to be more clear here. I'm feeling sick but will look later
