### ISSUE TITLE
Description of mangling example incorrect in documentation

### ISSUE THREAD

**Issue by Shotster** [terser/terser#559]
The documentation [here](https://terser.org/docs/cli-usage#cli-mangling-property-names-mangle-props) incorrectly states, "This will mangle all properties that start with an underscore." when in fact the provided example will mangle all properties that **END** with an underscore.

**Comment by fabiosantoscode** [comment]
Correct. This needs updating.

**Comment by fabiosantoscode** [comment]
Fixed in the meantime
