### ISSUE TITLE
Doesn't preserve // @license comments

### ISSUE THREAD

**Issue by Filip98** [terser/terser#560]
Terser preserves
`/* @license magnet:?xt=urn:btih:0ef1b8170b3b615170ff270def6427c317705f85&dn=lgpl-3.0.txt LGPL-3.0 */`
but not
`// @license magnet:?xt=urn:btih:0ef1b8170b3b615170ff270def6427c317705f85&dn=lgpl-3.0.txt `LGPL-3.0

e.g

npx terser msg.js --comments some
```
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
...
```
npx terser msg.js --comments all
```
// @license magnet:?xt=urn:btih:0ef1b8170b3b615170ff270def6427c317705f85&dn=lgpl-3.0.txt LGPL-3.0
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
...
```

**Comment by fabiosantoscode** [comment]
Nice catch! These `@xxx` comments are mostly for jsdoc, but `@license` and others might not always be.

**Comment by fabiosantoscode** [comment]
Fix will be released this week.

PS: Nobody's seeding that magnet link right now. I'll keep transmission on this week so if you seed it we can keep it alive :)

**Comment by Filip98** [comment]
Thanks for the patch.
I launched up my torrent client and got it, now I'm seeding but.. does anyone really need to download this? it's just an identifier for LibreJS, GNU's problem if it needs to download it too since it's their link.
I file bug reports to them tho
