### ISSUE TITLE
[feature] alias this if referenced numerous times in method

### ISSUE THREAD

**Issue by benmccann** [terser/terser#562]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.3.9 (from package-lock.json)

**Complete CLI command or `minify()` options used**

We're using `rollup-plugin-terser` and not passing any special arguments:
```
	terser({
		output: {
			preamble: banner
		}
	})
```

**`terser` input**

We have the following code:
```
	constructor(chart, datasetIndex) {
		this.chart = chart;
		this._ctx = chart.ctx;
		this.index = datasetIndex;
		this._cachedAnimations = {};
		this._cachedDataOpts = {};
		this._cachedMeta = this.getMeta();
		this._type = this._cachedMeta.type;
		this._config = undefined;
		this._parsing = false;
		this._data = undefined;
		this._dataCopy = undefined;
		this._objectData = undefined;
		this._labels = undefined;
		this._scaleStacked = {};

		this.initialize();
	}
```

**`terser` output or error**

The minified output is:
```
function t(e,i){n(this,t),this.chart=e,this._ctx=e.ctx,this.index=i,this._cachedAnimations={},this._cachedDataOpts={},this._cachedMeta=this.getMeta(),this._type=this._cachedMeta.type,this._config=void 0,this._parsing=!1,this._data=void 0,this._dataCopy=void 0,this._objectData=void 0,this._labels=void 0,this._scaleStacked={},this.initialize()}
```

**Expected result**

It would be additionally optimized is `this` showed up at least 3-4 times to alias it with a variable:

```
	constructor(chart, datasetIndex) {
		var m = this;
		m.chart = chart;
		m._ctx = chart.ctx;
		m.index = datasetIndex;
		m._cachedAnimations = {};
		m._cachedDataOpts = {};
		m._cachedMeta = this.getMeta();
		m._type = this._cachedMeta.type;
		m._config = undefined;
		m._parsing = false;
		m._data = undefined;
		m._dataCopy = undefined;
		m._objectData = undefined;
		m._labels = undefined;
		m._scaleStacked = {};

		m.initialize();
	}
```

**Comment by fabiosantoscode** [comment]
I need to look into the performance benefits/drawbacks from aliasing `this`. It might not make too much sense especially given gzip, which eats up this kind of repetition for breakfast!

**Comment by jridgewell** [comment]
While this decreases the byte size in the example, it actually increases the gzip or brotli compressed size. That's because both are able to handle repeated identifiers like this _very_ easily (and in fact, brotli has a [special dictionary entry](https://github.com/google/brotli/blob/master/c/common/dictionary.bin) for `this.` so it's _super_ tiny).

Additionally, this will increase the bytecode (the thing that's actually interpreted by V8 or SpiderMonkey).
