### ISSUE TITLE
Unsafe mode: `new RegExp("...")` doesn't escape forward slashes in emitted regexp literal

### ISSUE THREAD

**Issue by RoyTinker** [terser/terser#563]
#### Bug report

This is really confusing because I _can't_ repro this on the online REPL, but I can repro on many `terser` versions, including 4.6.3, from both the API and the command line.

Command line:
```
echo 'var x = new RegExp("^https://");' | terser -c unsafe=true
```

Output (note that syntactically, this is actually a different regexp followed by a comment):
```
var x=/^https:///;
```

Expected output would escape the forward slashes:
```
var x=/^https:\/\//;
```

**Comment by fabiosantoscode** [comment]
This is terrible! I'll have a look at this one when I have the time.

**Comment by fabiosantoscode** [comment]
I have a fix, will be released this week.

**Comment by RoyTinker** [comment]
Thanks @fabiosantoscode!
