### ISSUE TITLE
keep function declarations?

### ISSUE THREAD

**Issue by leeoniya** [terser/terser#565]
hey guys,

sorry if i missed this in the docs, but `inline: 0` does not appear to do what i'm looking for.

given this input:

```js
(function() {
  function bar(a) {
    return a * 2;
  }
  
  function foo(a, b) {
    return bar(a) + b;
  }

  for (var i = 1; i < 10; i++)
    foo(37,i);
})();
```

i get this output:

```js
!function() {
    function n(n, r) {
        return function(n) {
            return 2 * n;
        }(n) + r;
    }
    for (var r = 1; r < 10; r++) n(37, r);
}();
```

the problem is that the original version does not create a closed-over `bar` function on each call of `foo()`, while the compressed version does. it looks like this happens because `bar` is only called in a single place so it gets "inlined". an issue with doing this transformation is performance. besides the issue shown above, if this inlining happens to several nested layers (this is happening in my codebase), it can result it one giagantic complex function which the JITs might bail on.

one workaround is to insert `bar;` ahead of the loop, but it's umm...not great.

is it possible to opt out of this behavior? should `inline: 0` imply this?

thanks!

**Comment by fabiosantoscode** [comment]
You also need to disable reduce_vars.

**Comment by leeoniya** [comment]
makes sense. thanks!

maybe consider mentioning this for `inline: 0` in the docs.
