### ISSUE TITLE
Nullish coalescing / optional chaining support

### ISSUE THREAD

**Issue by bre7** [terser/terser#567]
**Bug report**
Error messages when using nullish coalescing / optional chaining ops.

**Version (complete output of `terser -V` or specific git commit)**:
4.6.3

**Complete CLI command or `minify()` options used**
-

**`terser` input**

nullish coalescing 
```js
var Terser = require("terser")

var code = {
    "file1.js": "function foo(a) { return a ?? 1; }",
    "file2.js": "console.log(foo(222));"
};
var result = Terser.minify(code);
console.log(result.code);
console.log(result.error);
```

optional chaining
```js
var Terser = require("terser")

var code = {
    "file1.js": "function foo(a) { return a?.val; }",
    "file2.js": "console.log(foo({val: 222}));"
};
var result = Terser.minify(code);
console.log(result.code);
console.log(result.error);
```

**`terser` output or error**

nullish coalescing error:
> Unexpected token: operator (?)

optional chaining error:
> Unexpected token: punc (.)

**Expected result**
Minified code (without errors)

**Comment by fabiosantoscode** [comment]
Thanks for pointing this out! Those two are simply not supported at the moment. But since they are stage 4, it's time to implement.

**Comment by tchetwin** [comment]
Nullish coalescing support was added in https://github.com/terser/terser/commit/575ba807c4e5dcad9e01ea8e602bc4c2b42c9dca on 5th April 2020, available as-of [v4.6.11](https://github.com/terser/terser/releases/tag/v4.6.11)

Regarding optional chaing, @fabiosantoscode [mentioned ](https://github.com/terser/terser/issues/643#issuecomment-615927662) on 18th April 2020:

> Optional chaining is way more complex to implement, and its ESTree spec is not finalised yet.

**Comment by tchetwin** [comment]
Discussions are ongoing in ESTree regarding the optional chaining spec: https://github.com/estree/estree/pull/204

**Comment by fabiosantoscode** [comment]
Yes @tchetwin that's my latest excuse :) it's going to be super hard either way!

**Comment by wongjiahau** [comment]
Are there any workaround for this at the moment?

**Comment by dnalborczyk** [comment]
@fabiosantoscode `acorn` with `optional chaining` support has been released:

https://github.com/acornjs/acorn/pull/891
https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#730-2020-06-11

**Comment by tchetwin** [comment]
Perhaps more significantly, the PR to the ESTree spec to add Optional Chaining was merged: https://github.com/estree/estree/pull/204

**Comment by fabiosantoscode** [comment]
Excellent!

That means I have some idea of the shape of the AST for this.

There is currently no workaround except for avoiding the feature, sadly.

**Comment by artalar** [comment]
Any news?

**Comment by fabiosantoscode** [comment]
Hey there @artalar!

There is progress on this feature on my machine :) I would've finished it sooner but I went on holiday pledging not to touch my shell :) It will only be released in the Terser 5 major.

**Comment by thiagozanetti** [comment]
@fabiosantoscode I don't get this. Terser 5 was released two days ago but it doesn't have any mention to nullish coalescing / optional chaining support. Was it postponed?

**Comment by Druux** [comment]
@fabiosantoscode should this feature already be part of v5.0.0?

**Comment by Xeevis** [comment]
Yeah that statement is a bit confusing, I assume it will be released sometime in **5.x.x** not the 5.0.0 itself?

**Comment by Atulin** [comment]
Guess we're waiting for 6.0.0 now..?

**Comment by fabiosantoscode** [comment]
Hello. 

I said "in the terser 5 major" to mean that it wouldn't be released before 5.0.0

Optional chaining is in the works. It's pretty complicated because it involves conditions in the middle of a chain (and a bunch of considerations across the code), and I'm considering whether to change the AST for it completely and start over.

**Comment by frederikhors** [comment]
Thanks @fabiosantoscode.

Please all do not ask for ETA!

**Comment by thiagozanetti** [comment]
Not asking at all. @fabiosantoscode statement was just a bit vague and made everyone confused I suppose. Nice to hear that good stuff is coming. Let me know if I can lend you a hand (or at least try). 😃

**Comment by thiagozanetti** [comment]
Thanks, man!
