### ISSUE TITLE
option output.inline_script should escape regexp and comment

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#568]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.6.3

**Complete CLI command or `minify()` options used** repl

**`terser` input**

```json
{
  "compress": {},
  "mangle": {},
  "output": {
    "inline_script": true,
    "comments": "all"
  },
  "parse": {},
  "rename": {}
}
```

```js
/*!
 * </script> in (LICENSE) comment
 */
var inRegExp = /[</script>]/;// </script>
```

**`terser` output or error**

```js
/*!
 * </script> in (LICENSE) comment
 */
var inRegExp=/[</script>]/;// </script>
```

**Expected result**

```js
var inRegExp=/[<\/script>]/;
```

And I'm not sure how to deal with `</script>` in comments would be best.

**Comment by fabiosantoscode** [comment]
Thanks for reporting this! Fix coming in :)
