### ISSUE TITLE
Tenser exits with 'Error: Call retries were exceeded'

### ISSUE THREAD

**Issue by ttyerl** [terser/terser#571]
**Bug report **

**Version (complete output of `terser -V` or specific git commit)**
terser@4.6.3

**Error displayed**
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100ba1aee node::Abort() (.cold.1) [/usr/local/Cellar/node/13.7.0/bin/node]
 2: 0x100084b65 node::FatalError(char const*, char const*) [/usr/local/Cellar/node/13.7.0/bin/node]
 3: 0x100084c8d node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/13.7.0/bin/node]
 4: 0x10017fcf5 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/13.7.0/bin/node]
 5: 0x10017fc9f v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/13.7.0/bin/node]
 6: 0x100299e57 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/13.7.0/bin/node]
 7: 0x10029b1f4 v8::internal::Heap::MarkCompactPrologue() [/usr/local/Cellar/node/13.7.0/bin/node]
 8: 0x100298dac v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node/13.7.0/bin/node]
 9: 0x100297853 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/13.7.0/bin/node]
10: 0x100296cd2 v8::internal::Heap::HandleGCRequest() [/usr/local/Cellar/node/13.7.0/bin/node]
11: 0x10026dc4d v8::internal::StackGuard::HandleInterrupts() [/usr/local/Cellar/node/13.7.0/bin/node]
12: 0x1004e162b v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/local/Cellar/node/13.7.0/bin/node]
13: 0x1007505b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/Cellar/node/13.7.0/bin/node]
14: 0x3722b62241a4
Failed to compile.

Failed to minify the bundle. Error: static/js/main.eff291cf.chunk.js from Terser
Error: Call retries were exceeded
    at /Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/react-scripts/scripts/build.js:196:23
    at finalCallback (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/aston/Downloads/aston_prjk/gitlab/aston_prjk-frontend/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/aston/Downloads/aston_prjk
[report.20200218.142136.9549.0.001.txt](https://github.com/terser/terser/files/4219857/report.20200218.142136.9549.0.001.txt)

/gitlab/aston_prjk-frontend/node_modules/webpack/lib/Compilation.js:1414:32

**Comment**
The indication is a memory allocation issue. 

**System**
MacOSX Catalina 10.15.3
node v13.7.0

Happy to try various options to get this going.

**Comment by fabiosantoscode** [comment]
Hey there!

This is a known issue that's in the backburner since it's so hard to fix, so I hope you don't mind if I close.

You can get around this by:

1. Try to make your bundle smaller, by splitting it into chunks. Refer to the webpack documentation on how to do this since I'm not sure how that's done these days.
2. Making sure webpack, and terser-webpack-plugin are in the latest version. There are mitigations to this which have come in the latest versions.
3. If 1. doesn't work, increase the memory capacity of your node process using `--max-old-space-size` option. Example: `node --max-old-space-size 4096 ./node_modules/.bin/webpack ...`

**Comment by macropin** [comment]
@fabiosantoscode Is this issue non-deterministic (ie race), or is it due to resource (memory) constraints?

**Comment by macropin** [comment]
FWIW: Allocating more memory seems to be a workaround.

**Comment by jiananshi** [comment]
technically, its `node --max-old-space-size=4096 ./node_modules/.bin/webpack ...`

> Hey there!
> 
> This is a known issue that's in the backburner since it's so hard to fix, so I hope you don't mind if I close.
> 
> You can get around this by:
> 
> 1. Trying to make your bundle smaller, by splitting it into chunks. Refer to the webpack documentation on how to do this since I'm not sure how that's done these days.
> 2. Making sure webpack, and terser-webpack-plugin are in the latest version. There are mitigations to this which have come in the latest versions.
> 3. If 2. doesn't work, increase the memory capacity of your node process using `--max-old-space-size` option. Example: `node --max-old-space-size 4096 ./node_modules/.bin/webpack ...`

**Comment by mirik999** [comment]
In my case I just updated react , react-dom and react-scripts to the latest versions. 

*But I want to notice that, this problem was only on Linux (Ubuntu) VPS server. On pc and mac without upgrading any package build works.

**Comment by fabiosantoscode** [comment]
@mirik999 possibly the VPC doesn't have enough memory.

For everyone else, I've been making some gradual improvements to memory usage. For example 5.3 spends a bit less. But in general, large files will always use a lot of RAM.

**Comment by briannicholls** [comment]
> Hey there!
> 
> This is a known issue that's in the backburner since it's so hard to fix, so I hope you don't mind if I close.
> 
> You can get around this by:
> 
> 1. Trying to make your bundle smaller, by splitting it into chunks. Refer to the webpack documentation on how to do this since I'm not sure how that's done these days.
> 2. Making sure webpack, and terser-webpack-plugin are in the latest version. There are mitigations to this which have come in the latest versions.
> 3. If 2. doesn't work, increase the memory capacity of your node process using `--max-old-space-size` option. Example: `node --max-old-space-size 4096 ./node_modules/.bin/webpack ...`

This worked for me, thank you! Specifically, I used the React docs for code splitting here:
https://reactjs.org/docs/code-splitting.html
