### ISSUE TITLE
mangle eval "with statement"

### ISSUE THREAD

**Issue by zakariamouhid** [terser/terser#573]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 4.4.3 also tested on [REPL](https://try.terser.org/)

**Complete CLI command or `minify()` options used**
```javascript
{
  mangle: { eval: true },
  output: { beautify: true },
}
```

**`terser` input**
```javascript
(function () {
  let obj = {
    hello: "prop hello",
    world: "prop world",
  };
  let func = function (world) {
    with (obj) {
      return [hello, world];
    }
  };
  console.log(func("arg world"));
}());
```

**`terser` output or error**
```javascript
!function() {
  let o = {
    hello: "prop hello",
    world: "prop world"
  }, l = function(l) {
    with (o) return [ hello, l ];
  };
  console.log(l("arg world"));
}();
```
**Expected result**
```javascript
!function() {
  let o = {
    hello: "prop hello",
    world: "prop world"
  }, l = function(l) {
    with (o) return [ hello, world ];
  };
  console.log(l("arg world"));
}();
```
**Details**
I think it should be an option to tell the compiler how to deal with "`with` statement"
like `isolateWith: true` to know that code inside `with` should not mangle names
while other code should mangle names

I found this problem when I compress code that contains "VueJS render function" that using `with`

**Comment by fabiosantoscode** [comment]
`with` is not something I'm happy to support or fix bugs for.

Do you have a compelling reason to use `with`? It doesn't work in strict mode, and it's as deprecated as a JavaScript feature can be.

**Comment by zakariamouhid** [comment]
thank you, I found as solution to my problem using `vue-template-es2015-compiler`
that compiles `with (this) prop` to `this.prop`

```javascript
const { compile } = require('vue-template-compiler');
const withCompiler = require('vue-template-es2015-compiler');
const Terser = require('terser');

let template = `
<div>
<h1>{{ title }}</h1>
<img :src="src" :alt="alt">
</div>`;
let code = compile(template).render;
code = `module.exports.render=function(){${code}}`;

code = withCompiler(code);
console.log(code);

code = Terser.minify(code).code;
console.log(code);
```
test on [runkit](https://runkit.com/zakariamouhid/vue-template-es2015-compiler)

**Comment by fabiosantoscode** [comment]
Cool!
