### ISSUE TITLE
Remove keys from primitive Symbol declarations

### ISSUE THREAD

**Issue by Kruithne** [terser/terser#580]
**Feature Request**
Symbols are really useful for defining unique identifiers in a code base. When it comes to compressing the code, it would be advantageous if we could have an option in Terser to remove the key string passed in to the constructor, since in most cases this is just used for debugging, even if it's disabled by default.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**`terser` input**
```
const SYMBOL_DOG = Symbol('kDog');
const SYMBOL_CAT = Symbol('kCat');

console.log(SYMBOL_DOG, SYMBOL_CAT);
```
**`terser` output**
```
const o=Symbol("kDog"),l=Symbol("kCat");console.log(o,l)
```
**Desired result**
```
const o=Symbol(),l=Symbol();console.log(o,l);
```

**Comment by fabiosantoscode** [comment]
Sure!

`unsafe_symbol` would be a good name for this new option, however I believe it should be disabled by default.

**Comment by Kruithne** [comment]
I agree on the disabled-by-default choice, as people's use-case for Symbols may differ and that might not be expected behavior for some of those use-cases.

**Comment by fabiosantoscode** [comment]
Not only does this make the code a bit harder to debug, but it changes runtime characteristics as well since you can inspect the symbol's name at runtime through toString. This is why the unsafe_ prefix is necessary.
