### ISSUE TITLE
Problem with setting --comments to false

### ISSUE THREAD

**Issue by cbettinger** [terser/terser#585]
**Bug report**

**v4.6.6**

**CLI command:**
`terser input.js --comments=false`

**input.js**
```
/*!
 * Test
 *
 * @license ISC
 */
console.log("test");
```

**Output**
```
/*!
 * Test
 *
 * @license ISC
 */
console.log("test");
```

**Expected output**
```
console.log("test");
```

**Description**
I am not quite sure if I am doing something wrong, since this misbehaviour is so obvious.

The problem is that the type of the value options.output.comments is string, not boolean, and therefore the non-empty string 'false' gets evaluated to true.

This is the object that gets passed into Terser.minify:

`{ compress: true, mangle: true, output: { comments: 'false' } }`

If I override that value within bin/terser (`options.output.comments = false;`), the output is as expected.

**Comment by fabiosantoscode** [comment]
Again thanks for the PR :)
