### ISSUE TITLE
Why convert await value to await(value), is there any edge case need that?

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#586]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.6.3

**Complete CLI command or `minify()` options used** `minify()` with default options

**`terser` input**

```js
async function f(){await await{}}
```

**`terser` output or error**

```js
async function f(){await(await({}))}
```

**Expected result**

```js
async function f(){await await{}}
```

**Comment by fabiosantoscode** [comment]
Interesting. No, there's no edge case here. But is anyone typing (or a compiler generating) `await await x`?

**Comment by LongTengDao** [comment]
I'm trying to await too event loop to control code running order...

**Comment by fabiosantoscode** [comment]
Ok. I'll add the label. The PARENS method in lib/output.js needs to be changed to accomodate.

**Comment by LongTengDao** [comment]
not important, just inquisitive. if you are busy, this is realy small thing.

**Comment by fabiosantoscode** [comment]
You can give it a go if you want :) it's certainly not my top priority

**Comment by LongTengDao** [comment]
I'm not familiar with terser source... So be it ;)

**Comment by L2jLiga** [comment]
@LongTengDao please keep issue opened. One fine day it can be fixed/improved
