### ISSUE TITLE
MouseEvent.movementX and MouseEvent.movementY DOM-props are getting mangled by --mangle-props

### ISSUE THREAD

**Issue by 0dinD** [terser/terser#610]
**Bug report**
[MouseEvent.movementX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX) and [MouseEvent.movementY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementY) DOM properties are mangled when using `--mangle-props`. (Because "movementX" and "movementY" are missing from `tools/domprops.js`)

**Version**
terser 4.6.4

**Complete CLI command**
`terser issue.js --mangle-props`

**`terser` input**
```javascript
document.addEventListener("mousemove", (e) => {
    console.log(e.movementX);
    console.log(e.movementY);
});
```

**`terser` output**
```javascript
document.addEventListener("mousemove",o=>{console.log(o.o);console.log(o.m)});
```

**Expected result**
```javascript
document.addEventListener("mousemove",o=>{console.log(o.movementX);console.log(o.movementY)});
```

**Comment by fabiosantoscode** [comment]
Thanks for your report. Looks like a missing property name in tools/domprops.js

**Comment by jridgewell** [comment]
Fixed by https://github.com/terser/terser/commit/a7c1673d73ac8ea941e9f82bc9d0573a6558d197.
