### ISSUE TITLE
Terser produce invalid code when inlining default parameters

### ISSUE THREAD

**Issue by scinos** [terser/terser#612]
**Bug report**

When inlining the value of a default parameter, if that value comes from a function terser sometimes produces invalid code.

**Version (complete output of `terser -V` or specific git commit)**

```
$ terser -V
terser 4.6.7

$ node -v
v12.15.0
```

**Complete CLI command or `minify()` options used**

```
$ terser -c -- example.js | node
```

**`terser` input**

```
function main () {
    "use strict";

    const foo = () => 42;

    const getData = (val) => {
        return {val}
    }

    const print = (data = getData(foo())) => {
        console.log(data);
    }

    print();
}
main();
```

**`terser` output or error**
```
$ terser -c -- example.js | node
[stdin]:1
function main(){"use strict";((data=(val=42,{val:val}))=>{var val;console.log(data)})()}main();
                                        ^

ReferenceError: val is not defined
    at [stdin]:1:41
    at main ([stdin]:1:86)
    at [stdin]:1:89
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([stdin]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:192:5)
```

**Notes**
Looks like the bug was introduced in `terser 4.5.0`. In `terser 4.4.3`, the output is:

```
function main(){"use strict";((data=(val=>({val:val}))(42))=>{console.log(data)})()}main();
```

Git bisect points to https://github.com/terser/terser/commit/2889744e409fa919abae195d00da926f51e980fb as the culprit

**Comment by scinos** [comment]
I can't produce an exact reproduction case, but this code is problematic even without the `"use strict"` part: it will pollute the global scope with the auxiliary variable (`val` in the example above), potentially overwriting any existing variable.

We found this when terser produced `n` as the mangled auxiliary variable, and it overwrote the global variable `n` that was pointing to `webpack_require` function, breaking everything.

**Comment by fabiosantoscode** [comment]
Nice issue! Your repro case is minimal already, don't worry about that.

I'm working atm, so I'll get to this one later.

Regarding polluting global scope, `let` and `const` don't end up in the global scope, so that shouldn't be a problem unless it also happens with `var`.

**Comment by jsnajdr** [comment]
Here's another version of a repro case which also illustrates how the bug can happen in practice. The `foo` function is similar to what webpack creates for modules.

```js
function foo(exports, require) {
    function getFunction() {
        return mod => {
            console.log("bad: " + mod);
        };
    }

    function toObject(param) {
        return { param };
    }

    function init(value = toObject(getFunction())) {
        return value;
    }

    require("a");
    init();
    require("b");
    return init;
}

function goodRequire(mod) {
    console.log("good: " + mod);
}

foo(null, goodRequire);
```

After compressing and mangling with `terser -c -m`, the transformed program is:
```js
function foo(o, n) {
    function e(
        o = ((n = o => {
            console.log("bad: " + o);
        }),
        { param: n })
    ) {
        var n;
        return o;
    }
    return n("a"), e(), n("b"), e;
}
function goodRequire(o) {
    console.log("good: " + o);
}
foo(null, goodRequire);
```

When ran in Node.js, it outputs:
```
good: a
bad: b
```
After calling `init`, the `require` variable is overwritten to a "bad" function.

Notice how both `require` and the inlining helper variable are both mangled to the same identifier `n`.

The mistake is that the following code:
```js
function x(a=(b=1,b)) {
  var b;
  return a;
}
```
doesn't do what the author expected. The `b` variable declaration is not hoisted _before_ the code that does the default assignment. The `b` identifier in the default assignment is outside the block scope.

Babel transpiles the above function to:
```js
function x() {
  var a = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : (b = 1, b);
  return function () {
    var b;
    return a;
  }();
}
```
It creates an IIFE to separate the two `b` usages from each other.

**Comment by fabiosantoscode** [comment]
I've been banging my head about this one :)

Related bugs:

 * https://github.com/terser/terser/issues/91
 * https://github.com/mishoo/UglifyJS2/issues/2662 (especially tricky and not even babel handles this)

**Comment by fabiosantoscode** [comment]
Ended up working around the fundamental issue. Will release fix this week.
