### ISSUE TITLE
Terser produce invalid code when inlining with const

### ISSUE THREAD

**Issue by filipesilva** [terser/terser#615]
**Bug report or Feature request?**
This is a bug.

**Version (complete output of `terser -V` or specific git commit)**
4.6.7

**Complete CLI command or `minify()` options used**
```
terser sample.js --toplevel --compress --beautify --output output.js
```

**`terser` input**

```
let something = null;
function getSomething() {
  return something;
}
function setSomething() {
  something = { value: 42 };
}
function main() {
  if (typeof somethingElse == "undefined") {
    const something = getSomething();
    console.log(something);
  }
}
main();
```

**`terser` output or error**
```
let something = null;

!function() {
    if ("undefined" == typeof somethingElse) {
        const something = something;
        console.log(something);
    }
}();
```

Running this code shows the following error:
```
kamik@RED-X1C6 MINGW64 /d/terser-const-inline (master)
$ node output.js 
D:\terser-const-inline\output.js:5
        const something = something;
                          ^

ReferenceError: Cannot access 'something' before initialization
    at D:\terser-const-inline\output.js:5:27
    at Object.<anonymous> (D:\terser-const-inline\output.js:8:2)
←[90m    at Module._compile (internal/modules/cjs/loader.js:774:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:641:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m
```

If instead of `--compress` I use `--compress inline=0`, disabling inlining, the program executes correctly.

**Expected result**
No `ReferenceError`s.

**Other information**

I think this is similar, if not the same, as https://github.com/terser/terser/issues/612.

**Comment by filipesilva** [comment]
The final repro is shown above, but I also want to bring up a couple of variations that came up while doing this repro that exhibited weird behaviour that I didn't expect.

If I remove the `if (typeof somethingElse == "undefined") {`:
```
let something = null;
function getSomething() {
  return something;
}
function setSomething() {
  something = { value: 42 };
}
function main() {
  const something = getSomething();
  console.log(something);
}
main();
```

Then inlining never happens at all:
```
let something = null;

function getSomething() {
    return something;
}

!function() {
    const something = getSomething();
    console.log(something);
}();
```
I find this unexpected because I didn't think having that `if` statement would influence inlining at all. If the inlining happened with the `if`, then it should happen without it (and vice versa).

Another odd case happens if I remove `function setSomething() {`
```
let something = null;
function getSomething() {
  return something;
}
function main() {
  if (typeof somethingElse == "undefined") {
    const something = getSomething();
    console.log(something);
  }
}
main();
```

Then the toplevel reference is dropped and the value inlined:
```
!function() {
    if ("undefined" == typeof somethingElse) {
        const something = null;
        console.log(something);
    }
}();
```

This was unexpected because `setSomething` was dropped anyway, so in hindsight I expected the value to always be inlined anyway.

I think these two cases are interesting because they point to possible bugs that might be preventing output from becoming smaller.

**Comment by fabiosantoscode** [comment]
Great report as usual, thank you very much!

I thought people would find less issues in Terser with this crisis, but looks like I need to be more on top of the project than usual :)

I'll try to find time to deal with this.

**Comment by filipesilva** [comment]
Yeah I was talking about that with a colleague yesterday as well, if people would be using OSS more or less. It seems about the same to me really. I guess less people might be doing their usual work but maybe they're on hobby projects instead. 

Regardless, we've worked around it on Angular's side for now, so we're green ourselves. Thanks for taking the time to look at this!

**Comment by fabiosantoscode** [comment]
Guess I'm glad that people on hobby projects choose to create GH issues rather than work around them and say nothing.

**Comment by fabiosantoscode** [comment]
Inlining should change the names of all incoming variables, no exceptions. There's so much checking for name collisions that at this point I think just changing every name would be better in every way.

**Comment by filipesilva** [comment]
I guess the tradeoff is that the more new names might be needed and it might roll over into another character?

**Comment by fabiosantoscode** [comment]
It's a good tradeoff in my book :)

**Comment by filipesilva** [comment]
Yeah that does sound like a net win.
