### ISSUE TITLE
Invalid class Inlining

### ISSUE THREAD

**Issue by marcusdarmstrong** [terser/terser#617]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

4.6.6, and others.

**Complete CLI command or `minify()` options used**

```
{
  compress: {
    passes: 4,
  },
  mangle: false,
}
```

**`terser` input**

```
function f(){
  var A; 
  A = class A {};
  class B extends A {};
  return [B,A];
}
```

**`terser` output or error**

```
function f(){var A;return[class extends A{},A=class{}]}
```

**Expected result**

```
function f(){var A;A=class{};return[class extends A{},A]}
```

Extending a class is immediately executed, so the terser generated output here triggers:
`TypeError: class heritage A is not an object or null`. While the original input is handled just fine by modern browsers.

**Comment by marcusdarmstrong** [comment]
Note that `collapse_vars: false` mitigates this issue.

**Comment by fabiosantoscode** [comment]
Nice report, thanks!
