### ISSUE TITLE
Terser produce invalid symbol reference when minify chunks produced by rollup

### ISSUE THREAD

**Issue by charles-lai** [terser/terser#619]
**Bug report or Feature request?**

We use terser to minify javascript chunks produced by rullup.js, three files:

./service.js
./module-a/worker.js
./service-chunk.js

After minify, some symbols in service.js references ./service-chunk.js is incorrect:

```javascript
C = e.F([ e.S(), e.a(0, $()), e.b('design:paramtypes', [ Array ]) ], C);
```
Above, "e" is module ./service-chunk.js, "F" is pointed to incorrect variable exported by e, this make program crash. I have changed "F" to "_"(the correct symbol in mangled ./service-chunk.js) manually, and the program run correctly.

We use the same terser options for other node service minify without chunk generated, it's OK!

We don't know whether this is a bug, or an error caused by mis-configuration. Google has no information about this.

**Version (complete output of `terser -V` or specific git commit)**

5.3.0

**Complete CLI command or `minify()` options used**

terser options:

```javascript
    terser({
      ecma: '2017',
      mangle: {
        properties: {
          regex: /^_[^_]*$/,
          // ! IMPORTANT: put all 3rd party system method overrides here, or it will be mangled.
          reserved: ['_subscribe'],
        },
      },
      output: {
        beautify: true,
        indent_level: 1,
        max_line_len: 120,
        quote_style: 1,
        semicolons: false,
      },
    }),  
```

**`terser` input**

before input to terser,  we use rollup-plugin-babel-minify to do some optimizations.

minify configuration:
```javascript
minify({
      booleans: false,
      mangle: false,
      replace: [
        {
          identifierName: '__DEV__',
          replacement: {
            type: 'numericLiteral',
            value: 0,
          },
        },
      ],
      removeConsole: true,
      removeDebugger: true,
      keepFnName: false,
      keepClassName: false,
      comments: false,
      bannerNewLine: true,
      sourceMap: true,
      // plugins:[]
    }),
```

**`terser` output or error**

Output will crash because of miss mangled reference between modules.

**Expected result**

Link symbol reference cross module correctly.

**Comment by fabiosantoscode** [comment]
This occurs because terser is called once per file. Therefore, it has no knowledge of properties present in other files, so it happily turns your `_` property into whatever it feels like.

Check out [this section](https://github.com/terser/terser#cli-mangling-property-names---mangle-props) of the documentation. If you need Terser to know about other runs of Terser (essentially maintain a memory of what it saw in other files) you need to pass it a name cache. I have no idea whether this is possible in rollup at the time, maybe @TrySound knows?

if this is not possible in vanilla rollup, you can rollup your files without minifying them at all, and then pass the whole bundle through Terser (it better be below 1 mb! :) ). This way Terser knows all the properties.

I understand that this solution is not optimal, and I'm working on something in the backburner.

**Comment by TrySound** [comment]
Yes, nameCache is supported.
https://github.com/TrySound/rollup-plugin-terser/pull/62

**Comment by fabiosantoscode** [comment]
@TrySound isn't it a problem that multiple modules are passed to Terser simultaneously, and as such they don't know of each other's props?

Maybe @charles-lai only needs to disable parallelism and it should work fine?

Alternatively, I'm OK with providing a method which retrieves the name cache from a JS string or Estree/Terser AST before it's minified. This adds an extra step, but is still faster than minifying in series.

**Comment by charles-lai** [comment]
Thanks @fabiosantoscode @TrySound a lot! I have changed my configuration to use `nameCache` in rollup configuration file, as following:

```javascript
const nameCache = { vars: {} }
..
  plugins: [
...
terser({
      ecma: '2017',
      mangle: {
...
      },
      output: {
...
      },
      nameCache,
    }),
...
```
The result is same. I have output the cached names, it seems rollup will not call terser in correct order, in my example, it must minify ./service-chunk.js first, but obviously, rollup feed terser service.js first.

Is there some hint to resolve this? Or else must I write a gulp script to minify rollup outputs chunks mannually?

**Comment by fabiosantoscode** [comment]
@charles-lai here's some things you can try:

 - Set the `numWorkers` rollup-plugin-terser option to 0. This should disable parallelism and fix the issue.
 - If not, try using rollup-plugin-terser as an output plugin (meaning, minify the result instead of the chunks) https://github.com/TrySound/rollup-plugin-terser#using-as-output-plugin

Let me know if one of them works! (or both)

**Comment by TrySound** [comment]
1. this will probably not help because numWorkers: 0 still serialise options
2. result is a set of chunks. Output plugins allows to run plugins for specific format when output is an array.

**Comment by fabiosantoscode** [comment]
I see. How do you suggest this is done, if it's possible?

**Comment by charles-lai** [comment]
@fabiosantoscode thanks! None will work. I finally use multiple targets rollups to output separate independent scripts to avoid this issue. 

But it will not work in another very complex problem, we have a library which must target mobile, electron, webview and must share most of the codes between them. The share itself must be transparent to library user, I had to split the library again.

It's frustrating!

**Comment by charles-lai** [comment]
I finally solved this by using multiple rollup with a independent terser "nameCache". Configuration like:

```javascript
const nameCache = {}
const pluginsWithJailed = pkgName =>
  [
    terser({
     ...
      nameCache,
    }),
    crossReference({ crossReferences, externalPrefixes }),
    resolve({
      extensions: ['.mjs', '.js', '.jsx', '.json'],
      jail: `${path.resolve('.')}/dist/build/${pkgName}`,
      preferBuiltins: true,
    }),
  ]
```

```javascript

// ! following order is critical because of terser names cache
export default [
  {
    ...cfgTemplate,
    // can be an array (for multiple inputs)
    input: { platform: 'dist/build/platform/index.js' },
    external: externalPackages,
    plugins: pluginsWithJailed('platform'),
  },
  {
    ...cfgTemplate,
    // can be an array (for multiple inputs)
    input: { provider: 'dist/build/provider/index.js' },
    external: externalPackages,
    plugins: pluginsWithJailed('provider'),
  },
  {
    ...cfgTemplate,
    // can be an array (for multiple inputs)
    input: { widget: 'dist/build/widget/index.js' },
    external: externalPackages,
    plugins: pluginsWithJailed('widget'),
  },
  {
    ...cfgTemplate,
    // can be an array (for multiple inputs)
    input: { utility: 'dist/build/utility/index.js' },
    external: externalPackages,
    plugins: pluginsWithJailed('utility'),
  },
  {
    ...cfgTemplate,
    // can be an array (for multiple inputs)
    input: { ehost: 'dist/build/ehost/index.js' },
    external: externalPackages,
    plugins: pluginsWithJailed('ehost'),
  },
  {
    ...cfgTemplate,
    // can be an array (for multiple inputs)
    input: { eapp: 'dist/build/eapp/index.js' },
    external: externalPackages,
    plugins: pluginsWithJailed('eapp'),
  },
]

```

Thanks a lot!

**Comment by jridgewell** [comment]
Closing as resolved.
