### ISSUE TITLE
Convert `Object` wrapping to a comma operator

### ISSUE THREAD

**Issue by joseprio** [terser/terser#620]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V` or specific git commit)**
All

**`terser` input**
```
Object(a.e)();
```

**`terser` output or error**
```
Object(a.e)();
```

**Expected result**
```
(0,a.e)();
```

Our output includes thousands of instances of `Object` wrapping that webpack inserts in order to ensure that `this` is `undefined` when calling module members.
According to https://github.com/webpack/webpack/issues/5600 , their first choice was wrapping those calls with `(0,<module>.<member>)()`, but that was a problem because of ASI, as their parser isn't able to handle those cases properly.

This conversion isn't only smaller than the `Object` wrapping, but also up to 50% faster across the board.

**Comment by fabiosantoscode** [comment]
:/

Terser doesn't really know if the global `Object` was re-assigned, much less if `a.e` is a function (try calling `Object(3)`)

And Terser can't deal with an identity function either:

```
const id = x => x                                 
                                                  
const the_module = {}                             
                                                  
the_module.func = function () { return this }     
the_module.func2 = function () { return this }    
the_module.func3 = function () { return this }    
                                                  
console.log(id(the_module.func)())                
console.log(id(the_module.func2)())               
console.log(id(the_module.func3)())               
```

I'm creating an issue. When that issue is solved, we might be able to tell webpack to use a simple identity function. Terser removes these and after the issue is fixed it will replace them with `(0, x.fn)(...)`

**Comment by joseprio** [comment]
My idea here is to detect a `CallStatement` whose callee is a `CallStatement` to `Object`, but yeah, there's no guarantee that is has been replaced, but at the same time I think that's a bad practice and this feature could be behind a flag that's disabled by default; if this seems reasonable, I could work on a PR.

Your solution definitely seems the ideal one down the line, but there's no guarantee that Webpack would update their code, and Chrome has optimized the `Object(...)()` path.

**Comment by fabiosantoscode** [comment]
It's nice that chrome did that, but other engines might not do it.

I believe we can reach a proper solution with the webpack team. I'm opening an issue there.

**Comment by fabiosantoscode** [comment]
Seems webpack 5 doesn't have this problem, so it won't be necessary to implement anything on the Terser side, since the output is pretty terse already!
