### ISSUE TITLE
Upgrading to 4.6.8 breaks webpack compilation

### ISSUE THREAD

**Issue by rodrigopedra** [terser/terser#624]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

$ ./node_modules/terser/bin/terser -V
terser 4.6.8

**Complete CLI command or `minify()` options used**

Usage from:

`laravel-mix@^5.0.4`

which requires terser from 

`terser-webpack-plugin@^2.2.3`

**`terser` input**

```bash
$ yarn prod
```

Which translates to:

```
cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

**`terser` output or error**

```bash
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                            4:22:04 PM

 error

/vendor.js from Terser
TypeError: Cannot read property 'variables' of undefined
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:209686
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:211321
    at AST_Call.optimize (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:137138)
    at ri.before (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:136915)
    at AST_Call.transform (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:87057
    at ri.before (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:136887)
    at AST_Assign.transform (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:84275
    at l (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:931)

 5 assets

ERROR in /vendor.js from Terser
TypeError: Cannot read property 'variables' of undefined
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:209686
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:211321
    at AST_Call.optimize (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:137138)
    at ri.before (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:136915)
    at AST_Call.transform (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:87057
    at ri.before (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:136887)
    at AST_Assign.transform (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:84111)
    at /home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:84275
    at l (/home/rodrigo/code/node_modules/terser/dist/bundle.min.js:1:931)
```

**Expected result**

Before updating webpack ran without problems

---

**Workaround**

From this issue:

https://github.com/webpack-contrib/terser-webpack-plugin/issues/66#issue-406001469

I added this resolution to my `package.json` file and my script ran without problems:

~~~json
    "resolutions": {
        "terser": "4.6.7"
    }
~~~

**Comment by pleek91** [comment]
Same issue. Wasted an hour of my day on this.

**Comment by BTARPAR** [comment]
Same Issue, waiting for this to be resolved

**Comment by zdods** [comment]
Same issue! :(

**Comment by paulconlin** [comment]
Looking like it was this commit - https://github.com/terser/terser/commit/67aa5c4876742fdbda4a678f06803e5e4916ea0b

@fabiosantoscode any ideas?

**Comment by stephanepericat** [comment]
Also this guy is still a thing... https://github.com/neutrinojs/webpack-chain/issues/204

**Comment by DWboutin** [comment]
Same issue with Gatsby.js `npm run build`

**Comment by JnMik** [comment]
Same !

**Comment by YodaNinja** [comment]
same here too!

**Comment by sagar7993** [comment]
I added this to my package.json file as suggested in the comment above but my react project build command is still NOT working.

```javascript
"resolutions": {
        "terser": "4.6.7"
}
```

Does any one have a way to resolve this?

**Comment by dacevedo12** [comment]
> I added this to my package.json file as suggested in the comment above but my react project build command is still NOT working.
> 
> ```js
> "resolutions": {
>         "terser": "4.6.7"
> }
> ```
> 
> Does any one have a way to resolve this?

This will only work if you use yarn. With npm you have to use shrinkwrap. Take a look at https://gitlab.com/fluidattacks/integrates/-/commit/26e910e1513f866fe848349cd775ff0d28f317c8

**Comment by dacevedo12** [comment]
> I added this to my package.json file as suggested in the comment above but my react project build command is still NOT working.
> 
> ```js
> "resolutions": {
>         "terser": "4.6.7"
> }
> ```
> 
> Does any one have a way to resolve this?

This will only work if you use yarn. With npm you gotta use shrinkwrap

**Comment by BakerAO** [comment]
In docker, i added this and it fixed it
`RUN npm install &&\
    rm -r node_modules/terser &&\
    npm install terser@4.6.7 --save-dev
RUN npm run build
`

**Comment by bilwit** [comment]
@sagar7993  if you're using `npm` and not `yarn` you need:

**packages.json**
`...`
`  "resolutions": {`
`    "terser": "4.6.7"`
`  }`

**In your CI script (use pass `--prefix client` or wherever accordingly)**
` - npm install  #assuming you're in a clean workspace`
`    - npm install npm-force-resolutions --save-dev`
`    - npx npm-force-resolutions`
`    - npm install `
`    - npm audit fix `

**Comment by mikdatdogru** [comment]
workaround:

add to package.json 
```json
"resolutions": {
        "terser": "4.6.7"
    }
```
you should now use `yarn` for build

**Comment by BTARPAR** [comment]
workaround: for npm and yarn 

add to package.json

        "terser": "4.6.7"

**Comment by fabiosantoscode** [comment]
Fix has been published.

**Comment by fabiosantoscode** [comment]
Please confirm.

**Comment by sagar7993** [comment]
Working after the fix

**Comment by rodrigopedra** [comment]
Sorry for the late response, wasn't at my machine in the meanwhile. It is indeed back working, thanks a lot for the quick fix and all hard work.

**Comment by bhkangw** [comment]
How exactly are we supposed to utilize the fix? Still broken for me as of now.

**Comment by bilwit** [comment]
@bhkangw try deleting `node_modules` and `package-lock.json` so that it grabs the latest version. If you're using terser directly then you can bump `"terser": "^4.6.9"` in your `package.json` or otherwise use the resolutions method to bump it.
