### ISSUE TITLE
TypeError: Cannot read property 'variables' of undefined

### ISSUE THREAD

**Issue by dacevedo12** [terser/terser#625]
Hello, sorry for ignoring the template but this one is pretty straight forward. 

terser latest (4.6.8)

https://travis-ci.org/github/terser/terser/jobs/668892224

Why did this deploy to npm if the CI is failing?

**Comment by rodrigopedra** [comment]
Related: #624

**Comment by chaudharidpka** [comment]
Hi Guys, I am getting this error as well and the build is failing because of it:
TypeError: Cannot read property 'variables' of undefined

Does someone know how to fix this?
Thanks!

**Comment by dacevedo12** [comment]
> Hi Guys, I am getting this error as well and the build is failing because of it:
> TypeError: Cannot read property 'variables' of undefined
> 
> Does someone know how to fix this?
> Thanks!

With yarn you can add terser 4.6.7 to resolutions in the package.json.
With npm you must use shrinkwrap to pin it to 4.6.7 while they fix it

**Comment by dustinsoftware** [comment]
Just ran into this too, will revert to `4.6.7`

**Comment by limonte** [comment]
CI is failing: https://travis-ci.org/github/terser/terser/jobs/668892225 with the very same error:

![image](https://user-images.githubusercontent.com/6059356/77965417-a20e1600-72e9-11ea-896b-40488644561f.png)

That is why @fabiosantoscode you might want to consider setting up the automated releasing which is usually happening **after** CI build is successful.

**Comment by fabiosantoscode** [comment]
Sorry. I didn't mean to remove that check but it looks like I did. I'm publishing a fix right now.

Version was released because not all tests are run locally. We need to start releasing from CircleCI after a build is successful.

**Comment by fabiosantoscode** [comment]
@limonte any npm packages, example implementations, or articles you can point me to?

I do want to release from Travis, but I want control over the version bump.

**Comment by limonte** [comment]
> @limonte any npm packages, example implementations, or articles you can point me to?
> 
> I do want to release from Travis, but I want control over the version bump.

The major tool for doing that is https://semantic-release.gitbook.io/semantic-release/

The example could be found here:
 - https://github.com/sweetalert2/sweetalert2/blob/master/release.config.js
 - https://github.com/sweetalert2/sweetalert2/blob/master/.github/workflows/ci.yml#L39-L49

**Comment by limonte** [comment]
The Travis example could be found here: https://github.com/karma-runner/karma-sauce-launcher/blob/master/.travis.yml#L13-L18

**Comment by fabiosantoscode** [comment]
Thanks! I already knew the tool but didn't know it was still used today. I'll look into configuration.

**Comment by shawnxusy** [comment]
@fabiosantoscode thanks a lot for the fix; I do want to mention that this has killed all of our builds this morning, and since we are using terser via TerserPlugin, we can't control the minor versions unless using things like https://github.com/rogeriochaves/npm-force-resolutions
There was a similar story with Terser here: https://lihautan.com/debugging-build-failed-error-from-terser/
Not to blame anyone, just hope we can be a bit more careful with the library changes. (especially such a widely used one)

**Comment by fabiosantoscode** [comment]
You're right @shawnxusy. I usually take what I think is enough care, but in this instance it was just a dumb mistake. I'll take the steps to make sure it doesn't happen again.

**Comment by shawnxusy** [comment]
Appreciate it and really awesome work! @fabiosantoscode

**Comment by jridgewell** [comment]
Fixed by https://github.com/terser/terser/commit/3406d87dfb69147fc722a56fe61fa94a9bdac2f8.
