### ISSUE TITLE
Incorrect `const A` declaration after a `class B extends A` is moved and becomes unnamed during minification

### ISSUE THREAD

**Issue by goto-bus-stop** [terser/terser#627]
**Bug report or Feature request?**
Bug report.

**Version (complete output of `terser -V` or specific git commit)**
```
terser 4.6.9
```

According to `git bisect`, this regressed in 0e40b8d2e96005121801ccb02340e4f990fd66d7.

**Complete CLI command or `minify()` options used**
```js
terser input.js --compress --beautify
```

**`terser` input**
```js
(function () {
    const HtmlContent = require('./html-content.js')
    class BreadcrumbPanel extends HtmlContent {}
    module.exports = BreadcrumbPanel
}())
```

From my tests, it seems to only happen with a combination of factors:
 - The `HtmlContent` variable is used in a class's `extends` node
 - The class that it is used in (`BreadcrumbPanel`) is named
 - The class that it is used in (`BreadcrumbPanel`) _becomes_ anonymous during minification, and/or the class that it is used in is _moved_ during minification (to `module.exports = class {}`)

For example, using the `HtmlContent` value in these patterns do _not_ have this bug:
```js
console.log(HtmlContent)
```
```js
const BreadcrumbPanel = class extends HtmlContent {}
```
```js
module.exports = class BreadcrumbPanel extends HtmlContent {}
```

**`terser` output or error**
The initializer is separated from the `const` declaration by a semicolon, which is invalid:
```js
!function() {
    const HtmlContent;
    require("./html-content.js");
    module.exports = class extends HtmlContent {};
}();
```

**Expected result**
```js
!function() {
    const HtmlContent = require("./html-content.js");
    module.exports = class extends HtmlContent {};
}();
```

**Comment by fabiosantoscode** [comment]
Nasty! I'll have a look right away.

**Comment by 200Puls** [comment]
I think I encountered the same issue. This happens since 4.6.8.

Chrome Console says: Uncaught SyntaxError: Missing initializer in const declaration

`{const e;Wt(t);return class extends e{`

I havent looked up the source as it occurs in a library I use (Polymer)

**Comment by goto-bus-stop** [comment]
That does the trick :tada:  Thanks for the quick fix @fabiosantoscode!

**Comment by fabiosantoscode** [comment]
I'm waiting for the functional tests to ship 4.6.10

**Comment by Haprog** [comment]
Thanks a lot for the quick fix!
