### ISSUE TITLE
[class+symbol regression] ReferenceError: symbols is not defined

### ISSUE THREAD

**Issue by AviVahl** [terser/terser#630]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
4.6.10 (4.6.7 works)

**Complete CLI command or `minify()` options used**
Using terser via `terser-webpack-plugin` with default values (for `--mode production` of webpack).

**`terser` input**
EDIT: see next comment for input file and command.

I **really** tried creating a smaller reproducible example, but couldn't. Any *smaller* example I created didn't exhibit this issue.

Source maps of the runtime evaluation error point to the following piece of code:
https://github.com/wixplosives/engine/blob/1d7476ff1ee697e6798798b110f9226e73eee3b6/packages/core/src/entities/slot.ts#L43

When passed to webpack, it is transpiled by loaders to:
```js
import { CREATE_RUNTIME } from '../symbols';
import { FeatureInput } from './input';
export class Registry {
    constructor() {
        this.items = [];
        this.callbacks = new Set();
    }
    register(item) {
        this.items.push(item);
        for (const callback of this.callbacks) {
            callback(item);
        }
    }
    [Symbol.iterator]() {
        return this.items[Symbol.iterator]();
    }
    subscribe(cb) {
        this.callbacks.add(cb);
    }
    unSubscribe(cb) {
        this.callbacks.delete(cb);
    }
    stream(cb) {
        for (const item of this) {
            cb(item);
        }
        this.subscribe(cb);
        return () => this.unSubscribe(cb);
    }
}
export class Slot extends FeatureInput {
    static withType() {
        return {
            defineEntity(env) {
                return new Slot(env, env);
            }
        };
    }
    [CREATE_RUNTIME]() { <-----------------------BOOOOOOM at evaluation time
        return new Registry();
    }
}
```

A class with a symbol-based method. The symbol is imported from '../symbols`, which might explain where the "symbols" in the error message came from.

I do have exact/consistent steps to reproduce (on an open-source repo):

```sh
git clone git@github.com:wixplosives/engine.git -b terser-bug
cd engine
yarn
cd packages/scripts/test/fixtures/engine-feature
yarn engine build
```
at this point, a `dist` folder will be created (inside `engine-feature` folder), containing a minified `main.web.js`. When evaluating this file in the browser (even by copying-pasting it to the console), you'll see the error: ReferenceError: symbols is not defined

if you `yarn engine build --mode development`, same folder will be built using webpack in development mode.

**`terser` output or error**
No errors/warnings emitted during minification.

**Expected result**
Output should evaluate successfully.

**Comment by AviVahl** [comment]
I now have a MUCH nicer reproduction!
see included bundle.
if you `terser input.js --compress -o output.min.js`
original bundle evaluates fine. output fails with error upon evaluation.

[input.zip](https://github.com/terser/terser/files/4417982/input.zip)

**Comment by fabiosantoscode** [comment]
Hey there!

I will have a look at this later.

You probably have a typo in your version (2.6.10 (2.6.7 works)) is probably 4.x but I get the gist of it!

Could you try to disable some options to see which one might be causing the issue? Usually `reduce_vars`, `inline`, `collapse_vars` or `unused` are the culprit (they're the most complicated ones).

**Comment by AviVahl** [comment]
Hey @fabiosantoscode thanks for the quick response!

I fixed the version typo in the original post.

`terser input.js --compress unused=false -o output.min.js` made the bundle evaluate properly.
I can now see `symbols` defined as `symbols=__webpack_require__(0)`.

Best guess from observations: imported symbols (variable declaration, inside the bundle) used as method names don't get "registered as used", and the variable declaration is removed.

**Comment by fabiosantoscode** [comment]
This happened because I made some changes to classes. I made your class droppable because it was unused, but then the unchanged code that dropped the variable "symbols" didn't know that your dropped class was actually using the variable.

**Comment by fabiosantoscode** [comment]
Will release this week, thank you very much for the report.

**Comment by AviVahl** [comment]
Thank you for fixing it so quickly! ❤️
