### ISSUE TITLE
Numeric Seperators are not supported

### ISSUE THREAD

**Issue by BrianMulhall** [terser/terser#632]
When trying to minify the following code in the test area provided by https://try.terser.org/

let num = 1_000_000;

I get an error.

https://github.com/tc39/proposal-numeric-separator
This feature is Stage 3 not Stage 4 so I am just wondering is there a set of rules i can use to know whether a feature will be supported by Terser? does something have to be stage 4 before it will be supported? I am just wondering how to document the build tool I am working on so users can know what to expect

**Comment by fabiosantoscode** [comment]
Thanks for the heads up. We really should include in the docs which stages we support.

Features usually need to be stage 4 to be included, but some things are easy and can just go in at stage 3. This sounds like one of them.

**Comment by BrianMulhall** [comment]
thanks for the quick response, would it be safe to assume that ES6 is fully supported by terser?

**Comment by fabiosantoscode** [comment]
There's one feature missing but all these years nobody's complained, and babel doesn't support it either, so yes ;)

**Comment by BrianMulhall** [comment]
awesome, thank you :)

**Comment by sebakerckhof** [comment]
@fabiosantoscode Thanks for the info. If you say there's one feature missing, do you mean ES6 specifically, are all stage 4 features of the current ES spec (ES2020)?

**Comment by fabiosantoscode** [comment]
I mean ES6 specifically. There's a special scope nobody knows about, which is the scope for function parameters when one of the parameters has a default, and it's not supported. However, this lack of support is super stealth and you won't notice anything unless you really know where to look and are trying to break your own code.

**Comment by fabiosantoscode** [comment]
As for this year, only nullish coalescing and optional chaining are missing.
