### ISSUE TITLE
Feature request: Obfuscate / mangle filenames (fix information leakage)

### ISSUE THREAD

**Issue by mik3y** [terser/terser#634]
Terser exposes source filenames in minified output. Here's an example snippet:

```
[...]
({"../js/components/SuperSecretFeature.js":function(e,t,n){"use
strict";n.r(t),n.d(t,"default",function(){return c});var
o=n("../node_modules/axios/index.js"),r=n.n(o),
s=n("../node_modules/@sentry/browser/esm/index.js");
[...]
```

There are situations where this exposure might be unwanted, for example, it can expose details about the code structure of an application, and filenames might expose "secret" features or functionality.

One idea would be to replace these filenames with symbolic or hashed versions, for example:

```
[...]
({"5b834557b4a5b73ecd817d09c8d5c896.js":function(e,t,n){"use
strict";n.r(t),n.d(t,"default",function(){return c});var
o=n("442891977490bb2a49745e82df2c1cfe.js"),r=n.n(o),
s=n("7147bc04ac0fd3bf482e071e6f2bb15f.js");
[...]
```

I don't know much about the internals of terser, but I'd be happy to give this a shot as an option, if someone might provide a few pointers to get me started (specific modules / pipeline phases that would need to be touched). Assuming of course it isn't a non-starter..

thanks for this project! cheers.

**Comment by fabiosantoscode** [comment]
Hey there!

I think you've opened the issue in the wrong project :) as terser doesn't add any file names to the output. This sounds like a reasonable feature request for your bundler though!

**Comment by mik3y** [comment]
Ah! Well that explains it.. looking at the completely wrong part of the toolchain. Thanks!
