### ISSUE TITLE
Feature request: inline output of TypeScript's `??` operator

### ISSUE THREAD

**Issue by shicks** [terser/terser#640]
**Bug report or Feature request?**

Feature request.

**Version (complete output of `terser -V` or specific git commit)**

4.6.11

**Complete CLI command or `minify()` options used**

```
echo 'if (null ?? false) console.log(42);' > main.ts
tsc --out /dev/stdout main.ts | terser -c
```

**`terser` input**

main.ts:
```
if (null ?? false) console.log(42);
```

main.js:
```
var _a;
if ((_a = null) !== null && _a !== void 0 ? _a : false)
    console.log(42);
```

**`terser` output or error**

```
var _a;null!==(_a=null)&&void 0!==_a&&_a&&console.log(42);
```

**Expected result**

```
0;
```

**Discussion**

The null coalescing operator is becoming increasingly common.  It would be very useful for terser to be able to understand the pattern generated by common transpilers.

In particular, this enables a useful pattern of using webpack/rollup to substitute a function call that falls back to returning undefined:

```
const DEBUG: boolean = define('DEBUG') ?? false;
```

With the fallback, this should be able to be stripped unconditionally of whether or not `define('DEBUG')` is replaced (and indeed it can if it's substituted with the long-form `define('DEBUG') != null ? define('DEBUG') : false`.  But the null-coalesce transpilation breaks this.

**Comment by shicks** [comment]
FWIW it seems like the difficulty is the use of the non-const local variable.  Is there some way to recognize that it's only assigned once and read immediately and then treat it as effectively const?

**Comment by fabiosantoscode** [comment]
I'll see what I can do!

**Comment by shicks** [comment]
Looking into this further, it seems that terser can already do this _if_ it can assume that the temporary variables doesn't escape.  In particular, if I wrap the input in an IIFE (or change the `var` to `const`), it compiles down to nothing.  In this case it's not strictly required because it's executed immediately after being set, so even if it's reassigned externally, the result is already set in stone.

In my use case, these are module-local variables, but it seems that for some reason webpack isn't necessarily delivering them in a way that convinces terser that they don't escape:

```
// webpack_out.js
(() => {
  "use strict";
  /*@__INLINE__*/
  function define(name) {
    return  false ?
        undefined : undefined;
  }

  var _a, _b;

  const DEBUG = (_a = define('DEBUG')) !== null && _a !== void 0 ? _a : false;
  const ENABLE_ASSERTS = (_b = define('ENABLE_ASSERTS')) !== null && _b !== void 0 ? _b : DEBUG;

  function assert(x) {
    if (!ENABLE_ASSERTS) return;
    if (!x) throw new Error('assertion failed');
  }

  function foo(x, y) {
    assert(x);
    assert(y);
    return x / y;
  }
  console.log(foo(5, 2));
})();
```

```
$ npx terser -c < webpack_out.js
(()=>{"use strict";const ENABLE_ASSERTS=(void 0,void 0,!1);function assert(x){if(ENABLE_ASSERTS&&!x)throw new Error("assertion failed")}var x,y;console.log((y=2,assert(x=5),assert(y),x/y))})();
```

This is odd - the input is in an IIFE, and there's this really obviously inlineable `const ENABLE_ASSERTS=(void 0,void 0,!1);` that I would expect to inline to `false`, and yet it doesn't. 
 So there's definitely some issues here, but I'm having trouble isolating them.

In any case, I'm ultimately barking up the wrong tree, since my assumption was that webpack and/or terser could do a replacement on `define('DEBUG')` the way rollup can (I'd done some experiments but potentially misinterpreted the results).  Since it can't, this doesn't actually help my primary goal, which is finding _some_ way to make replacements (via global_defs, or else webpack's DefinePlugin _and_ rollup's plugin-replace) have _defaults_ when they're not explicitly specified.  I've opened one more FR (#653) to track that request more directly, rather than beating around the bush with an [XY problem](http://xyproblem.info).

**Comment by fabiosantoscode** [comment]
Regarding inlining the ?? operator, if you enable the toplevel option it improves the situation a lot. This option should be enabled if you aren't inlining your script tag in the browser. It should be enabled by default, but that would be a breaking change, and I want to keep Terser as compatible with its UglifyJS parent as possible.

Things like `void 0` and other inert things being stuck in sequences is one of those things that you can fix with more compressor passes. I've tried multiple times to get rid of those (mostly because they trip up people, not because they're that bad in terms of output size) but it's too hard to justify the benefit.

**Comment by jridgewell** [comment]
I'm closing this as implemented in https://github.com/terser/terser/commit/575ba807c4e5dcad9e01ea8e602bc4c2b42c9dca. We can track the global variable optimization in https://github.com/terser/terser/issues/653.
