### ISSUE TITLE
Question around object property accesses/inlining

### ISSUE THREAD

**Issue by jdb8** [terser/terser#645]
**Bug report or Feature request?**

Question/possible bug/feature request

**Version (complete output of `terser -V` or specific git commit)**

`terser 4.6.11`

**Complete CLI command or `minify()` options used**

`terser terser-input.js --verbose --warn --toplevel -c passes=3 -m`

**`terser` input**

```js
const myObj = { a: 1, b: 2, c: 3 };

function getProperty(someVar) {
  return myObj[someVar];
}

console.log(getProperty("a"));
console.log(getProperty("b"));
```

**`terser` output or error**

`const o={a:1,b:2,c:3};function n(n){return o[n]}console.log(n("a")),console.log(n("b"));`

**Expected result**

`console.log(1);console.log(2);`

**Additional context**

I'm curious about why terser is able to optimize the above code when only a single call to `getProperty` is present: i.e. the following code:

```js
const myObj = { a: 1, b: 2, c: 3 };

function getProperty(someVar) {
  return myObj[someVar];
}

console.log(getProperty("a"));
```

is minified down entirely to `console.log(1)`, with the following terser warnings/logs:

```
WARN: Collapsing someVar [terser-input.js:4,15]
WARN: Dropping unused function getProperty [terser-input.js:3,9]
WARN: Dropping unused variable someVar [terser-input.js:3,21]
WARN: pass 0: last_count: Infinity, count: 18
WARN: Dropping unused variable myObj [terser-input.js:1,6]
WARN: pass 1: last_count: 18, count: 6
WARN: pass 2: last_count: 6, count: 6
```

whereas adding any additional `getProperty` calls (as in the first code example) instead includes both the original `myObj` object (including unused properties), as well as the `getProperty` function itself, with the following warnings:

```
WARN: pass 0: last_count: Infinity, count: 32
WARN: pass 1: last_count: 32, count: 32
WARN: pass 2: last_count: 32, count: 32
```

(note no mention of collapsing `someVar` or dropping the unused object + function)

This doesn't seem to change even when increasing the number of `passes` or by setting any other terser compress options that I could find: I tried also using `PURE` and `INLINE` terser annotations but that also didn't get me the output I want.

So my question is: what makes these two inputs different? Is it a question of safety, given that `getProperty` is called multiple times? And if so, is there a way I can force terser to fully inline the output of both calls?

Apologies if this belays a fundamental misunderstanding of how this specific optimisation works under the hood: I'm very curious what I'm missing here. Thanks!

**Comment by jdb8** [comment]
> I tried also using PURE and INLINE terser annotations but that also didn't get me the output I want

Correction here: I had not tried to use an `INLINE` annotation **using my installed copy of terser** - I had been using https://try.terser.org/ for quick experiments, only using the installed copy to verify before writing this issue. When I try use terser on the command line, I'm able to minify the following code:

```js
const myObj = { a: 1, b: 2, c: 3 };

function getProperty(someVar) {
  return myObj[someVar];
}

console.log(/*@__INLINE__*/ getProperty("a"));
console.log(/*@__INLINE__*/ getProperty("b"));
```

into the desired `console.log(1),console.log(2);` (requiring 5 passes).

So, going to close this issue - I can make an issue or PR on https://github.com/terser/repl to update the version of terser/add a version identifier to the UI.

**Comment by fabiosantoscode** [comment]
It's going to take before I implement this, but the inline annotation will be placeable before the function declaration itself, be it `/*#__INLINE__*/function x(){}` or `/*#__INLINE__*/const x = () => {}`.

Regarding the amount of passes you needed, some things just require more passes. Specifically inlining something multiple times in to the same closure prompts Terser to create loose `var` statements to replace arguments. And after it does, further inlining of the same function in the same closure will be impeded because of that new `var` statement with a name colliding with the argument :)

I tried to mitigate these loose `var` statements and their impact, by inlining inert things like strings used just once, right into where they're being used, and by renaming everything in the function before it's inlined. But it makes a lot of code more complicated.

I went ahead and made the Terser repl always use the latest version of Terser, simply by using jsdelivr to retrieve Terser. I should've done this before, and sorry if it caused you grief.

**Comment by jdb8** [comment]
@fabiosantoscode makes sense, thank you for the context.

Once I realised that the `INLINE` comment wasn't working originally, it made sense why my example didn't work. Good to know that it might be possible in the future to declare that at function-definition time, that would simplify usage of this in some cases I can think of.

> I went ahead and made the Terser repl always use the latest version of Terser, simply by using jsdelivr to retrieve Terser. I should've done this before, and sorry if it caused you grief.

No problem, and thank you for doing this! Although just a quick note, it seems https://try.terser.org/ has some styling issues and appears visually broken right now for me in Chrome (I realise this isn't the right repo or thread for bug reports, but just bringing it up).

**Comment by fabiosantoscode** [comment]
I'll check it out in Chrome, thanks :)
