### ISSUE TITLE
Customize mangled properties names

### ISSUE THREAD

**Issue by martindzejky** [terser/terser#649]
## Bug report or Feature request?

Feature request, enhancement

## Version (`npm ls terser`)

`terser@4.6.3`

## Complete CLI command or `minify()` options used

Does not really matter but for my project it looks like this (we are using Rollup):

```
        require('rollup-plugin-terser').terser({
            compress: {
                // this is disabled because it inlines the top level IIFE parameters
                evaluate: false,
            },
        }),
```

## `terser` input

The most important part is the beginning:

```
(function (scriptString, objectName, cookieRegex, clientName, document, window, options) {
    // the rest of the code continues
```

## `terser` output

```
!function(e,n,t,i,r,a,c){ ...
```

## Expected result

```
!function(s,o,m,e,S,t,r,i,n,g){ ...
```

## Description

I would like to customize which names are chosen when mangling property names. Currently, as far as I understand the code, the names are generated [here using `base54` method](https://github.com/terser/terser/blob/master/lib/propmangle.js#L289). I would like to customize _some_ variable names.

## Why?

I'm compiling a piece of code which is an [IIFE](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression). The function has a number of parameters which is the first thing my users see when they use this piece of code. Currently, Terser produces an output where the function parameters usually form something like `entirac` or `entiro`. I would like to have these properties form a custom word, so, I need to tell Terser specifically how to mangle the top level function parameter names. This should probably be customizable in the Terser config.

How hard would be to implement such a change?

**Comment by fabiosantoscode** [comment]
This would be a really cool feature I believe. I've seen an issue about this in the past but can't find it.

I think you can get somewhere by modifying the `base54` object present in lib/scope.js to accept an option to spell something out (and after spelling it out, work as normal).

Just in case you're willing to send a PR, it should be as easy as:

 - Introducing a new `spell_out` mangle option.
 - Passing the `spell_out` option to `base54.sort()` every time it's called
 - Sort it in a way that spells out the passed-in option.
 - Add a mocha test or two ;)

**Comment by martindzejky** [comment]
Thanks @fabiosantoscode, I'll try to make a PR for this.
