### ISSUE TITLE
Getting error: redeclaring const variable

### ISSUE THREAD

**Issue by bdwain** [terser/terser#650]
**Bug report or Feature request?**  BUG REPORT

**Version (complete output of `terser -V` or specific git commit)**
what
whatever is in the [REPL](https://try.terser.org/), though I noticed locally with 4.6.3

**Complete CLI command or `minify()` options used**
defaults in the [REPL](https://try.terser.org/)

**`terser` input**
```js
for (const key of Object.keys(ret)) {
  const value = ret[key];
  if (typeof value === 'object' && value !== null) {
    for (const k of Object.keys(value)) {
      value[k] = parseValue(value[k], options);
    }
  } else {
    ret[key] = parseValue(value, options);
  }
}
```

**`terser` output or error**
```js
for(const e of Object.keys(ret)){const o=ret[e];if("object"==typeof o&&null!==o)for(const e of Object.keys(o))o[e]=parseValue(o[e],options);else ret[e]=parseValue(o,options)}
```
note the `const e` is repeated twice

**Expected result**
do not reuse variable names

**Comment by fabiosantoscode** [comment]
Reusing variable names doesn't break the output code, so it's something out of scope for this project.

During mangling, variable names are reused when there is no collision between them.

In this case, the inner for..of loop contains a new scope, which doesn't use the outer `e` (in this case `key`), so it's safe to reuse the name.
