### ISSUE TITLE
feature request: option to minify repeated strings

### ISSUE THREAD

**Issue by patrickkettner** [terser/terser#652]
**Feature request**

(obviously contrived example)
```js
var a = "foo"
var b = "foo"
var c = "foo"
var d = "foo"
var e = "foo"
var f = "foo"
var g = "foo"
var h = "foo"
var i = "foo"
var j = "foo"
var k = "foo"
var l = "foo"
var m = "foo"
var n = "foo"
var o = "foo"
var p = "foo"
var q = "foo"
var r = "foo"
var s = "foo"
var t = "foo"
var u = "foo"
var a = "foo"
var w = "foo"
var x = "foo"
var y = "foo"
var z = "foo"

console.log(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,q,r,s,t,u,v,w,x,y,z)
```

I have some builds that do string comparisons in multiple places (like typeof foo !== "undefined"), and as a result strings are repeated numerous times in larger builds.

It would be great if terser was able to do something like hoist repeated strings to a var, and then use that variable in place of the string throughout

**Comment by fabiosantoscode** [comment]
Hey there!

This kind of duplicates https://github.com/terser/terser/issues/578. See my comment there on why I closed it :)

**Comment by patrickkettner** [comment]
thanks!
