### ISSUE TITLE
Optimize function to arrow

### ISSUE THREAD

**Issue by rentalhost** [terser/terser#654]
**Bug report or Feature request?** 

Feature

**Version (complete output of `terser -V` or specific git commit)** 

4.6.11

**Complete CLI command or `minify()` options used** 

`terser test.js --compress unsafe_arrows=false --beautify`

**`terser` input**

```js
const t = n => n;
function x(n) { return n; }
y(function (n) { return n; })
z(function (n) { return this[n]; });
```

**`terser` output or error** (with additional breaklines)

```js
const t = n => n;

function x(n) {
    return n;
}

y((function(n) {
    return n;
})), 

z((function(n) {
    return this[n];
}));
```

**Expected result**

```diff
  const t = n => n;

- function x(n) {
-     return n;
-  }
+ const x = n => n;

- y((function(n) {
-     return n;
- })), 
+ y(n => n),

  z((function(n) {
      return this[n];
  }));
```

**Comment by fabiosantoscode** [comment]
Hey there!

As the docs state, you need to set the `ecma` option to 2015 or higher, which yields the result you intend:

```
const t = n => n;

function x(n) {
    return n;
}

y(n => n),

z((function(n) {
    return this[n];
}));
```

Note that `function x` remains. This is probably because dealing with function hoisting would overcomplicate the code, so Terser just doesn't deal with it and leaves a good old function declaration.

**Comment by rentalhost** [comment]
@fabiosantoscode thanks for reply. Yeah, maybe the `function x()` example just can't be converted to const automatically because it is in fact a function. But maybe in this point some optimization can occur too, right? By benchmarking it, the speed is the same, so maybe it can be replaced too, maybe with `let` in global scope and `const` in strict scope or where is possible predict that it will be never modified (eg. `function x(){}; function x(){}`).

**Comment by fabiosantoscode** [comment]
Turning it into a var and hoisting it is complicated for internal reasons. When the function is turned into an arrow, the compressor is "looking at" the function, so to hoist it would be to get around this simplification. It's best just to keep the output code a bit more bloated and Terser a lot simpler.

**Comment by fabiosantoscode** [comment]
But if you enable toplevel Terser will be able to inline the function into where it might be used.
