### ISSUE TITLE
[Bug] CompressOptions is missing unsafe_symbols

### ISSUE THREAD

**Issue by d3lm** [terser/terser#659]
**Bug report or Feature request?**

Bug

`CompressOptions` is missing the `unsafe_symbols` option as mentioned in the readme.

**Version (complete output of `terser -V` or specific git commit)**

`terser 4.6.7`

**Compress options used**

```diff
compress: {
  passes: 3,
  pure_getters: true,
  unsafe: true,
  unsafe_math: true,
  unsafe_comps: true,
- unsafe_symbols: true, // <-- is missing
  unsafe_methods: true,
  unsafe_proto: true
},
```

**Comment by d3lm** [comment]
I could create a PR that adds this field to the `CompressOption` interface in [terser.d.ts](https://github.com/terser/terser/blob/575ba807c4e5dcad9e01ea8e602bc4c2b42c9dca/tools/terser.d.ts#L17) if that's desired.

**Comment by fabiosantoscode** [comment]
Hello there!

A PR would be appreciated indeed :)

**Comment by d3lm** [comment]
I figured that in master that property already has been added. So I am closing this one.
