### ISSUE TITLE
Support pre-existing source maps better

### ISSUE THREAD

**Issue by BSFishy** [terser/terser#660]
**Bug report or Feature request?**

Right now, existing source maps feel a little bit janky. In my personal project, I am using Typescript to write the code, compiling it to Javascript, then minifying it for release. I am using Gulp to automate this whole process to make things easier for me. When setting up code coverage, I noticed that the coverage is much better if I include source maps with my code. So I started trying to set everything up, but for some reason my source maps just weren't what I was expecting. Temporarily disabling the Terser action fixed my issues, so I went to check on the Terser Gulp plugin I was using ([`gulp-terser-js`](https://github.com/A-312/gulp-terser-js)) to see if there was some quick fix I could make. I ended up providing the `content` option, which fixed my project's source maps. However, when testing the change in the plugin, it was failing for some cases. I believe the issue is that when using a compiled Javascript file, the mappings and everything are specified, which gives some additional information. Without that, it just completely ruins the file.

I haven't tested anything, but I noticed the `source-map` package has `fromSourceMap` on both the generator and consumer classes. I'm thinking that those functions could be used (especially on the generator) to make sure all of the necessary information is retrieved from the existing source map. Again, I haven't tested that or anything, but I'm hopeful that a fix could be as simple as that.

The following information shows what is happening in the Gulp plugin with the test file.

**Version (complete output of `terser -V` or specific git commit)**
4.6.11

**Complete CLI command or `minify()` options used**

```js
terser.minify({
  sourceMap: {
    filename: [existing source map file option],
    content: [existing source map content],
  }
});
```

**`terser` input**

Javascript:
```js
function A() {
  console.log('A')
}
```

Source map:
```json
{
  "version": 3,
  "names": [],
  "mappings": "",
  "sources": ["fixtures/sm-test/a.js"],
  "sourcesContent": [ "function A() {\n  console.log('A')\n}" ],
  "file": "fixtures/sm-test/a.js"
}
```

**`terser` output or error**

Javascript:
```js
function o(){console.log("A")}
//# sourceMappingURL=http://127.0.0.1/fixtures/sm-test/a.js.map
```

Source map:
```json
{
  "version": 3,
  "sources": [],
  "names": [],
  "mappings": "",
  "file": "a.js",
  "sourcesContent": []
}
```

**Expected result**

Source map:
```json
{
  "version": 3,
  "sources": ["fixtures/sm-test/a.js"],
  "names": ["A","console","log"],
  "mappings": "AAAA,SAASA,IACPC,QAAQC,IAAI",
  "file": "a.js",
  "sourcesContent": ["function A() {\n  console.log('A')\n}"]
}
```

**Comment by fabiosantoscode** [comment]
Hey there!

I see it's a gulp-terser-js issue after all! Thanks for posting this anyway :)
