### ISSUE TITLE
Two similar yet different function calls get minified into one

### ISSUE THREAD

**Issue by sangmokh** [terser/terser#662]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

4.6.11

**Complete CLI command or `minify()` options used**

```sh
terser --compress -o foo.min.js -- foo.js
```

**`terser` input**

```js
function foo(value) {
  if (value) {
    return hello(1, world(2), 3);
  }
  return hello(1, world(2, 3));
}
```

**`terser` output or error**

```js
function foo(value){return hello(1,world(2),3)}
```

**Expected result**

```js
function foo(value){return value?hello(1,world(2),3):hello(1,world(2,3))}
```

**Observation that might be useful for debugging**

The below code gets correctly minified.

FROM:
```js
function foo(value) {
  if (value) {
    return hello(1, world(2), 3);
  }
  return hello(1, world(2, 4));
}
```
TO:
```js
function foo(value){return value?hello(1,world(2),3):hello(1,world(2,4))}
```

**Comment by fabiosantoscode** [comment]
This is pretty bad!

**Comment by sangmokh** [comment]
Great! Thanks for the quick response & fix!

**Comment by fabiosantoscode** [comment]
Was a cool problem :) basically Terser sometimes compares two branches of an if, in case they are the same. I recently optimised this code a lot, but broke it in this subtle way.
