### ISSUE TITLE
remove used destructuring when pure_getters is true

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#664]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.6.3

**Complete CLI command or `minify()` options used**

```
{
  compress: { pure_getters: true },
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
function f ({ a, b, c }) { b.d; }
```

**`terser` output or error**

```js
function f({b:f}){}
```

**Expected result**

```js
function f(){}
```

**Comment by fabiosantoscode** [comment]
This is a matter of increasing passes. Probably worth a look but low priority since nobody changes defaults :P

With passes=2, this is the result:

```
function f({}) {}
```

Object isn't removed so as to not mess with f.length

**Comment by LongTengDao** [comment]
Oh, I forgot it's sometime necessary for f.length. The default behaviour is right. But...

```
{
  compress: { pure_getters: true, keep_fargs: false, passes: 2 },
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

this still got `function f({}){}`...

**Comment by fabiosantoscode** [comment]
I don't think that's too much of a big deal. Remember, suboptimal code is not a bug.
