### ISSUE TITLE
Question regarding minification

### ISSUE THREAD

**Issue by sarsamurmu** [terser/terser#665]
**Bug report or Feature request?**
Bug report

**Version**
4.6.11

**Complete CLI command or `minify()` options used**
Options used
```js
{
  toplevel: true,
  compress: {
    passes: 10
  }
}
```

**`terser` input**
```js
const add = (x, y, z) => x + y;

setNum(add(2, 4, someVar));
```

**`terser` output or error**
```js
setNum((someVar, 6));
```

**Expected result**
```js
setNum(6);
```
My question is that why it keeps the `someVar` when it is not used?

**Comment by fabiosantoscode** [comment]
Hey there!

someVar is a global variable. Accessing it without it being defined might throw, and if something is supposed to throw, Terser won't stop it.

**Comment by sarsamurmu** [comment]
I didn't know that. Thanks!
