### ISSUE TITLE
Invalid character in IE11

### ISSUE THREAD

**Issue by creage** [terser/terser#678]
**Bug report or Feature request?**
Bug

Minifying unicode literal keys results into ``Invalid character`` exception in IE11.

**Version (complete output of `terser -V` or specific git commit)**
terser@4.6.12 as a dependency of terser-webpack-plugin@1.4.3

**Complete CLI command or `minify()` options used**
```javascript
{
    mangle: {
        keep_fnames: true
    }
}
```

**`terser` input**
this particular file fails https://github.com/select2/select2/blob/develop/src/js/select2/diacritics.js on this char ``'\uA7A0'`` (line [128](https://github.com/select2/select2/blob/defe232bf6d233f17f3c26b776ad179ad26fe2bc/src/js/select2/diacritics.js#L128)) being converted into unicode and quotes stripped

**`terser` output or error**
```Ꞡ:"G"```

**Expected result**
working code in IE11?

P.S. changing minification parameters to these

```javascript
{
    mangle: {
        keep_fnames: true
    },
    output: {
        ascii_only: true,
        keep_quoted_props: true
    }
}
```
produces working code

**Comment by Agamnentzar** [comment]
here's another, simpler failing example, that produces the same error
```js
console.log({ "\u2139\uFE0F": "2139" });
```

**Comment by fabiosantoscode** [comment]
This is a side effect of a new optimization. With default settings, Terser shouldn't convert ES5 compatible code into ES6+ code unless the original chunk was ES6+ too or you explicitly opt in using the ecma option. Thank you for this report.

**Comment by fabiosantoscode** [comment]
@Agamnentzar the `\uFE0F`  shouldn't be necessary. I ended up using your example but with just `\u2139`.
