### ISSUE TITLE
Add option to define custom directives?

### ISSUE THREAD

**Issue by kuoruan** [terser/terser#679]
**Bug report or Feature request?**

Feature request. Keep the quoted strings at the beginning of files. Not only ```"use strict";```

**Version (complete output of `terser -V` or specific git commit)**

4.6.12

**`terser` input**

```js
"use strict";
"require view";

console.log("terser this");
```

**`terser` output or error**

```js
"use strict";console.log("terser this");
```

**Expected result**

```js
"use strict";"require view";console.log("terser this");
```

**Comment by fabiosantoscode** [comment]
I'm inclined to say no, but please tell me the use case. Some sort of custom directive for another tool to read?

**Comment by kuoruan** [comment]
@fabiosantoscode
I am writing user interfaces for [OpenWrt](https://openwrt.org/).
It uses custom directive ```require xxx``` to import other modules.

http://openwrt.github.io/luci/jsapi/LuCI.html

https://github.com/openwrt/luci/blob/551d839f90853b58f81d124c77442009d4df0cb4/modules/luci-base/htdocs/luci-static/resources/luci.js#L2458-L2494

I will find some other way to handle this.
Thank you for the reply.

**Comment by fabiosantoscode** [comment]
Legit use case. Let's add an option that allows people to define what is and what isn't a directive.

**Comment by fabiosantoscode** [comment]
This option should be a regex where you can match the contents of a string to see if it's a directive and deserves to not be mercilessly dropped.

Suggested option name: `custom_directives`

**Comment by kuoruan** [comment]
just found that there is already has a option named ```directives```.
https://terser.org/docs/api-reference#compress-options

That's enough. Thanks again.
