### ISSUE TITLE
Accessing `arguments` inside function considered as side effect

### ISSUE THREAD

**Issue by bhovhannes** [terser/terser#687]
**Bug report or Feature request?**

Not sure if this is a bug, but I have no idea why it should work like this.  
I'll be grateful for explanation.

**Version (complete output of `terser -V` or specific git commit)**

4.6.13

**Complete CLI command or `minify()` options used**

`terser terser-bug.js -c -m`

**`terser` input**

Contents of `terser-bug.js`:
```javascript
(function () {                
    function looksAsImpureForTerser() {
        return arguments.length
    }

    looksAsImpureForTerser();

    console.log('hello');
})();
```

**`terser` output or error**

```javascript
!function(){arguments.length}(),console.log("hello");
```

**Expected result**

```javascript
console.log("hello");
```

**Additional notes**

1. Running terser as:
```
terser terser-bug.js -c pure_funcs=looksAsImpureForTerser -m
```
produces
```javascript
console.log("hello");
```

2. Running terser as:
```
terser terser-bug.js -c pure_getters=true -m
```
also produces correct output.

3. Adding `/*@__PURE__*/` annotation also helps:
```javascript
(function () {                
    function looksAsImpureForTerser() {
        return arguments.length
    }

    /*@__PURE__*/ looksAsImpureForTerser();

    console.log('hello');
})(); 
``` 

This behavior has big impact on dead code removal as babel transpiles argument spread `(...args) {}` and optional argument `(a = 3) {}` syntax using `arguments` keyword.  

For example, for DOMPurify the whole library is left in the bundle even if nobody uses it.  
The reason is that almost whole code of DOMPurify is wrapped inside a single [function createDOMPurify(window = getGlobal()) {..}](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L74).  
Babel transpiles optional argument to `var window = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : getGlobal();`, and that ended up in ESM bundle of DOMPurify.  
For terser `createDOMPurify` is no longer pure and as a result webpack terser plugin does not remove that function, even when nobody is calling it.

**Comment by fabiosantoscode** [comment]
This issue isn't technically a bug in this project's definition, but I'm marking it as such to signify its importance.

Thank you for the nice issue description.

I see that `arguments` itself is considered pure (as should be) but the property access `.length` isn't. This is because unless `pure_getters` is enabled, Terser doesn't assume getting a property is a pure operation.

I'm surprised this didn't pop up earlier.

**Comment by fabiosantoscode** [comment]
Will be released this week, probably tomorrow!

**Comment by bhovhannes** [comment]
Thank you !
