### ISSUE TITLE
How can I keep a function from being mangled?

### ISSUE THREAD

**Issue by fclaussen** [terser/terser#688]
**Question**

Sorry, I tried messing with the mangle properties and regex but that didn't work and I have a launch tomorrow morning so I'm kinda desperate. I tried searching for the solution but couldn't find anything that worked.

I need to keep a function after the file get's minified. It's a translation function `__( 'translation string', 'textdomain' )`

I could not figure this out on my own and I am hoping someone will be able to rescue me.
I'm compiling with webpack.

When I shut mangle off it works but I couldn't make it work with any of the options. I also tried using keep_fnames but that didn't work either.

```
new TerserPlugin( {
		cache: false,
		parallel: true,
		sourceMap: false,
		extractComments: false,
		terserOptions: {
			mangle: {
				properties: {
					regex: /^__/
				}
			}
		}
	} )
```

**Expected result**
Look at the minified file and see `__(` functions all around.
such as `__("Sign-in to redeem","coc")`

**Actual Result**
`s("Sign-in to redeem","coc")`

**Comment by fclaussen** [comment]
I tried using `reserved` instead of regex there, but maybe I'm implementing it wrong?

**Comment by fabiosantoscode** [comment]
Hey there! 

I realise it's too late by now, but you're looking for the `reserved` mangle option, not the mangle.properties option.

I just checked, and these options should do what you expect:

```
{ mangle: { reserved: ["__"] } })
```

Also, Terser does not mangle global variables, so I suppose `__` was defined somewhere, perhaps through an import?

**Comment by fclaussen** [comment]
Oi @fabiosantoscode!

Yes. That's correct. This is the new WordPress translation lib for JS.
I call it like this `const { __ } = wp.i18n;`

Your code worked. I can't believe how simple it was. 
I guess I must have been too desperate and tired that day that I maybe didn't fully understand the documentation for this. I thought the properties key was required.

Obrigado!

**Comment by fabiosantoscode** [comment]
The first thing to do is look at the code without minification. If there's some tool in the middle, like a bundler, it may move things around in a way that Terser won't expect.

For instance it could turn a clear `import { __ } from 'i18n'; __('abc')` into `autoGeneratedModuleObject.__('abc')`

**Comment by mateuswetah** [comment]
Yes, you are correct @fabiosantoscode... just checked disabling the `minimize` and the bundled js has a `var edit_=wp.i18n.__;`

In terms of order, does the place where I put the terserPlugin affects it? I don't have any other attribute inside the `minimize` or the `optimize` attributes .... but I do have some different loaders in the `module`.

**Comment by fabiosantoscode** [comment]
I think rollup doesn't do that, as it places all modules in a large file. But I haven't checked in a while. Webpack IIUC always creates a wrapper function per module.

If it's important for some compiler or tool to pick up __ as a global function, my suggestion is to use it as a global function.

If it's not defined during development you can always import it in some module and conditionally assign it to the window object.
