### ISSUE TITLE
reorder assignments to where the variable is first used

### ISSUE THREAD

**Issue by heavyk** [terser/terser#690]
**Bug report or Feature request?** feature request

**Version (complete output of `terser -V` or specific git commit)** try.terser.org (btw, should put the versoin on the page, so people can reference it here)

**Complete CLI command or `minify()` options used**
(none) the defaults

**`terser` input**
```js
// unordered:
var _prop1 = me.prop1
obj._prop1 = _prop1
obj.prop2 = prop2
arr.push([prop2, obj])
```
vs
```js
// reordered so that the first place `_prop2` is used, is where it's assigned
var _prop1 = me.prop1
obj._prop1 = _prop1
arr.push([obj.prop2 = prop2, obj])
```

**`terser` output or error**

in the unordered case, terser outputs:
```js
//unordered
var _prop1=me.prop1;obj._prop1=_prop1,obj.prop2=prop2,arr.push([prop2,obj]);
//ordered
var _prop1=me.prop1;obj._prop1=_prop1,arr.push([obj.prop2=prop2,obj]);
```

**Expected result**

both should output  the ordered result.

I did try enabling all the unsafe options (even pure_getters), but it doesn't reorder the statements, so I figured this could be a pretty good optimisation 👍

**Comment by avdg** [comment]
Terser doesn't do variable flow analysis, so there is no guarantee that changing the order of operations will result in the same output. Especially with possible getters and setters.

In this example case however, the assignment is coincidentally collapsing and the order is remained (although the intend was to sort the props by name). So the example might be an optimisable edge case. Though I have no idea how hard it is to implement this.

**Comment by heavyk** [comment]
yeah, I might take a swing at it sometime when I'm feeling like doing something like this.

also, upon seeing this with fresh eyes, there's another optimisation too: prop1 can also be reordered.

```js
var _prop1 = obj._prop1 = me.prop1
arr.push([obj.prop2 = prop2, obj])
```

**Comment by fabiosantoscode** [comment]
Can you try doing the same with pure_getters enabled?

**Comment by heavyk** [comment]
yep, tried it with the latest version locally and on try.terser.org, and it's the same result:

```js
var _prop1=me.prop1;obj._prop1=_prop1,obj.prop2=prop2,arr.push([prop2,obj]);
```

**Comment by fabiosantoscode** [comment]
Terser already does this with variables, where it's way easier :)

I think this is a valid optimisation Terser could make, but I have to refuse because of maintenance costs, and the fact that it would have to be gated behind pure_getters.

**Comment by heavyk** [comment]
no worries. I was mainly posting it so that it's there. I'm interested in perhaps doing this some day in the future because I like these sorts of problems. that one, and this one, too:

```js
const fn = (G) => {
  let { a, b, c } = G
  // .. no more usages of G
}
// -> const fn = ({a, b, c}) => { ... }
```

cheers :)
