### ISSUE TITLE
optimise `=== -1`

### ISSUE THREAD

**Issue by heavyk** [terser/terser#692]
**Bug report or Feature request?** feature request

**Version (complete output of `terser -V` or specific git commit)** try.terser.org

**Complete CLI command or `minify()` options used** any set of options 

**`terser` input**

```js
if (some_index === -1) do_something()
```

**`terser` output or error**
```js
-1===some_index&&do_something()
```

**Expected result**
```js
!~some_index&&do_something()
// or
~some_index||do_something()
```

**Comment by Conduitry** [comment]
Doing this with `===` is definitely not safe, as `~'-1'` is also `0`.

**Comment by heavyk** [comment]
ok, sure it's not 'safe' because it coerces a string to an integer: `~-1 === ~'-1'` -- but in the case where you're sure to be getting integers, it's definitely safe... the most common use-case for this is comparison with indexOf. so, `str.indexOf('...') !== -1` -> `~str.indexOf('...')` which is definitely safe.

then, I suppose it could go under the `unsafe_comps` flag or something.

another optimisation (which would be safe) could target specifically the case of comparisons with  .indexOf, of the permutations: `>= 0` `> -1` `!== -1` `!= -1`

**Comment by fabiosantoscode** [comment]
Hello there!

Terser isn't sure what type the object you're calling `indexOf` on is. It has no type system. Maybe in a distant future it will, but by then people will be able to use `.contains` without a polyfill.
