### ISSUE TITLE
Uninitialized const produced by compression

### ISSUE THREAD

**Issue by strangebeer** [terser/terser#699]
**Bug report or Feature request?**

Bug.

**Version (complete output of `terser -V` or specific git commit)**

`terser 4.6.13`

**Complete CLI command or `minify()` options used**

`terser input.js --compress --beautify`

**`terser` input**

``` js
class Demo {
    method(arg) {
        const argSomething = arg.something()

        try {
            doSomethingWithArg(argSomething)
        } catch (err) {
            doSomethingWithError(err)
        }

        const err = somethingElse
        return err
    }
}
```

**`terser` output or error**

``` js
class Demo {
    method(arg) {
        const err, argSomething = arg.something();
        try {
            doSomethingWithArg(argSomething);
        } catch (err) {
            doSomethingWithError(err);
        }
        return somethingElse;
    }
}
```

Note the constant named `err` in 3rd line that come from nowhere and uninitialized.

**Expected result**

Should not produce the uninitialized `err` constant. This seems only to happen if the variable in the catch statement has the same name as the last constant.

Thanks for the great work.

**Comment by fabiosantoscode** [comment]
Hello!

Thanks for the reproduceable snippet! This is pretty terrible and I'm going to have a look right now.

**Comment by fabiosantoscode** [comment]
Workaround is to disable `collapse_vars` or `unused`, or rename your error variable. I'm able to reproduce this with regular functions as well, and I found two separate issues cooperating to cause this bug, a previously unknown scope issue, and a very old issue where `const` turned out to have zero elements.

**Comment by fabiosantoscode** [comment]
I've implemented a simple fix. A new version will be released during the week, probably monday.

**Comment by strangebeer** [comment]
Great, thanks!
