### ISSUE TITLE
Feature | Exclude mangling for files in a specific folder

### ISSUE THREAD

**Issue by Xambey** [terser/terser#703]
**Bug report or Feature request?**
feature

**Version (complete output of `terser -V` or specific git commit)**
4.6.3
**Description**
Hello, I have a folder with generated client in the project for api (many services) work and I need the method parameter names not to be mangled, how can I do this? I would like to keep the minimization for these files, excluding only the names of the method parameters

**Complete CLI command or `minify()` options used**
none

**`terser` input**
none

**`terser` output or error**
none
**Expected result**

**Comment by fabiosantoscode** [comment]
Terser doesn't change anything depending on what folder the specific input file is. In fact, it doesn't really do anything cross-file at all. For that, you can look into configuring whatever is calling Terser, or if you're calling Terser yourself, change options depending on what file you're currently minifying.

About keeping parameter names, what's your use case? Parsing parameter names from an `unknownFunction.toString()`?

**Comment by Xambey** [comment]
@fabiosantoscode In a sense, yes. I have a factory that creates request handlers based on a reference to a method, the context of this method and a list of parameter values that map relative to the string parameter names. (That is, in the place where this generator is used, the user creates a settings object by specifying the name of the corresponding parameter in the transferred method - like { paramKey: "someKey", method: this.service.someHttpReqest, context: this.service } , where someHttpRequest(..., someKey: string, ... ) ). That is, I need the method names not to change in the files I specified or at least classes

**Comment by ianmclaury** [comment]
I have a similar use case with Svelte and Rollup. I have a svelte store object that has a set of 'computed' methods that are recalculated automatically every time one of their parameters changes. The original parameter names are what's used to set up the subscriptions, and it chokes when the mangled names don't match anymore.

This could be worked around by recoding the [package](https://github.com/freedmand/svue) I'm using, but the current syntax is elegant and it would be easier if I could tell terser to turn off mangling (or just parameter mangling if such existed) for that one module or section of code. For now I'm turning off mangling for the project.

**Comment by RobinTail** [comment]
I'm voting for this.
I need a way to prevent any minifications to a specific pre-compiled module.
The `exclude` is not enough.

**Comment by fabiosantoscode** [comment]
This is a bundler issue inherent to the process of bundling.

Commonly bundlers will give terser a big JS file with all the input modules, and the origin of each bit is lost.

A way to work around this is to have the bundler create separate bundles/chunks and try to customize Terser options based on which chunk is being output, or alternatively to run Terser on each input file, through some sort of Terser loader.
