### ISSUE TITLE
nulish compress error

### ISSUE THREAD

**Issue by juvenrui** [terser/terser#704]
code:
`const x = null;
const y = x ?? 500;
console.log(y);`

`$ terser --version`
terser 4.7.0
`$ terser script.js --output script.min.js --compress -m --ecma 2020`

but, nulish error. output:
Unexpected token ?

**Comment by fabiosantoscode** [comment]
Hello there!

I can't reproduce that on my machine. Is your code example complete? Perhaps you're using the `?.` operator which is not supported yet?

**Comment by juvenrui** [comment]
Hi:
```
const bla = null;
const data = bla ?? 500;
console.log(data);
```

   I test cli: `terser nulish.js -c -o nulish.min.js` is OK.

thank you!
