### ISSUE TITLE
Errors cause exports to be removed

### ISSUE THREAD

**Issue by guybedford** [terser/terser#718]
**Bug report or Feature request?**

A top-level `throw` statement triggers dead code elimination that will remove all subsequent exported bindings.

As a result, the module will not link properly in build tools and execution environments.

Even though the code is dead, the exported bindings should still be provided so that the error remains an execution time error.

**Version (complete output of `terser -V` or specific git commit)**

4.7.0

**Complete CLI command or `minify()` options used**

dead_code

**`terser` input**

```js
throw new Error('Explicit throw');

export function p () {
}
```

**`terser` output or error**

Outputs an empty source.

**Expected result**

Should output at least `export var p` so that linking still works and the build can complete, so we can report an error to users properly at execution time instead of a difficult to debug linking error.

**Comment by fabiosantoscode** [comment]
This is very interesting. Thanks for reporting it.

Exports should be immovable entities, which can't be reordered or removed.
