### ISSUE TITLE
Feature request: Override character frequency analysis

### ISSUE THREAD

**Issue by dmichon-msft** [terser/terser#719]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V` or specific git commit)**
terser 4.7.0

**What:**
I would like to be able to pass an option to Terser to explicitly override character frequency analysis for the purposes of identifier allocation. For example:

```
mangle: {
    character_precedence: 'etnrisouaflchpdvmgybwESxTNCkLAOM_DPHBjFIqRUzWXV$JKQGYZ0516372984'
}
```

Currently I am doing this via monkey-patch to produce the desired consistent result:
```
const DEFAULT_DIGIT_SORT = 'etnrisouaflchpdvmgybwESxTNCkLAOM_DPHBjFIqRUzWXV$JKQGYZ0516372984';

const base54 = terser.base54;
const coreReset: () => void = base54.reset;
base54.reset = (): void => {
    coreReset();
    for (let i = 0, len = DEFAULT_DIGIT_SORT.length; i < len; i++) {
        base54.consider(DEFAULT_DIGIT_SORT[i], len - i);
    }
    base54.sort();
};

terser.AST_Toplevel.prototype.compute_char_frequency = (): void => {
    base54.reset();
};
```

**Why:**
When bundling independently minified chunks of code (e.g. multiple ECMAScript modules), Terser's character frequency analysis results in different identifier selection between chunks, which causes the final file to have a suboptimal gzip profile.

Additionally, the existence of a static mapping allows it to be reused by other tools that mangle identifiers (e.g. renaming imports/exports in Webpack) for further gzip improvement.

Edit: renamed property for consistency with other options

Related: #649 is somewhat related in overriding identifier allocation; this item is about doing so all the time instead of just for top level, though.

**Comment by fabiosantoscode** [comment]
This seems like a valid use case.

However I can't consider this high priority, as I can't imagine this is a significant gain in compression. Feel free to send a PR though!

Once Terser 5 comes out, it will not be possible to monkey-patch things since AST objects and the base54 object will be hidden.
