### ISSUE TITLE
Bracket key definition removed

### ISSUE THREAD

**Issue by chaffeqa** [terser/terser#734]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

```terser@^4.6.13```

**Complete CLI command or `minify()` options used**

same as [create-react-app](https://github.com/facebook/create-react-app/blob/41a1088d04ef7f44a4d1dc46f173181cba91c215/packages/react-scripts/config/webpack.config.js#L225)

**`terser` input**

```
const key = {"t": "t"};
const val = {
default: {},
"string": {},
["stringInBracket"]:{},
[t["t"]]: {}
}
```

**`terser` output or error**

```
const val = {
default: {},
"string": {},
}
```

**Expected result**

```
const val = {
default: {},
"string": {},
"stringInBracket":{},
"t": {}
}
```

**Comment by tchetwin** [comment]
I couldn't reproduce the issue using the following in the Terser repl (config from your [link](https://github.com/facebook/create-react-app/blob/41a1088d04ef7f44a4d1dc46f173181cba91c215/packages/react-scripts/config/webpack.config.js#L225)):

```javascript
{
  parse: {
    ecma: 8,
  },
  compress: {
    ecma: 5,
    warnings: false,
    comparisons: false,
    inline: 2,
  },
  mangle: {
    safari10: true,
  },
  keep_classnames: true,
  keep_fnames: true,
  output: {
    ecma: 5,
    comments: false,
    ascii_only: true,
  },
}
```

```javascript
const key = {"t": "t"};

const val = {
  default: {},
  "string": {},
  ["stringInBracket"]:{},
  [t["t"]]: {}
};
```

The result was:

```javascript
const key={t:"t"},val={default:{},string:{},stringInBracket:{},[t.t]:{}};
```

Which is not *wrong*, but is conservative w.r.t. side-effects in `Object` prototype overrides.

**Comment by jridgewell** [comment]
I'm not able to reproduce the issue. If you can manage to recreate on https://try.terser.org/, please comment with the options/code used.
