### ISSUE TITLE
Error happened when processing on the assignment statement of 'process.env'.

### ISSUE THREAD

**Issue by superhos** [terser/terser#736]
**Bug report**
I have used terser in my electron project to compress code. But error happened in compress processing.

**My input**
````javascript
if (app.isPackaged) {
  let start = process.argv[process.argv.length - 1].lastIndexOf('-') + 1
  let end = process.argv[process.argv.length - 1].lastIndexOf('.')

  let env
  if (process.platform !== 'darwin') {
    env = process.argv[process.argv.length-1].substring(start,end)
  } else {
    env = process.argv[process.argv.length-1].slice(start)
  }

  if (env === 'uat') {
    process.env.NODE_ENV = 'uat'  //  Error Happend
  } else {
    process.env.NODE_ENV = 'production'  //  Error Happend
  }
}
````
**`terser` output or error**
ERROR in ./app/main.prod.js from Terser
[0] Invalid assignment [./app/main.dev.js:57,4][./app/main.prod.js:1388,17]

57 Line is `process.env.NODE_ENV = 'uat' `.

Any suggestion or it's a bug of Terser?

**Comment by fabiosantoscode** [comment]
That piece of code does not throw any error when compressed. Does the code run without compression?

**Comment by fabiosantoscode** [comment]
I see what happened.

Your code went through one of your bundler's plugins, which resulted in `process.env.NODE_ENV` being replaced with whatever `NODE_ENV` was at compile time.

The result was:

```
'production' = 'uat'
```

Which is an invalid assignment.
