### ISSUE TITLE
Bug when optimizing loop 

### ISSUE THREAD

**Issue by jschneider** [terser/terser#741]
**Bug report**

**Version 4.6.11**

**Cmd Line**
`terser ../quickchart.js --beautify --verbose --compress toplevel=true,unsafe=true,keep_infinity=true,keep_fnames=false,keep_fargs=false --source-map --output _compressed.js`

**Input**

```
for (var a = o, s = 0, u = t.length; s < u;) {
                var c = s, p = t[s];
                a.setTimestamp_5wr77w$(c, p.timestamp);
                for (var l = p.values, h = 0, d = l.length; h < d;) {
                  a.setValue_224j3y$(h, c, l[h]),
                    h = h + 1 | 0;
                }
                s = s + 1 | 0;
              }
```

**`WARN: Dropping unused variable c [../quickchart-beautiful.js:13690,20]`**

**Expected Output:**

```
              for (var a = o, s = 0, u = t.length; s < u;) {
                var c = s, p = t[s];
                a.setTimestamp_5wr77w$(c, p.timestamp);
                for (var l = p.values, h = 0, d = l.length; h < d;) {
                  a.setValue_224j3y$(h, c, l[h]),
                    h = h + 1 | 0;
                }
                s = s + 1 | 0;
              }
```

In the line `a.setTimestamp_5wr77w$(c, p.timestamp);` the variable "c" is replaced with "0".
I think terser does not realize that "s" is updated and therefore "c" is updated, too.

**Comment by fabiosantoscode** [comment]
Thanks for reporting! I just reproduced the issue.
