### ISSUE TITLE
Simplify `Array.from` calls with a static array

### ISSUE THREAD

**Issue by joseprio** [terser/terser#746]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V` or specific git commit)**
4.8.0

**Complete CLI command or `minify()` options used**
Defaults from https://xem.github.io/terser-online/

**`terser` input**
console.log(Array.from([1,2]))

**`terser` output or error**
console.log(Array.from([1,2]))

**Expected result**
console.log([1,2])

**Comment by L2jLiga** [comment]
Hi there, currently there's `new Array(1, 2) => [1, 2]` optimization in place (marked as unsafe).
I think it would be quite easy to add `Array.from` optimization too (also marked as unsafe)

**Comment by fabiosantoscode** [comment]
Hey there!

What's the use case for this? Is some compiler outputting this?
