### ISSUE TITLE
File extension is missing in some imports in terser's source code

### ISSUE THREAD

**Issue by CoolCmd** [terser/terser#754]
**Bug report or Feature request?**
Feature

**Version (complete output of `terser -V` or specific git commit)**
4.8.0

This problem is inside `terser` source code.

Node.js requires a file extension (.js) in the `import` statement. Otherwise, you can not use `terser` in unpacked (non-minified) form.

These strings:

`./tools/node` in `main.js`
`../lib/minify` in `node.js`
`./scope` in `propmangle.js`

should be replaced with these:

`./tools/node.js`
`../lib/minify.js`
`./scope.js`

**Comment by L2jLiga** [comment]
Hi there,

Afaik Terser 4.x is not distributed as ESM so no issue so far.
Distributing as ESM is planned for [Terser 5](https://github.com/terser/terser/issues/700) and as far as I see everything fine with it.

**Comment by CoolCmd** [comment]
OK, in the `feature/terser-5` branch these strings was fixed.
