### ISSUE TITLE
feature: enhance dead code elimination

### ISSUE THREAD

**Issue by vankop** [terser/terser#763]
**Bug report or Feature request?**

feature. Template string comparison could be enhanced. For given example str1 `aaaa${something}` str2 `aa${something}` str3 `1a${something}` terser can easily statically analyze that `str1 !== str3`  since smallest prefixes `aa` and `1a` are not equal. For str1 and str2 this enhancement could not be applied since `aa` === `aa`. Same for postfix could be applied

**Version (complete output of `terser -V` or specific git commit)**

latest on https://try.terser.org/

**Complete CLI command or `minify()` options used**
{
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}

**`terser` input**

```js
let value = 0;
if (`${value++}hello` === `${value++}world`) {
	console.log(value)
}
```

**`terser` output or error**

```js
let value=0;value+++"hello"==value+++"world"&&console.log(value);
```

**Expected result**

```js
let value = 3; // or nothing if unused
```

**Comment by fabiosantoscode** [comment]
This is an interesting optimization, but is this a common use case, or something which a compiler outputs?

There are technically a lot of things that Terser could optimize, but it remains small and (not really) fast by only optimizing things you can commonly find out in the wild.

**Comment by vankop** [comment]
No, this is not a part of compiler output, just found out that this does not work

**Comment by fabiosantoscode** [comment]
I see!

This would be quite tricky to implement so if it's not something someone would write by hand, or something a compiler would output, I have to close this.
