### ISSUE TITLE
When using fetch inside a function, it gives the same key param to the function and the promise respons

### ISSUE THREAD

**Issue by yejiel** [terser/terser#765]
**Bug report or Feature request?**
Bug Report

 `
 function getData(param){
    fetch(`${url}param=${param}`)
        .then(res => res.status === 200 && res.json())
        .then(res => res );
  }
`
**Version (complete output of `terser -V` or specific git commit)**
4.3.0 
**Complete CLI command or `minify()` options used**
Via parcel (or in https://try.terser.org/)

**`terser` input**

**`terser` output or error**
`
function(e){ fetch(${url}param=${e}).then(e=>200===e.status&&e.json()).then(e=>e)}();
`
**Expected result**
Differnt var name for the promise response to avoid conflict
now the promise resolved is getting the parent function value

Our work around was to use async await

**Comment by L2jLiga** [comment]
Hi there,
according to your example there's nothing wrong with code

```javascript
var original = function getData(param) {
  fetch(`${url}param=${param}`)
    .then(res => res.status === 200 && res.text())
    .then(res => res.length);
}

var minified = function(e){
  fetch(`${url}param=${e}`)
    .then(e => 200 === e.status&&e.text())
    .then(e => e.length)
};

Promise.all([original(1), minified(1)])
  .then((a, b) => a === b); // true
```

**Comment by yejiel** [comment]
@L2jLiga actually if you try to run that code on Chrome 84 at the very least, you will see that the first `.then( e )` is getting the parent function `e` value and not the response from the resolved promise, this was tested on the "try.terser.org)" site

**Comment by L2jLiga** [comment]
I've run this code using Chrome 84 on Windows 10 2004 and have no problem

**Comment by yejiel** [comment]
Yes, i have tried it and the sample code works
if we add a console.log(e) to our code works 
if we let it as is, it doesn't, ill close this and try to find the real issue.

**Comment by L2jLiga** [comment]
Good luck!
