### ISSUE TITLE
[Request] Mangle class properties that start with _

### ISSUE THREAD

**Issue by alshdavid** [terser/terser#770]
**Bug report or Feature request?** 
Feature Request

I feel like the option to mangle properties would be valuable. 
We can discriminate by a character suffix in a property name.

```
terser --mangle-private-class-properties
```

To help avoid collisions with other dependencies, perhaps offering the ability to set the private suffix would help.
e.g. below I am saying that any class property that starts with `__` should be considered for mangaling.

```
terser --mangle-private-class-properties --private-property-suffix="__"
```

This has a significant impact on applications that use classes and do a lot of constructor based dependency injection. We find a lot of repetition of "private" property names in the final output (which we lean on compression to help out).

So the expectation would be something like:

**`terser` input**

```javascript
class Foobar {
   constructor() {
      this._foo = 'something private'
      this.bar = 'something public'
   }

   print() {
      console.log(this._foo + this.bar)
   }
}
```

**Expected result**

```javascript
class Foobar {
   constructor() {
      this._0 = 'something private'
      this.bar = 'something public'
   }

   print() {
      console.log(this._0 + this.bar)
   }
}
```

**Comment by L2jLiga** [comment]
Hi there

This is possible as of now with --mangle-properties regex option

**Comment by fabiosantoscode** [comment]
@L2jLiga I think they mean to only mangle those properties when they are found in the constructor.

This would mean, though, that you can only use the properties within the scope of the class. If you had a utility function which needed to use that property, Terser wouldn't be able to find it and you'd be better off using the global mangle-properties.

I think this could be a fine way to use the property mangler in a way that doesn't break your code 100% of the time because we can assume private properties are read and written to only within the class.

I think, however, that we shouldn't look for these properties in the constructor, but instead in the class body, as it would be faster and clearer.

```
class WithPrivProps {
  __priv = null
  //...
}
```

**Comment by fabiosantoscode** [comment]
I would still prefer to implement mangling standard JS private properties (this.#x) because it's 100% safe, as the language enforces those property accesses to always be contained in their class.

**Comment by alshdavid** [comment]
Silly question, I am trying to mangle using webpack:
```javascript
new TerserPlugin({
  terserOptions: {
    mangle: {
      properties: {
        regex: /_$/
      },
    },
  },
}),
```
But this doesn't pick up properties in classes such as:
```
Foo {
  constructor() {
    this._bar = ''
  }
}
```
Mind helping me out a little?

**Comment by justinfagnani** [comment]
We would really like the ability to control the mangled name of class properties.

We can't use true private fields for a few reasons: browser support, the performance cost of transpired versions, and that we often need to share these fields across other module-internal classes and functions.

So we use properties with a `__` prefix and rename them with a name cache so they're the same across files.

This works fine except that there's no indication in the mangled names that they are "private" and not just one-char public names. We would like to prefix the output names with `_` or `$` to set them apart.

**Comment by fabiosantoscode** [comment]
@justinfagnani that's an interesting feature request, but it makes a lot of sense. If you can spare the extra _ in your output, you can now have your users tell an `x` or `y` property from randomly mangled stuff.

Could you please open a separate feature request as it seems unrelated to this one?

**Comment by justinfagnani** [comment]
@fabiosantoscode I think it's basically just the ability to control the mangle output, possibly with a replace string. Do you recall if this has been requested before? Seems somewhat likely.

**Comment by fabiosantoscode** [comment]
It's a separate issue.

This one is about only mangling names if they are found in the constructor, yours is about unconditionally adding a prefix.

**Comment by alshdavid** [comment]
Just a quick update, I have achieved this by using the following option in Webpack:

```javascript
mangle: {
 properties: {
    regex: /^_/
  }
}
```
