### ISSUE TITLE
Documentation: Removal of warnings not mentioned in changelog for v5.0.0

### ISSUE THREAD

**Issue by yellcorp** [terser/terser#782]
Hi there,

This seems like a very minor one, but a significant amount of code relating to warnings was removed in 71dc3456be968ddce2281b93beb4079e609e28ef. However there's no mention of this in the changelog for v5.0.0.

It's not strictly a breaking change for me as I was already checking the return value from `minify(...)` for a truthy `warnings` property.

While I don't depend on the feature, I _was_ logging the warnings for the benefit of end users, so I am curious why it was removed. Was it considered out of scope? Perhaps more the job of a linter?

I'm skipping the test case as I don't strictly consider this a bug in functionality, but I can provide one comparing the output of v5.0.0 against v4.8.0 if desired.

**Comment by fabiosantoscode** [comment]
Hello!

I did remove warnings, since a lot of them amounted to spam, and they seemed unnecessary. Dead code removal for example caused a lot of warnings nobody using Terser actually cared about.

I'll update the changelog, thanks for the heads up!
