### ISSUE TITLE
Bugs with inlining array with hole and object with getter or setter inside spread

### ISSUE THREAD

**Issue by evanw** [terser/terser#787]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V` or specific git commit)** 5.1.0

**Complete CLI command or `minify()` options used** `terser spread-in.js -c`

**`terser` input**

This bug report contains three independent input files for three separate but related bugs:

```js
// array-spread-in.js
let x = [...[,]]
let y = [,]
console.log(0 in x, 0 in y)
```

```js
// call-spread-in.js
let x = (a, b) => [a, b]
let y = x(...[,], 1)
console.log(...y)
```

```js
// object-spread-in.js
let x = { ...{ get x() { return 1 } } }
let y = { ...{ set y(_) { console.log(_) } } }
console.log(x.x, y.y, x.x = 2, y.y = 3, x.x, y.y)
```

**`terser` output or error**

```js
// array-spread-terser.js
let x=[,],y=[,];console.log(0 in x,0 in y);
```

```js
// call-spread-terser.js
let x=(a,b)=>[a,b],y=x(,1);console.log(...y);
```

```js
// object-spread-terser.js
let x={get x(){return 1}},y={set y(_){console.log(_)}};console.log(x.x,y.y,x.x=2,y.y=3,x.x,y.y);
```

**Expected result**

```js
// array-spread-expected.js
let x=[void 0],y=[,];console.log(0 in x,0 in y);
```

Running `array-spread-in.js` with node prints `true false` but running `array-spread-terser.js` with node prints `false false`, which is incorrect.

```js
// call-spread-expected.js
let x=(a,b)=>[a,b],y=x(void 0,1);console.log(...y);
```

Running `call-spread-in.js` with node prints `undefined 1` but `call-spread-terser.js` contains a syntax error and cannot be run.

```js
// object-spread-expected.js
let x={...{get x(){return 1}}},y={...{set y(_){console.log(_)}}};console.log(x.x,y.y,x.x=2,y.y=3,x.x,y.y);
```

Running `object-spread-in.js` with node prints `1 undefined 2 3 2 3` but running `object-spread-terser.js` with node prints in `3 1 undefined 2 3 1 undefined`, which is incorrect.

I recently came across #224 and it seemed like a nice feature, so I'm adding it to esbuild. But when writing tests, I realized that holes in inlined arrays are supposed to become undefined non-holes in the parent expression. I also realized that getter and setter methods are evaluated at iteration time inside the spread operator instead of having their property descriptors copied into the parent object.

**Comment by fabiosantoscode** [comment]
Very interesting bugs, thanks for letting me know!

I'm thinking that the easiest thing to do is to bail out when these more complicated cases come in.

As the body of features in ES increases, it's going to be harder and harder to deal with all kinds of constructs simultaneously.
