### ISSUE TITLE
Object literal shorthand aware renaming

### ISSUE THREAD

**Issue by justinfagnani** [terser/terser#803]
**Bug report or Feature request?**

Feature request

It would save a few bytes to be able to take advantage of object literal shorthand property names after renaming. If a variable is used as a literal's property value, it could be renamed to the property's key.

**`terser` input**

With a property mangle regex of `/^__/`:

```ts
const foo = 'abcdefghi'.split('');
const o = {
  __one: foo,
};
console.log(foo, o);
```

**`terser` output or error**

```ts
const y="abcdefghi".split("");console.log(y,{k:y});
```

**Expected result**

```ts
const k="abcdefghi".split("");console.log(k,{k});
```

**Comment by fabiosantoscode** [comment]
Hello there!

This is an old suggestion, but the byte savings are just too little for the difficulty of the implementation.

Right now, the variable name mangler already has to consider extremely weird scoping rules, and appease gzip :)
