### ISSUE TITLE
Critical: Incorrect optimization of equality checks of expressions with optional chaining and a constant

### ISSUE THREAD

**Issue by cbxp** [terser/terser#806]
**Bug report**

**Version 5.2.1**

**Complete CLI command or `minify()` options used**
`terser -c`

**`terser` input**

`typeof init?.body === 'string' ? init.body : JSON.stringify(init?.body)`

**`terser` output or error**

`JSON.stringify(init?.body);`

It seems that compression optimized out the typeof check if it contains optional chaining.
Without optional chaining the typeof check is left intact.

**Expected result**

`typeof init?.body==="string"?init.body:JSON.stringify(init?.body);`

If `-c` is not provided, then the result is correct

**Update:**

it seems that all equality checks of optional chaining with a constant are left out

**Comment by Druux** [comment]
Experiencing the same - looks like the types are resolved wrong.
Example:

```
function foo(options?: { bar: number }) {
     console.log(typeof options?.bar) // returns "object"
}
```

**Comment by fabiosantoscode** [comment]
I'm pushing a fix which will be released tomorrow. Thanks for bringing this up!

**Comment by angryziber** [comment]
Wow, that's a simple fix!
Maybe it would be a good idea to add a test case to avoid this repeating in future?

**Comment by fabiosantoscode** [comment]
It's a good idea, but it was late at the time :)
