### ISSUE TITLE
Produce incorrect code for named anonymous functions

### ISSUE THREAD

**Issue by maksimr** [terser/terser#807]
**Version (complete output of `terser -V` or specific git commit)**

5.2.1

**Complete CLI command or `minify()` options used**

```js
const {minify} = require('terser');
const vm = require('vm');

async function main() {
  const code = (await minify(`
    result = []
    function main() {
      var foo = function foo(it) {
         if(!foo[it]) {
           result.push(foo[it] = []);
         }
         return foo[it];
      };
      ['x', 'x'].forEach((it) => foo(it).push(it));
    };
    main();
    result;
  `)).code;
  console.log(vm.runInNewContext(code, {}));
}

main();
```

**`terser` input**

    result = []
    function main() {
      var foo = function foo(it) {
         if(!foo[it]) {
           result.push(foo[it] = []);
         }
         return foo[it];
      };
      ['x', 'x'].forEach((it) => foo(it).push(it));
    };
    main();
    result;

**`terser` output or error**

`[ [ 'x' ], [ 'x' ] ]`

Terser inline `foo` function in `forEach` that leads to the wrong behavior

**Expected result**

`[ [ 'x', 'x' ] ]`

About real-world example:
This is the common case if you use babel with `preset-env` where enabled transformation `babel-plugin-transform-function-name` by default
https://babeljs.io/docs/en/babel-plugin-transform-function-name

**Comment by fabiosantoscode** [comment]
Very interesting bug.

Thanks for letting me know!

**Comment by fabiosantoscode** [comment]
This is a twist on https://github.com/terser/terser/issues/407 because Terser is assuming functions aren't recreated every time.

**Comment by fabiosantoscode** [comment]
Managed to fix it in quite a simple way. The fix will be released tomorrow.

**Comment by maksimr** [comment]
@fabiosantoscode awesome! Thanks a lot
