### ISSUE TITLE
It does not compress or mangle HTML spaces inside JS 

### ISSUE THREAD

**Issue by francogp** [terser/terser#813]
**Bug report or Feature request?**

may be its a feature or a bug

**Version (complete output of `terser -V` or specific git commit)**

terser 5.0.0

**Complete CLI command or `minify()` options used**

  terser --compress drop_console=true,passes=2 --mangle -- "input.js" >"output.min.js" 

**`terser` input**
```
function loginDialog() {
    acceptDialog(`<form id="webLoginForm" class="needs-validation" novalidate>
                        <div class="modal-header text-center">
                            <p class="modal-title w-100 font-weight-bold h4">Ingrese sus credenciales</p>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>`);
}
```
**`terser` output or error**
```
function loginDialog(){acceptDialog('<form id="webLoginForm" class="needs-validation" novalidate>\n                        <div class="modal-header text-center">\n                            <p class="modal-title w-100 font-weight-bold h4">Ingrese sus credenciales</p>\n                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n                                <span aria-hidden="true">&times;</span>\n                            </button>\n                        </div>`);
```
**Expected result**
```
function loginDialog(){acceptDialog('<form id="webLoginForm" class="needs-validation" novalidate><div class="modal-header text-center"><p class="modal-title w-100 font-weight-bold h4">Ingrese sus credenciales</p><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>`);
```

**Comment by Conduitry** [comment]
I have no idea why you would expect this a JS minifier to behave this way.

**Comment by francogp** [comment]
because some benchmark state: "your min files are not minified enough"

**Comment by fabiosantoscode** [comment]
@francogp this is a use case that is kind of in the same space as Terser, but is already fulfilled by tools like [this babel plugin](https://github.com/cfware/babel-plugin-template-html-minifier).

Besides minifying, it's also important to make sure tree shaking is working correctly, and also code splitting (per-route, per-section or whatever makes sense for your use case). A lot of unused code makes its way into production if you're not looking. 

If you're using webpack a tool like [this](https://www.npmjs.com/package/webpack-bundle-analyzer) can help you visualize where the heavy parts are. Once I found out three versions of a heavy library being used in my bundle. You, too, might have imported something that's heavier than it seemed at first.

Of course, if your bundle isn't big enough, maybe it's not a good use of your time to look into those things.
