### ISSUE TITLE
Consumption of reflow-forcing statements

### ISSUE THREAD

**Issue by Lucent** [terser/terser#820]
In JavaScript, statements that force an interruption and reflow of the document by measuring some property, even if not assigned to any variable, can have real effects. For example:

    document.getElementById("Node").style.display = "none";
    document.getElementById("Node").offsetWidth;
    document.getElementById("Node").style.display = "initial";

Without the middle statement, which terser removes, #Node's display will be set to `initial`. However, if there are CSS transitions set, the middle statement will force the transitions to display.

Here's a comprehensive list of statements that, when removed, will alter the meaning and interpretation of code:
https://gist.github.com/paulirish/5d52fb081b3570c81e3a

I could not find an option in terser that would leave this statement intact. I tried `defaults: false` and `dead_code: false`.

**Comment by fabiosantoscode** [comment]
Hello there!

I can't reproduce this issue. 

With the `--toplevel` option (which needs to be enabled to remove stuff) I get the following:

```javascript
document.getElementById("Node").style.display = "none", document.getElementById("Node").offsetWidth, 
document.getElementById("Node").style.display = "initial";
```

If you enable the `pure_getters` compress option, Terser will indeed remove `.offsetWidth` there, but not the statement.

Could you please elaborate on a specific way to reproduce this? Thanks :)

**Comment by Lucent** [comment]
I believe this was my error in leaving tree shaking on in rollup itself.
