### ISSUE TITLE
Possible slow-down of terser in recent verions

### ISSUE THREAD

**Issue by lucamug** [terser/terser#821]
While upgrading terser I noted a sharp increase in the time that terser take to run.

Specifically between v.4.6.10 and v.4.6.11 (from 42 seconds to 279 seconds).

This is how I run terser:

```
terser elm.js --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=elm.min.js
```

These the details of performance in several terser versions:

```
terser@5.3.0
283 secs
552684 bytes

terser@4.6.13
273 secs
554738 bytes

terser@4.6.12
253 secs
554738 bytes

terser@4.6.11
279 secs
554738 bytes

terser@4.6.10
42 secs
554738 bytes

terser@4.6.4
48 secs
554711 bytes

terser@4.6.0
44 secs
554770 bytes

terser@4.5.1
45 secs
554770 bytes
```

**Comment by fabiosantoscode** [comment]
This is very interesting!

Is this `elm.js` file something you could share? I would love to run some performance tests to figure this slowdown out.

**Comment by lucamug** [comment]
@fabiosantoscode, here is the code, I added you as collaborator: https://github.com/lucamug/js-for-terser

I did some more test and I found something interesting. Not all files have the same drop in performances:

```
terser@4.6.11

elm0.js     17 secs
elm1.js     18 secs
elm2.js    261 secs

terser@4.6.10

elm0.js     12 secs
elm1.js     13 secs
elm2.js     12 secs
```

These are all compiled from the same Elm repository. The difference is that they have more or less features, but the Elm core code is the same.

It seems that the size of these file is not influencing this result, because `elm2.js`, the one that has the bigger issue, is not the bigger file.

```
2191213 bytes elm0.js
2540894 bytes elm1.js
2275377 bytes elm2.js
```

**Comment by fabiosantoscode** [comment]
Thank you!

I'll probably have a look tonight

**Comment by fabiosantoscode** [comment]
This is a real head scratcher :) I've narrowed this down to a very innocent looking line (in the part of the code optimizing binary operations). This is totally reproducible with 

When I remove a certain condition, not only elm2 compresses in 2 seconds (down from several minutes), but elm1's compress time goes down by 50%. There's a 1kb (~300b after gzip) increase however.

But this is just me fiddling with profiling. I won't rest until I get to the bottom of this, because there might be more slowdowns of the same type I'm not aware of.

**Comment by fabiosantoscode** [comment]
I think I got to the bottom of this :) 

Take a look at this simple code which takes roughly 16 seconds to compress:

```
(identifier +
  ("string" +
    (identifier +
      ("string" +
        (identifier +
          ("string" +
            (identifier +
              ("string" +
                (identifier +
                  ("string" +
                    (identifier +
                      ("string" +
                        (identifier +
                          ("string" +
                            (identifier +
                              ("string" +
                                (identifier +
                                  ("string" +
                                    (identifier +
                                      ("string" +
                                        (identifier +
                                          ("string" +
                                            (identifier + ("string" + identifier))
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)
```

As you remove items from the center of this huge expression, the compress time halves.

`(identifier + ("string" + identifier))` in the middle takes 16

`(identifier + "string")` takes 8

`identifier` takes 4

And you can continue unraveling outward and have the same effect.

--------

Just thought this was cute.

I'm looking into how to avoid this slowdown right now.

**Comment by fabiosantoscode** [comment]
This was a simpler fix than I originally thought. It involved a lot of self-recursion. I plugged this instance of it and looked for others as well.

I'll release this fix tomorrow.

**Comment by lucamug** [comment]
Thank you for the great work!
💯
