### ISSUE TITLE
Not working if code contains Optional Chaining Operator

### ISSUE THREAD

**Issue by sankarkumar23** [terser/terser#830]
Looks like javascript's Optional Chaining Operator "?." has not been incorporated.
Giving out error if code contains "?."
Appreciate if this can be fixed ASAP.

**Comment by Conduitry** [comment]
This is already supported as of v5.2.0.

**Comment by sankarkumar23** [comment]
Then it should be a bug...
here is the error screen shot..
<img width="345" alt="MinifyError" src="https://user-images.githubusercontent.com/12550023/93719345-9e947280-fb47-11ea-9119-4f12fbc1b73e.PNG">
<img width="259" alt="MinifyError2" src="https://user-images.githubusercontent.com/12550023/93719349-a3f1bd00-fb47-11ea-8123-ed9d0cdab4e9.PNG">

If I replace '?.' with '.' it's working fine. Please advice.
I am using MinifyAll v2.4.5 in VS Code

**Comment by mischnic** [comment]
That plugin will need to update to Terser 5: https://github.com/Josee9988/MinifyAll/blob/8a350fb1c45b981e1f41cf8bc3b0fb71dc3e2927/package.json#L263

**Comment by sankarkumar23** [comment]
Thanks a bunch for quick reply.

**Comment by tommedema** [comment]
Using terser 5 (default options) this:

```
document.querySelector('#i-may-not-exist')?.classList.remove('nav-pill-active')
```

we're getting:

```
[!] (plugin terser) SyntaxError: Unexpected token: punc (.)
```
