### ISSUE TITLE
--mangle-props regex=/^_/  is selecting all props with '_' (not only the ones with  '_' as FIRST character)

### ISSUE THREAD

**Issue by JLBab** [terser/terser#831]
** Bug report**

> terser -V => terser 5.3.2

**Complete CLI command or `minify()` options used**
> terser tersertest.js  -c    --mangle-props regex=/^_/   -o temp.js --name-cache cache.json

**`terser` input**

    let myobject = {
        _myprop1: [],
        myprop_2: 0,
        myprop3_: [],
        my_prop4: function(i) {
            this._myprop1[i] = 2*i;
        },
        myprop5: function(arg) {
            this.myprop_2 = arg;
        },
    };

**`terser` output or error**

As you can see in cache.json, all props with _ in their name (wherever it is) is uglified :
> {"vars":{"props":{}},"props":{"props":{"$_myprop1":"p","$myprop_2":"o","$myprop3_":"m","$my_prop4":"t"}}}

**Expected result**
Only _myprop1 should have been modified !!

**Comment by bbabic** [comment]
This is most likely likned with [issue-829](https://github.com/terser/terser/issues/829#issuecomment-694725218).
Try not to use regex delimiters, i.e. pass **^_** instead of **/^_/**.

**Comment by JLBab** [comment]
I tested as well without delimiters : 

terser tersertest.js -c --mangle-props regex=^_  -o temp.js --name-cache cache.json

but it provides exactly the same issue.

**Comment by bbabic** [comment]
Indeed, this is not linked with before mentioned issue. Problem here is probably in your console and node envoronment.
Widows console does not like **^** character so you have to "escape it" by writing **^^**. In case of terser's regex values, this needs to be escaped again, so your regex value should be set to **/^^^^_/**.

Example:
create file argv.js with following content:
`console.log(process.argv);`

Then, run it like this:
`node argv.js thos^does^not^work this^^works`

Output will be something like:
```
[
  ...
  ...
  'thosdoesnotwork',
  'this^works'
]

```

**Comment by JLBab** [comment]
Great findings!
I should have tried in linux !  The issue is ONLY on WINDOWS with escape characters ^ required!

So you are right : the correct syntax on WINDOWS is 👍 

> terser tersertest.js -c --mangle-props regex=/^^^^_/ -o temp.js --name-cache cache.json

**Comment by fabiosantoscode** [comment]
Very interesting.

Can't you do something like `"regex=/^_/"` on windows to avoid escaping the ^?

Anyway this seems like a windows specific issue and stuff, so I'm closing :)
