### ISSUE TITLE
Dropping function without warning if declared after 'continue' 

### ISSUE THREAD

**Issue by denyaalt** [terser/terser#833]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 5.3.2

**Complete CLI command or `minify()` options used**
```
{
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**
```
var a=1,object={};
for(var p in object) {
  if(a) {
    test(); continue; 
    function test() {alert(1)}
  }
}
```

**`terser` output or error**
`var a=1,object={};for(var p in object)a&&test();`
Dropping function without warning

**Expected result**
`var a=1,object={};for(var p in object)if(a){function test(){alert(1)}test()}else;`

**Comment by fabiosantoscode** [comment]
Very interesting! Thanks for reporting this.

**Comment by fabiosantoscode** [comment]
Turns out it's the `if_return` option acting up.

**Comment by fabiosantoscode** [comment]
I've tried multiple times to fix this and it's trickier to figure out a nice fix than I thought :)
