### ISSUE TITLE
Extend TypeScript definition for MinifyOptions to include output and output.comments

### ISSUE THREAD

**Issue by dilyanpalauzov** [terser/terser#835]
Please include in the current TypeScript [definitions](https://github.com/terser/terser/blob/master/tools/terser.d.ts):
```TypeScript
export interface MinifyOptions {
    compress?: boolean | CompressOptions;
    ecma?: ECMA;
    ie8?: boolean;
    keep_classnames?: boolean | RegExp;
    keep_fnames?: boolean | RegExp;
    mangle?: boolean | MangleOptions;
    module?: boolean;
    nameCache?: object;
    format?: FormatOptions;
    parse?: ParseOptions;
    safari10?: boolean;
    sourceMap?: boolean | SourceMapOptions;
    toplevel?: boolean;
}
```
the elements `output` and `output.comments`.

**Comment by fabiosantoscode** [comment]
Hey there!

These are now known as [format options](https://github.com/terser/terser#format-options)

`MinifyOptions` already has a `format` property. `output` is still supported but deprecated, so it's not included in the typedef.

**Comment by dilyanpalauzov** [comment]
I use rollup-plugin-terser.  It suggests the syntax 
```javascript
rollup-plugin-terser({
  'output': {
    'comments': "RegEx",
  },
});
```
Do you mean, that instead of output, I shall use some 'format'?

**Comment by bennypowers** [comment]
Closing as irrelevant. Thanks!

**Comment by bennypowers** [comment]
Typescript 4 supports the `@deprecated` jsdoc tag. Would you consider adding it?

**Comment by fabiosantoscode** [comment]
@bennypowers I did not know about that, it seems like a great addition

**Comment by bennypowers** [comment]
Please see #836
