### ISSUE TITLE
[BUG] Minifying returns the wrong value

### ISSUE THREAD

**Issue by Le0Developer** [terser/terser#838]
**Bug report or Feature request?**

After minifying another unrelated value is added to the return statement.

**Version**

terser 5.3.2

**Complete CLI command or `minify()` options used**

Default.
```coffee
minified = await terser.minify js_code
``` 
Working with default options on https://try.terser.org/

**`terser` input**
```js
uielement_wrapper = function(func) {
  return function(name) {
    func(name);
    return new Reference("Misc", "JAVASCRIPT", "Script Items", name);
  };
};
```

**`terser` output or error**

```js
uielement_wrapper=function(e){return function(n){return e(n),new Reference("Misc","JAVASCRIPT","Script Items",n)}};
```
Prettified:
```js
uielement_wrapper = function (e) {
    return function (n) {
        return e(n),
        new Reference("Misc", "JAVASCRIPT", "Script Items", n)
    }
};
```

**Expected result**

Without returning the `e(n)`.

```js
uielement_wrapper=function(e){return function(n){e(n);return new Reference("Misc","JAVASCRIPT","Script Items",n)}};
```
Prettified:
```js
uielement_wrapper = function (e) {
    return function (n) {
        e(n);
        return new Reference("Misc", "JAVASCRIPT", "Script Items", n)
    }
}
```

**Comment by fabiosantoscode** [comment]
The output code is equivalent to the input code.

`return a(), b()` evaluates a(), then returns b(). a() is not returned. That's just how the comma operator works.

If you wish to disable this feature, set the sequences compress option to false, but your output size will probably increase.
