### ISSUE TITLE
Optional chaining interferes with property mangling

### ISSUE THREAD

**Issue by Kruithne** [terser/terser#846]
**Bug report or Feature request?**
Bug report.

**Version (complete output of `terser -V` or specific git commit)**
v5.3.4

**Complete CLI command or `minify()` options used**

```
{
	toplevel: true,
	compress: {
		unsafe: true,
	},
	mangle: {
		properties: {
			regex: /^_/,
		}
	}
}
```

**`terser` input**

```
class TestClass {
	constructor() {
		this._testMap = new Map();
	}

	_testFunction() {
		const test = this._testMap?.get(42);
		console.log(test);
	}
}

const test = new TestClass();
test._testFunction();
```

**`terser` output or error**

`(new class{constructor(){this.o=new Map}t(){const s=this._testMap?.get(42);console.log(s)}}).t();`

**Expected result**

`(new class{constructor(){this.o=new Map}t(){const s=this.o?.get(42);console.log(s)}}).t();`

**Comment by tchetwin** [comment]
You can actually get at this bug using only this configuration:

```
{
	mangle: {
		properties: {
			regex: /^_/,
		}
	}
}
```

Output:

```js
class TestClass{constructor(){this.t=new Map}o(){const s=this._testMap?.get(42);console.log(s)}}const test=new TestClass;test.o();
```

Expected:

```js
class TestClass{constructor(){this.t=new Map}o(){const s=this.t?.get(42);console.log(s)}}const test=new TestClass;test.o();
```

**Comment by Kruithne** [comment]
Yep, this is just related to property mangling. Apologies, I forgot to clear out the unnecessary options from my test.

**Comment by fabiosantoscode** [comment]
Should be a simple fix!
