### ISSUE TITLE
Issue #175 is back

### ISSUE THREAD

**Issue by MichaelRFox** [terser/terser#847]
**Bug report**

Closed issue #175, *code generates "undefined"* has returned. terser(code).code returns undefined on all JavaScript files (see reproducible code below). Rolled back to v4.9.0 and terser works as expected. The bug seems to have returned with terser v5.0.0 and later.

Great tool BTW...use it for everything!

**terser 5.0.0 and greater**
**node v10.15.3**

**Complete CLI command or `minify()` options used**

terser-dir.js
```    
var Terser = require('terser');
var fs = require('fs');
var path = require('path');

function getAllFiles(dirPath, arrayOfFiles) {
  
  var files = fs.readdirSync(dirPath);
  arrayOfFiles = arrayOfFiles || [];

  files.forEach(function(file) {
    if (fs.statSync(dirPath + '/' + file).isDirectory()) {
      arrayOfFiles = getAllFiles(dirPath + '/' + file, arrayOfFiles);
    } else {
      arrayOfFiles.push(path.join(__dirname, dirPath, '/', file));
    };
  });

  return arrayOfFiles.filter(path => path.match(/\.js$/));
}

function minifyFiles(filePaths) {
    var options = {mangle: false, compress: false, output: {beautify: true, quote_style: 1}};
    filePaths.forEach(function(filePath) {
        console.log('compressing ', filePath);
        var code = fs.readFileSync(filePath, 'utf8');
        var result = Terser.minify(code, options);
        fs.writeFileSync(filePath, result.code);
  });
}

const files = getAllFiles('./src');
minifyFiles(files);
```

**`terser` output or error**

*undefined*

**Expected result**

*minified code*

**Comment by Kruithne** [comment]
Hey,

This isn't a bug with Terser. `Terser.minify` now returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), so `result.code` will never equal anything.

You need to wait for the promise to resolve either by attaching a callback with [`.then()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) or using `await` in an async function block. I've posted examples of both below.

```
// Option A: Attach a callback handler.
Terser.minify(...).then(res => {
	// Do something with the `res.code` here.
}).catch(err => {
	// Something went wrong, handle `err` here.
});

// Option B: Await the result in an async flow.
async function myFunction() {
	try {
		const res = await Terser.minify(...);
		// Do something with `res.code` here.
	} catch (err) {
		// Something went wrong, handle `err` here.
	}
}
```

**Comment by MichaelRFox** [comment]
Thank you for the clarification. Note that the documentation at https://terser.org/docs/api-reference may need to be updated then.

**Comment by fabiosantoscode** [comment]
The docs need to be updated indeed.

I've been putting off doing this because I think I'm going to write something to do it automatically, but I never do.

**Comment by fabiosantoscode** [comment]
It's updated! I also added a small script to the website to grab sections of the README and place them on the website's pages
