### ISSUE TITLE
logical OR assignment & optional chaining support

### ISSUE THREAD

**Issue by onuryarar** [terser/terser#850]
I minify files with .js extension with _gulp-uglify-es_ but I get some syntax errors.

I opened the issues to ["gulp-uglify-es" repository](https://gitlab.com/itayronen/gulp-uglify-es) and was told the problem was caused by this package.

I'm getting errors like:

```shell
[15:11:57] SyntaxError in plugin "gulp-uglify-es"
Message:
    Unexpected token: operator (=)
Details:
    filename: IncomingList\controller\PartialAcceptDialog.controller.js
    line: 27
    col: 40
    pos: 1247
    domainEmitter: [object Object]
    domainThrown: false
```

I am doing [logical OR assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment) and it fails here.

*PartialAcceptDialog.controller.js:26-28*
```javascript
if (key.indexOf("Quantity") > 0) {
        item[key] ||= {}
}
```

and other error:

```shell
[16:02:32] SyntaxError in plugin "gulp-uglify-es"
Message:
    Unexpected token: punc (.)
Details:
    filename: VariantTable.js
    line: 32
    col: 61
    pos: 1082
    domainEmitter: [object Object]
    domainThrown: false
```

I am doing [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and it fails here.

*VariantTable.js:32*

```javascript
var sPath = item.getBindingContext()?.getPath() || null
```

**Comment by fabiosantoscode** [comment]
Logical assignment is a work in progress, and hasn't been shipped yet.

To use optional chaining you should try to update Terser. The latest versions support it (starting with 5.2.0), but gulp-uglify-es has pinned 4.x.x. The API changed so forcing a new version is probably not going to work.

**Comment by snoack** [comment]
Any update on progress with logical assignment?

**Comment by fabiosantoscode** [comment]
Logical assignment has been implemented quite a while ago. In the latest Terser 5.x it should just work.
