### ISSUE TITLE
Bug: compress and inline ES6+ code outputs "const a=a" or stalls

### ISSUE THREAD

**Issue by dr-js** [terser/terser#851]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

`terser 5.3.5` with `nodejs@14.13.1` on Linux

**Complete CLI command or `minify()` options used**

~~This command output wrong result: `npx terser --compress --ecma 6 test.js -o test-out.js`.
And without `--ecma 6` process stall and never end: `npx terser --compress test.js -o test-out.js`.~~(incorrect argument order)
~~Using which ecma seems not matter much as I also tried `8` and `2020`.~~

This command output wrong result: `npx terser test.js -o test-out.js --compress`.

And change the problematic assignment to `const { WEBLOG_GENERATE_MARKDOWN: ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN } = ACTION_TYPE;` can avoid the issue.

**`terser` input**

`test.js` (reduced webpack output)
```js
  (() => {
    "use strict";

// CONCATENATED MODULE: ./source/module/ActionJSON/weblog.js
    const WEBLOG_GENERATE_MARKDOWN = 'weblog.generate-markdown';
    const ACTION_TYPE = {
      WEBLOG_GENERATE_MARKDOWN
    };

// CONCATENATED MODULE: ./source/server/feature/Weblog/setup.js
    const Weblog_setup_setup = async ({
      featureActionJSON: {
        actionMap,
        URL_ACTION_JSON_ABBR
      }
    }) => {
      const ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN = ACTION_TYPE.WEBLOG_GENERATE_MARKDOWN; // NOTE: this line is the problem!
      if (!actionMap[ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN]) throw new Error(`expect ActionJSON provide: ${ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN}`);
    };

// add function call so code do not get dropped
    Weblog_setup_setup();
  })();
```

**`terser` output or error**

`test-out.js`
```js
(()=>{"use strict";const ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN="weblog.generate-markdown";(async({featureActionJSON:{actionMap,URL_ACTION_JSON_ABBR}})=>{const ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN=ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN;if(!actionMap[ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN])throw new Error("expect ActionJSON provide: "+ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN)})()})();
```

**Expected result**

Should not output `const ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN=ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN` like `const a=a`, or stall otherwise.

**Comment by fabiosantoscode** [comment]
The stalling is related to argument order :)

You should add the files first, and options after, like `terser file.js --compress --mangle`

I don't understand what you mean by `const a=a` here. If you mean that you'd like to turn variable names into single-letter, you simply pass `--mangle`.

**Comment by dr-js** [comment]
Yes, the stalling is caused by argument only, sorry about that.

The problem is essentially:
```diff
- const ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN=ACTION_TYPE.WEBLOG_GENERATE_MARKDOWN; // input
+ const ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN=ACTION_TYPE_WEBLOG_GENERATE_MARKDOWN; // output
                                                        ! here the "." changed to "_"
```

And further reducing the `test.js` code:
```js
(() => {
  const CCC = 'some-name'
  const BBB = { CCC }
  // const BBB = { CCC: 'some-name' } // NOTE: using this will result the same

  const main = () => {
    const BBB_CCC = BBB.CCC // NOTE: this line is the problem!
    console.log(BBB_CCC)
    // const AAA_BBB_CCC = BBB.CCC // NOTE: change to this will avoid the bug
    // console.log(AAA_BBB_CCC)
  }

  main()
})()
```

The output and expected: (with `npx terser test.js -o test-out.js --compress`)
```diff
- (()=>{const BBB_CCC="some-name";(()=>{const BBB_CCC=BBB_CCC;console.log(BBB_CCC)})()})(); // will get "ReferenceError: Cannot access 'BBB_CCC' before initialization"
+ (()=>{const BBB_CCC="some-name";(()=>{const AAA_AAA=BBB_CCC;console.log(AAA_AAA)})()})(); // expect a different naming
```

I think the bug is naming related, and during compress same name from different scope got mixed up somehow.

And sorry about the confusion.
The `const a=a` is the typical mangled output, and it'd be a runtime error if left in code, I dropped the `--mangle` option since the code is already wrong after compress.

**Comment by fabiosantoscode** [comment]
Hey there!

Thanks for the clarification!

I'm not at my PC right now but I think disabling the hoist_props compress option is the workaround here. This option is responsible for turning the `.` into `_` and ditching the corresponding object.

**Comment by dr-js** [comment]
Glad to help!

Currently I'm using the `const { CCC: BBB_CCC } = BBB` style to avoid the bug, guess disable `hoist_props` will work, too.
