### ISSUE TITLE
sourceMap: true produces error in 5.0.0 as webpack plugin

### ISSUE THREAD

**Issue by renefournier** [terser/terser#852]
Terser 5.0.0 (from 4.0.0) breaks when webpack.config.json is configured:

```
  optimization: {
    minimizer: [
      new TerserPlugin({
        sourceMap: true,
      }),
    ],
  },

```
...and when `npm run dev` we get:

```
ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, parallel?, minify?, terserOptions?, extractComments? }
    at validate (/Users/rene/Sites/_sandbox/__WHQ-MEPS/avt-dubbleyou/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)

```

This is in a Framework7 fresh install/build.

**Comment by Conduitry** [comment]
That stack trace indicates that it's [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin) complaining about the option, not Terser. Their [changelog](https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/CHANGELOG.md#500-2020-10-14) indicates that this is an expected breaking change in version 5.

**Comment by renefournier** [comment]
Oh right, my bad. Noted!
