### ISSUE TITLE
Fail logical nullish assignment (??=) support

### ISSUE THREAD

**Issue by fedetango** [terser/terser#853]
**Bug report or Feature request?**
Bug report

**Version (complete output of terser -V or specific git commit)**
npm Version 5.3.5

** Complete CLI command or minify() options used **
`minify(code, {ecma:2020})`

**terser input**
`var a = 50;`
`a ??= 200;`

**terser output or error**
`JS_Parse_Error [SyntaxError]: Unexpected token: operator (=)`

 **Expected result**
`var a = 50; a ??= 200`

The nullish logical assignment operator seems to be not supported.

**Comment by fabiosantoscode** [comment]
Correct. Logical assignment is still not supported

**Comment by fabiosantoscode** [comment]
To clarify, it's a work in progress

**Comment by fabiosantoscode** [comment]
Closed in 5907df8941dcfa4b52dfd588331483923795cd1f. Will be released soon
