### ISSUE TITLE
Incorrect engines syntax in 5.3.6

### ISSUE THREAD

**Issue by maxdavidson** [terser/terser#854]
**Bug report**

The installation fails when installing 5.3.6

Yarn 1.22.5:
```
error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "14.13.1"
```

The correct semver syntax should be `^10.0.0 || ^11.0.0 || ^12.0.0 || >=14.0.0`

**Comment by AndKiel** [comment]
Also breaks on node v 12.18.3:

> error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "12.18.3"

**Comment by sionzeecz** [comment]
I was just updating packages on production and it failed 🙈 
This must be released ASAP.

**Comment by maxdavidson** [comment]
A temporary workaround for Yarn is to install with `yarn --ignore-engines`

**Comment by ollwenjones** [comment]
@maxdavidson or anyone able to explain the how/why here? I thought one of the main points of the `yarn.lock` file was that installs are deterministic because we are getting the same versions every time... so how does a breaking upgrade like this sneak in?

**Comment by maxdavidson** [comment]
Another temporary solution is to manually modify yarn.lock to resolve terser to 5.3.5:
```
terser@^5.3.5:
  version "5.3.5"
  resolved "https://registry.npmjs.org/terser/-/terser-5.3.5.tgz#9e080baa0568f96654621b20eb9effa440b1484e"
  integrity sha512-Qw3CZAMmmfU824AoGKalx+riwocSI5Cs0PoGp9RdSLfmxkmJgyBxqLBP/isDNtFyhHnitikvRMZzyVgeq+U+Tg==
  dependencies:
    commander "^2.20.0"
    source-map "~0.7.2"
    source-map-support "~0.5.19"
```

**Comment by ollwenjones** [comment]
@maxdavidson yeah... I got lazy about locking deps in package.json because of yarn.lock... to my knowledge, no one here has upgrade anything, though. maybe that integrity sha isn't doing what I thought it did? I thought it was a content sha.

**Comment by ccambournac** [comment]
> Another temporary solution is to manually modify yarn.lock to resolve terser to 5.3.5:
> 
> ```
> terser@^5.3.5:
>   version "5.3.5"
>   resolved "https://registry.npmjs.org/terser/-/terser-5.3.5.tgz#9e080baa0568f96654621b20eb9effa440b1484e"
>   integrity sha512-Qw3CZAMmmfU824AoGKalx+riwocSI5Cs0PoGp9RdSLfmxkmJgyBxqLBP/isDNtFyhHnitikvRMZzyVgeq+U+Tg==
>   dependencies:
>     commander "^2.20.0"
>     source-map "~0.7.2"
>     source-map-support "~0.5.19"
> ```

With `yarn`, use the [resolutions' package.json field](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) for that:
```
"devDependencies" : {
...
	"terser": "5.3.5"
...
},
"resolutions": {
	"terser": "5.3.5"
}

**Comment by fabiosantoscode** [comment]
v5.3.7 has been released, if it's still not working, let me know.

**Comment by melnikovic** [comment]
Please also publish it on npm

**Comment by fabiosantoscode** [comment]
@melnikovic you might be experiencing some cache issues, it should be released by now.
