### ISSUE TITLE
5.3.6 breaks compatibility with Node v12 and older

### ISSUE THREAD

**Issue by seppevs** [terser/terser#856]
Hi,

I'm not using terser directly myself, but it's an indirect dependency of a project I'm trying to build

I get this error when I try to install my project. I'm on Node v12.18.2

```
error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "12.18.2"
error Found incompatible module.
```

When I inspect the package.json file from terser@5.3.6, I notice this line:
```
  "engines": {
    "node": "^10.0.0,^11.0.0,^12.0.0,>=14.0.0"
  },
```

Apparantly this line was changed yesterday in [this commit](https://github.com/terser/terser/commit/2703fc8c48d5d680e980ee8faf9cc8fde5ca71d0).

I think this should be changed to:
```
  "engines": {
    "node": ">=10.0.0"
  },
```

Can you please fix this? I can make a PR if you want ..

**Comment by sionzeecz** [comment]
duplicated: https://github.com/terser/terser/issues/854

**Comment by Tengelberg** [comment]
Issue has been fixed in release 5.3.7

**Comment by fabiosantoscode** [comment]
This has been indeed fixed. Right now I'm trying to find out ways of stopping me from publishing a non-installable package. Any pointers would be helpful!

**Comment by dr-js** [comment]
The `npm publish` is actually `npm pack` that packs a `name-version.tgz` tarball, and then `npm publish name-version.tgz` to push to npm server.

@fabiosantoscode how about adding a CI step like this:
- run `npm pack` to get the tarball
- create mock package dir `mkdir test-install && cd test-install && npm init`
- run `npm install ../name-version.tgz` to test local install

**Comment by fabiosantoscode** [comment]
This is a good idea. I'll open an issue for it.

**Comment by KlausHans** [comment]
Why is v13 incomaptible? 
Got the error:
`error terser@5.3.7: The engine "node" is incompatible with this module. Expected version "^10.0.0 || ^11.0.0 || ^12.0.0 || >=14.0.0". Got "13.14.0"`

**Comment by fabiosantoscode** [comment]
Hi :) node 13 has a buggy ESM implementation. But there's an open PR to fix it that I'm about to merge and release.
