### ISSUE TITLE
Invalid node version

### ISSUE THREAD

**Issue by paleite** [terser/terser#858]
I couldn't install terser because of a version mismatch. I think the trailing comma after each version may be causing the issue:
https://github.com/terser/terser/blob/571fd998ddac312bae2e987aa622d49b11d6c97d/package.json#L9

I think it should be space-separated

**Comment by paleite** [comment]
https://github.com/terser/terser/pull/859

**Comment by tomaszs** [comment]
Same here:

```
error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "1
```

Installed version:

```
14.13.1
```

**Comment by harshitsilly** [comment]
same here

**Comment by LoaderB0T** [comment]
duplicate #854

**Comment by ycjcl868** [comment]
+1

**Comment by neverin882** [comment]
+1

**Comment by Nelosen** [comment]
+1

**Comment by CarlosAzocar** [comment]
+1

**Comment by dmoosocool** [comment]
+1
```
terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "13.13.0"
```
Installed version:

```
13.13.0 14.7.0 14.14.0 
```

**Comment by akryll** [comment]
+1 
`error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "12.19.0"`

**Comment by dolmira** [comment]
+1

**Comment by xsaliniere** [comment]
+1

**Comment by coderrorer** [comment]
+1

**Comment by s-dupuis** [comment]
+1
```
error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "14.14.0"
```

**Comment by anachronic** [comment]
[here's a temporary workaround](https://github.com/terser/terser/issues/854#issuecomment-712088865) for y'all

**Comment by jodybrewster** [comment]
> [here's a temporary workaround](https://github.com/terser/terser/issues/854#issuecomment-712088865) for y'all

That works, big thanks!

**Comment by ipeshev** [comment]
+1

**Comment by akryll** [comment]
> > [here's a temporary workaround](https://github.com/terser/terser/issues/854#issuecomment-712088865) for y'all
> 
> That works, big thanks!

Lol, screw this into my company's deployment with a wagon of approvals and signatures

**Comment by alxkat** [comment]
+1

**Comment by dev7ch** [comment]
+1000 ;)

**Comment by ollwenjones** [comment]
Anybody know why this happens when yarn.lock should be enforcing the same versions of everything? I wouldn't have expected to see this breakage unless someone at my org upgraded something on our project.

**Comment by mattvb91** [comment]
@ollwenjones yarn lock is only enforced if you use `yarn --frozen-lockfile` its not enabled by default

**Comment by ollwenjones** [comment]
@mattvb91 it is 100% enabled in our build scripts though. this got past it. unless it's the combination of `--frozen-lockfile` and `--force` ?

**Comment by mattvb91** [comment]
@ollwenjones puuuh not sure, we have also been struggling with both npm's and yarns locking mechanism for the past year

**Comment by ollwenjones** [comment]
@mattvb91 Looks like there's a known issue with `--frozen-lockfile` and `--force` flags at the same time.
https://github.com/yarnpkg/yarn/issues/5215 This is how it happened in our environment, in case anyone else hits the same thing.

**Comment by GThairi** [comment]
+1

**Comment by fabiosantoscode** [comment]
Hey there! This is now fixed in 5.3.7.

**Comment by sclausen** [comment]
> Hey there! This is now fixed in 5.3.7.

So it's correct, that 5.3.7 is incompatible with node 13?

**Comment by fabiosantoscode** [comment]
That is correct. Terser on node 13 works fine when require()d but it's not supported due to a large amount of ESM bugs stopping it from being imported.

**Comment by fabiosantoscode** [comment]
Hey there @ljharb!

If you can do it while maintaining support for the other versions, I would appreciate it!

**Comment by ljharb** [comment]
Absolutely; PR incoming.

**Comment by ljharb** [comment]
https://github.com/terser/terser/pull/861
