### ISSUE TITLE
incorrect minified template literals

### ISSUE THREAD

**Issue by tao-cumplido** [terser/terser#863]
**Bug report**

Template literals are possibly minfied to non-equivalent code. This happens when the template literal contains objects. In template literals `toString()` is called on the object but in string concatenation `valueOf()` is called. When an object has different implementations for both methods the resulting code is not equivalent. I noticed this with luxon's `DateTime` class which produces an ISO date-string with `toString()` but a miliseconds number since epoch with `valueOf()`.

For example
```js
const foo = { toString: () => 'foo', valueOf: () => 42 };
console.log(`${foo}`);
```

will log `"foo"` unminified but `"42"` with the minified `console.log(""+foo);`

**Version**
`terser 5.3.8`

**Complete CLI command or `minify()` options used**
none

**`terser` input**
```js
terser.minify("const foo = { toString: () => 'foo', valueOf: () => 42 };\nconsole.log(`${foo}`)")
```

**`terser` output**
```js
{code: "const foo={toString:()=>\"foo\",valueOf:()=>42};console.log(\"\"+foo);"}
```

**Expected result**
```js
{code: "const foo={toString:()=>\"foo\",valueOf:()=>42};console.log(`${foo}`);"}
```

**Comment by fabiosantoscode** [comment]
This is why people hate javascript :) 

Thanks for reporting this. It needs fixing.
