### ISSUE TITLE
 Error while bundling with webpack: 

### ISSUE THREAD

**Issue by kongaraju** [terser/terser#864]
**Bug report**

I am seeing an error while bundling my code with webpack.

**Version (complete output of `terser -V` or specific git commit)** 5.0.2

**`terser` output or error**

ERROR in [filename] from Terser
Invalid syntax: 3d [filename:114523,28]

**Expected result**

no errors

**Comment by fabiosantoscode** [comment]
Hello there!

You seem to have ignored the issue template and provided no way to reproduce, so I'm closing this.

**Comment by kongaraju** [comment]
My code is huge, and am not able to figure out from where issue is occurring.

Could you please at least give, when will the below error occurs.
**Invalid syntax: 3d**

**Comment by fabiosantoscode** [comment]
Is the string `3d` in your bundle, on line 114523? Is that valid syntax without experimental numbers?

Does this bundle run in the browser if you disable Terser?
