### ISSUE TITLE
Error when using sourceMap option in UMD version

### ISSUE THREAD

**Issue by stefandobre** [terser/terser#865]
**Bug report**

**Version 5.3.8**

Run the following on https://try.terser.org/

**`terser` options**
```
{
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
  sourceMap: true
}
```

**`terser` input**
`console.log(123);`

**`terser` output or error**
`Cannot read property 'SourceMapGenerator' of undefined`

**Comment by fabiosantoscode** [comment]
Thanks for reporting!

**Comment by fabiosantoscode** [comment]
It's fixed!

There's not much use in using source maps on the REPL, but it's there.

I'm also adding a jsdelivr example to the README.md to show how it can be loaded (inefficiently) using script tags.
