### ISSUE TITLE
base

### ISSUE THREAD

**Issue by pirquessa** [terser/terser#867]
**Bug report**

The type declaration for **`SourceMapOptions`** is missing the `base` attribute :(

It is supposed to be used for "_Path to compute relative paths from input files._" as I found in documentation.

See https://github.com/terser/terser/blob/master/tools/terser.d.ts#L160

**Version (complete output of `terser -V` or specific git commit)**

terser 5.3.8

**Complete CLI command or `minify()` options used**

**`terser` input**

```
minify(code, {
      sourceMap: {
        base: "My_Base_Path",
        filename: 'bundle-min.js',
        url: 'bundle-min.js.map',
        includeSources: true
      }
  })
```

**`terser` output or error**

```
error TS2322: Type '{ base: string; filename: string; url: string; includeSources: true; }' is not assignable to type 'boolean | SourceMapOptions | undefined'.
  Object literal may only specify known properties, and 'base' does not exist in type 'SourceMapOptions'.

64         base: config.rtvPath,
           ~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Expected result**
A working method that accept all available options :)

**Comment by fabiosantoscode** [comment]
Hello there!

Base is a CLI-only option, so it's not available in the minify API.

**Comment by pirquessa** [comment]
My bad :( Thx for the quick answer !
