### ISSUE TITLE
Feature request: replace multiple references of `null` with a variable to reduce output size

### ISSUE THREAD

**Issue by ivanhofer** [terser/terser#877]
If `null` values in a script exist, it would make sense to store the value `null` to a variable and replace all references with that variable. e.g.

```
const options = {
   a: null,
   b: null,
   c: null
}
```
would become
```
const _ = null
const options = {
   a: _,
   b: _,
   c: _
}
```

This would reduce the file-size by a few additional bytes.

**Comment by fabiosantoscode** [comment]
Hello there!

This has been brought up in the past. Not just null -- other constants can repeat themselves and code becomes larger.

But there's more to optimization than removing bytes. After gzip, things are often different (this is why the mangler doesn't create variables in alphabetical order), and there's a cost to parsing each token too.

Moreover, there's a maintenance cost in this project, which is already pretty hard to maintain as it is!
