### ISSUE TITLE
Optimize Array.join() string concatenation

### ISSUE THREAD

**Issue by fluidsonic** [terser/terser#883]
**Feature request**

It would be great if Terser could optimize `Array.join()`-based string concatenation.

Version: Whatever https://try.terser.org/ is using, with default options.

**`terser` input**

```js
var a = []
a.push("1")
if (a.length) // known to be true
  a.push(" ")
a.push("2")
console.log(a.join(""));
```

**`terser` output or error**

```js
var h=[];h.push("1"),h.length&&h.push(" "),h.push("2"),console.log(h.join(""));
```

**Expected result**

```js
console.log("1 2")
```

**Comment by fabiosantoscode** [comment]
Hey there!

The `unsafe` option provides some of this, but not all of it.

Terser doesn't feature flow analysis, so `.push` won't be inlined into a single array.

However this is compiled down to a single string with the `unsafe` option:

```
const x = ['a', 'b', 'c']

console.log(x.join(' ')) 
```

**Comment by fluidsonic** [comment]
Is it more complex to implement this for `Array.push/join` than already done for `+=` of String?

```js
const x = []
x.push('a')
x.push(' ')
x.push('b')
console.log(x.join(''))
```
-> `const o=[];o.push("a"),o.push(" "),o.push("b"),console.log(o.join(""));`

isn't so much different (flow-wise) from

```js
var x = ""
x += "a"
x += " "
x += "b"
console.log(x)
```
-> `console.log("a b");`

**Comment by fabiosantoscode** [comment]
Adding strings is a lot easier because strings are pure and safe in every sense. Terser follows the flow of a single function and keeps concatenating, top to bottom.

If this were to be done with arrays it would be one of the unsafe options, we'd have to check that the array was uninitialised, and people really don't use them
