### ISSUE TITLE
bug: when using keyword static as class filed, even in string

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#884]
**Bug report or Feature request?** But report

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

```js
class Foo { static }
```

```js
class Foo { 'static' }
```

**`terser` output or error**

error

**Expected result**

no error

**Comment by fabiosantoscode** [comment]
Can reproduce like this:

`class Foot { static = 'foo' }`

Terser doesn't support shorthand class fields yet.

**Comment by LongTengDao** [comment]
Supplement: these are ok:

```js
class Foo { static () {} }
```

```js
class Foo { 'static' () {} }
```

```js
class Foo { ['static'] = 'bar' }
```

```js
class Foo { ['static'] }
```

**Comment by fabiosantoscode** [comment]
Fixed in the meantime!
