### ISSUE TITLE
Bug with returning result of regexp

### ISSUE THREAD

**Issue by perf2k2** [terser/terser#885]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

5.5.1

**Complete CLI command or `minify()` options used**

With webpack:
```
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        extractComments: false,
      }),
      new CssMinimizerPlugin(),
    ],
  },
```

**`terser` input**

It's a part of axios library:
```
module.exports = function isAbsoluteURL(url) {
  // A URL is considered absolute if it begins with "<scheme>://" or "//" (protocol-relative URL).
  // RFC 3986 defines scheme name as a sequence of characters beginning with a letter and followed
  // by any combination of letters, digits, plus, period, or hyphen.
  return /^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(url);
};
```

**`terser` output or error**

```
t.exports=function(t){return/^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(t)}}
```
Devtools prints at Console: `Uncaught SyntaxError: Invalid regular expression: missing /`

**Expected result**

```
t.exports=function(t){return /^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(t)}}
```
After inserted space it works without errors.

**Comment by fabiosantoscode** [comment]
Hey there!

I can't reproduce this issue. What I see there is an extra `}` at the end, which Terser couldn't have created.

Could you provide some more context? Is this something that used to happen before 5.5.1? And what is the code around that causes that missing space to be problematic?

**Comment by perf2k2** [comment]
Hello! Sorry, i made a mistake when copied code. This is the correct:
```
406:t=>{"use strict";t.exports=function(t){return/^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(t)}},
```
I don't know how I can provide more information. I just created a webpack config and ran the build. And then I opened the page with the bundle, I received a message:

![image](https://user-images.githubusercontent.com/7932964/100700537-b9d4f700-33ae-11eb-8b97-074c30457360.png)

**Comment by perf2k2** [comment]
Sorry once again, it was my mistake - it's a bug within our backend assets compressor.
I think you may close this issue.
