### ISSUE TITLE
Variable used in func.call() as parameter is removed

### ISSUE THREAD

**Issue by mischnic** [terser/terser#888]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V` or specific git commit)** 5.5.1

**Complete CLI command or `minify()` options used** `terser --module -c`

**`terser` input**

```js
function Source(options) {
  console.log(options);
}

var something = {
  ready: "ready",
};

export var Vector = function () {
  Source.call(undefined, something.ready);
};
```

**`terser` output or error**
```js
function Source(options) {
  console.log(options);
}
export var Vector = function () {
  Source.call(void 0, something.ready);
};
```

**Expected result**

`something.ready` should be inlined or the variable should not be removed

**Comment by fabiosantoscode** [comment]
Appears to have been fixed in the meantime
