### ISSUE TITLE
More than one bracket with `new` giving wrong output

### ISSUE THREAD

**Issue by atfzl** [terser/terser#892]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
The version used in https://try.terser.org/

**Complete CLI command or `minify()` options used**
try on https://try.terser.org/

**`terser` input**
```js
new Foo()();
```

**`terser` output**
```js
(new Foo)();
```

**Expected result**
```js
(new Foo)()();
```

**Comment by Conduitry** [comment]
`new Foo()()` is a `CallExpression` where the callee is a `NewExpression`. This is the same as `(new Foo)()`.

`(new Foo)()()` is a `CallExpression` where the callee is another `CallExpression` where the callee is a `NewExpression`. This is a different expression.
