### ISSUE TITLE
Inlining of variables across block-scopes breaks the script

### ISSUE THREAD

**Issue by brandon942** [terser/terser#893]
**Bug report or Feature request?**
Bug
**Version (complete output of `terser -V` or specific git commit)**
5.5.1
**Complete CLI command or `minify()` options used**
minify()

**`terser` input**
```javascript
if(1) {
	var object = 1
	var object2 = 2
	let temp_variable= something() ? object2 : object
	{
		let object = temp_variable
		x(object)
		x(object)
	}
}
```
terser inlines `temp_variable` (default settings)

**`terser` output or error**
```javascript
{
	let object = something() ? object : object2 // throws if something() == true
	//...
}
```
Terser falsely assumed that `object` in the block-scope (declared with `let`) and outside is the same variable. 
As the conditional in the example shows, the error is not always easy to detect because an exception is thrown only on access of the uninitialized variable.

**Expected result**
```javascript
var temp_variable = something() ? object : object2
{
	let object = temp_variable
	//...
}
```
Edit: I changed the sample to be reproducible. The transform doesn't always happen like that.

**Comment by fabiosantoscode** [comment]
Hey there! Thanks for reporting this. Seems rather serious.

This can be avoided by enabling the `toplevel` option. If `var` isn't supposed to create a global variable for you this is a good workaround.

**Comment by fabiosantoscode** [comment]
Was fixed in the meantime
