### ISSUE TITLE
Top level await SyntaxError

### ISSUE THREAD

**Issue by wzh19960613** [terser/terser#903]
When I use a top level await just like:

```
\\\ index.js
await db.init()
```

It returns:

> SyntaxError: Unexpected await identifier inside strict mode

Can I keep going to use top level await by just turning this check off?

By the way I can't delete 'use strict' for some reasons.

**Comment by fabiosantoscode** [comment]
Terser doesn't support top level await. I'm implementing it right now.

The error you're getting is because before top level await was proposed, `await` was a reserved word when used in strict mode outside an async function.

**Comment by GarethOates** [comment]
I'm still seeing this error when I try to bundle my code. I have the following:

npm version 8.3.1
node version 17.4.0

 "rollup": "^2.3.4",
 "rollup-plugin-terser": "^7.0.2"

What do I need to do to get rid of this error?

**Comment by fabiosantoscode** [comment]
What's the version of Terser itself? I haven't checked rollup-plugin-terser but it may have pinned an older version.

If you run `npm ls terser` you can ascertain this

**Comment by GarethOates** [comment]
my.project.name@1.0.0 C:\Developer\
└─┬ rollup-plugin-terser@7.0.2
  └── terser@5.3.7

**Comment by jridgewell** [comment]
To at least [v5.6.0](https://github.com/terser/terser/blob/master/CHANGELOG.md#v560)

**Comment by caramboleyo** [comment]
With 5.16.1 I now get an “Unexpected token: name” after top level awaits.

**Comment by fabiosantoscode** [comment]
For future reference, because this may trip up future visitors to this issue:

Without strict mode (which module: true enables for you), `await` is a valid identifier in the top-level. For example `var await = 1` is possible without strict mode.

To avoid breaking code with `await`, Terser needs you to enable strict mode to disambiguate between that and a real top-level await.

**Comment by chase-moskal** [comment]
for extra clarity, hoping to help somebody else -- when i experienced this issue, i found two different ways to solve it:

1. as a workaround, i found i could wrap the expression after `await` in parens:

    ```js
    // broken
    await adapter.fetch_store_info()

    // fixed
    await (adapter.fetch_store_info())
      //  🡑                          🡑
      //  +                          +
    ```

2. or, even better, i could add `--module` as a command-line option to the `terser` command:

    ```sh
    # broken
    terser x/main.js --compress --mangle --source-map --comments false -o x/main.bundle.js

    # fixed
    terser x/main.js --module --compress --mangle --source-map --comments false -o x/main.bundle.js
      #                 🡑
      #                 +
    ```

**Comment by cnlohr** [comment]
I could not get await working with the extra parens.  It  does compile, but breaks in the browser.  Any idea what could be going on?  I'm on `terser 5.31.1`.  No parens yield `ERROR: Unexpected token: name`

**Comment by cnlohr** [comment]
Aaaahhhhh.  Wow, that's an unintuitive error.  I got the error because the function I was calling async in was not async.
