### ISSUE TITLE
Is it possible to get such a printout with Terser?

### ISSUE THREAD

**Issue by rendstack** [terser/terser#909]
I just started taking care of React. When I saw that Instagram was developed with react, I wanted to look at the source code, there is a similar encryption in bundle files.

`__d(function(g,r,i,a,m,e,d){ ... }`

Is it possible to do this with a terser or whatever? It looks different from the files react extracted for the production

**Comment by fabiosantoscode** [comment]
I've noticed this pattern in Facebook properties. I don't know what might generate it.

You can do something similar in Terser, by enabling mangling and passing a pre-built cache mapping your function names to the desired "encrypted" names.

The [API documentation](https://terser.org/docs/api-reference.html) specifies how one can extract a mangle cache object from the code. By following that format, you can place your own entries in this cache. Sadly the format isn't well documented.

**Comment by rendstack** [comment]
How can I do this with webpack? is there any example

**Comment by fabiosantoscode** [comment]
Not really. If what you're looking for is just to change how webpack organizes modules it's not really a question for me but my guess is that you can't do this.

What I was responding to, is how you would turn a set of known name functions into those prefixed with underscores.

**Comment by rendstack** [comment]
Yes, I want to do something like this, but in which file the configuration files mentioned here should be made, for example: terser.config.js ?  It does not write details and is confusing

**Comment by fabiosantoscode** [comment]
If you're using webpack what terser sees is already bundled in a specific format. And the configuration is through the TerserPlugin, in its terserOptions object.

If you're using terser directly (CLI or API) you can pass the mangle configuration through the second argument (API) or through command line arguments. Check out the readme for more details.
