### ISSUE TITLE
Minify on JavaScript doesn't work correctly

### ISSUE THREAD

**Issue by drodiger** [terser/terser#911]
# **🐞 Bug Report**

## **Describe the bug**

I am using MinifyAll extension for VS Code, which uses Terser to minify JavaScript.
If I minify following code:
```
function jsonPath(obj, expr, arg) {
    var P = {
        resultType: arg && arg.resultType || "VALUE",
        result: [],
        normalize: function (t) {
            var n = [];
            return "test"
        }
    }
}
```
this is translated on minify to:
`function jsonPath(n,t,e){e&&e.resultType}
`
Whole file is tagged as JavaScript document in VS Code.
This was reported to MinifyAll, but they said, I should report here as well.
[https://github.com/Josee9988/MinifyAll/issues/76](https://github.com/Josee9988/MinifyAll/issues/76)

### **Your environment**

* OS: Win 10
VS Code: 1.52.1 (user)
MinifyAll: 2.4.13
---

**Comment by fabiosantoscode** [comment]
Hello there!

The code is functionally equivalent to the input. 

P is an unused variable. `arg && arg.resultType` is an expression which may have side effects because of a possible impure getter.

If you do something like console.log(P) or return P, you will still see your object in the output.
