### ISSUE TITLE
npx error "cb.apply is not a function"

### ISSUE THREAD

**Issue by yairEO** [terser/terser#914]
Running this on a tiny project:

    npx terser -- foo.js > foo.min.js
    
Get this error:

    cb.apply is not a function
     
 For the sake of experiment, I've deleted the whole content of `foo.js` and still have this error.
 
### Spec:
<table>
<tr>
	<td>node 
	<td>v15.4.0
<tr>
	<td>npm 
	<td>7.0.15
<tr>
	<td>OS
	<td>Microsoft Windows [Version 10.0.18363.1316]
</table>

**Comment by fabiosantoscode** [comment]
Hey there! I cannot reproduce this on windows. `npx` with node 15.4 and npm 7 works as expected. Terser doesn't use callbacks and the string "cb.apply" is not in the project, so I don't think this is a Terser issue.
