### ISSUE TITLE
An edge case with invalid JS output

### ISSUE THREAD

**Issue by lewisl9029** [terser/terser#917]
**Bug report or feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**
5.5.1

**Complete CLI command or `minify()` options used**

(Copy pasted from webpack defaults: https://webpack.js.org/plugins/terser-webpack-plugin/#terseroptions)
```js
{
    ecma: undefined,
    parse: {},
    compress: {},
    mangle: true, // Note `mangle.properties` is `false` by default.
    module: false,
    // Deprecated
    output: null,
    format: null,
    toplevel: false,
    nameCache: null,
    ie8: false,
    keep_classnames: undefined,
    keep_fnames: false,
    safari10: false,
  }
```

**`terser` input**

```js
"use strict";

const a = {};

const fn = v => v;

if (a.b === "b") {
  var _a$c;

  const d = (_a$c = a.c) !== null && _a$c !== void 0 ? _a$c : "";
  const e = fn(d);
  const intervalId = setInterval(async () => {
    e(intervalId);
  }, 1000);
}
```

The above is a minimal repro I set up for a real bug we encountered in production. Based on a babel transpilation of the following source code:

```js
const a = {}
const fn = (v) => v
if (a.b === "b") {
  const d = a.c ?? "";
  const e = fn(d);

  const intervalId = setInterval(async () => {
    e(intervalId);
  }, 1000);
}
```

[playground link](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDA3gXwFCkrAZmJGACgDcBKJAPhhIwEtdi4A6AIyUWQCJWuKUMMGNmgwAJoRbAYAfhkwuXANyDh4UQFNC-ImLIrVI2HTBQNAJxJwANgEkJyCBqi3TFq9aJwIATzDSiCkRqASEhDSITM0sbe31VNAAaGABGAAYM-MwgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=)

This was about as minimal as I could make it while still repro'ing the issue. Probably a whole bunch of different contributing factors here.

Note that if we copy paste either of the above snippets and run them in a browser console, they should execute without errors.

**`terser` output or error**

```js
"use strict";const a={},fn=a=>a;var _a$c;if("b"===a.b)const e=null!==(_a$c=a.c)&&void 0!==_a$c?_a$c:"",intervalId=setInterval((async()=>{e(intervalId)}),1e3);
```

This is invalid JS due to the `if("b"===a.b)const` part (we can only omit braces when `if` is followed by an expression, but const is a statement). If we try to run the above we'll get an error like the following:
```
Uncaught SyntaxError: expected expression, got keyword 'const'
``` 

**Expected result**

If we add braces around the block like in the original source, it runs as expected:

```js
"use strict";const a={},fn=a=>a;var _a$c;if("b"===a.b){const e=null!==(_a$c=a.c)&&void 0!==_a$c?_a$c:"",intervalId=setInterval((async()=>{e(intervalId)}),1e3);};
```

Here's the script I used to repro for your convenience:

```js
const fs = require('fs')
const terser = require('terser')

terser.minify(`"use strict";

const a = {};

const fn = v => v;

if (a.b === "b") {
  var _a$c;

  const d = (_a$c = a.c) !== null && _a$c !== void 0 ? _a$c : "";
  const e = fn(d);
  const intervalId = setInterval(async () => {
    e(intervalId);
  }, 1000);
}`, {
    ecma: undefined,
    parse: {},
    compress: {},
    mangle: true, // Note `mangle.properties` is `false` by default.
    module: false,
    // Deprecated
    output: null,
    format: null,
    toplevel: false,
    nameCache: null,
    ie8: false,
    keep_classnames: undefined,
    keep_fnames: false,
    safari10: false,
  }).then((minified) => fs.writeFileSync('./test2.min.js', minified.code))
```

Let me know if there's any additional information we could provide that could help debug. Thanks!

**Comment by lewisl9029** [comment]
@fabiosantoscode would really appreciate your 👀 on this. This issue broke our entire app and took a while for us to debug and find the root cause, and isolate the minimal repro steps listed above. It could easily end up happening to other users as well.

A colleague did a bit of investigation and was able to nail down the line where we might need to apply the fix:

> https://github.com/terser/terser/blob/d51b6b9c22e8e8452a7ca0bb27b0f80b54b8d415/lib/output.js#L1499
> Might want to override the braces: true option here if the body is const or some other case that isn’t handled well

We'd also be happy to try to submit a PR if you have your hands full. Just let me know if that's what you'd prefer.

**Comment by fabiosantoscode** [comment]
Hello! This went under my radar.

Yes I would totally appreciate a PR. I had a look and the problem seems to be in this function:

force_statement

It's only used to print bodies that could be wrapped in braces, but it doesn't know that `const` and `let` need to have braces (maybe var definitions too, worth a check).
