### ISSUE TITLE
For/of mangling produces duplicated const names

### ISSUE THREAD

**Issue by TrySound** [terser/terser#921]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

terser 5.5.1

**Complete CLI command or `minify()` options used**

terser  --module --mangle -o output.js input.js

**`terser` input**

```
export function Stave() {
    const beams = [];
    for (const [key, notes] of []) {
        const isUp = true;
        beams.push(isUp);
    }
}
```

**`terser` output or error**

```
// prettified output
export function Stave() {
  const o = [];
  for (const [t, n] of []) {
    const t = true;
    o.push(t);
  }
}
```

**Expected result**

Without conflicting consts

**Comment by fabiosantoscode** [comment]
Hey there @TrySound :) 

Thanks for this report!

**Comment by fabiosantoscode** [comment]
Closing as the conversation on the other ticket didn't really find a bug. (for future reference, a duplicate `t` is fine in this case because the scope of `const [t` is not the same as the loop body's scope)
