### ISSUE TITLE
Incorrect code generated with `__INLINE__` annotation

### ISSUE THREAD

**Issue by utkarshkukreti** [terser/terser#922]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

    terser 5.5.1

(can also reproduce on the current version on https://try.terser.org)

**Complete CLI command or `minify()` options used**

    terser --toplevel --compress

**`terser` input**

```
const add = (a, b) => a + b

const x = /*#__INLINE__*/ add(1, 2)

const y = /*#__INLINE__*/ add(3, 4)

export const z = add(5, 6)
```

**`terser` output or error**

```
export const z=7;
```

**Expected result**

```
export const z=11;
```

For some reason `z` gets whatever value `y` should get if I change the arguments to the `add()` call in that line.

**Comment by utkarshkukreti** [comment]
If I change the last line to:

```
export const z = add(zzz, 3)
```

I get:

```
export const z=(zzz,7);
```

**Comment by fabiosantoscode** [comment]
Thanks for this report!

I've created __INLINE__ as a way to tell Terser to lower its guard and inline anyway, however this doesn't seem like an unreasonable use case.

**Comment by fabiosantoscode** [comment]
This appears to have been fixed in the meantime
