### ISSUE TITLE
Mangle props for #props inconsistenccy

### ISSUE THREAD

**Issue by sirian** [terser/terser#928]
**Bug report or Feature request?**

Bug, just look at output and you see

**Version (complete output of `terser -V` or specific git commit)**

current master branch (https://github.com/terser/terser/commit/91068aea284450a8cee52d0b6d856a67610b7029)

**Complete CLI command or `minify()` options used**

`bin/terser --compress --mangle --mangle-props -- /tmp/index.js`

**`terser` input**
```javascript
(() => {
class Base {
  static #privateStaticMethod() {
    return 42;
  }
  static publicStaticMethod() {
    return Base.#privateStaticMethod();
  }
}

class Derived extends Base {}

console.log(Derived.publicStaticMethod());
})();
```

**`terser` output or error**
```javascript
(() => {
    class t {
        static #t() {
            return 42
        }
        static i() {
            return t.#privateStaticMethod() // oooops
        }
    }
    console.log(class extends t {}.i())
})();
```

**Expected result**
```javascript
(() => {
    class t {
        static #t() {
            return 42
        }
        static i() {
            return t.#privateStaticMethod()
        }
    }
    console.log(class extends t {}.i())
})();
```

**Upd** Same problem for non-static #private fields

**Comment by fabiosantoscode** [comment]
Thank you for this report!
