### ISSUE TITLE
terser could remove boolean wrappings when used in if statements

### ISSUE THREAD

**Issue by danieltroger** [terser/terser#929]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V` or specific git commit)**
terser 5.5.1

**Complete CLI command or `minify()` options used**
terser <infile.js> -cm > outfile.js

**`terser` input**

```
(function() {
  const exists = Boolean(document.querySelector("body"));
  if (exists) {
    console.log("body exists");
  }
})();
```

**`terser` output or error**
```
Boolean(document.querySelector("body"))&&console.log("body exists");
```

**Expected result**
```
document.querySelector("body")&&console.log("body exists");
```

**Comment by fabiosantoscode** [comment]
Hey there!

Terser doesn't know if you've redefined `Boolean`, so it's not technically safe to do this. There's an option that ignores some of these unlikely issues, `unsafe`, for which you can find details [here](https://github.com/terser/terser#the-unsafe-compress-option).

I've checked that it does remove the wrapping Boolean in your example (but it does leave `!!` behind ;) ).

**Comment by danieltroger** [comment]
Oh nice, thank you!
