### ISSUE TITLE
5.6.0-beta has been tagged as 'latest' on npm

### ISSUE THREAD

**Issue by Conduitry** [terser/terser#930]
Hey, just a heads up. The 5.6.0-beta you published was tagged as terser@latest, rather than terser@beta it was presumably intended to. Folks running `npm install terser` will currently get the beta.

**Comment by fabiosantoscode** [comment]
Thanks for the heads up! 

I'll release 5.6.0 proper with the same code.

Guess this means I really have to look into automating releases.

**Comment by AviVahl** [comment]
Issue still stands: https://www.npmjs.com/package/terser?activeTab=versions
This can be fixed, even without publishing, by using the `npm dist-tag` command: https://docs.npmjs.com/cli/v6/commands/npm-dist-tag

**Comment by fabiosantoscode** [comment]
This week has been hectic and I forgot :) Since 5.6.0-beta is so stable I've just released 5.6.0 with the same code.

**Comment by fabiosantoscode** [comment]
Aaaand I forgot the changelog, committing it right now.
