### ISSUE TITLE
A case of ignoring removing console.

### ISSUE THREAD

**Issue by quietnumeric** [terser/terser#933]
**Bug report**

**Version**
4.8.0 (in the webpack-terser-plugin)

**`terser` input**

```
// I already found real cause. That is spread syntax.
const array = ['zero', 'one', 'two'];
console.log(...array);

// Of course, when I used string join, removing was successful.
console.log(array.join(' '));
```

**`terser` output or error**

No.
Remains console.log() in minified source code.

**Expected result**
Removing console.log().

**Comment by fabiosantoscode** [comment]
Hey there!

This is not an issue on the current version of Terser.
