### ISSUE TITLE
If a class prototype is modified, the class isn't tree-shaken

### ISSUE THREAD

**Issue by marcofugaro** [terser/terser#936]
**Feature request**

If a class prototype is modified in any way, that class is not subject to tree-shaking anymore if the class isn't used anywhere.

Even if the class is modified in place, it should be removed if unused.

This behaviour is respected by rollup.js, I have provided a [repro](https://github.com/marcofugaro/webpack-treeshake-test) indicating the differences between the [webpack + terser output](https://github.com/marcofugaro/webpack-treeshake-test/blob/8d4d14cc424f0016487dcc8146025b1a1f5ce5e8/dist/main.js#L1) and the [rollup output](https://github.com/marcofugaro/webpack-treeshake-test/blob/8d4d14cc424f0016487dcc8146025b1a1f5ce5e8/dist/main-rollup.js#L1).

**`terser` input**
```js
class UsedClass {}

class UnusedClass {}
UnusedClass.prototype.type = 'UnusedClass'

console.log(new UsedClass())
```

**`terser` output**
```js
(class{}).prototype.type="UnusedClass",console.log(new class{});
```

**Expected result**
```js
console.log(new class{});
```

**`terser` version**
v5.6.0

**Comment by fabiosantoscode** [comment]
Thanks for reporting this!

It was already the case for function, now it works with class too.

**Comment by mrdoob** [comment]
Thanks for fixing this! 🙏
