### ISSUE TITLE
Spread this

### ISSUE THREAD

**Issue by amk221** [terser/terser#937]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

5.5.0

**Complete CLI command or `minify()` options used**

n/a

**`terser` input**

```javascript
{ ...this }
```

**`terser` output or error**

```
Cannot read property 'references' of undefined
```

**Expected result**

No error

**Downstream**

https://github.com/ember-cli/ember-cli-terser/issues/254

**Comment by fabiosantoscode** [comment]
Closed in c8e49def920b6cbc5521bf27f331b8cc2ef4fbc3
