### ISSUE TITLE
Null byte emitted by RegEx optimization

### ISSUE THREAD

**Issue by aomarks** [terser/terser#942]
**Bug report or Feature request?**

Bug (maybe)

**Version (complete output of `terser -V` or specific git commit)**

terser 5.6.0

**Complete CLI command or `minify()` options used**

```sh
echo 'console.log(new RegExp(`\0`))' | terser -c unsafe | hexdump -c
```

**`terser` input**

```js
console.log(new RegExp(`\0`))
```

**`terser` output or error**

```js
console.log(new RegExp(NUL))
```

(note `NUL` above is an actual `0` byte)

**Expected result**

```js
console.log(new RegExp(`\0`))
```

**Explanation**

Terser emits a null byte for either `\0` or `\x00` escape sequences when optimizing `RegExp` constructor calls.

Interestingly, it *only* does this for `RegExp` constructor calls, and not for other uses of strings. Other strings seem to always escape nulls, even though *other* escape sequences (like `\x01`) are emitted as their unescaped UTF-8 bytes:

```sh
# escaped (good)
echo 'console.log(`\0`)' | terser -c unsafe | hexdump -c

# escaped (good)
echo 'console.log(`\x00`)' | terser -c unsafe | hexdump -c

# unescaped (fine)
echo 'console.log(`\x01`)' | terser -c unsafe | hexdump -c

# unescaped null byte (risky?)
echo 'console.log(new RegExp(`\0`))' | terser -c unsafe | hexdump -c
```

It *should* be valid for a UTF-8 file to include a null byte, however it may cause problems in practice.

For example, VSCode will fail to detect UTF-8 encoding if a null byte appears early enough in the file (presumably it sniffs the first N bytes), and will warn the user that it is a binary file before displaying it. The meldmerge.org diffing tool detects the encoding as UTF-16 instead of UTF-8. A server I was working with crashed when serving the JavaScript, again because it didn't detect UTF-8 encoding.

I think you could fairly argue that the above examples are bugs in the tools, and/or that this sort of thing comes with the territory with `unsafe` optimizations.

However, I think I'd lean towards the position that the practical risks of null bytes probably outweigh the advantages of saving 1 byte by optimizing `\0` to `NUL`.

So I'd propose that the unsafe `RegExp` constructor optimization should escape null characters, in the same way that they are escaped for strings in other contexts.

**Comment by fabiosantoscode** [comment]
This is a totally valid concern. Thanks for bringing this up! I don't want to be tripping over encoding sniffers.
