### ISSUE TITLE
[BUG] Compression with passes=2 worse than passes=1

### ISSUE THREAD

**Issue by sirian** [terser/terser#943]
**Bug report**

In some cases terser add redundant vars (leading to extra braces and `return` keyword for arrow functions). And code size grows

**Version 5.5.1**

**`terser` input**
```javascript
(() => {
    const getType = (value) => typeof value;
    const isSome = (value, values) => values.includes(value);
    const isType = (v, types) => Array.isArray(types)
                                 ? isSome(getType(v), types)
                                 : isType(v, [types]);
    
    console.log(isType("foo", "string"));
})();

```

`terser -c passes=1 -m`
```javascript
(() => {
    const o = (r, s) => Array.isArray(s) ? ((o, r) => r.includes(o))(typeof r, s) : o(r, [ s ]);
    console.log(o("foo", "string"));
})();
```

`terser -c passes=2 -m`
```javascript
(() => {
    const r = (o, n) => {
        return Array.isArray(n) ? (s = typeof o, n.includes(s)) : r(o, [ n ]);
        var s;
    };
    console.log(r("foo", "string"));
})();
```

**Expected result**

```javascript
(() => {
    const r = (o, n) => Array.isArray(n) ? n.includes(typeof o) : r(o, [ n ]); 
    console.log(r("foo", "string"));
})();
```

**Comment by fabiosantoscode** [comment]
Hey there! Thanks for spotting this. This is an issue with an internal function, size(), which was returning the wrong thing in the case of arrow functions.

It's fixed now, and will be released soon.

**Comment by sirian** [comment]
But why there is a redundant `var s` appears? Look careful  - `(s = typeof o, n.includes(s))` - should be just `n.includes(typeof o)`

**Comment by sirian** [comment]
@fabiosantoscode

**Comment by sirian** [comment]
Opened new issue with minimalistic example  https://github.com/terser/terser/issues/950

**Comment by fabiosantoscode** [comment]
It's created to hold intermediate values, and meant to be picked up by other compression passes. It's added later after the statement where it was needed, because it's a safe way to modify the tree while looping over it.
