### ISSUE TITLE
Await on the left-hand side of exponentiation operator 

### ISSUE THREAD

**Issue by balazssagi** [terser/terser#945]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 5.6.0

**Complete CLI command or `minify()` options used**
`terser ./file.js`

**`terser` input**

```js
async function test() {
    (await fn1()) ** 2 
}
```

**`terser` output or error**

```js
async function test(){await fn1()**2}
```

**Expected result**

```js
async function test(){(await fn1())**2}
```

Terser strips the parentheses around the awaited function and as of Chrome 89 this will result in the following error: `Uncaught SyntaxError: Unary operator used immediately before exponentiation expression. Parenthesis must be used to disambiguate operator precedence`.
Related Chromium issue:
https://bugs.chromium.org/p/v8/issues/detail?id=11213&q=11213&can=2

**Comment by fabiosantoscode** [comment]
Hey there! Thanks for bringing this up.

I'm not disallowing this form when it comes in, but I'm massaging it into the correct format on the way out.
