### ISSUE TITLE
Question: Terser doesn't generate unique Function names across scripts when the function is assigned to a object property

### ISSUE THREAD

**Issue by dsathyakumar** [terser/terser#948]
If Terser is used to minify multiple files (code-split bundles) via the `nameCache` option
- A.js
- B.js
- C.js

it currently does not output unique function names for top level functions (that are assigned to object properties) within each of these scripts.

**What works?**

**A.js** 
```js
function hello () {}
```

**B.js** 
```js
function foo() {}
```

**C.js** 
```js
function bar() {}
```

The above get minified to:

**A.js** 
```js
function a () {}
```

**B.js** 
```js
function b() {}
```

**C.js** 
```js
function c() {}
```

_In the above case, the function names are unique.
But in the case below its not,_

**What doesn't work?**
**A.js** 
```js
t.$A = function hello () {}
```

**B.js** 
```js
t.$B = function foo() {}
```

**C.js** 
```js
t.$C = function bar() {}
```

The above get minified to:

**A.js** 
```js
t.$A = function a () {}
```

**B.js** 
```js
t.$B = function a() {}
```

**C.js** 
```js
t.$C = function a() {}
```

In this case, the names are not unique. While the function names are unique within each of the files, they are not unique across the 3 of them, thereby creating collisions for code that relies on **Function.prototype.name**. 

Is there a workaround for this?

**Comment by fabiosantoscode** [comment]
Terser likes to reuse the same names if they don't collide when the code executes. In your case, `a` is only seen inside the function so it's OK to reuse. This helps keep variable names one character long, before starting to use two characters.

You can use the keep_fnames option in mangle to prevent mangling function names, it keeps more names around than you'd like, but it has the nice side effect of giving you more readable stack traces.

**Comment by dsathyakumar** [comment]
@fabiosantoscode any chance of being able to mangle functions uniquely across scripts? 
This kind of becomes uselul when dealing with code split bundles that have cross references and still rely on `function.prototype.name`. Would like some suggestions for the same.
