### ISSUE TITLE
compress privateIdentifier by default

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#955]
**Bug report or Feature request?** feature request

**Version (complete output of `terser -V` or specific git commit)** 5.6.0

**Complete CLI command or `minify()` options used**

**`terser` input**

```js
console.log(class {
    #outer = 0;
    static inner = class {
        #inner = 0;
        method (outer) { return outer.#outer + this.#inner; }
    };
});
```

**`terser` output or error**

```js
console.log(class {
    #outer = 0;
    static inner = class {
        #inner = 0;
        method (a) { return a.#outer + this.#inner; }
    };
});
```

**Expected result**

```js
console.log(class {
    #a= 0;
    static inner = class {
        #b = 0;
        method (a) { return a.#a + this.#b; }
    };
});
```

**NOTE**: keep away for`#constructor`, because that's special in spec.

**Comment by jridgewell** [comment]
Apologies, fixed by ￼ https://github.com/terser/terser/pull/1060
