### ISSUE TITLE
SyntaxError: Unexpected token: operator (=)

### ISSUE THREAD

**Issue by andrewmaxwell** [terser/terser#966]
**Bug report**

**Version 5.6.0**

```
const doStuff = ({get = 'a'}) => {}
```
or
```
const doStuff = ({set = 'a'}) => {}
```

results in an error: `SyntaxError: Unexpected token: operator (=)`

**Expected result**
Not an error!

**Comment by andrewmaxwell** [comment]
The error is easily reproduced here: https://xem.github.io/terser-online/

**Comment by fabiosantoscode** [comment]
Thanks for the really small repro :)
