### ISSUE TITLE
Consider allowing more files from export map

### ISSUE THREAD

**Issue by wooorm** [terser/terser#973]
**Feature request**

I would like to use the terser API (internals, although preferably a clean api instead) to transform estrees (spidermonkey / mozilla / acorn ast).

The [export map](https://github.com/terser/terser/blob/321837181373b5dd356fa818eaa5b5977559842b/package.json#L18-L28) in `package.json` prevents that.

Is it\
a) possible to allow more files from the export map, or\
b) expose more stuff that is currently internal as an API?

<details><summary>Not that important but here’s an example:</summary>

```js
import {Parser} from 'acorn'
import astring from 'astring'

import 'terser/lib/transform.js';
import 'terser/lib/mozilla-ast.js';
import {minify} from 'terser/lib/minify.js';
import {AST_Node} from 'terser/lib/ast.js'

var input = Parser.parse(
  'var number = 1;var other = 2;\nexport var b = number + other + 3 + 2', {
    ecmaVersion: 2020,
    sourceType: 'module'
  }
)

var output = (await minify(
  AST_Node.from_mozilla_ast(input),
  {ecma: 2020, format: {ast: true, code: false}, module: true}
)).ast.to_mozilla_ast();

console.log(astring.generate(output));
```

Actual:

```sh
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/transform.js' is not defined by "exports" in ~/Projects/oss/example-terser/node_modules/terser/package.json imported from ~/Projects/oss/example-terser/example.js
    at new NodeError (node:internal/errors:329:5)
```

Expected

```js
export var b = 8;
```

</details>

**Comment by fabiosantoscode** [comment]
Very interesting. I really don't want to expose the AST, to make internal breaking changes not bump the major version of the package, but this should be available from the minify() API just like it is from the CLI.

**Comment by wooorm** [comment]
That’s understandable!

Are you saying this *should* already work, or that something like this *should* be added?

**Comment by fabiosantoscode** [comment]
It needs to work without exposing AST_Node :)

If you feel like sending a PR to lib/minify (which has the minify function) look at lib/cli.js which implements the "spidermonkey" parse option.

**Comment by wooorm** [comment]
So you’re open to `minify` accepting an ESTree (spidermonkey ast), and returning a modified and minified one?

**Comment by fabiosantoscode** [comment]
Because of the fact that Terser uses its own internal AST, and spidermonkey is merely a conversion, there wouldn't be an advantage un forcing the user to both input and receive a spidermonkey AST. Plus, it's closer to what you can do in the CLI.
