### ISSUE TITLE
Identifier 'r' has already been declared

### ISSUE THREAD

**Issue by simonroloff** [terser/terser#978]
**Bug report**

**Version**
terser 5.6.1

**Steps to reproduce the issue / `terser` input**
1. `git clone https://github.com/simonroloff/ui5tooling.git`
2. `cd ui5tooling`
3. `npm i -g terser`
4. `npm i -g eslint`
5. `terser --mangle -- webapp/Component.js | eslint --stdin`

**`terser` output or error**
```<text>
  1:1441  error  Parsing error: Identifier 'r' has already been declared

✖ 1 problem (1 error, 0 warnings)
```

**Expected result**
I would expect terser to minify my file in a correct manner.

**Comment by fabiosantoscode** [comment]
I isolated this minimal repro:

```javascript
function x() {
  {
      let name1 = "something"
      function name2() {}
  }
}
```

When analyzing scope, functions are always hoisted and placed in the nearest non-block scope. However, in strict mode that's not the case, as we can verify by running this with and without strict mode:

```javascript
(function () {
  if (true) {
    function x() {}
  }
  return x
})()
```
