### ISSUE TITLE
Extra code appears in callback

### ISSUE THREAD

**Issue by dgeibi** [terser/terser#979]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

- version used by https://try.terser.org/
- 5.6.1
- 4.8.0

**Complete CLI command or `minify()` options used**

**`terser` input**

```
import React, { useEffect, useRef } from 'react';

const getParam = () => {
  if (window.x) {
    return 1;
  }
  return 2;
};

const Inner = () => {
  const { params } = {};
  const { a, b } = params || {};
  const x = useRef();

  const fn = () => {
    getParam();
  };

  useEffect(() => {
    fn();
  }, []);

  return 'hello';
};

const withXX = Comp => props => {
  return React.createElement(Comp, props);
};

export default withXX(Inner);
```

**`terser` output or error**

```
import e,{useEffect as r,useRef as t}from"react";export default(a=()=>{const{params:e}={},{a:a,b:o}=e||{};t();return r((()=>{(t(),()=>{window.x})()}),[]),"hello"},r=>e.createElement(a,r));var a;
```

**Expected result**

no extra useRef() call in useEffect callback

**Comment by sokra** [comment]
It's a little bit difficult to see in the minimized code, so here is the same with mangle disabled and beautify enabled:

``` js
import React, { useEffect, useRef } from "react";

export default (Comp = () => {
    const {params: params} = {}, {a: a, b: b} = params || {};
    useRef();
    return useEffect((() => {
        (useRef(), () => {
            window.x;
        })();
    }), []), "hello";
}, props => React.createElement(Comp, props));

var Comp;
```

Note the unexpected `useRef()` call in `useEffect` in addition to the correct call before `useEffect`.

**Comment by fabiosantoscode** [comment]
Oof, this sounds pretty bad

**Comment by fabiosantoscode** [comment]
`const fn` gets optimized into `(useRef,() => {getParam()})` by `join_vars`, which should be fine, but then when `fn` gets inlined, it brings the rest of the sequence expression with it.

**Comment by csvan** [comment]
Has this fix been released?

**Comment by fabiosantoscode** [comment]
Indeed it has!
