### ISSUE TITLE
Properties minifier with computed properties is incorrect

### ISSUE THREAD

**Issue by adamburgess** [terser/terser#980]
**Bug report or Feature request?** Bug

**Version (complete output of `terser -V` or specific git commit)** master 80c1848

**Complete CLI command or `minify()` options used**
Default options. or `{ compress: { defaults: false, properties: true, side_effects: true } }`.

**`terser` input**

```js
console.log({
  a: 'wrong',
  // String.fromCharCode(97) is "a"
  [String.fromCharCode(97)]: 'correct'
}.a)
```

**`terser` output or error**
```js
console.log(["wrong",String.fromCharCode(97)][0]);
```
this prints `"wrong"`
**Expected result**
```js
console.log({a:'wrong',[String.fromCharCode(97)]:'correct'}.a)
```
this prints `"correct"`

---

A test case:

```js
dont_mangle_computed_property_3: {
    options = {
        defaults: true,
        toplevel: true,
    }
    mangle = {
        properties: {},
        toplevel: true,
    }
    input: {
        console.log({
            a: "bar",
            [String.fromCharCode(97)]: "baz"
        }.a);
    }
    expect: {
        console.log({a: "bar",[String.fromCharCode(97)]: "baz"}.a);
    }
    expect_stdout: [
        "baz",
    ]
}
```

**Comment by fabiosantoscode** [comment]
Thanks for bringing this up! This optimization is being a bit too optimistic about those computed props. There's also another bug I can tackle at the same time, #956. Maybe I'll get to delete some code :)
