### ISSUE TITLE
Invalid minification for yield expression with comments before argument

### ISSUE THREAD

**Issue by weareoutman** [terser/terser#983]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

4.6.7 or 5.6.1

**Complete CLI command or `minify()` options used**

`terser --compress --mangle --module -- yield.js`

**`terser` input**

```js
const apiWithComments = () =>
  /**! @preserve any comments with leading and trailling line-endings */
  http.get("any");

export function* test() {
  const data = (yield apiWithComments()).data;
}
```

**`terser` output or error**

```js
export function*test(){(yield
/**! @preserve any comments with leading and trailling line-endings */
http.get("any")).data}
```

**Expected result**

```js
export function*test(){(yield(
/**! @preserve any comments with leading and trailling line-endings */
http.get("any"))).data}
```

We should wrap a pair of parentheses for the argument of yield expression.

**Comment by fabiosantoscode** [comment]
I see! So `yield` needs the same treatment as return in this respect -- since it's valid without an argument, semicolon insertion comes in and breaks it up.

Example of the `return` treatment:

```javascript
// in:
function x(){
  return /*!hello*/ leak(1)
}

// out:
function n(){/*!hello*/
return leak(1)}n(),n();
```
