### ISSUE TITLE
Feature request: support for null-safe optional chaining

### ISSUE THREAD

**Issue by eugeneblinn** [terser/terser#984]
Currently if any null-safe optional chains are included in JS code (e.g., object?.parent?.child instead of object && object.parent && object.parent.child) it results in 'undefined' as output from terser.

**Comment by fabiosantoscode** [comment]
Hey there!

I don't think I understand this issue. Optional chaining is supported, and Terser assumes that `undefined` is what they return if something is `== null`.

Try this code in try.terser.org:

```
let foo = null
console.log(foo?.bar)
```

This gets optimized to `console.log(void 0)`

**Comment by fabiosantoscode** [comment]
I'm closing, because as per the spec, undefined is what these expressions return.
