### ISSUE TITLE
Always Getting Promise<Pending>as the result

### ISSUE THREAD

**Issue by haneenmahd** [terser/terser#986]
**Bug report?**

**Version (complete output of `terser -V` or specific git commit)**
5.6.1

**Complete CLI command or `minify()` options used**
```js
var options = {
            toplevel: true,
            compress: {
                'global_defs': {
                    "@console.log": "alert"
                },
                passes: 2
            },
            format: {
                preamble: "/* minified */"
            }
        };
```

**`terser` input**
```js
let code = {
            "file1.js": "function add(first, second) { return first + second; }",
            "file2.js": "console.log(add(1 + 2, 3 + 4));"
        };
```

**`terser` output or error**
```js
Promsise<pending>
/* minified */
alert(10); 
```

**Expected result**
Do not know why it is showing Promise<pending> everytime.

I tried changing the code and options many times but sometimes it only shows `Promise<pending>`;

**Comment by fabiosantoscode** [comment]
Hello! 

`minify` is an asynchronous function starting at 5.0.0. You need to await that promise, or use .then, to get the minification results.

Cheers!

**Comment by haneenmahd** [comment]
it shows the result with Promise<pending>
