### ISSUE TITLE
Invalid output while using optional chaining and assignment

### ISSUE THREAD

**Issue by claneo** [terser/terser#987]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

`5.7.0`

**Complete CLI command or `minify()` options used**

REPL default

```
// edit terser options
{
  module: true,
  compress: {},
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```
var a = b?.c
a.d = e
```

**`terser` output or error**

```
b?.c.d=e;
```

```
Uncaught SyntaxError: Invalid left-hand side in assignment
```

**Expected result**

```
(b?.c).d=e;
```

**Comment by fabiosantoscode** [comment]
Thanks for reporting, and this small repro :rocket:
