### ISSUE TITLE
Function names are not mangled

### ISSUE THREAD

**Issue by billreynolds007** [terser/terser#991]
**Bug report **
terser 5.7.0
terser hello.js --mangle --output hello2t.js
The hello.js input is
```
function Hello( )
{
	// superclass initialization
}
Hello.prototype.MY_CONSTANT = 123456;
Hello.prototype.fileTypeForFileName = function(fileName)
{
	var pieces = fileName.split('.');
	var fileExt = pieces[pieces.length - 1];
	return fileExt;
}

var myThing = new Hello();
myThing.fileTypeForFileName("foo.txt");
```
The output is
```
function Hello(){}Hello.prototype.MY_CONSTANT=123456;Hello.prototype.fileTypeFor
FileName=function(e){var l=e.split(".");var o=l[l.length-1];return o};var myThin
g=new Hello;myThing.fileTypeForFileName("foo.txt");

```

**Expected result**
Hello and fileTypeForFileName mangled.

**Comment by Conduitry** [comment]
You need to tell Terser either to treat this as an ESM module or that top-level variables can be minified. This does not happen by default because that would affect which globals are exposed.

**Comment by billreynolds007** [comment]
Thank you for the quick suggestion.
I looked at the CLI at
`https://www.npmjs.com/package/terser
`

 This command had no affect
`terser hello.js --mangle --ecma 2016 --output hello2t.js
`

This command
`terser hello.js --mangle --toplevel --output hello2t.js
`

generated output that is a lot closer

```
function e(){}e.prototype.MY_CONSTANT=123456;e.prototype.fileTypeForFileName=
function(e){var t=e.split(".");var o=t[t.length-1];return o};
var t=new e;t.fileTypeForFileName("foo.txt");
```

We still have the fileTypeForFileName not being mangled. 
I guess because it is not being seen as a function?

**Comment by fabiosantoscode** [comment]
Hey there :) 

Terser isn't as smart as you think. Rarely does it know where a variable came from, except if it's in-scope and is never reassigned. This means that a lot of functionality isn't possible to do.

You can use the property mangler to mangle properties, but it's very unsafe and all your code has to be written with it in mind, lest you break all of it. But if you think your code is short enough or can take the abuse of that transform, have a look at the `keep_quoted: "strict"` option for it, which is the least unsafe and lets you opt-out from mangling by quoting all your un-mangleable properties.

As for keeping Bar unmangled, you can use the `reserved` mangling option, which is a list of names that the mangler will leave alone.

**Comment by fabiosantoscode** [comment]
Btw thanks for your help @Conduitry

**Comment by billreynolds007** [comment]
Thank you for the details. Many thanks to both of you for your help.
```
As for keeping Bar unmangled, you can use the reserved mangling option, 
which is a list of names that the mangler will leave alone.
```
I thought I did that in
`terser foo.js --mangle --toplevel --mangle-props reserved=[Bar,myBarFunction] --output foot.js
`
It seemed to pick up the myBarFunction correctly.
Maybe I have the command line incorrect or some other confusion?

**Comment by billreynolds007** [comment]
In scope.js, within the SymbolDef code, adjusting unmangleable(options) {...} to have

```
unmangleable(options) {
...
if (this.orig[0] instanceof AST_SymbolDefun)
{
 var reserved = options.properties.reserved || {};
 if (reserved.indexOf(this.orig[0].name) >= 0)
   {
   console.log('KEEP', this.orig[0].name);
   return true;
   }
}
       return this.global && !options.toplevel ...

```
will leave Bar alone.
Matching wise , most class names will have an upper case first character while functions names a lower case one.

The result is now what I was looking for in my simple example,
```
function r(){}r.prototype.t=123456;r.prototype.o=function(r){var n=r.split(".");
var a=n[n.length-1];return a};
function Bar(){}Bar.prototype.t=123456;
Bar.prototype.myBarFunction=function(r){var n=r.split(".");var a=n[n.length-1];return a};
var n=new r;var a=new Bar;n.o("foo.txt");a.myBarFunction("bar.txt");
```
