### ISSUE TITLE
terser cannot distinguish path that include $

### ISSUE THREAD

**Issue by hualongdai** [terser/terser#992]
**`terser` input**
terser ./packages/promo/mc$21/index.js

**`terser` output or error**
ENOENT: no such file or directory, open './packages/promo/mc/index.js'

**Expected result**
can open ./packages/promo/mc$21/index.js

**Comment by Conduitry** [comment]
If your shell interprets `$` as a variable reference, you need to escape it. This would be the case for any CLI and is unrelated to Terser.

**Comment by fabiosantoscode** [comment]
This is correct. If you're on Linux, simply wrap the path in single quotes to avoid the shell interpreting $ as something special
