### ISSUE TITLE
Name collision caused by let in loop initializer

### ISSUE THREAD

**Issue by lorenzodallavecchia** [terser/terser#997]
**Bug report**

**Version**

```
terser 5.7.0
```

**Complete CLI command**

```
terser --compress -- input.js
```

**`terser` input**

```js
function main(e) {
    console.log(e.length);
    let other = "12";
    for (let e; e = 0;) {
        console.log(e);
    }
}
main("foo");
```

**`terser` output**

```js
function main(e){console.log(e.length);let e;for(;e=0;)console.log(e)}main("foo");
```

When executed, the code throws `SyntaxError: Identifier 'e' has already been declared`.
The `let` declaration hoisted from inside the `for` loop causes a name conflict with the function parameter.

**Expected result**

I would expect the `let` declaration to stay inside the loop, even if there is a previous `let` declaration outside of the loop

**Other notes**

I can work around the issue by disabling `join_vars` compress option.

**Comment by fabiosantoscode** [comment]
This is so tricky :/ here's some valid JavaScript without that repeated declaration syntax error:

```
let e = 10; for (let e = 10;;) { let e = 10; break }
```

There is an extra scope in the for's head, which Terser doesn't take into account (it thinks it's the same as the one on the outside).

**Comment by fabiosantoscode** [comment]
Indeed, this hasn't been addressed. I should tackle the issue with the duplicated scope as another topic and not conflate it into this specific bug.

**Comment by ehoogeveen-medweb** [comment]
The issues with `let` look tricky, but shouldn't this option only apply to `var` in the first place? That's what its name and description suggest.

**Comment by Slapbox** [comment]
I don't think "vars" in `join_vars` should be taken to literally mean `var` as a JS term, but variable as a general programming term.

**Comment by ehoogeveen-medweb** [comment]
I agree that "vars" in `join_vars` could be taken as short for "variables", but the description literally says "join consecutive `var` statements", so I think it's confusing since this bug is only about `let` (and maybe `const`).
