### ISSUE TITLE
Syntax error in Safari 10.x with reused const name in inner scope

### ISSUE THREAD

**Issue by DavidZidar** [terser/terser#998]
**Bug report**

We have a problem in a project I'm working in where minifying d3 (specifically d3-array v2.12.1) with Terser is reusing the same name for a constant in an inner scope which seems to trigger an error in Safari 10.x.

Specifically Safari throws this error: `SyntaxError: Cannot declare a const variable twice: 't'.`

Other browsers do not throw an error so I assume it is a bug in Safari, however it probably needs a workaround in Terser.

**Version (complete output of `terser -V` or specific git commit)**

terser 5.7.0

**Complete CLI command or `minify()` options used**

We are using webpack, I have tried a bunch of different Terser-settings including enabling both `safari10` options but neither seem to change the naming of the constants.

**`terser` input**

Comments have been removed for brevity.

```js
if (!Array.isArray(tz)) {
  const max = x1, tn = +tz;
  if (domain === extent) [x0, x1] = nice(x0, x1, tn);
  tz = ticks(x0, x1, tn);
  if (tz[tz.length - 1] >= x1) {
    if (max >= x1 && domain === extent) {
      const step = tickIncrement(x0, x1, tn);
      if (isFinite(step)) {
        if (step > 0) {
          x1 = (Math.floor(x1 / step) + 1) * step;
        } else if (step < 0) {
          x1 = (Math.ceil(x1 * -step) + 1) / -step;
        }
      }
    } else {
      tz.pop();
    }
  }
}
```

**`terser` output and error**

This output is beautified for readability.

```js
if (!Array.isArray(_)) {
    const t = p,
        e = +_;
    if (n === o.default && ([h, p] = Object(c.default)(h, p, e)), (_ = Object(f.default)(h, p, e))[_.length - 1] >= p)
        if (t >= p && n === o.default) {
            const t = Object(f.tickIncrement)(h, p, e);
            isFinite(t) && (t > 0 ? p = (Math.floor(p / t) + 1) * t : t < 0 && (p = (Math.ceil(p * -t) + 1) / -t))
        } else _.pop()
}
```

**Expected result**

It should be possible to make Safari 10.x run minified d3 code.

**Comment by Conduitry** [comment]
There's a `safari10` option listed in the readme that can be enabled to work around this Safari bug.

**Comment by DavidZidar** [comment]
Thank you for the quick response @Conduitry, I just tried the `safari10` option and diff compared the result with the previously minified code and I can't really see any meaningful differences. The double const with the same name is still there for instance.

Unfortunately, I don't have any Safari 10.x browsers to test with so I'm not exactly sure what is blowing up, the above is my best guess by looking through the code.

I can try to enable the `safari10` flag and deploy to production and see if the issue disappears in the logs but it will take a few days.

**Comment by DavidZidar** [comment]
Although I just removed the pre-minified code from `node_modules` entirely and the output is exactly the same anyway. :(
